### ISSUE TITLE
Deployed environment throwing error

### ISSUE THREAD

**Issue by ivosanchez** [webiny/webiny-js#1002]
I hope it is ok to post this here instead of on slack

installation on: 
Catalina /  node 10.20.  / yarn 1.22 

&. my default role in AWS has full programmatic,

I get graphql playground ok, 
but,
keep getting error bellow instead of home and admin pages. 
I've tried with 3 diff environments, each with their respective databases 

{
  "requestContext": {
    "resourceId": "se09x2",
    "resourcePath": "/cms/{key+}",
    "httpMethod": "GET",
    "extendedRequestId": "OIUJFFFQIAMFS_A=",
    "requestTime": "14/Jun/2020:18:05:58 +0000",
    "path": "/prod/cms/read/production",
    "accountId": "209017412021",
    "protocol": "HTTP/1.1",
    "stage": "prod",
    "domainPrefix": "t3stjpqzlk",
    "requestTimeEpoch": 1592157958801,
    "requestId": "42f953f4-45b8-47b1-a910-2b82c7640557",
    "identity": {
      "cognitoIdentityPoolId": null,
      "accountId": null,
      "cognitoIdentityId": null,
      "caller": null,
      "sourceIp": "46.25.50.77",
      "principalOrgId": null,
      "accessKey": null,
      "cognitoAuthenticationType": null,
      "cognitoAuthenticationProvider": null,
      "userArn": null,
      "userAgent": "Amazon CloudFront",
      "user": null
    },
    "domainName": "t3stjpqzlk.execute-api.us-east-1.amazonaws.com",
    "apiId": "t3stjpqzlk"
  },
  "context": {
    "callbackWaitsForEmptyEventLoop": true,
    "functionVersion": "$LATEST",
    "functionName": "bb470b81_webiny-front_api_prod_cmsContent",
    "memoryLimitInMB": "512",
    "logGroupName": "/aws/lambda/bb470b81_webiny-front_api_prod_cmsContent",
    "logStreamName": "2020/06/14/[$LATEST]47ae9179e16a40109a0649af51d9018e",
    "invokedFunctionArn": "arn:aws:lambda:us-east-1:209017412021:function:bb470b81_webiny-front_api_prod_cmsContent",
    "awsRequestId": "70f514c0-7f79-4375-8798-f847ac7d95a3"
  },
  "error": {
    "name": "TypeError",
    "message": "Cannot read property 'environment' of null",
    "stack": "TypeError: Cannot read property 'environment' of null\n    at apply (/var/task/handler.js:87176:46)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
  }
}

**Comment by Pavel910** [comment]
Hi @ivosanchez, sure it's totally fine :)

Did you run through the installation wizard when you deployed the `prod` environment to AWS?

**Comment by ivosanchez** [comment]
hi there Pavel910 ,
thanks,
no, I hadnt done that, when I saw the last message on terminal during installation, the one that gives you the graphql playground url and the read /  preview urls, I thought I was supposed to have them working correctly before installing the admin app

**Comment by Pavel910** [comment]
When you deploy a new instance of an environment (`--env=dev` or `--env=prod`), you're creating a completely isolated instance of infrastructure. And since you also have a separate database, it's blank until you run the setup wizard. So each environment is completely isolated, and requires the same setup process.

Whenever you deploy a new `--env` - you always have to run the admin app and complete the installation wizard.

Let me know how it goes, and if you need more help, feel free to get in touch! Cheers!

**Comment by ivosanchez** [comment]
will do so. thank you !!

**Comment by Pavel910** [comment]
@ivosanchez I'm closing this as we seem to have figured out the problem. Feel free to reopen or post a new issue if necessary!
