### ISSUE TITLE
RTL support.

### ISSUE THREAD

**Issue by Mohamed-Abubucker** [webiny/webiny-js#1003]
## This is:

- Question

Hi team,

I want to use webiny for my personal blog project. i am planning to keep it in 2 languages. 
1. English
2. Arabic.

I am complete beginner with webiny framework, i don't know webiny support RTL (for Arabic Language - only for public website not for admin) or not.

Kindly help in this by suggessions / guidelines

**Comment by Pavel910** [comment]
Hi @Mohamed-Abubucker, thanks for the issue.  Unfortunately for now RTL is not available. Let's keep this issue open so it's not lost.

**Comment by Mohamed-Abubucker** [comment]
Hi @Pavel910 ,

Thanks for your prompt reply. 

by the way, i want to create websites in 2 languages (English and Arabic). i don't need RTL support for admin site. i want know whether the page builder supports RTL or not.

Kindly let me know is it possible in the current release?

**Comment by Pavel910** [comment]
@Mohamed-Abubucker unfortunately, it's not possible.

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
