### ISSUE TITLE
Scaffolding plugin for a new React app

### ISSUE THREAD

**Issue by Pavel910** [webiny/webiny-js#1006]
## This is:
- Feature request

## Detailed Description
We need a new scaffolding plugin to quickly setup a React app skeleton. The plugin should ask users if they want to setup an `admin` app, a `site` app or an empty skeleton without any templates, just an `index.tsx` with all the config files so the user can start developing his own thing.

**Comment by Fsalker** [comment]
**Implementation Plan**

- I'll create a new package in **/packages**: `cli-plugin-scaffold-react-app`, which creates an app very similar to `admin` and displays **"Hello world!"** when you run it.
- this package will be as **similar** as possible to the **existing scaffold plugins**.
- all apps generated with this new scaffold plugin **must** reside within **<project_root>/apps/**
- the generated app will be added to **<project_root>/apps/resources.js** using **ASTs**. it will look very similar to the `admin` resource already present there

- I'll make sure that all required config files are present and (if it's the case) populated, following `<project_root>/apps/admin` app's structure: **.gitignore**, **tsconfig.json**, **example.env.json**...

**Comment by Pavel910** [comment]
@Fsalker ask the user where he wants to generate the app, it's `apps` by default, but the user has to be able to change the location. Follow the approach we use in other scaffolding plugins.

Also provide the user with a selection of 3 templates: `admin`, `site`, `custom`. The first 2 should look similar to our current setup, and the `custom` one is just a simple `index.tsx`, similar to what `create-react-app` generates.

**Comment by Fsalker** [comment]
alright

**Comment by Fsalker** [comment]
should i also add the generated react app to `resources.api.inputs.endpoints` in `resources.js`?

![image](https://user-images.githubusercontent.com/16700631/86840180-1b689200-c0ab-11ea-861f-a782aeae091b.png)

**Comment by Pavel910** [comment]
@Fsalker yeah, the scaffolded app should be added to `resources.js`.
