### ISSUE TITLE
Scaffolding plugin for a new node package

### ISSUE THREAD

**Issue by Pavel910** [webiny/webiny-js#1008]
## This is:
- Feature request

## Detailed Description
We need a new scaffolding plugin to quickly setup a skeleton for a new package for node/api. It should link the package with `tsconfig.build.json` and extend `babel.node.js` file (see our repo for examples).

**Comment by Fsalker** [comment]
eg: clone api-i18n keeping only src/plugins/index.ts + keep 1 example plugin

just like scaffold-graphql-service
