### ISSUE TITLE
Headless CMS - make sure to lowercase environment slugs

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#1015]
Mange API URLs like `/cms/read/Development` should not happen.

Make sure the environment slugs, used in URLs, are always lower-cased, so the above URL should actually be `/cms/read/development`.

**Comment by EmilK15** [comment]
This issue arises once somebody decides to create an Alias under Headless CMS. They can create a new environment alias, and although the default behavior of the form is to lowercase the text like below:
![image](https://user-images.githubusercontent.com/9532882/84792179-90bbd800-afc1-11ea-87b4-e3bd206471a2.png)
The user can then edit the alias name to include capitals.
Solution:
I'll most likely add an event handler when the user clicks away from the text so it doesn't change as they are typing (would be weird as a user)
Or add an error message/disable flag around the button to show the slug must be lowercase

**Comment by doitadrian** [comment]
1. The `Bind` component support `onAfterChange` prop, you can use that to lowercase it.

2. The UI check is OK, but it's mandatory for the force-lowercase logic to be implemented on the backend as well. You can do that with a `beforeCreate` hook.

3. Finally, make sure to write a simple test, that ensures that the backend works correctly. One of the recent tests I've written is `packages/api-headless-cms/__tests__/unlockingFields.test.js`. But note that it uses the `useContentHandler`, and in your case, you need `useGqlHandler` and an example for that can be found here - `packages/api-headless-cms/__tests__/accessTokensAuthentication.test.js`

**Comment by EmilK15** [comment]
Update:
Solution was the following:
Adding an onChange to the Input containing the slug within `NameSlug` component
Adding a `pipe` on the `onceSet` call within `environmentAlias.model`.
Testing used the GraphQL queries within `environmentAliases.tsx`
