### ISSUE TITLE
Headless CMS - repeater fields

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#1021]
We had a question from the community related to "repeater fields". The following comment explains well what those are:

https://github.com/strapi/strapi/issues/1779#issuecomment-414795715

Action items:
- [x] refactor `app-headless-cms` package
- [x] introduce `<FieldsEditor />` component to render arrays of fields and support nested objects
- [x] add `object` field and support `multiple values` 
- [x] generate GraphQL schema based on nested objects
- [ ] generate resolvers for object fields
- [ ] nested resolvers must respect existing toStorage/fromStorage/toIndex/fromIndex rules and behavior
- [ ] style UI components to make it clear and easy to use

**Comment by doitadrian** [comment]
Another cool video that shows how components and dynamic zones work.
https://strapi.io/blog/release-beta-18-dynamic-zones

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!

**Comment by Pavel910** [comment]
Adding this reference as well, it looks like what we want to have, but we'll most likely have a slightly different UI:
https://strapi.io/blog/repeatable-groups-feature
https://strapi.io/documentation/user-docs/latest/content-manager/writing-content.html#filling-up-fields

**Comment by zoezoezoe** [comment]
This would be very helpful! We have a use case for this and currently we are looking into creating a custom field type (an object with a few basic fields) to achieve the same thing. Having this configurable from the CMS Admin UI would be a lot more robust than a plugin with a hardcoded data structure.

**Comment by Pavel910** [comment]
I'm working on this for the `5.10` release, hopefully no blockers pop up along the way and we manage to wrap it by then.

**Comment by Pavel910** [comment]
UPDATE: this **will not** be released in `5.10`, but we're aiming at finishing it for `5.11`.
