### ISSUE TITLE
Got "TypeError: task.skip is not a function" when start a new project

### ISSUE THREAD

**Issue by pzg250** [webiny/webiny-js#1022]
Got TypeError when start a new project

## This is:

- Question

## Specifications
  - OS:  Ubuntu18.04

## Detailed Description

Got TypeError when run command `npx create-webiny-project new-project` .

Output Message:
```
npx: installed 216 in 22.96s
  Creating project at /root/new-project:
  ✔ Pre-template setup
  ✔ Install template package
  ✔ Create project folders
  ✔ Set up project dependencies
  ✖ Initialize git
    → task.skip is not a function
    Get proper package versions
    Resolve packages
    Install dependencies
    Run template-specific actions
Unable to complete project initialization { TypeError: task.skip is not a function
    at Task.task (/root/.npm/_npx/7851/lib/node_modules/create-webiny-project/init.js:92:26)
    at Promise.resolve.then.then.skipped (/root/.npm/_npx/7851/lib/node_modules/create-webiny-project/node_modules/listr/lib/task.js:167:30)
    at process._tickCallback (internal/process/next_tick.js:68:7) context: [Object: null prototype] {} }
```

**Comment by Pavel910** [comment]
@pzg250 thanks for reporting. Apparently one if these 2 commands fail, and then i throws on the `task.skip` below which I think is a bug on our side:

![image](https://user-images.githubusercontent.com/3920893/84896181-c89b4c00-b0a3-11ea-8f3c-86a73328adfb.png)

Is it possible that `git --version` or `git init` are failing on your system? Maybe `git` is not installed?
Try installing `git`, and then the project creation should work, and I'll assign this issue for our next release cycle.

Cheers!

**Comment by pzg250** [comment]
Hi @Pavel910 , 
Thank you very much . Yes , git is not installed on my system. But I met a new problem. 
Could you help? Thanks in advance. 

```
npx: installed 216 in 22.502s
  Creating project at /root/new-project:
  ✔ Pre-template setup
  ✔ Install template package
  ✔ Create project folders
  ✔ Set up project dependencies
  ✔ Initialize git
  ✔ Get proper package versions
  ✔ Resolve packages
  ✖ Install dependencies
    → Unable to install the necessary packages.
    Run template-specific actions
Unable to complete project initialization { Error: Unable to install the necessary packages.
    at Task.task (/root/.npm/_npx/8224/lib/node_modules/create-webiny-project/init.js:230:27)
    at process._tickCallback (internal/process/next_tick.js:68:7) context: [Object: null prototype] {} }
```

**Comment by Pavel910** [comment]
@pzg250 to figure out what package bothers him, we need to enable logging using `--log` parameter.
Run `npx create-webiny-project my-project --log`. It will log everything into a file at `./my-project/log.txt`. So when the setup fails, look in that file to see which package exactly is causing problems. We'll continue from there.

**Comment by pzg250** [comment]
I got the log. Any advise ? Thanks

```
yarn install v1.22.4
[1/4] Resolving packages...
warning @webiny/cli > @webiny/tracking > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
error Couldn't find any versions for "@webiny/tracking" that matches "^4.1.0"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by Pavel910** [comment]
That's weird because the package version is on `npm`: https://www.npmjs.com/package/@webiny/tracking

This has something to do with npm cache, maybe try `npm cache clean` and retry project creation.

**Comment by pzg250** [comment]
Hmm, after clean the cache I got same error. 
And I forgot provide one information, I create the project in a docker container. 
This container comes from the docker hub, the latest ubuntu 18.04.

**Comment by Pavel910** [comment]
As long as it talks to `npm` it should work. Don't really know how this is related to Webiny. This looks more like a problem with pulling packages. We use `yarn` to install packages, if that's of any help.

**Comment by pzg250** [comment]
Hi All,
I changed to use centos, and the error disappeared. But I met a new issue. Will open a new ticket. 
Close this.
