### ISSUE TITLE
Admin page not loading in 4.1.0

### ISSUE THREAD

**Issue by jakubgs** [webiny/webiny-js#1029]
I tried deploying `4.1.0` today and it went fine without any errors, but when I try to open the `/admin` page I get nothing and this error in the JS console:
![webiny_admin_page_error](https://user-images.githubusercontent.com/2212681/85015162-cb5f7500-b167-11ea-92d6-8829979f290c.png)
I checked CloudWatch logs but there's nothing there.

**Comment by Pavel910** [comment]
@jakubgs so this is deployed to AWS, judging by the JS file name. I'll have to double check, haven't encountered this, but will deploy to AWS and see what's going on.

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!

**Comment by jakubgs** [comment]
I've abandoned my plans to use the software as it seemed too unstable.
