### ISSUE TITLE
Webiny Telemetry - Improvements and implementation details

### ISSUE THREAD

**Issue by SvenAlHamad** [webiny/webiny-js#1030]
As with any product, for the team behind it., it's important to know how users are interacting with the product. This data tells us where we need to invest time in making things better and how to prioritize them. This is also important for us as the company behind Webiny as our work on the project is funded by investors and if we can't show them our progress, its hard for us to justify additional capital to make Webiny even a greater product.

At the moment Webiny doesn't track any events inside its user interface. Only events via our CLI are tracked. Which is explained [here](https://www.webiny.com/telemetry). Which this task we propose several upgrades to our telemetry system where we would be looking at how users are interacting with the product, including the interface. 

## Plan

The plan is to implement two levels of telemetry: 
**standard:** includes personal data, like name, email and domain name.
**limited:**: no personal data is included. 

Things that will be tracked are:
- Webiny admin page view
- Name of the Webiny app (PageBuilder, FormBuilder, Headless CMS)
- Webiny successful deploy event
- Webiny unsuccessful deploy event
- Webiny new project created
- Webiny version used

Essentially these 3 things will tell us how actively Webiny is being used, and which apps are used the most.

A user can opt-out from the `standard` monitoring inside the Webiny admin interface. There will be a section under settings to do that. 
From the `limited` monitoring you cannot opt-out. If that causes a problem for anybody, we might explore the option of adding a code level change for those users with instructions on how to disable this. Please let us know in the comments

## Data storage

Webiny will be using a self-hosted tracking tool and the data will be kept inside our own cloud and won't be shared with any 3rd parties. The data will strictly be used to improve the product and gain a sense of the daily active users. The data will never leave our cloud and will never be re-sold to any external entity. 

## Final thoughts
Our community is super important to us and we want to be as transparent as possible about implementing any tracking, thus this ticket. 
It's also important for our community to understand our intentions behind this, that they are all about making Webiny better and being able to hire even more brilliant engineers to work on the product.

**Comment by Pavel910** [comment]
This is implemented in 4.3.0 release.
