### ISSUE TITLE
 landing page builder text box bug

### ISSUE THREAD

**Issue by mike23333** [webiny/webiny-js#1033]
On landing page when I click inside the text boxes the white box editor will appear twice. It seems to be happening when I click a 3rd text box. For example when I first fresh page I will click on a text box. Then another text box and it works fine. But when I click the 3rd text box that's when it starts showing the white box twice the whole time. Just keep clicking and double click in text boxes and you'll see it.

Here's a video of the issue: https://drive.google.com/file/d/1LbM_Gu1E6ZPX5xoduFbSNF_ZCUC_RTnf/view?usp=sharing

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
