### ISSUE TITLE
TooManyRequests during API Gateway removal

### ISSUE THREAD

**Issue by Pavel910** [webiny/webiny-js#1044]
## This is:
- Bug

## Expected Behavior
When running `webiny remove api --env=local` the whole stack should be removed without errors.

## Actual Behavior
Sometimes the removal breaks on `api` resource, with `TooManyRequests` error.

## Possible Solution
Most likely this has something to do with API Gateway endpoint removal without pause in between SDK calls. Need to review the whole removal process and see if there is any interaction with SDK that could cause this.

At this reference: `packages/serverless-aws-api-gateway/utils.js:549` we have 3 functions, each removing it's resources/methods/authorizers in parallel. So if we have 3 endpoints, 3 parallel requests will be made to the AWS SDK. I suspect this to be the main problem here. We should delete each resource in series, with a `pRetry` in case one of them fails.

**Comment by ValiDraganescu** [comment]
For the delete API command the quota is `1 request every 30 seconds per account` per [https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html](https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html)

**Comment by Pavel910** [comment]
Yes, but I think the problem is not that, but too many parallel requests to remove integrations/endpoints/methods. The error is thrown before deleting the main API Gateway.

I'll debug this more if I ever manage to replicate this. So far, I'm unable to replicate no matter how much I deploy/remove :(

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
