### ISSUE TITLE
Headless CMS - Multisite

### ISSUE THREAD

**Issue by jeans** [webiny/webiny-js#1046]
## This is:
- Feature request (first draft)

## Basic idea
- add multisite functionality to webiny CMS 
- run multiple websites/apps from 1 webiny installation and 1 database
- global: user administration, Webiny settings, file management, taxonomy/tags ...
- site specific: site settings (title, description, tags, structured data), xml sitemap, routes/site tree, navigation/menus, front pages, ...

## UX
- the global admin sets up sites (routes, trees, settings)
- global admin assigns editors to sites
- editor UX: a selectbox in left navigation sets the scope for an editor, in terms of loading all pages from one selected site (editor 1 can work on site A and C, editor 2 can only work on site C)

**Comment by Pavel910** [comment]
Hey @jeans thanks for the issue, we'd love to discuss this in more details!

Are we talking about just the Headless CMS here, or do you also want this to apply to the PageBuilder/FormBuilder ?

Please post as much info as you can to give us a better understanding of the final goal. If you have  examples of other systems, maybe some screenshots, etc., everything will help to paint the bigger picture.

Looking forward to discussing this! Cheers!

**Comment by tmikaeld** [comment]
I'd assume it to work just like any shared hosting or multi-site Wordpress.

This would make it possible to use Webiny as a real hosting competitor and would attract a lot of agencies and even hosting providers.

**Comment by jeans** [comment]
Right. You should be able to switch not only between environments, but also between different brands or apis, e.g. like this:
![image](https://user-images.githubusercontent.com/10599/90532903-130a7900-e178-11ea-8a0a-29a79878cfe9.png)

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
