### ISSUE TITLE
npx create-webiny-project new-project 安装错误

### ISSUE THREAD

**Issue by jinyindu** [webiny/webiny-js#1049]
## This is:

- Bug
- Feature request
- Question
- Idea

## Specifications

  - version:
  - OS:
  - Browser:

## Steps to Reproduce the Problem

1.
![image](https://user-images.githubusercontent.com/18224886/85263151-55c61280-b4a1-11ea-814a-f7f6252cdb92.png)

2.
3.

## Possible Solution

![image](https://user-images.githubusercontent.com/18224886/85263187-61193e00-b4a1-11ea-8a6f-2c942dfc89f4.png)``

**Comment by Pavel910** [comment]
Hey @jinyindu, to debug this and find out what package is causing the problem, please run this:

```
npx create-webiny-project my-project --log
```

The `--log` parameter will stream the output of the background process into your `my-project/log.txt` file, and you'll be able to see what package is causing the problem.  Once you have that, send us the error here in this issue.

Cheers!
