### ISSUE TITLE
Page Builder - prevent deletion of a category

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#1054]
Prevent deletion of a category if there are pages linked with it.

The check should be done in this file:
```packages/api-page-builder/src/plugins/models/pbCategory.model.ts:9```

**Comment by TommyJackson85** [comment]
I will work on this this week.

**Comment by doitadrian** [comment]
Sounds awesome, let us know if you'll have any questions. An example of how to achieve this can be found here - `packages/api-headless-cms/src/content/plugins/models/contentModel.model.ts:81`

**Comment by TommyJackson85** [comment]
I'm just curious, what steps did you go about to find this problem? Can you list it out for me so I can find the problem first?

Under pages, I clicked the the plus button at the bottom to select a category (one I created my self) which seemed to create a new page with the category. I edited it and published it, then I deleted the page.

When navigating back to the categories section I found the category still existed.

I haven't done any code changes yet as I just wan't to re create the problem for myself first.
