### ISSUE TITLE
Headless CMS - drodpown menu changing sides

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#1059]
Results are showing above the auto-complete complete - this is fine. 

But when I type something that's not in the suggestions list, the dropdown gets rendered below the input. Shouldn't it be rendered above the auto-complete input as well?

![Untitled](https://user-images.githubusercontent.com/5121148/85390312-f1f72480-b548-11ea-9f9a-3f77dd8c00e6.gif)

**Comment by Pavel910** [comment]
I think is rendered dynamically, based on how large the dropdown is. I don't know if you'll be able to force him to render in one direction. For dialogs at least, it would be best if the large list was rendered below the input as well.

**Comment by doitadrian** [comment]
This above-the-input rendering is our own implementation, so we should be able to make it render above as well.
