### ISSUE TITLE
Test deployment with non-default AWS_PROFILE

### ISSUE THREAD

**Issue by Pavel910** [webiny/webiny-js#1063]
## This is:
- Bug Suspicion

## Expected Behavior
Setting AWS_PROFILE to something other than `default` should deploy everything to that profile.

## Actual Behavior
A user reported that that variables is ignored and `default` profile is used instead.

## Steps to Reproduce the Problem
1.  change AWS_PROFILE in `.env.json` to something other than `default`
2. deploy

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
