### ISSUE TITLE
Fix: 'Authentication error' remains on Login Page after a password change action (preceded by a login failure)

### ISSUE THREAD

**Issue by TommyJackson85** [webiny/webiny-js#1068]
## This is:

- Bug

## Specifications

  - version:
  - Browser:

## Expected Behavior
This is my opinion:
Only related alert messages in response to the most recent action (prior to being redirected to login page), should be displayed. In this case the 'password updated' alert is the only correct response as it was in response to changing the password successfully.

## Actual Behavior

As I also failed to login, prior to deciding to change the password in which I received an 'athentication error' for, the login page has retained the previous failure alert and it is displayed with the 'password updated' alert together. 

I feel this is a glitch and is causing slight confusion. I don't think it's important to keep multiple alert from previous multiple user interactions, only alerts from the most recent action.

## Steps to Reproduce the Problem

1. From Login page, attempt to login in to the database, but give an incorrect password. This should display the authentication error.
2. Without refreshing the page, reset the password successfully, following the correct procedures, until it redirect you to the login page.
3. From here, take note of the two displayed messages. 

<img width="503" alt="password-authentication-error-updated" src="https://user-images.githubusercontent.com/22279028/85625076-c6685d00-b662-11ea-9e66-b829c1d33e93.png">

## Detailed Description

The alerts didn't refresh or were emptied prior to adding new alerts, that is if they are being displayed from a list or set of boolean values for example. This may not just be with this this example. Other pages might have similar glitches might be created from going about multiple actions and scenarios, i.e. failure to register or post a message.

If this issue is universal across the site, I am open to changing this issue's title and posting. I am going about this issue from one example scenario I came across.

## Possible Solution

I have not looked through the code base, as I have only tested this one example but I have come across other similar situations before in other projects.

Would I be right in saying that this is due to potential alerts components not being refreshed or remounted? Are the alerts displaying from a mapped out array of text data OR maybe from boolean state values? I will take a look through the code base if this is a valid issue.

**Comment by Pavel910** [comment]
@TommyJackson85 Good catch! Actually this has to do with the fact that those  2 messages are handled by 2 different components. The first success message is handled by the `Authenticator` component, and the second one by the `SignIn` component.

Some references for you to dig in:
This is where we set the first `success` message: `packages/app-plugin-security-cognito/src/cognito/states/SetNewPassword.ts:33`, and it actually calls a method on the `Authenticator` component, here: `packages/app-plugin-security-cognito/src/cognito/Authenticator.ts:88`.

The `SignIn` component is located here: `packages/app-plugin-security-cognito-theme/src/admin/views/SignIn.tsx`.
In this file you'll see both messages being printed:

![image](https://user-images.githubusercontent.com/3920893/85699484-dcfeca80-b6db-11ea-9db1-a723218df103.png)

What we could do is, if there is an `error`, don't print the `authProps.message`. That would take care of double messages being rendered. Kind of like this:

```jsx
{authProps.message && !error && ( ... )}
```

**Comment by Pavel910** [comment]
@TommyJackson85 just noticed we never got back to this issue :)

**Comment by TommyJackson85** [comment]
What method do you recommend for this ? Should each communicate with a parent component to over write ?

**Comment by Pavel910** [comment]
@TommyJackson85 Try the approach I suggested in my previous comment, the code example is at the very bottom of the message.

**Comment by TommyJackson85** [comment]
>@Pavel910 :
> What we could do is, if there is an `error`, don't print the `authProps.message`. That would take care of double messages being rendered. Kind of like this:
> 
> ```js-jsx
> {authProps.message && !error && ( ... )}
> ```

I tired this, but we want the authProps message to appear after a password change, its the error message we want to remove.

I will take a look at the other files you referenced.

**Comment by TommyJackson85** [comment]
@Pavel910 Maybe comparing previous props and current props to see what was displayed previously, then maybe remounting might work

**Comment by Pavel910** [comment]
@TommyJackson85 the way I see it, using `{authProps.message && !error && ( ... )}` will render the message after a successful password change. Then, when you try to login and fail, the error will be rendered, and the previous password message will disappear, which sounds like what we want.

Not sure if I'm missing something 🤔

**Comment by TommyJackson85** [comment]
> @TommyJackson85 the way I see it, using `{authProps.message && !error && ( ... )}` will render the message after a successful password change. Then, when you try to login and fail, the error will be rendered, and the previous password message will disappear, which sounds like what we want.
> 
> Not sure if I'm missing something 🤔

I think it is good to do this for defensive programming purposes and could also be used for the other way around to display errors (i.e. ```{ error && !authProps.message && ( ... )}``` ). 

However it is not enough and creates other errors (in your suggested case it kept the authentication error alert after successfully resetting password. The reason they were appearing at the same time was because both the error and authProps.message object data were appearing on the console (see my above screenshot of the console log), so `{authProps.message && !error && ( ... )}` wont work in this case.

I can't think of a scenario where more than one alert type should appear, so with that, at least one of them, either the error or authProps.message alert object, should be turned to undefined.

Maybe we could solve this from the ```SignIn``` file, where when both alert data sets appear, we force the incorrect alert object data set to be undefined (either error or authProps.message), that said we need to make sure this solves all cases, force changing the CORRECT object data. For example, After resetting the password successfully (making a success alert appear), you might then fail a login. In this case, we need to make sure the authentication error appears only and not also the password success reset alert.

**Comment by TommyJackson85** [comment]
You were referring to line 88 in the ```Authenticator.ts``` file:
<img width="663" alt="Screenshot 2020-07-13 at 01 29 28" src="https://user-images.githubusercontent.com/22279028/87260201-59e5be80-c4a8-11ea-9543-c701d019a9d2.png">

Could we try and tackle it from here?

**Comment by Pavel910** [comment]
@TommyJackson85 I'll need to dive into the code to provide some useful directions, will let you know when I check this out.

**Comment by TommyJackson85** [comment]
> @TommyJackson85 I'll need to dive into the code to provide some useful directions, will let you know when I check this out.
Ok, no problem.

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
