### ISSUE TITLE
fix: Hide Settings tab within the Side nav for user accounts with no permissions.

### ISSUE THREAD

**Issue by TommyJackson85** [webiny/webiny-js#1073]
## This is:

- Bug

## Specifications

  - version:
  - Browser:

## Expected Behavior
When creating/adding a new user (from an administrative user account) without giving new user any access permissions (no roles assigned), that new user (when logged in) should not be able to see any Settings tab / dropdown.

## Actual Behavior
After logging in (from a user account with no permissions), the settings dropdown bar can be seen with no links to click when dropped down. Furthermore there is a big empty space below it wether closed or opened.
I can't even tell when it is open or closed from these two images:

<img width="249" alt="Screenshot 2020-06-26 at 12 39 17" src="https://user-images.githubusercontent.com/22279028/85853295-29b0d700-b7aa-11ea-888f-4f242bd768f9.png">
<img width="243" alt="Screenshot 2020-06-26 at 12 39 06" src="https://user-images.githubusercontent.com/22279028/85853312-303f4e80-b7aa-11ea-9839-bb21089cbaef.png">

## Steps to Reproduce the Problem

1. Create a new user via Security -> Users module, don't assign any roles to the new user.
2 . Log in with the new user credentials
3. Open the main navigation
4. Take note of the side and the settings dropdown within it.

## Detailed Description

The settings tab and drop down should be removed, and MAYBE replaced with a guide, or other use that is engaging to the new user, but for now we should focus on removing the Settings tab.

## Possible Solution

Me and @Pavel910 were discussing this in [Pull Request: 1066](https://github.com/webiny/webiny-js/pull/1066).

@Pavel910 noted one of the challenges:
> @TommyJackson85 it's difficult to know if Settings menu has any items visible, or is completely empty. Each menu plugin is standalone and handles only itself. We'll have to think about how to approach this.
> 
> This is where the main `Settings` menu is being rendered: `packages/app-admin/src/plugins/init.tsx:24`. As you can see, it just loops over the `settingsPlugins` and renders those plugins, which may or may not render any DOM depending on the scope.

From this initial post, we could discuss further possible solutions.

**Comment by Pavel910** [comment]
@TommyJackson85 I don't think that a message about permissions is the right way to go. If you don't have permissions to see something, then you just don't see it. Imagine you being an app admin, and you have 2 team members who create and publish content. You don't want them to see any Settings at all, so you don't assign scopes to their accounts.

When they login, they simply won't see the menu. It wouldn't really be nice to see a message `You're not authorized to see this` every time you open a menu. 

So I think we just need to figure out how to hide the `Settings` menu if it's empty.

**Comment by TommyJackson85** [comment]
> @TommyJackson85 I don't think that a message about permissions is the right way to go. If you don't have permissions to see something, then you just don't see it. Imagine you being an app admin, and you have 2 team members who create and publish content. You don't want them to see any Settings at all, so you don't assign scopes to their accounts.
> 
> When they login, they simply won't see the menu. It wouldn't really be nice to see a message `You're not authorized to see this` every time you open a menu.
> 
> So I think we just need to figure out how to hide the `Settings` menu if it's empty.

Ok, good point. I will edit my initial post and heading in regards to this.

**Comment by TommyJackson85** [comment]
@Pavel910 I will look into this now. I might create a PR too.

**Comment by Pavel910** [comment]
UPDATE: this issue is not dead, we're just redoing the security permissions, and once that is in place we can get back to this issue and see how to properly handle that Settings navigation.
