### ISSUE TITLE
fix: Action link Widgets displayed on main page to unauthorised users.

### ISSUE THREAD

**Issue by TommyJackson85** [webiny/webiny-js#1074]
## This is:

- Bug

## Specifications

  - Browser:

## Expected Behavior

If an account has no permissions to either of these widgets / links I would think they should not be displayed.

<img width="1259" alt="Screenshot 2020-06-26 at 12 58 25" src="https://user-images.githubusercontent.com/22279028/85856518-1143bb00-b7b0-11ea-8bfa-2fd0bf0bfd75.png">

## Actual Behavior

They are displayed from an account with no permissions, and when accessing them they report the following error:

<img width="385" alt="Screenshot 2020-06-26 at 13 25 14" src="https://user-images.githubusercontent.com/22279028/85856793-8a431280-b7b0-11ea-8e00-7b6f3034c2be.png">

## Steps to Reproduce the Problem

1. Create a new user via Security -> Users module, don't assign any roles to the new user.
2. Log in with the new user credentials
2. Open the main navigation and take note of the three widgets.
4. Attempt to navigate to each link.

## Detailed Description

Each panel be hidden if not permitted.

## Possible Solution

Follow similar approaches from
#957 

Hiding using ```SecureView``` and applying the correct scopes for each, where the widgets might be displayed. For example, this ```welcomeScreenWidget``` file from the ```app-form-builder``` folder:

<img width="698" alt="Screenshot 2020-06-26 at 13 40 24" src="https://user-images.githubusercontent.com/22279028/85857970-b495cf80-b7b2-11ea-8023-128fe042a03a.png">

Would you apply the SecureView jsx tag to the WelcomeScreenWidget file?

Maybe this best for a separate issue, but if one or two are only permitted and as such disrupt the design of the site, we could also alter the design with such scenarios. What grid system does the application use? (i.e., CSS Grid ? UI framework grids? CSS / SASS stylings? )

**Comment by Pavel910** [comment]
I'll include @EmilK15  in the conversation, he's the author of this Welcome screen.

**Comment by TommyJackson85** [comment]
No problem, as I solved an issue similar to this, I would be willing to create a PR on this.

**Comment by Pavel910** [comment]
@TommyJackson85 sure, it's most welcome! 🚀 ❤️

**Comment by Pavel910** [comment]
Regarding the Grid, we use Material, and here are the docs: https://storybook.webiny.com/?path=/story/components-grid--usage

But for that Welcome screen in particular I think we went with flexbox and fixed width of widgets, otherwise on large screens it would be stretched way too much. Feel free to dive in and if you need more details, @EmilK15 will be able to assist you.

**Comment by EmilK15** [comment]
hey @TommyJackson85 Taking a look at the details now

**Comment by EmilK15** [comment]
If you are looking to change the Scope of what should appear to the user; it would be important to note here that there are multiple widgets following this plugin type: `admin-welcome-screen-widget`. So the solution you come up with would need to be applied in the following files: `app-form-builder\src\admin\plugins\welcomeScreenWidget`, `app-headless-cms\src\admin\plugins\welcomeScreenWidget`, and `app-page-builder\src\admin\plugins\welcomeScreenWidget`.
Let me know how the process is coming along and I can provide assistance :)
