### ISSUE TITLE
Headless CMS - Add ApolloClient for CMS to Webiny site app

### ISSUE THREAD

**Issue by gpips** [webiny/webiny-js#1083]
Is it possible to create a way to use `useQuery` from apollo in the site app allowing to choose which api endpoint to query?

For instance switching between /graphql and /cms/manage or read.

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
