### ISSUE TITLE
Page Builder - spacer layout element not rendering

### ISSUE THREAD

**Issue by gpips** [webiny/webiny-js#1089]
While using the page builder app I can click and drag the spacer element in between two other elements and it creates a gap of 20px. then I go back to the page-builder pages list page the preview on the right does not contain the 20px of space between elements.

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
