### ISSUE TITLE
Handle partial deploy resources in any order

### ISSUE THREAD

**Issue by Pavel910** [webiny/webiny-js#1091]
## This is:
- Bug

## Expected Behavior
When you run a partial deploy, like `yarn webiny deploy api apolloGateway apiOtpService  --env=dev`, it should deploy the 2 resources without errors.

## Actual Behavior
Currently, it's important to specify resources in the specific order, the way they depend on each other internally.
For example: `yarn webiny deploy api apolloGateway apiOtpService --env=dev` will throw an error `Error: invalid reference ${apiOtpService.name}`.

## Possible Solution
We need to handle these parameters in a way that the user doesn't have to think about the order of resources. Order of resources should be handled internally using the dependency graph.

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
