### ISSUE TITLE
Headless CMS - cannot delete models

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#1092]
I had two CMs, Blog and Category, where Blog was referencing Category.

I tried deleting the Category CM, and an error message was correctly shown:
![image](https://user-images.githubusercontent.com/5121148/86247906-6e26e300-bbad-11ea-929c-e0078b4305f9.png)

After that, I went to remove the Blog CM, which worked, but the above error message was still shown when I again tried to remove the Category CM, which should not happen.

The `referencedIn` (`packages/api-headless-cms/src/content/plugins/modelFields/refField/addRefFieldHooks.ts`) is probably not being updated correctly, so we'll need to check that. We'll also going to need to upgrade the `packages/api-headless-cms/__tests__/refFieldReferencedIn.test.js:` test probably.

**Comment by EmilK15** [comment]
After trying to reproduce the steps above,
in this case when deleting Category I was able to do so without error. The reference field within the CM for Blog was then changed to blank when looking at that specific Blog.

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
