### ISSUE TITLE
create-webiny-project error logging

### ISSUE THREAD

**Issue by Pavel910** [webiny/webiny-js#1093]
## This is:
- Bug

## Expected Behavior
`npx create-webiny-project project-name` should print error log when something goes wrong.

## Actual Behavior
If something breaks, the following happens:
![image](https://user-images.githubusercontent.com/3920893/86271510-46e00e00-bbcd-11ea-8c82-2bf1a7e9dbc5.png)

## Possible Solution
1) `log` must either have a default value you can use to check if logging is necessary, or...
2) Check if  `log` is actually a string before doing `log.startsWith`

The screenshot below shows the place where the code explodes and we never get to see the real error that triggered the `catch` block:

![image](https://user-images.githubusercontent.com/3920893/86271677-9cb4b600-bbcd-11ea-9e7d-033a6f608d05.png)

**Bonus bug**: `log.startsWitch("file:")` also shown in the screenshot.

**Comment by MasMedIm** [comment]
I'm unable to create a project because of that problem, stuck in step 1! A fix would be appreciated

**Comment by Pavel910** [comment]
@MasMedIm Just add a `—log` flag to the command and you’ll get a log file with full log and an error, if any:

```
npx create-webiny-project my-project —log
```

**Comment by bbarthel** [comment]
When I run the command today I get this:

**Comment by Pavel910** [comment]
@bbarthel @MasMedIm just realized I'm commenting on an issue that I myself created exactly for the problem you're running into 😅 This will be fixed on Tuesday, for our next release. Stay tuned :)
