### ISSUE TITLE
Headless CMS - remove old `searchModel` property

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#1097]
This field isn't used anymore so we should remove it. It's present on all fields in `packages/api-headless-cms/src/content/plugins/modelFields/`

![image](https://user-images.githubusercontent.com/5121148/86464170-3ba4f380-bd2f-11ea-88a8-8cb572b629c4.png)

**Comment by TommyJackson85** [comment]
I will work on this @doitadrian

**Comment by TommyJackson85** [comment]
@doitadrian check the pull request to see if I'm going about this correctly. Wasn't sure if you wanted to remove searchModel or the model parameter of searchModel.
