### ISSUE TITLE
Version checker 

### ISSUE THREAD

**Issue by SvenAlHamad** [webiny/webiny-js#1098]
To notify and incentivize users to keep their Webiny installation up to date we need to provide them with a visual cue. My suggestion is to have a small UI widget that's part of the welcome screen which will tell the user if their Webiny version is up to date. 

The widget can be placed on the right side of the user's welcome screen.
![image](https://user-images.githubusercontent.com/3808420/86476725-fbe60800-bd3e-11ea-8d72-a3c691f63e76.png)

The widget should act as an indicator with 2 states:
1. New version available
![image](https://user-images.githubusercontent.com/3808420/86477946-554f3680-bd41-11ea-8cb5-eccedd009a0a.png)
2. Up to date

When a user clicks on this widget we should display a dialog, like an iframe, containing certain content. That content will contain upgrade instructions together with a change log.

**Comment by Pavel910** [comment]
This is very much doable. We could pull in changelog from Github release, it's not always beautiful, but at least it's a solid source located in one place. 

Upgrade instructions are sometimes one command, and sometimes a whole blog post. I think that to make things simple, we need to only focus on the contents of the Github Release, pull that and display in the dialog. Our Release always includes instructions for upgrade, or a link to the blog post, so the information is there.

**Comment by doitadrian** [comment]
Maybe an easier solution would be just to have this link to a `docs.webiny.com` page, on which we would have all upgrade instructions, so for `4.1.0 -> 4.2.0`, `4.2.0 -> 4.3.x`, etc....

That means the user would have to apply upgrade instructions for each version, which is a MUST, as @Pavel910 mentioned.

**Comment by Pavel910** [comment]
@doitadrian our Github Releases contain those links so using the release body covers both change log and upgrade instructions. It's easy enough to pull in the release data via public API: https://api.github.com/repos/webiny/webiny-js/releases/latest.

We just need to somehow communicate that sometimes you can't skip version and need to apply upgrades one by one.

**Comment by SvenAlHamad** [comment]
The goal is to keep the users on the latest version. I would imagine a minority of users is after the changelog, but if they need it, we can just provide a link.

My thought would be to kind of power this with our headless cms and have a model in there that controls the content which will be displayed when they click on this version icon. This way we can experiment with a few approaches. We can, for example, move the upgrade instructions to the top and then highlight 1 or 2 top changes with a link to the changelog for details.

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
