### ISSUE TITLE
Project state management

### ISSUE THREAD

**Issue by Pavel910** [webiny/webiny-js#1099]
The goal of this issue is to give an overview and reasons behind current project state management, and collect feedback from the community on potential improvements.

## Current state of things

Our default deployment mechanism is provided by [@webiny/cli-plugin-deploy-components](https://github.com/webiny/webiny-js/tree/master/packages/cli-plugin-deploy-components). Under the hood, that mechanism uses AWS SDK to create/update/remove resources on your AWS account.

Webiny supports deployment of multiple stacks ([read this article](https://docs.webiny.com/docs/deep-dive/stacks) to learn about stacks ), and multiple environments. The environments are artificially created using resource naming, since not every AWS service has a concept of stages (API Gateway is one of the rare services that has a built-in concept of stages). Note that  terms `stage` and `environment` mean the same thing, and we tend to use the term `environment`, so that's what you'll see from this point on. State of your infrastructure is stored in `.webiny` folder, in the root of your project.

### Environments

To support `environments`, we have decided to use a particular naming of resources, which looks like this:
`{stateId}_{projectName}_{stack}_{env}_{resourceName}`. Once your stack is deployed, and you open your AWS console, you will see your resources named something like this: `49ae3be_webiny-js_api_dev_apolloGateway`.

- `{stateId}` is an auto-generated ID to help name your resources uniquely
- `{projectName}` comes from `webiny.root.js` file, and is initially set for you by `create-webiny-project`
- `{stack}` is the name of your stack folder, for example: `api`, `apps`, or some of your custom stacks
- `{env}` comes from `webiny deploy stack --env=dev` command, so `dev` will become part of the resource name
- `{resourceName}` comes from `resources.js` file

### Why do we need `stateId` ?

We need to clarify one key thing, as it is the only reason why things with state management are more complicated than they would ideally be: AWS S3 bucket names are *globally unique*. All other resources are unique on AWS account level, but S3 buckets are unique on AWS level. 2 users can't have buckets with same names, but they can have 2 Lambda functions with same names just fine. 

`stateId` helps us create unique resource names per project instance, and also takes care of global uniqueness. `Project instance` means `a project created using create-webiny-project`. Let's stay away from `git`, multiple computers or teams for a moment, we'll get to that soon enough.

So, you've created your project, you have your unique `stateId` generated for you in `.webiny/state/_.json` file and that ID is now used to create unique resource names when you deploy your stacks to AWS. During project bootstrap, we also generate an S3 bucket name, and store it into `api/.env.json` under `default` set of environment variables, using `S3_BUCKET` name. This means that all your `api` stack environments will use that particular S3 bucket name, unless you specify a new name for a different environment.

As long as you have that `.webiny` folder with the same `stateId`, the deployment mechanism will use those resources. If you delete that whole folder, the deployment mechanism will generate a new `stateId` and will lose any knowledge of your existing cloud resources. Instead, next time you run a `deploy`, new resource names will be generated, and it will deploy your whole stack from scratch, as if nothing ever existed before. 

As long as you're working alone, on a single computer - this setup will work perfectly fine, and you'll have no issues. However, that will rarely be the case and we need to dive deeper and analyze the possible setups for multiple computers, and teams.

## One developer - multiple computers

> IMPORTANT: this particular use-case is focusing on 1 developer, using a version control system all by himself.

Many of us work on multiple computers, but we still want to work on the same project. There are 2 easy ways to handle this use-case:
1) Add `.webiny` folder and your `.env.json` files to Git, and push them with the project. This way, your repository will be the source of truth for your state, and you can easily switch between several computers. Simple push/pull is all you'll need to have your state synchronized.

2) Store `.webiny` folder and your `.env.json` files to an S3 bucket. This way your state files are not in the VCS, and each time you run a `deploy`, you will pull the current state from your S3 bucket, and upload the new state to the bucket when `deploy` has finished (this is easily done using a simple CLI plugin). This approach is also very suitable for CI environments.

## Many developers (teams)

This section represents our workflow at Webiny. We have found this one to be the most suitable for teams, and so far we never had any real problems with it. The setup looks like this:
- each team member works on his own AWS account, or a company sub-account. The goal is for every team member to work on a completely isolated account.
- each team member has his own database (we use Mongo Atlas).
- each team member has his own state files (`.webiny` and `.env.json`) - this way the whole team works on the same code base, using Github (in our case), but every team member has his own state/configuration files that are never pushed into the repository. 

Using this setup, we never had any clashes or problems with state, because of complete isolation.

To make this setup possible, we introduced a simple script that prepares the project for every new developer. It generates the aforementioned `.webiny/state/_.json` and generates all the necessary `.env.json` files. An example can be found in our repository: https://github.com/webiny/webiny-js/blob/master/scripts/setupRepo.js

Keeping state isolated between developers is the key to avoiding problems. You won't be able to share state between developers, as each deploy/removal will modify the state files and it will be a nightmare to sync it between team members.

## CI/CD

This one is simple enough: simply store `.webiny` folder and your `.env.json` files to an S3 bucket. This way your state files are not in the VCS, and each time you run a `deploy`, you will pull the current state from your S3 bucket, and upload the new state to the bucket when `deploy` has finished. 

There is also a good example of this in one of the issues on our Github: https://github.com/webiny/webiny-js/issues/960. This one shows that you can easily push/pull state from S3 using plain AWS CLI.

## Any feedback?

We'd like to hear from you - the community. Send us your feedback, you ideas, concerns, experience, etc. We want to be sure that you can configure Webiny to fit your workflow. Please comment on this issue and let's have a good discussion if there is anything that you'd like to clarify or suggest.

**Comment by jcode-hub** [comment]
I'll leave my CI/CD pipeline here: https://github.com/oev-berlin/aws-cdk-webiny-deployment-pipeline it's written in python with the AWS CDK
