### ISSUE TITLE
Apollo GraphQL Service Scaffold - Removal Command

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#1107]
We had a question about removing the previously scaffold-generated GraphQL Apollo Service.

It would be really useful to have it, so that our users don't have to manually remove the generated files and entries in the `resources.js` file.

What do you think would be the best approach for this?

Any ideas?

I'm starting to think that choosing `Apollo GraphQL Service` scaffold could actually be another menu, from where we can create and remove scaffolds, but maybe also generate new models / parts of GraphQL schema.

But all in all, I'm sure this is not high on core team's priority list, so ideally, somebody from the community could take this over.

**Comment by tbender-unicon** [comment]
This would be helpful. In fact, it would be helpful to know how to do this manually as well. I have created scaffold service `api/catalog` with an entity `organization` --- but now my playground does not come up and I'd like to remove this scaffold service and bring up the playground and try again.

**Comment by doitadrian** [comment]
Good point @tbender-unicon.

For starters, can you try removing the entry in the `resources.js` file and redeploy it?

For example, if I added the api/books service, I would have something like this in it:
![image](https://user-images.githubusercontent.com/5121148/92244384-1d8c7880-eec3-11ea-807d-52ddffebcf89.png)

Can you try that?

**Comment by tbender-unicon** [comment]
YEs, I"ll remove that. Is that all I have to remove then?

**Comment by doitadrian** [comment]
Just to confirm, yeah, that should be removed as well.

Good catch 👍
