### ISSUE TITLE
Error during Installation 4.3.0 TypeError: Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by jinman** [webiny/webiny-js#1110]
- Bug
## Specifications

  - version: 4.3.0
  - OS: Catalina
  - Browser:Chrome

## Expected Behavior
npx create-webiny-project new-project should install a new project

## Actual Behavior

```
MacBook-Pro:cms$ npx create-webiny-project new-project
  Creating project at /Users/xxx/Projects/Projects/cms/new-project:
  ✔ Pre-template setup
  ✖ Install template package
    → Failed to install template package

  Aborting installation.
  Unexpected error. Please report it as a bug:
TypeError: Cannot read property 'startsWith' of undefined
    at /Users/xxx/.npm/_npx/69061/lib/node_modules/create-webiny-project/index.js:236:21
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async run (/Users/xxx/.npm/_npx/69061/lib/node_modules/create-webiny-project/index.js:234:9)

  Done.
```

I had previous versions (3.xx) of webiny installed but I removed it manually from AWS as well as from my system.

**Comment by Pavel910** [comment]
Hey @jinman, this is fixed and will be released in a few hours. We're working on a 4.4.0 release right now :)

**Comment by Pavel910** [comment]
@jinman `4.4.0` is live, so feel free to run `npx create-webiny-project new-projec` again :)

**Comment by jinman** [comment]
@Pavel910,

I tried 4.4.0 but now it just does:
```
MacBook-Pro:cms xxx$ npx create-webiny-project serverless-cms
  Creating project at /Users/xxx/Projects/Projects/cms/serverless-cms:
  ✔ Pre-template setup
  ✖ Install template package
    → info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

  Cleaning up project...
  Project cleaned!
```

Does it have to do with the fact that I had previous versions of webiny installed? Also what is a best way to remove webiny stacks in a clean way since there are no CFN stacks. I tried npx remove-aws-resources and had to manually remove the previous instances.

**Comment by Pavel910** [comment]
@jinman there should be an error printed... this look very weird. Try running like this:
`npx create-webiny-project serverless-cms --log` - it will create a log file `cwp-log.txt` and you will be able to see errors in there, if any.

Regarding stacks removal: if the project is not broken, there is a `yarn webiny remove api --env=xy` command to remove a particular stack for a particular environment. If the stack is broken, then `remove-aws-resources` is the only way to cleanup everything.

**Comment by jinman** [comment]
contents of cwp.log.txt file

```
{
  "context": {}
}

```

**Comment by Pavel910** [comment]
@jinman this is definitely not what is supposed to be in there. I'll debug this and get back to you.

**Comment by Pavel910** [comment]
@jinman this PR fixes this particular problem and improves the logging overall: https://github.com/webiny/webiny-js/pull/1117.

It will be released on Tuesday with the other stuff we're working on at the moment.

I'm really interested in seeing the error that's causing you problems.

**Comment by jinman** [comment]
@Pavel910, thanks for your help. but now I am getting...

```
MacBook-Pro:cms xxx$ npx create-webiny-project serverless-cms
npx: installed 183 in 8.143s
  Creating project at /Users/xxx/Projects/Projects/cms/serverless-cms:
  ✔ Pre-template setup
  ✖ Install template package
    → info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
    Create project folders
    Set up project dependencies
    Initialize git
    Get proper package versions
    Resolve packages
    Install dependencies
    Run template-specific actions

    ERROR OUTPUT:
    ----------------------------------------
    Command failed with exit code 1: yarn add --exact @webiny/cwp-template-full@latest --cwd /Users/xxx/Projects/Projects/cms/serverless-cms
    error An unexpected error occurred: "https://registry.yarnpkg.com/@webiny%2fcwp-template-full: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:5000".
    yarn add v1.22.4
    info No lockfile found.
    [1/4] Resolving packages...
    info There appears to be trouble with your network connection. Retrying...
    info There appears to be trouble with your network connection. Retrying...
    info There appears to be trouble with your network connection. Retrying...
    info There appears to be trouble with your network connection. Retrying...
    info If you think this is a bug, please open a bug report with the information provided in "/Users/xxx/Projects/Projects/cms/serverless-cms/yarn-error.log".
    info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
    ----------------------------------------

    Please open an issue including the error output at https://github.com/webiny/webiny-js/issues/new.
    You can also get in touch with us on our Slack Community: https://www.webiny.com/slack


  Writing log to /Users/xxx/Projects/Projects/cms/cwp-logs.txt...
  Cleaning up project...
  Project cleaned!
```

**Comment by Ashu96** [comment]
@jinman It looks like there is a network problem on your end as the error message suggests.

**Comment by Pavel910** [comment]
@jinman this isn't really related to Webiny. It's an `npm` issue. It looks like your registry is configured to be at `127.0.0.1:5000`. A wild guess is that you're hosting a private registry using `vedaccio` or something.

Look into that, or simply switch the registry back to the original `https://registry.npmjs.org`..

**Comment by Pavel910** [comment]
I'm closing the issue, as we now moved away from the original problem.
