### ISSUE TITLE
Fix: On shorter screen widths, the display of Welcome screen's widgets and footer links could be improved for better UX

### ISSUE THREAD

**Issue by TommyJackson85** [webiny/webiny-js#1115]
## This is:

- Bug

## Specifications

  - version:

  - Browser:

## Expected Behavior

Details on the welcome page should be better displayed for reading and clarity.
Grid of columns / widgets should change to full width or 2 columns on smaller screen widths.
Text could be decreased in size.
Links shouldn't overlap each other and should be better aligned.

## Actual Behavior

On smaller screen widths: 

Widgets remain set in 3 columns. It's not very user friendly and it is harder to read -

<img width="582" alt="Screenshot 2020-07-09 at 00 22 08" src="https://user-images.githubusercontent.com/22279028/86981029-64891680-c17d-11ea-8724-3c10707e9cf9.png">

The footer is inconsistent. "Documentation" and "code examples" links aren't aligned. Other links over lap with each other -

<img width="471" alt="Screenshot 2020-07-09 at 00 22 54" src="https://user-images.githubusercontent.com/22279028/86981212-db261400-c17d-11ea-8bd9-82d4912a2b30.png">
<img width="728" alt="Screenshot 2020-07-09 at 00 23 11" src="https://user-images.githubusercontent.com/22279028/86981216-dcefd780-c17d-11ea-9c49-8d1761902e38.png">

## Steps to Reproduce the Problem

1. Login to an authorized account to make sure the widgets appear.
2. Decrease screen width to small / medium size.
3. Take note of the widgets and footer links bad design.

## Detailed Description

Widths of widgets need to be changed for smaller screen sizes. From what I already understand, they already change to widths for rows of two when less than three widgets are displayed.
Other changes like reduction of text and icon sizes, column alignments, etc., need to be changed to make it more clear.

## Possible Solution

Changes are probably to be done from  ```packages/app-plugin-admin-welcome-screen/src/components/welcome.tsx```, but correct me if I am wrong.

For the widgets:
We could possibly include Grid jsx tags for the widgets, but I don't know if we need them.
We need to find what already changes to rows from 3 to 2, where only 1 or two are displayed. This might be a good place to start.
Would be good to know what is changing the sizes of the widgets. 
When only 1 or 2 widgets are displayed they are in rows of two.

Other similar issues may be prevalent on this page, so I am open to adding more tasks and highlighting more issues for this.

**Comment by Ashu96** [comment]
Hey, @TommyJackson85 thanks for all this information.
Could, you please tell us more about the screen size? (i.e what does small and medium actually means in pixel or device)

Because in my testing the welcome screen's widgets look good on IPad pro and IPad and I'm not sure if the admin app has a use-case for mobile screens.

**Comment by TommyJackson85** [comment]
Yeah I think it's not bad on iPad Pro to be fair:
<img width="563" alt="Screenshot 2020-07-09 at 13 31 59" src="https://user-images.githubusercontent.com/22279028/87040484-adc28000-c1e8-11ea-943c-c36fee3e10f2.png">

The regular iPad makes the text squash on the widgets and footer links could be better aligned maybe:
<img width="551" alt="Screenshot 2020-07-09 at 13 31 42" src="https://user-images.githubusercontent.com/22279028/87040477-aac78f80-c1e8-11ea-8dfb-bffa7c1fa4cb.png">

Are you getting similar results?

On mobile it gets much worse.

<img width="290" alt="Screenshot 2020-07-09 at 13 43 51" src="https://user-images.githubusercontent.com/22279028/87041528-46a5cb00-c1ea-11ea-9735-12e17f0870de.png">

Those are all tests from Chrome browsers, maybe they are different on actual mobile and iPads.

I've spotted these errors from the Chrome browser.
On browsers if you decrease the width of the browser tab you can pin point where the design gets messy.
At around 1000 width, the footer links start to get messy.
At around 898 width, the widgets start to get a bit messy.
You need to keep in mind the widget's grid changes from rows of three to two with less widgets displayed, so maybe it is better to start from that file that makes those changes.

Another alternative is to have a minimum width at the point where it breaks, but it would mean users would have to scroll left and right.

Material-UI's Grid system doesn't appear to be used for the widgets, atleast no from the ```welcome.tsx``` file

**Comment by Ashu96** [comment]
@TommyJackson85 thanks for reporting this issue.

I'm still not sure that the admin app is meant to be used via a mobile device.
Using any admin app on mobile is not an ideal case IMHO.
Anyhow, this issue will be resolved soon and the result will look something like this:

![localhost_3001_(iPhone X)](https://user-images.githubusercontent.com/13612227/87150437-ade97b00-c2cf-11ea-96c1-5b88e96dd749.png)

**Comment by TommyJackson85** [comment]
Yeah, I’m reporting this error from web browsers only. Not mobile. It could be different on mobiles for sure. Best thing to do is check the live website from a mobile device.

**Comment by TommyJackson85** [comment]
@Pavel910 the problem is still prevalent on desktop browsers:
<img width="476" alt="Screenshot 2020-07-14 at 14 42 54" src="https://user-images.githubusercontent.com/22279028/87434006-dc25ce00-c5e1-11ea-841a-08f049ecc022.png">

**Comment by Pavel910** [comment]
@TommyJackson85 Admin app is not supposed to be used on mobile devices. You can force any app to  get out of whack if you hit the correct dimension where it breaks. We won't be investing any time at all into trying to making it work on small screens, especially not touch screens. 

The reason is simple: PageBuilder, FormBuilder and CMS UI relies heavily on drag&drop, which won't work on any touchscreen device. There's no point in even attempting to make it work. Touch screen devices require a completely different approach to UI/UX design.

**Comment by TommyJackson85** [comment]
@Pavel910 I'm not talking about mobile devices though, I am talking about browsers on desktops and laptops when you decrease the width of the browser. The screenshot is from a laptop chrome browser decreased in width.

I pulled the master branch again to get most recent changes and ran yarn start from apps/admin to check, and the same design issues are there.

By all means though, if this is not even import for desktop/laptop browsers, fair enough.

**Comment by Pavel910** [comment]
@TommyJackson85 Desktop or mobile, it doesn’t really matter, it’s the screen width that’s the constraint. If the viewport width is smaller than around 1200px, you can safely ignore all the problems.
