### ISSUE TITLE
Deployment to non "default" account not possible

### ISSUE THREAD

**Issue by jcode-hub** [webiny/webiny-js#1123]
## This is:

- Bug

## Expected Behavior
When the value of "AWS_PROFILE" in .env.json is changed to "anotheraccount" the deployment should happen in "anotheraccount"

## Actual Behavior

When the value of "AWS_PROFILE" in .env.json is changed to "anotheraccount" the deployment happens in "default" account. It's not possible to deploy in other accounts except of changing your .aws/credentials file

## Steps to Reproduce the Problem

1. create a new project
2. in .env.json change the account you want to deploy in from "default" to something else
3. run the deployment
4. check your default aws account. Everything will be in there

**Comment by Pavel910** [comment]
@jcode-hub several users reported this so far, but I couldn't reproduce it myself using non-default profile.
I'll give it some more testing but we're currently very busy with other stuff, so I can't promise a quick fix.

Hopefully I'll manage to reproduce this, then we can at least begin to think about the cause of the problem.

**Comment by jcode-hub** [comment]
@Pavel910 let me know if I can provide any further information.

**Comment by alessandrolosacco** [comment]
+1

**Comment by jcode-hub** [comment]
the issue seems to be gone with the new version (checkd with cwp-template-cms@4.8.0)
