### ISSUE TITLE
Content Model validation message not show in the dialog

### ISSUE THREAD

**Issue by Pavel910** [webiny/webiny-js#1124]
## This is:
- Bug

## Expected Behavior
When an invalid model name is specified, for example `3D Asset`, a validation message should be shown under the `Name` input.

## Actual Behavior
Validation fails with a very obscure `Validation failed` error:
![image](https://user-images.githubusercontent.com/3920893/87415973-49c7ff00-c5ce-11ea-97f6-dba593bc164a.png)

## Steps to Reproduce the Problem
1. Open `New Model` dialog
2. Enter `3D Asset` for model name
3. Click `Create`

## Possible Solution
The validation message should be show in the form, ideally beneath the `name` input. The validation could also be performed on the client side, to avoid form submission all together.

**Comment by WioZak** [comment]
I'd like to be assigned to this issue. Participating in Hacktoberfest, first-timer in open-source.

**Comment by Pavel910** [comment]
Hey @WioZak! Welcome! Here are some links to get you started:
Some instructions about contributing: https://github.com/webiny/webiny-js/blob/master/docs/CONTRIBUTING.md
Our YouTube channel with different videos about the project, how stuff works, etc: https://www.youtube.com/c/Webiny/videos

Regarding the issue:
https://github.com/webiny/webiny-js/blob/master/packages/app-headless-cms/src/admin/views/ContentModels/NewContentModelDialog.tsx#L126

You'll see there's a validator missing from the `description` field. See other fields in the same file for examples of how to add a validator to the <Bind> component.

If you have any questions, please do leave a comment or reach out via Slack, it's a lot faster :)
Cheers!

**Comment by josselineperdomo** [comment]
Hello! Does @WioZak still working on this issue or is this available? I'd like to work on this :)

**Comment by AlbionaHoti** [comment]
@WioZak can you please post an update of your progress on the issue and the solutions you tried (communication here is key) - Join our[ slack community](http://webiny.com/slack?utm_source=GitHub&utm_medium=webiny-slack-invite&utm_campaign=webiny-hacktoberfest-slack-github&utm_content=webiny-slack-community&utm_term=W00173) to communicate faster with the community and the core team. Enjoy :)

@josselineperdomo if @WioZak can't continue with the issue, we can assign it to you :)

**Comment by josselineperdomo** [comment]
Hello again! @AlbionaHoti Please let me know if I can start working on this issue :)

**Comment by AlbionaHoti** [comment]
Hey @josselineperdomo, since @WioZak didn't respond and it's been 12 days since his last activity, you can continue with the issue :)

**Comment by WioZak** [comment]
Hi! Sorry for not responding, I had issues with my hardware. If it’s ok with you, I’ll find another task.

**Comment by josselineperdomo** [comment]
@AlbionaHoti and @Pavel910 I opened a PR to solve this issue, but there is a stage in the actions which doesn't pass. Please let me know any comments :blush:
