### ISSUE TITLE
Create new Content Model dropdown has wrong background in dark-mode

### ISSUE THREAD

**Issue by EmilK15** [webiny/webiny-js#1125]
This is:
- Bug

## Expected Behavior
You should be able to see the actual content models to choose from instead of white background on white text.

## Actual Behavior
Most likely black/grey background for that section

## Steps to Reproduce the Problem
1. Select Dark mode on the top right hand corner of the page
2. Click on Create Model
3. Click on Group to select from dropdown

## Detailed Description
![image](https://user-images.githubusercontent.com/9532882/87437746-b4703f00-c5bc-11ea-9a96-df379d697220.png)

**Comment by imrishabh18** [comment]
I would like to take up this issue

**Comment by Ashu96** [comment]
Sure @imrishabh18 :100: 
Welcome! Here are some links to get you started:
Some instructions about contributing: https://github.com/webiny/webiny-js/blob/master/docs/CONTRIBUTING.md
Our YouTube channel with different videos about the project, how stuff works, etc: https://www.youtube.com/c/Webiny/videos

Regarding this issue:
Here is the code responsible for creating the `New Content Model` dialog:
https://github.com/webiny/webiny-js/blob/master/packages/app-headless-cms/src/admin/views/ContentModels/NewContentModelDialog.tsx#L118

If you have any questions, please do leave a comment or reach out via [Slack](https://www.webiny.com/slack/) :)
Cheers!

**Comment by adithyaakrishna** [comment]
Hii @Ashu96 @AlbionaHoti , Saw there was no assignees to the issue, I have worked on this and updated it locally. Do lmk if I can commit and create a PR 🚀

**Comment by Ashu96** [comment]
Yeah go ahead @adithyaakrishna  👍🏼

**Comment by imrishabh18** [comment]
@Ashu96 But I am already working on this.

**Comment by Ashu96** [comment]
No worries @imrishabh18 
I might have missed the acknowledgment from your side.
I'm assigning you this issue :)

**Comment by adithyaakrishna** [comment]
Okay No Worries!, Happy Hacking @imrishabh18 🚀

**Comment by BhuwanChandra** [comment]
@imrishabh18 are you still working on this issue? if not, I would like to work on this one.

**Comment by imrishabh18** [comment]
@BhuwanChandra I am a bit busy with some repos for contribution. Will make a PR for this in some time. Otherwise, will let you know for the grab.

**Comment by AlbionaHoti** [comment]
hey, @imrishabh18 can you please share your progress? If you weren't able to work on this one, don't worry there will be other issues coming up :) Otherwise, @BhuwanChandra will continue working on this one.

**Comment by AlbionaHoti** [comment]
@BhuwanChandra are you still interested to contribute to this issue? If yes, we can assign it to you :)

**Comment by BhuwanChandra** [comment]
@AlbionaHoti yes, I would like to work on it.

**Comment by khanjasir90** [comment]
@AlbionaHoti  can i work on this issue

**Comment by AlbionaHoti** [comment]
@khanjasir90, unfortunately, we'll close this issue due to the next version of Webiny in which a lot of things will change, one of the changes will be this part here. But, please join us on our [slack community](webiny.com/slack) to follow our journey, and in the near future, we'll have options for our community to work on different areas of Webiny. Thank you for your effort!
