### ISSUE TITLE
Fix: logging into a new unauthorised account for the first time gives an unauthorised error

### ISSUE THREAD

**Issue by TommyJackson85** [webiny/webiny-js#1127]
## This is:

- Bug

## Specifications

  - version:
  - OS:
  - Browser:

## Expected Behavior

When logging into a newly added user account for the first time (added by an admin account), and then resetting password as required, I should be navigated to the welcome screen.

## Actual Behavior

I am navigated to the "You are not authorized to access this route" page. I have to manually navigate to "localhost:3001/" to get to the welcome screen.

## Steps to Reproduce the Problem

1. Create a new user from an admin account giving it no permissions.
2. Logout and login to the new users account, take note you are directed to a reset password page.
3. Reset password to the same password the admin set it at OR to a new one. Don't think either has any relevance to the error but I reset it to the same password.
4. After resetting take note of the error page.

## Detailed Description

From what I can see, the reset password page's href is at this link:
http://localhost:3001/users?id=xxxxxxxxxxxxxxxxxxxxxxxxxxx   (xxxxx.. is the id number)

Afterwards resetting the password I am still stuck on that route once brought to the error page.
When logging back in to the unauthorised account (where I am not asked to reset the password), the error disappears and I am navigated back to localhost:3001.

## Possible Solution
Maybe see if this error is coming from the reset password files.

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
