### ISSUE TITLE
GraphQL Syntax Error on create-webiny-project Deploy

### ISSUE THREAD

**Issue by PercyJax** [webiny/webiny-js#1141]
Admin webpage shows "GraphQL API is unavailable" error. When I visit XXX.cloudfront.net/graphql page to test if API works, I get JSON response with SyntaxError: Unexpected token � in JSON at position 0.

Waiting 30+ minutes does not change.

Upon refresh, slight changes every time, to fields like "functionName" switches between XXX_api_local_pageBuilderGraphQL, XXX_api_local_cmsGraphQL, XXX_api_local_securityGraphQL

## This is:
- Bug

## Specifications

  - version:  Webiny 4.5.0, Node 10.14.0, 10.14.2, 12.18.2
  - OS: Windows 10 Version 20H2 Build 19042.388 native, AND Debian 10 WSL
  - Browser: Google Chrome and Microsoft Edge

## Expected Behavior
Upon deployment of API and building of Admin app, localhost:3001 opens, and after ~15 minutes, a page refresh will show admin interface.

## Actual Behavior
localhost:3001 shows GraphQL API is unavailable

Your API seems to be unavailable!
Make sure your API is working by visiting https://XXX.cloudfront.net/graphql.
If you've recently deployed your API, please allow ~10 minutes for your API URL to become available.

## Steps to Reproduce the Problem
1. Followed exact instructions in https://docs.webiny.com/docs/get-started/quick-start
2. Modified .env.json file with mongodb credentials
3. Database connection check passed on the API deployment
4. Web page pops up
5. Admin interface never worked
6. Tried on cmd, WSL

## Detailed Description
Unsure if .env.json is correct. See below:
```{
	"default": {
		"AWS_PROFILE": "default",
		"AWS_REGION": "us-east-1"
	},
	"local": {
		"MONGODB_SERVER": "mongodb+srv://u:p@crosstalk-cluster-0.wtakx.mongodb.net/crosstalk-site?retryWrites=true&w=majority",
		"MONGODB_NAME": "crosstalk-site-local",
		"DEBUG": true
	},
	"dev": {
		"MONGODB_SERVER": "mongodb+srv://u:p@crosstalk-cluster-0.wtakx.mongodb.net/crosstalk-site?retryWrites=true&w=majority",
		"MONGODB_NAME": "crosstalk-site-dev",
		"DEBUG": true
	},
	"prod": {
		"MONGODB_SERVER": "mongodb+srv://u:p@crosstalk-cluster-0.wtakx.mongodb.net/crosstalk-site?retryWrites=true&w=majority",
		"MONGODB_NAME": "crosstalk-site-prod"
	}
}
```
(Username and Password redacted)

## Possible Solution
No Idea

**Comment by doitadrian** [comment]
Hi @PercyJax,

thanks for the report.

can you provide a screenshot of `XXX.cloudfront.net/graphql` please? Or even better, can you try checking out the CloudWatch logs in AWS, and see if there more details there?

You can check the logs for these functions here (type "GraphQL" into the top filter input):
![image](https://user-images.githubusercontent.com/5121148/87849895-76d92200-c8ec-11ea-82c1-a09106ae7efe.png)

These are all of the functions that Webiny deploys for you. So, just open those that were mentioned in the error responses, and open the CloudWatch logs via the Monitoring tab:
![image](https://user-images.githubusercontent.com/5121148/87849945-c61f5280-c8ec-11ea-820d-b70799a9aa12.png)


Let us know if you'll need any help regarding anything else.

Thanks!

**Comment by doitadrian** [comment]
Hey @PercyJax, 

we've managed to reproduce it. So far, it looks like that an update on one of 3rd party dependencies is causing this issue. 

We'll update you as soon as we have some concrete info.

Thanks!

**Comment by doitadrian** [comment]
Hey @PercyJax,

as suspected, the issue is happening because of the `apollo-server-lambda` package, that was released yesterday.

I tried to deploy a brand new project, and changed the version of the package to `  "version": "2.15.1",`, it started working immediately.

**Comment by doitadrian** [comment]
Hey @PercyJax,

You might be able to resolve this via the `resolutions` setting in `package.json`, something like:

```
  "resolutions": {
    "apollo-server-lambda": "2.15.1"
  }
```

It's a `yarn` feature, check this article for more info:
https://classic.yarnpkg.com/en/docs/selective-version-resolutions/

**Comment by PercyJax** [comment]
Wow - thanks for the quick response! 

I tried out the resolutions fix on a brand new install and the admin app seems to be coming up fine. Just saw this though https://github.com/webiny/webiny-js/commit/f6f57e4c91dada71d6feb3ed7e5d11e267c2182d so not actually sure if that was the fix or the resolutions, but glad to see something past the Syntax Error!

**Comment by Pavel910** [comment]
@PercyJax it's your `resolutions` that fixed it. The commit in question is not yet released. Glad you made it past that error. We'll see how we can automate dependency version locking during publishing so this kind of stuff never happens again.

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
