### ISSUE TITLE
Add a CLI command to view project information

### ISSUE THREAD

**Issue by Pavel910** [webiny/webiny-js#1143]
## This is:
- Feature request

## Description
Webiny CLI needs to contain a command to list all relevant URLs for all environments and stacks as it is very difficult to find this information when you need it. Ideally, it would be `yarn webiny info`, and it would list all the data for each stack and every environment that is deployed for each stack.

## Possible Solution
Since every project can be different, and bootstrapped using different project templates, we can't create a generic command for this, but we can create a placeholder command, which will in turn trigger hooks registered by project template.

We already have project template hooks, in this form:
```js
// webiny.root.js
require("@webiny/cwp-template-full/hooks/api")(),
require("@webiny/cwp-template-full/hooks/apps")(),
```

These can internally be upgraded to add a hook plugin for the `info` command.
The `info` command can be added directly to the `cli` itself, also as a plugin, so developers can easily override it if they have a custom way of printing project information. This command would load the hooks of type `hook-project-info` which would individually print project information how they see fit.

**Comment by Fsalker** [comment]
here's how I'd approach this issue:

we'll have a new file `deployed-stacks.json` where we store info about deployed stacks/envs

1. create info folder similar to `webiny3\packages\cli\commands\run`. this command prints all information stored in `deployed-stacks.json`
	`webiny3\packages\cli\commands\info\index.js`
1* add the new command in `commands/index.js`, next to `run`
	`webiny3\packages\cli\commands\index.js`
	
2. create or update `deployed-stacks.json` based on `stack`, `env` and `output.cdn.url`
	`webiny3\packages\cli-plugin-deploy-components\deploy\deploy.js:93`

3. add a `hook-stack-after-remove` plugin which updates `deployed-stacks.json` upon stack removal
	`webiny3\packages\cli-plugin-deploy-components\remove\remove.js:47`


Note(s):
	-custom stacks that are deployed/removed will automatically update `deployed-stacks.json`, as they make use of the `deploy` and `remove` scripts we've updated earlier

Question(s):
	-is is possible for stacks to get deployed/removed in any other **way** than using `webiny create` or `webiny remove`?
		(^I'll have to figure out a way to make the new "**ways**" comply with my solution)

**Comment by Fsalker** [comment]
after discussing on Slack, here's the new take on this issue:

For our `apps`/`api` stacks, we will export a plugin with type `hook-stacks-info` (see the ss below for the files containing the new plugins), which reads state data from `./.webiny/state/<STACK_NAME>` to get all stacks, then reads every particular stack's `url` from its `Webiny.cdn.json` file. In the end, we will have an array containing: `stackName`, `env` and `url`.

![image](https://user-images.githubusercontent.com/16700631/88675381-8d088e80-d0f3-11ea-8f91-df82a52870ba.png)

For custom stacks created by the users, they will have to write `hook-stacks-info` kinda plugins and print their own info.

---

so, I'll have to:
1. update `cli` package with a new `info` command very similarly to the existing `run` command
![image](https://user-images.githubusercontent.com/16700631/88676275-8d555980-d0f4-11ea-9df6-04f3543481c7.png)
2. add `hook-stacks-info` hook in `cwp-template-full/hooks/api`
3. add `hook-stacks-info` hook in `cwp-template-full/hooks/apps`
