### ISSUE TITLE
Delete models and contents in bulk

### ISSUE THREAD

**Issue by asastre** [webiny/webiny-js#1149]
## This is:
- Feature request

## Detailed Description
It would be nice to have the possibility to delete models and contents in bulk. Now you have to delete individually each model or content created and if there are lots of them created it's a hard task to do.

## Possible Solution
For each element in the lists (models and contents), add a checkbox in order to select/deselect the elements to be deleted. 
Add a bulk action selector in top of the list with the options available (delete for now) to apply to all selected elements.

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
