### ISSUE TITLE
Plugin repository

### ISSUE THREAD

**Issue by Ashu96** [webiny/webiny-js#1151]
A public searchable repository of Webiny plugins.
---
As you may know, everything in Webiny is built using [plugins](http://docs.webiny.com/docs/deep-dive/plugins-crash-course).

There are a ton of plugins available in Webiny and you can also create these plugins by yourself.

As a part of our roadmap, the plan is to create a public searchable repository of Webiny plugin.
It will be a place where people can share the plugins that they created with the community.

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
