### ISSUE TITLE
Support 3rd party identity providers

### ISSUE THREAD

**Issue by Ashu96** [webiny/webiny-js#1152]
Support 3rd party identity providers (Okta, Auth0)
---

Manage access to Webiny using 3rd party identity providers.
It is very often the case that one wants to manage access to their app using 3rd party identity providers like [Okta](https://www.okta.com/) and [Auth0](https://auth0.com/)

The goal of this issue is to discuss the support and implementation of such a workflow.

**Comment by Pavel910** [comment]
This issue will be resolved by implementing #1194 and #1206. Those 2 issues cover the approach in details, and will allow anyone to implement any number of 3rd party identity providers.
