### ISSUE TITLE
Amazon Aurora Serverless

### ISSUE THREAD

**Issue by Ashu96** [webiny/webiny-js#1153]
Add support for Amazon Aurora Serverless
---
As a part of our product road map, we want to run Webiny using an SQL database on [Serverless Aurora](https://aws.amazon.com/rds/aurora/serverless/).

Currently, Webiny only supports MongoDB as a database out of the box. The goal of this issue is to discuss this possibility of
running Webiny using an SQL database on Serverless Aurora.

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
