### ISSUE TITLE
Research deployment to VPC

### ISSUE THREAD

**Issue by Pavel910** [webiny/webiny-js#1158]
## This is:
- Feature request

## Detailed Description
We need to try deploying Webiny to VPC to allow using services like DocumentDB. It's a request that occurs frequently, so we need to conduct a research and review our current setup to see what is necessary to allow deployments to VPC.

**Comment by rsmngdlmx** [comment]
Hi! We're using Webiny to develop a project at my work and we've made some adjustments to enable deployment to VPC, as VPC and DocumentDB were both requirements for the project. Everything seems to be working fine so far, so, we'd like to know if we could contribute (maybe even create a PR) to help with this issue. :)

Generally speaking, we've made 2 things:
1) Enable TLS connection to the database by adding a CA file (specified in an env variable).
2) Enable the creation of the lambdas in a VPC by adding Security Group IDs and Subnet IDs (specified in env variables).

**Comment by Pavel910** [comment]
This is implemented. Closing.
