### ISSUE TITLE
'future-proof' slugs for the serverless-cms

### ISSUE THREAD

**Issue by econtentmaps** [webiny/webiny-js#1161]
## This is:
- Feature request

## Detailed Description
To get an item from the (any) headless CMS for an SPA and support mapping content reliably to a valid path,  I can see 2 issues 1) slug is cool, but it needs to be “sluggy” (users can’t be trusted to understand valid URL syntax!).  And what if someone changes the slug for whatever reason? This is something we’ve dealt with on numerous occasions with big clients, but it’s marketing, right! :slightly_smiling_face: which leads to 2) how can you reliably map a ‘chain’ of friendly URLs changed over time by any number of content editors to a final, definitive article, Well, if you had 1) namespace collision detection for slugs throughout (the site’s) history, and 2) AN IMMUTABLE UUID, then that would be ok and would work quite well…

**Comment by econtentmaps** [comment]
For example. A client creates an article in the CMS and it's therefore visible in their site at a path defined by them using some SEO research using a user-editable slug. The SEO agency comes back a month or so later and says 'that did OK, but there's this new campaign we think will perform better so we need to change the URL. Now this may be demonstrable B$, but the client's an idiot. They want to tie the path to this social media campaign tagline. What about the URls to the article that are already in the wild? If I can say 'from this ephemeral path to this DEFINITE URI', then sharing content is very robust - this is particularly important for content that is subject to compliance etc. The number of 404's you get with bank and insurance content is crazy, for this very reason.

**Comment by econtentmaps** [comment]
Of course, this means more than one feature:  1) a simple text field that can be slugified and therefore used for a path and 2) exposing he UUID (and potentially slug history) in the API to allow the client to source the content irrespective of when the URL to it was shared and 3) a global namespace for 'slugs' that could be queries when setting the field. I'd appreciare feedback on the idea?

**Comment by Pavel910** [comment]
@econtentmaps really sorry for the delay, really busy on all fronts 🤯 

I understand the intention here. Will you be loading the data from CMS dynamically, when the user hits a certain URL, or will you simply rebuild the site when the slugs change?

The unique document ID you're talking about, and slug history - how do you plan on using that?

**Comment by econtentmaps** [comment]
I was thinking this: Slug is an array. When an article is created, the first item in the array is populated with the item's (not version's) unique id. If the user creates a 'friendly URL' slug, then that will simply be added to the end of the array (once the string has been slugified). The SPA would take the URL path and query the API for articles that have a match in their slug array, and if it's not the last one in the list, it will serve a redirect to the last one in the list and then render the content. I guess something like Gatsby would need a custom source plugin that would generate nodes for each slug in the array that could be configured with client-side redirects.

**Comment by Pavel910** [comment]
@econtentmaps nice explanation, thanks! 

What happens if another content entry uses the slug that is in the "history" of another entry? Should that even be allowed?

**Comment by econtentmaps** [comment]
Yes. I guess the safest would be global name collision detection on save, but maybe you could have an option to enable sit a scope level instead... I can see collections being presented at specific paths in many apps...?

**Comment by Pavel910** [comment]
I think uniqueness on a content model level is enough, since you always need to know what model you're querying. You can't just query a `slug` and expect the CMS to know what content model it is - so we're safe here.

This is very interesting, I'll talk this over with the team internally to see if there is a way to implement this without too many changes.

Thanks a lot for taking part in this and providing a clear example! 🍻

**Comment by fultonm** [comment]
I'm interested in this.
