### ISSUE TITLE
Form Builder form is not updating the redirect url

### ISSUE THREAD

**Issue by arvi** [webiny/webiny-js#1163]
## This is

- Bug

## Specifications

  - version: 4.6.0
  - OS: Mac OS
  - Browser: Chrome

## Expected Behavior

The form redirect url should be updated when I click "Save" and "Publish Changes" after editing the url
## Actual Behavior

I recorded it. Sometimes it work, sometimes it doesn't. The issue is appearing on both cloudfront url and alias domain.

This one is recorded in the cloudfront url because I was verifying if the issue is only at the alias domain.
https://www.loom.com/share/e0d7f992414f4798bb3c6284623120f3

I also clicked empty cache as I thought it was the cache. I also tried to wait a little bit, but still same issue.

## Steps to Reproduce the Problem

1. Create a form with redirect url in Triggers tab
2. Edit the redirect url
3. Click Save and Publish Changes
4. Click the pencil icon on the forms list of the form edited and check the redirect url

**Comment by Ashu96** [comment]
Hey @arvi 
Thanks for reporting the issue :+1: 

I'm curious to know one thing. Can you please try `step 4` a little differently. i.e

Before clicking the pencil icon on the form to edit from the list. Try reloading the revisions by clicking the `refresh list button`

![image](https://user-images.githubusercontent.com/13612227/88534366-90354900-d025-11ea-8f21-78fbc2a667f6.png)

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
