### ISSUE TITLE
Use camelCased version of the appName where needed

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#1166]
The other day, I ran `webiny create-webiny-project wby-4.5.1`, which caused an issue when trying to create S3 buckets and a new database in runtime.

### How to resolve?
Upon assigning the `MONGODB_NAME` value in the `env.json` files, we should at least `camelCase` it, so we don't end up with an invalid database name. We should do the same for the S3 bucket name.

### Implementation

When creating a new Webiny project, users can choose between `cms` and `full` templates. So, the fix should be implemented in the following files:
`packages/cwp-template-cms/index.js`
`packages/cwp-template-full/index.js`

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!

**Comment by ng29** [comment]
@doitadrian 
Can i work on this one ?

**Comment by doitadrian** [comment]
No need, because in v5 this is irrelevant. 

But you can maybe try to solve this one -  https://github.com/webiny/webiny-js/issues/1294. What do you say?

**Comment by ng29** [comment]
Just checked that issue @doitadrian can give it a shot, but to be honest, I have started aws within a month ago so might not be win win for me.

But yeah will give it a shot for sure :)
