### ISSUE TITLE
Handle duplicate element ids

### ISSUE THREAD

**Issue by Pavel910** [webiny/webiny-js#1168]
## This is:
- Bug

## Actual Behavior
Sometimes, element manipulation and undo/redo actions leave the state in a broken state, and duplicate IDs happen on multiple elements.

## Steps to reproduce
It's very hard to reproduce from the editor, but it is possible to replicate by explicitly assigning the same ID to 2 elements via a DB client.

## Note
We need to see why the error is not localized with this `packages/app-page-builder/src/editor/components/Element.tsx:104` and potentially implement an Error Boundary on top of the existing try/catch.

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
