### ISSUE TITLE
Add a CDN distribution comment to easily identify distributions in AWS console

### ISSUE THREAD

**Issue by Pavel910** [webiny/webiny-js#1169]
## This is:
- Feature request

## Detailed Description
Add a `comment` input to the `resources.js` files in all `cwp-template-*` packages to contain the name of the API the CDN is pointing to. It will make it easier to locate the relevant distribution in the AWS console.

![image](https://user-images.githubusercontent.com/3920893/88792887-41f68600-d19c-11ea-9275-8e76dad0b8ae.png)

**Comment by doitadrian** [comment]
Let's revisit this one with V5.

**Comment by ng29** [comment]
Heya Guyz,

Can i take this one?  ?

**Comment by CandyZack** [comment]
Hey @doitadrian  @Pavel910  
I have raised a PR- #1335 for this issue. Please assign this to me.

**Comment by Pavel910** [comment]
@CandyZack we'll have to pause with this for now, as we're completely changing the deployment mechanism for v5. We do not accept any contributions to v5 at this point as the system is still not stable enough.

**Comment by CandyZack** [comment]
@Pavel910  Okay, I shall keep the PR as draft then.
