### ISSUE TITLE
Admin darkmode dashboard cards' shadow are not dark moded

### ISSUE THREAD

**Issue by KudMath** [webiny/webiny-js#1181]
## This is:

- Improvement

It seems the shadows in darkmode are not changed to darkmode (or are not that beautiful :) )
![Screenshot 2020-08-10 at 16 41 43](https://user-images.githubusercontent.com/3056289/89795396-a31d4280-db28-11ea-97ba-da043e08b700.png)

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
