### ISSUE TITLE
Basic site search not available

### ISSUE THREAD

**Issue by everium** [webiny/webiny-js#1183]
## This is:

- Feature request

## Detailed Description

The GraphQL API currently allows searching by title or tags, but page content appears to be excluded. It would be useful to at least have the ability to search the snippet text as a v1 basic site search.

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
