### ISSUE TITLE
Supporting Union in CMS

### ISSUE THREAD

**Issue by KudMath** [webiny/webiny-js#1187]
## This is:

- Feature request

## Specifications
<img width="534" alt="Screenshot 2020-08-13 at 12 15 57" src="https://user-images.githubusercontent.com/3056289/90123275-d812da80-dd5e-11ea-826d-44838f638c45.png">

**Comment by TommyJackson85** [comment]
@KudMath  what would be the main purpose and advantages in using Graphql unions here?
Would it be for searching both pages and images types in one for example?
