### ISSUE TITLE
Feature request: Show version of webiny

### ISSUE THREAD

**Issue by bbarthel** [webiny/webiny-js#1195]
Feature request:  Show what version of Webiny that is published 

Thoughts about location (/admin):
- API Information
- at the very bottom, e.g.  webiny.com v4.9.2

**Comment by blenderskool** [comment]
@AlbionaHoti I would like to work on this :slightly_smiling_face:

**Comment by AlbionaHoti** [comment]
> @AlbionaHoti I would like to work on this 🙂
> 
> Edit: Nevermind, I don't have an AWS account to work on this project ☹️

Hi @blenderskool, Welcome to Webiny :) Regarding the AWS account, you can read more from one of the [FAQ](http://docs.webiny.com/docs/faq/is-webiny-free/). If you want to, you can [follow up our Get Started](https://www.youtube.com/playlist?list=PL9HlKSQaEuXScbySDD7QgITEA8RCHp-IS?utm_source=GitHub&utm_medium=webiny-youtube-get-started&utm_campaign=webiny-hacktoberfest-blog-oct-1&utm_content=webiny-hacktoberfest-github-issue&utm_term=W00101) YouTube videos to set up the requirements for starting with Webiny. :rocket:

**Comment by parshnt** [comment]
Hello @AlbionaHoti @bbarthel 

I would like to work on this issue :)

**Comment by AlbionaHoti** [comment]
Hi @parshnt, You can continue with the issue. If you do have any question, please join our [community slack](https://webiny.com/slack?utm_source=GitHub&utm_medium=Hacktoberfest-issues-github&utm_campaign=webiny-hacktoberfest-work-oct-4&utm_content=webiny-hacktoberfest-2020&utm_term=W00124), for it's easier to get in touch with the core team :) 

 @blenderskool thank you for your effort :)

**Comment by parshnt** [comment]
Sure @AlbionaHoti 

I'm part of the community on Slack as well now :)

**Comment by aloks98** [comment]
@AlbionaHoti since there is no updates or PR by parshnt can I take up this issue?

**Comment by AlbionaHoti** [comment]
Hey @aloks98, let's see if @parshnt has an update, if not, you can continue on the issue :)

**Comment by parshnt** [comment]
@AlbionaHoti 

I'm halfway there, I've successfully added the current version to the bottom left on /admin but I'm a bit confused about API information part.

**Comment by AlbionaHoti** [comment]
@parshnt please reach out if you have any questions on our [slack community](https://webiny.com/slack).

**Comment by AlbionaHoti** [comment]
Hey @aloks98, if you are interested to contribute, you can continue with this issue, I'll assign it to you, just let me know! 
Note that we have time up until 31st of October for the `hacktoberfest` approved issues  🚀

**Comment by aloks98** [comment]
@AlbionaHoti I have some questions about this.
1. Where exactly I can find the version of webiny in the project? I found some version fields in `package.json` of some packages in api
2. I also found the last released version from `CHANGELOG.md`. Should I use that?
3. Where do I need to show the version of webiny? In the admin app/or the actual website that will be published?

**Comment by Ashu96** [comment]
Hey @aloks98, thanks for asking these questions.

1. We should first try to add a `REACT_APP_WEBINY_VERSION` variable to our bundling process. Something similar to this [project-utils/bundling](https://github.com/webiny/webiny-js/blob/master/packages/project-utils/bundling/app/index.js#L4). As the CLI version will always be the same as other package versions, so it's safe to add it there.
2.  Ideally we want the version shown somewhere in the navigation, at the very bottom. For example,

![image](https://user-images.githubusercontent.com/13612227/97200340-1739bf00-17d7-11eb-8049-f0ab83b5c6e6.png)

Please let me know if you have more question :slightly_smiling_face:

**Comment by aloks98** [comment]
Hey @Ashu96 I have made some changes!
![Screenshot from 2020-10-26 22-51-26](https://user-images.githubusercontent.com/45600289/97205769-e446f980-17dd-11eb-9488-a4bc55a74df1.png)
One more thing, the `process.env.REACT_APP_WEBINY_VERSION` will be static? If it's static we have to change it with every version release.
If I may suggest, we can change the version in the `package.json` of the admin or webiny package (wherever the version is updated) and pull it from there into the bundling process?

**Comment by Ashu96** [comment]
Nice work @aloks98 

I don't get why `process.env.REACT_APP_WEBINY_VERSION` will be static if we're setting it to the package version we're importing like:
```js
 const { version } = require("@webiny/project-utils/package.json");
```
as mentioned in the earlier comment.

**Comment by aloks98** [comment]
Oh okay I missed that part xD I will change that now and make a PR :D
