### ISSUE TITLE
Upgrade to @apollo/client v3

### ISSUE THREAD

**Issue by Pavel910** [webiny/webiny-js#1200]
## This is:
- Feature request

## Detailed Description
As part of our v5 release, we'll use the opportunity and upgrade Apollo Client to the recent v3, which greatly reduces the amount of  dependencies you, as a developer, need to work with. The whole Apollo Client is now in one package which makes it a lot faster to work with: https://www.apollographql.com/docs/react/migrating/apollo-client-3-migration/

**Comment by aloks98** [comment]
This looks like something I can help with. Can I take up this issue as part of Hacktoberfest?

**Comment by Pavel910** [comment]
@aloks98 glad you're up for a challenge! :) Sure, we can easily assign it to hacktoberfest.
One thing though, before you begin: we already tried this, and the main problem is that Apollo Client 3 completely changed how InMemory cache works, so we were unable to make it work without introducing the insanity of their new approach. Just something to keep in mind. The best way to attack this issue is to start with InMemory cache and see if it's possible to make a painless transition to v3.

Feel free to open a draft PR, so we know you're working on it. I'm assigning this issue to you. Please keep us in informed of your findings, we'd love to see this upgrade come to life 🚀

**Comment by aloks98** [comment]
What exactly are the breaking changes for `InMemoryCache` when moving to apollo v3? I am not really familiar with Apollo but I would like to learn more about it!

**Comment by Pavel910** [comment]
@aloks98 oh, if you're not familiar with it, probably this issue will be too complex to start with. See the official changelogs and migration guides on apollo's site, they have it all laid out in details.

They changed the normalization of data in cache, which is a `big` change and is not easy to overcome. That's why we put this issue on hold.

**Comment by aloks98** [comment]
Hey if you think it's too complicated for me then it will be better for me not to work right now but at a later time when I have a better understanding of Apollo client 😀 I have seen other issues like implementation of Yarn v2 and RMWC v6. If they're not too complicated I can work on them for hacktoberfest! Is that okay?

**Comment by Pavel910** [comment]
@aloks98 you could try `yarn2`. We haven't tried it yet, would be interesting to see if it will `just work`. Please branch off the `master` branch for that one.
