### ISSUE TITLE
Documentation: Have the Slack community and older community links more easily spotted in the Readme file

### ISSUE THREAD

**Issue by TommyJackson85** [webiny/webiny-js#1203]
## This is:

- Idea

## Specifications

  - version:
  - OS:
  - Browser:

## Expected Behavior

For new users of Webiny it might be better to have all valuable community discussion boards at the top of the Readme file discussed clearly for user to spot them.
i.e. The [Slack Community](https://www.webiny.com/slack) and the links to older discussion boards.
 Just presented in a small paragrah with links in bullet points maybe.

## Actual Behavior

The Slack link is just lumbered in with other links here:

<img width="855" alt="Screenshot 2020-08-31 at 18 00 43" src="https://user-images.githubusercontent.com/22279028/91746479-8e2a5100-ebb4-11ea-96ec-9edf777d5fc9.png">

Furthermore when searching webiny slack or webiny-community slack in Google search its not appearing available to us. 

## Steps to Reproduce the Problem

Just check the the top of the readme file displayed and try searching for it in google.

## Detailed Description

Taken from [Webiny's Introduction page](https://docs.webiny.com/docs/webiny/introduction/), we could use this as a basis:

```
Community
There are several places you can join and get involved with Webiny:

Slack Community - join to get help or discuss bugs and features
Community Forum - if you prefer forum for discussions
```

**Comment by ng29** [comment]
Hey Tom,

Can i pick this one up ? ?

**Comment by TommyJackson85** [comment]
If you would like to, go ahead.

**Comment by TommyJackson85** [comment]
@ng29 this was given a wontfix label so maybe dont bother anymore. I wasnt sure what that label meant until hovering over it. Sorry for wasting your time.

**Comment by ng29** [comment]
@TommyJackson85 
Ahh i see, no worrries. I just started the prep work
(Lil sad as it makes me one step backward for Webiny swag pack)
