### ISSUE TITLE
Security layer upgrade (React)

### ISSUE THREAD

**Issue by Pavel910** [webiny/webiny-js#1206]
This is part 2 of our *Security layer upgrade* journey, and it's focused on the React side of things. You can find part 1 here: https://github.com/webiny/webiny-js/issues/1194, which talks about how things will work on the API side.

## Security Framework (React)

A high level architecture looks like this:
![image](https://user-images.githubusercontent.com/3920893/91831973-0c363880-ec45-11ea-9fc9-2852627d92f6.png)

`SecurityProvider` is a context provider which simply holds identity information, and provides a setter for (un)setting an identity. We need this centralized place to hold identity information so that other parts of the app know how to access that information. On its own, this provider doesn't do anything, It serves only as a centralized state for the identity/user information.

## The Code

The following code snippet contains everything there is to the `security framework`. Using this minimal concept you can implement all kinds of authentication using any number of 3rd party identity providers.

```ts
// NOTE: The code is greatly simplified and stripped of all React optimizations just to get the point across.
import React from "react";
import { useSecurity, SecurityIdentity } from "@webiny/app-security";

const Authentication = ({ children }) => {
    // Use hook to access security context anywhere in your app
    const { identity, setIdentity } = useSecurity();

    const login = () => {
        // In reality, you will process the credentials however you want (Okta, Auth0, Cognito...),
        // obtain a JWT token, and do one of the following:
        // - populate the `SecurityIdentity` with the data from JWT, or
        // - perform some kind of a `login/getUser` query to your API to load more of the user data relevant to your app
        // (that's how we load `permissions`, avatar, etc. in the Admin app)
        setIdentity(
            new SecurityIdentity({
                id: "6420cb70-17a1-4c5c-8db4-66df21bb7198",
                // `login` can be an email, phone number, username, whatever you're using in your identity provider
                login: "name@email.com", 
                // In this example we'll hard code user permissions
                permissions: [{ name: "pb.*" }, { name: "fb.form.list", own: true }],
                logout() {
                    // Perform logout procedure according to your identity provider.
                    // Then unset identity data in the Security context.
                    setIdentity(null);
                }
            })
        );
    };

    // A "logout" callback
    const logout = () => identity.logout();

    if (identity) {
        return (
            <div>
                <h2>Hi, {identity.firstName}!</h2>
                <button onClick={logout}>Logout</button>
                {children}
            </div>
        );
    }

    return (
        <div>
            <button onClick={login}>Login</button>
            {children}
        </div>
    );
};

export default Authentication;

```

The only requirement our security framework has are these 2 data types:
```ts
type SecurityPermission = { name: string; [key: string]: any };

type SecurityIdentityData = {
    id: string;
    login: string;
    permissions: SecurityPermission[];
    logout(): void;
    getPermission?(permission: string): SecurityPermission;
    [key: string]: any;
};
```

`SecurityIdentity` on React side is very similar to the one on the API side, but requires you to set `permissions` array immediately, and provide a `logout` function. **You're free to set anything you want for your app into the identity**. Your business logic may depend on any number of custom attributes, and that's why you'll most likely roll your own `login` GraphQL query/mutation to return data relevant to your business logic.

If you have a custom way of defining what `permissions` a user has, you can also override the `getPermission` function and provide your own implementation, as long as you return permissions in a standard `SecurityPermission` form.

## Checking permissions within the app

Now that we have the context setup, we can perform permission checks anywhere in our app:

```tsx
import React from "react";
import { useSecurity, SecurityIdentity } from "@webiny/app-security";

const Menu = () => {
    const { identity } = useSecurity();

    const permission = identity.getPermission("pb.page.list");

    if (!permission) {
        return null;
    }
    
    // Perform additional checks based on specific business logic rules
    if(permission.own) {
        return <div>My own menu item</div>;    
    }

    return <div>Common menu item</div>;
};
```
## Attaching JWT to all requests to the API

Our setup of Apollo Client got upgraded as well. We now support creation of client links using plugins:

![image](https://user-images.githubusercontent.com/3920893/91844475-d64e7f80-ec57-11ea-9a31-d39201b6053a.png)

Now all you need to do is register a plugin which knows how to get a JWT token from your particular authentication mechanism (Cognito, Okta...) and add it to request headers. In our particular example, we use [Amplify Auth](https://docs.amplify.aws/lib/auth/getting-started/q/platform/js) to get current user session and get the latest `idToken`:

![image](https://user-images.githubusercontent.com/3920893/91844686-2fb6ae80-ec58-11ea-9113-0e2110056a4f.png)

This gives you complete control over what and how you send to the API. It can be 1 token, 2 tokens, not-a-token - all up to you. If your security plugins on the API side know how to handle it - you can do literally anything.

## What does Webiny provide at this moment?

Out of the box, Webiny comes with packages that support Cognito User Pools, and a package to manage `admin` users in the admin app. For publicly-facing websites/apps you will most likely roll a custom UI, custom signup flow, etc. That we **do not** provide, but you can see how simple it is to implement custom user flows using this security framework. 

Handling users and permissions is also very different between user-facing apps, and your admin app. For user-facing apps you will always have some kind of abstractions on top of the underlying system of permissions, to make UX more pleasant. You will also have a very specific signup flow, maybe even involving payment, so we leave that part to be implemented on per-project basis.

**Comment by markwilcox** [comment]
This looks very straightforward. One thing I don’t see here (maybe Amplify is doing it behind the scenes but I don’t think it did when I last used it) is managing token refresh. When your token expires it’d be good to have the framework automatically managed refreshing it for you where possible, even if you need to define a plugin, or a function in the plugin to do that.

As a more general comment, it seems to me that, although everything is flexible, the current structure is biased towards having some managed authentication, but storing all the user data in the main database. I believe modern security best practice in the age of GDPR would be to keep data about your users (particularly personally identifiable data) separately from your application data. Cognito is a bit rubbish for this because it has no ability to index/query custom attributes and the rate limits for admin access to the data are low, hampering workarounds to the former. Auth0 on the other hand is built to keep custom user profiles separate from your application database. I’d love to see the default security position with Cognito not have user emails in the rather insecure MongoDB that’s open to connections from the world. If a user collection outside of the managed auth provider is necessary then keeping it DynamoDB would be preferable, even if the app content is in MongoDB or a relational DB.

I know the defaults are ‘only’ for admin users, but I think most developers are likely to use the defaults as a model for their other user accounts.

**Comment by Pavel910** [comment]
@markwilcox Thanks for joining this topic 🚀 

Amplify **does** handle token refresh for you. Any time you call an `Auth.currentSession()` it does it behind the scenes.

As for the rest: it's not biased at all. You can store user data anywhere you want. If you don't want to use our `user-management` package (which provides Users/Groups/Permissions management for admin app), you can do everything using 3rd party identity services and get data from their JWTs (and use that on both API and React side). In that case you'll have to manage permissions on your own however you find suitable for your project. We'll have guides on configuring stuff with all those 3rd party services to make it really clear.

For example, if you use Auth0, you manage everything in Auth0 console. When the user logs into Webiny, you can have predefined sets of permissions that will be assigned to his identity (on both React and API side) based on some user group or attribute that you will store into the token on Auth0 side. We only need you to provide us with permissions in a specific form, and those permissions must contain the options for specific business rules that will be defined for each app. 

Different services have different approaches and vocabulary for defining permissions/scopes/whatever, so it will be **your** task to map your specific service token to a set of permissions for that particular identity (that's the reason why we don't have the word `user` anywhere in our `security framework`, we only talk about `identity`).

On the DB note: we're already working on full migration to DynamoDB. Besides that, we've already implemented VPCs, so you'll be able to use DocumentDB, RDS, etc. in the upcoming `v5` of Webiny. So your database will not be publicly accessible for much longer 🚀 

If you have some more questions, I'll be glad to dive deeper and clarify :)

**Comment by markwilcox** [comment]
> Amplify does handle token refresh for you. Any time you call an Auth.currentSession() it does it behind the scenes.

That’s awesome, 👏 for the Amplify team. Doing it manually with the Cognito SDK never felt like a good use of time.

> As for the rest: it's not biased at all. You can store user data anywhere you want. If you don't want to use our user-management package (which provides Users/Groups/Permissions management for admin app)

I understand the whole replaceable “I can do whatever I want myself” but I do want the batteries included, I’d just prefer them to keep the PII separate. I probably would choose Cognito (because IaC and cheap) as long as I don’t want social/federated login (I know it can, but not well). Bias was probably the wrong word, but it’s how it works out of the box if you don’t replace anything, and since you’re soliciting comments on security I’m trying to explain why I’d feel the need to replace parts. As webiny is moving very fast at the moment (which is generally awesome and impressive) it’s hard to feel confident investing in replacing lots of parts to use it.

> On the DB note: we're already working on full migration to DynamoDB.

If you embrace the single table design it’d still be good to keep PII in a separate table with appropriately scoped IAM roles in the functions to minimise access to it.

> Besides that, we've already implemented VPCs, so you'll be able to use DocumentDB, RDS, etc. in the upcoming v5 of Webiny. So your database will not be publicly accessible for much longer 🚀

🍻👏 Fantastic. Keeping my eye on DynamoDB though, because VPCs are a pain!

**Comment by Pavel910** [comment]
@markwilcox hahah, yeah the batteries 🔋 😄 I understand your point of view, it's perfectly legitimate. But also keep in mind that Webiny is a **framework** more than **app provider**. The apps we have are a showcase of what you can do with the framework, but we're a **dev tool** first, apps second. 

The main challenge with security is that everybody will want his own set of batteries, which we can't possibly predict. You can see how that makes it difficult to settle for a specific "default" configuration to make everyone happy. Thus we're focusing on making this very flexible, so later, as we get more and more feedback from the community, we can identify the more popular choices and either develop those packages ourselves or help community develop them.

It would be great if you could open a separate issue on our Github and flush out what you think would be your perfect setup.

Regarding the single-table design: the plan is to have a separate table per-app, since each app has its own GraphQL service, but we'll see how that goes. If that becomes a reality, the `security` service will have its own table and it will be locked down to only that specific lambda.
