### ISSUE TITLE
Upgrade Page Builder to latest Slate.js version

### ISSUE THREAD

**Issue by Pavel910** [webiny/webiny-js#1208]
## This is:
- Important improvement

## Detailed Description
For the next release (v5) we need to upgrade Page Builder slate editor to use the same version as the rest of the apps in the repo. This is important for 2 reasons:
1) from 0.50.x a lot has changed in the data structure and API of Slate.js which makes it a lot more flexible and easier to handle (+ full TS support). We're already using the new Slate everywhere in the system, except the Page Builder.
2) This old version of Slate is creating a blocking issue with dependencies between packages and is preventing us from making other improvements to CMS and RichText editor for our users.

**Comment by brunozoric** [comment]
@Pavel910 i removed slate from page builder with a new pr so we can close this one
