### ISSUE TITLE
CMS - Content Model: Adding a description to a content model causes DB crash

### ISSUE THREAD

**Issue by nkumnberlin** [webiny/webiny-js#1210]
After adding a description within a content the Database crashes and the user is unable to access them unless he deletes the description in the mongo db.

## This is:

- Bug

## Specifications

  - version: latest Webiny Version
  - OS: W10
  - Browser: Chrome
  - Database: MongoDB

## Steps to Reproduce the Problem

1. Open a random Model and try to change the description.
![originalModel](https://user-images.githubusercontent.com/26595416/92096658-6f57d480-edd7-11ea-9dc2-18bc7cdcb349.PNG)
2. After adding a description, click save and save the Content Model
![changeDescription](https://user-images.githubusercontent.com/26595416/92096668-7252c500-edd7-11ea-850d-b7af4b4219bd.PNG)
3. After reloading the page, all content models disappeared.
![dbCrash](https://user-images.githubusercontent.com/26595416/92096669-7252c500-edd7-11ea-95fb-e7fd29957d5e.PNG)
4. After manually deleting the description within the mongo DB, the content Model are displayed correctly.
![image](https://user-images.githubusercontent.com/26595416/92098949-30774e00-edda-11ea-87ee-aaf2118f8dce.png)

**Comment by Ashu96** [comment]
@nkumnberlin Can you please confirm you're using the latest version of `webiny v4.10.0`?

If not, please try upgrading the Webiny project using `yarn upgrade` and then redeploy the API stack.

**Comment by nkumnberlin** [comment]
@Ashu96 
Its 4.8.0
We will update the project tomorrow and test it again. We'll be in touch

**Comment by nkumnberlin** [comment]
@Ashu96  fixed. Worked with the latest version! Thanks
