### ISSUE TITLE
Project Utils: OpenBrowser option for StartApp should work

### ISSUE THREAD

**Issue by latotty** [webiny/webiny-js#1214]
## This is:

- Bug

## Specifications

  - version: 4.10.0
  - OS: MacOS

## Expected Behavior
When I set the openBrowser flag to false, it shouldn't open the browser.

## Actual Behavior
It currently reseted to 'true' on every falsy input.

## Steps to Reproduce the Problem
In admin or site webiny.config.js:
```javascript
      // Start local development
      await startApp({ ...options, openBrowser: false }, context);
```

## Detailed Description

Problematic code: https://github.com/webiny/webiny-js/blob/614e558bf04bd92c9f41de9def40af4d13d482be/packages/project-utils/bundling/app/createDevConfig.js#L5-L7

## Possible Solution
I will publish a PR.

**Comment by Pavel910** [comment]
@latotty oh that's a bad `if` :D Please do send a PR :) Thanks!
