### ISSUE TITLE
CLI: Deploy Status is spamming the CI output logs

### ISSUE THREAD

**Issue by latotty** [webiny/webiny-js#1219]
## This is:

- Bug
- Feature request

## Specifications

  - version: 4.10.0

## Expected Behavior

When the `CI` environment variable is enabled, the progress notifications should be disabled.

## Actual Behavior

Currently it pollutes the output in our CI environment.

## Steps to Reproduce the Problem

Try to deploy using Github Actions/Gitlab CI (or any CI solution)

## Detailed Description

We use Gitlab CI to do all the testing, building, deploying.
The [Status class](https://github.com/webiny/webiny-js/blob/3feb6e3c599d0f1ac58de103c32f3f5d6e62506d/packages/cli-plugin-deploy-components/execute/Status.js#L9)  is logging every second, which is logged in a separate line in a non interactive terminal environment.
This is a problem because it creates a reeaaally long log output, which is nearly impossible to read by eye, and freezes the browser on open, also a big unnecessary load to the storage.

The `CI` env variable is enabled in ~all CI solutions.

A few examples:
https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
https://docs.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#default-environment-variables
https://docs.travis-ci.com/user/environment-variables/#default-environment-variables

## Possible Solution

I created an ugly solution for our codebase.
I added a hook before deploy and remove, and disabled the Status class...

```javascript
const hook = async () => {
  if (process.env.CI) {
    const { Status } = require('@webiny/cli-plugin-deploy-components/execute/Status');

    Object.assign(Status.prototype, {
      start: () => {},
      stop: () => {},
      render: (status, entity) => {
        console.log({ status, entity });
      },
      clearStatus: () => {},
    });
  }
};

module.exports = () => [
  {
    type: 'hook-before-deploy',
    name: 'hook-before-deploy-ci-silence',
    hook,
  },
  {
    type: 'hook-before-remove',
    name: 'hook-before-remove-ci-silence',
    hook,
  },
];
```

**Comment by Pavel910** [comment]
Great, we can solve this for the next release, next week :) Thanks for reporting!

**Comment by Pavel910** [comment]
Leaving this reference here for whoever will be working on this issue:
https://github.com/webiny/webiny-js/blob/master/packages/cli-plugin-deploy-components/execute/Status.js#L23

I think we can just this simple `if` and it should do the trick:

![image](https://user-images.githubusercontent.com/3920893/92591357-0b815000-f29e-11ea-9cf5-a5a2c8ee407b.png)
