### ISSUE TITLE
Implement TypeScript 4.0

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#1226]
As the title of the issue says, we need the latest TS support in the V5 version of Webiny.

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html

**Comment by sccalabr** [comment]
Would this just be bumping the typescript version in the package json?

**Comment by Ashu96** [comment]
@sccalabr It's more than that and Is being worked on. Sorry for the confusion :slightly_smiling_face:

**Comment by brunozoric** [comment]
Sorry, forgot to link the PR to the issue.
