### ISSUE TITLE
Headless CMS: Enable adding more typedefs to the read endpoint in a CmsModelFieldToGraphQLPlugin

### ISSUE THREAD

**Issue by markwilcox** [webiny/webiny-js#1234]
I've been trying to create a custom field for the CMS, with a single string as input (the key for a file uploaded to the file manager) then the API side adds more data to the model before it's stored and returned. The extra data has known structure, so I'm using a 'fields' field in Commodo, but the only option to return it from the "read" endpoint currently via GraphQL is using JSON rather than a custom GraphQL type to match the structure.

The issue is that while it's possible to add extra typedefs to the "manage" endpoint, it's not possible to add them to the "read" endpoint in the CmsModelFieldToGraphQLPlugin. This could be resolved if the plugin structure allowed adding extra typedefs to the "read" endpoint.

## This is:
- Feature request

**Comment by doitadrian** [comment]
Hi @markwilcox,

I don't know how, but this works:
![image](https://user-images.githubusercontent.com/5121148/93209124-eee18e00-f75d-11ea-976d-f6fa885daba4.png)

So it seems that the `createSchema` is read in the `read` property too.

I also created a test for exactly this case, so we're sure it works in the future. Will pushing it as a separate PR that will close this issue.

In any case, let me know if you'll still need help around this (I know we ended up using `JSON` in the end).

**Comment by markwilcox** [comment]
Hey - that's awesome, thanks.

I have the sort of personality that's never happy with "I don't know how, but this works for me" 😄, so I did some digging.
It works because of this:
https://github.com/webiny/webiny-js/blob/master/packages/api-headless-cms/src/content/plugins/utils/getSchemaFromFieldPlugins.ts

Given this is intentionally working for "read", and createSchema() can basically be used to arbitrarily add anything to the GraphQL schema, can I suggest changing the type definition for the "read" endpoint in the plugin to include createSchema? (just in case you didn't already). That way there's at least type-level documentation that this works.
https://github.com/webiny/webiny-js/blob/c8650c7752de78d381bba72a0a49556c1e826125/packages/api-headless-cms/src/types.ts#L165

**Comment by Pavel910** [comment]
@markwilcox @doitadrian CMS supports any number of plugins, and will just process everything you throw at him. `createSchema` does work for both `manage` and `read` so you're free to use that for custom types/resolvers.

**Comment by doitadrian** [comment]
![image](https://user-images.githubusercontent.com/5121148/93220152-6fa78680-f76c-11ea-87a4-3f0b763d2f7f.png)

This is what @markwilcox was referring to, the TS doesn't have `createSchema` listed on the `read` property.

You are right @markwilcox , will add it and will be available today/tomorrow.
