### ISSUE TITLE
Add password protection to site app

### ISSUE THREAD

**Issue by Pavel910** [webiny/webiny-js#1252]
## This is:
- Feature request

## Detailed Description
We need to allow users to password-protect their sites. Once `v5` is out we'll be able to create a proper login mechanism for apps, but at the very least we should allow Basic Auth for the whole app (any app). Especially since we're serving the site app via a dedicated lambda, this should be doable.

## Possible Solution
Enabling something like this https://gist.github.com/lmakarov/e5984ec16a76548ff2b278c06027f1a4 when app is protected by a password.

**Comment by ritwikchakraborty123** [comment]
Hai I want to solve this issue

**Comment by ritwikchakraborty123** [comment]
Can anyone help me with some of resources

**Comment by Pavel910** [comment]
Hey @ritwikchakraborty123, this issue is assigned to v5 project, as it's related to infrastructure setup, which is changing in v5. So for now this issue is in `on-hold` mode. Thanks for your interest! 🚀
