### ISSUE TITLE
Page Builder link validation is too restrictive.

### ISSUE THREAD

**Issue by econtentmaps** [webiny/webiny-js#1260]
## This is:

- Feature request

## Detailed Description
When specifying the URL for a link (in a button or a menu item, for example), Page Builder requires a full URL. 

## Possible Solution
Ideally, it should allow anything that the href property of the a tag supports (#, relative, absolute etc). I imagine the value should also be sanitized server(less)-side before being stored, though.

**Note:** Page builder [Docs](http://docs.webiny.com/docs/webiny-apps/page-builder/getting-started)

**Comment by sccalabr** [comment]
Id like to give this a try. What kind of sanitation are you looking for? Also roughly where is the code for this?

**Comment by Ashu96** [comment]
Hey @sccalabr! Welcome! Here are some links to get you started:
Some instructions about contributing: https://github.com/webiny/webiny-js/blob/master/docs/CONTRIBUTING.md
Our YouTube channel with different videos about the project, how stuff works, etc: https://www.youtube.com/c/Webiny/videos

**Regarding this issue**:
Here is the code responsible for handling the Page Builder `menu item` link:
https://github.com/webiny/webiny-js/blob/master/packages/app-page-builder/src/admin/plugins/menuItems/link/LinkForm.tsx#L35
And, here is the code responsible for handling `button link` settings:
https://github.com/webiny/webiny-js/blob/master/packages/app-page-builder/src/editor/plugins/elementSettings/link/LinkSettings.tsx#L45

We are using the [@webiny/validation](https://github.com/webiny/webiny-js/blob/master/packages/validation/src/index.ts) package here, for `URL` validation. Validators are simple functions, so you can create your own custom validator if needed.


If you have any questions, please do leave a comment or reach out via [Slack](https://www.webiny.com/slack) :)
Cheers!

**Comment by ritwikchakraborty123** [comment]
Hai can anyone help me to solve this issue

**Comment by sccalabr** [comment]
Let me know if this is what you were thinking. Thanks :)

**Comment by aloks98** [comment]
@Ashu96 I would like to take up this issue if the PR made by @sccalabr is invalid or it needs more work.
