### ISSUE TITLE
Outdated Theme Docs + Question how it works

### ISSUE THREAD

**Issue by Th-Os** [webiny/webiny-js#1262]
## This is:
- Question

### Outdated Docs:

Navigate to [https://docs.webiny.com/docs/developer-tutorials/new-theme-overview/](https://docs.webiny.com/docs/developer-tutorials/new-theme-overview/). You will find outdated information and broken links.

### Question:

Currently, I am trying to set a theme to the PageBuilder, Admin App and Site App to be able to set colors and fonts of the Text element (or plugin). Basically I want to be able to change the values that are used in this context:
<img src="https://user-images.githubusercontent.com/13185949/94111340-36de7000-fe44-11ea-9e93-48f80847aa21.png" width="500" height="300">

I couldn't create a Theme by following this Issue: https://github.com/webiny/webiny-js/issues/806. So I need your help.
Are you able to achieve this via Themes? Could you give me some details on how this could work?

Thank you in advance!

**Comment by SvenAlHamad** [comment]
Hi @Th-Os,

apologies about that, you're right, some information on that page is out of date and needs updating. I'll handle this in the next few days. In the meantime, so you can move forward:
1. Create a new folder `theme` inside `apps/site/src` (the apps/site/src folder should already exist with the default webiny installation)
2. Inside that folder copy the contents of this package: https://github.com/webiny/webiny-js/tree/master/packages/app-page-builder-theme/src
3. Then amend the files inside the theme folder to fit your visual needs.
4. Update the contents of `apps/site/src/App.tsx` like so to activate your new theme

```
import createSite, { SiteAppOptions } from "@webiny/app-template-site";
import myTheme from "./theme";
import `./theme/styles.scss`

export default (params: SiteAppOptions = {}) => {
   const plugins = params.plugins || [];
   plugins.push(myTheme());
    return createSite(params);
};
```

5. Finally, you need to import the theme into the Admin app as well so the new styles are reflected in the Page Builder Editor as well. To do that, edit `apps/admin/src/App.tsx` file. It should look like so:

```
import adminTemplate from "@webiny/app-template-admin-full";
import myTheme from "../../site/src/theme";
import `../../site/src/theme/styles.scss`

export default adminTemplate({
    cognito: {
        region: process.env.REACT_APP_USER_POOL_REGION,
        userPoolId: process.env.REACT_APP_USER_POOL_ID,
        userPoolWebClientId: process.env.REACT_APP_USER_POOL_WEB_CLIENT_ID
    },
    plugins: [myTheme()]
});
```

I hope this helps.

**Comment by Th-Os** [comment]
Hello @SvenAlHamad,

thank you for your help! 

I still have problems with the imports in ```apps/admin/src/App.tsx```:
```
import myTheme from '../../site/src/theme';
import '../../site/src/theme/styles.scss'
```

The upper import won't resolve, because it is not in rootDir and not in include. Both configurations can be found in the tsconfig.json. I tried to use ```import myTheme from 'site/src/theme'``` but that throws the following error:

```
../site/src/theme/index.ts 147:6
Module parse failed: Unexpected token (147:6)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|             }
|         }
>     } as PbThemePlugin,
|     {
|         name: "pb-page-layout-static",
```


Seems like i have an import or a webpack loading error. Could you show me, how you did it?

**Comment by Pavel910** [comment]
Hey @Th-Os, sorry for the troubles. I'll record a video and update the docs which will explain what and how of creating a custom theme. It's not very straightforward in the current version of Webiny so it's best to create a video guide and explain the mechanics and reasons behind them. 

We do have it on our roadmap for v5, so it will be more dev-friendly in the future.
Please hang on, I'll try to post an update today.

Cheers!

**Comment by Pavel910** [comment]
@Th-Os I've added an example of code with step-by-step instructions: https://github.com/webiny/webiny-examples/tree/master/custom-theme

Please try following those, and let me know if you still have problems.

Cheers!

**Comment by Th-Os** [comment]
@Pavel910 Thank you for you help!

I tried your approach and got it working, when I added "--config-file ../../.babel.react.js" to the build command in the package.json of my theme package.

**Comment by Pavel910** [comment]
@Th-Os I don't know why you need that parameter, it should work out of the box, since there is `.babelrc.js` inside of `packages/theme`, which imports the `.babel.react.js` file from your project root.

**Comment by Th-Os** [comment]
Seems like i didn't copy that. Totally my fault.
