### ISSUE TITLE
Question: How to add custom Security Service

### ISSUE THREAD

**Issue by Th-Os** [webiny/webiny-js#1265]
## This is:

- Question

## Question

Hello, it's me again.
I want to add a custom Security Service to implement an existing authorization API. The workflow would look like this:
1. User enters his credentials
2. Security Service is called
3. Within Security Service it calls my external API and gets a token
4. The user will be logged in and gets a JWT Token and have some other informations
5. Security Service is enabled App-wide + Tracking Possibilities (e.g. Google Analytics)

At the end I want a login and an authentication for every page I built with the PageBuilder. Is this even possible?
Can I just extend the existing Cognito service (https://docs.webiny.com/docs/deep-dive/architecture/security-service/)?

Thank you in advance!

**Comment by Pavel910** [comment]
Hi @Th-Os!

Our current security layer is not at all flexible and we're addressing it in the next major release of Webiny coming around New Year (#1194 and #1206). 

The way you imagined it is doable, you'll need to create a new [GraphQL service](https://youtu.be/SgfWQG8YirU?t=66), and add your token generation logic there. Then you'll add a login/signup to your custom app and handle that however you like. 

> Note that this will be completely detached from what we currently have for security; there's currently nothing you can reuse from what we have for our admin app. So you're essentially implementing your own security for your app.

The main problem is with the `listPublishedPages` query, which is not protected at all, so anonymous users can query that on your API and get all published pages. However, you can override our default resolver and implement your own authorization logic. I'm posting the full `api/pageBuilder/src/index.ts` so you can C/P it and try:

```ts
import { createHandler } from "@webiny/handler";
import apolloServerPlugins from "@webiny/handler-apollo-server";
import dbProxy from "@webiny/api-plugin-commodo-db-proxy";
import securityServicePlugins from "@webiny/api-security/plugins/service";
import googleTagManagerPlugins from "@webiny/api-google-tag-manager";
import cookiePolicyPlugins from "@webiny/api-cookie-policy";
import mailchimpPlugins from "@webiny/api-mailchimp";
import pageBuilderResolvers from "@webiny/api-plugin-page-builder-resolvers-mongodb";
import pageBuilderPlugins from "@webiny/api-page-builder/plugins";
import useSsrCacheTagsPlugins from "@webiny/api-page-builder/plugins/useSsrCacheTags";
import settingsManagerPlugins from "@webiny/api-settings-manager/client";
import gql from "graphql-tag";
import listPublishedPages from "@webiny/api-page-builder/plugins/graphql/pageResolvers/listPublishedPages";

export const handler = createHandler(
    apolloServerPlugins({
        debug: process.env.DEBUG,
        server: {
            introspection: process.env.GRAPHQL_INTROSPECTION,
            playground: process.env.GRAPHQL_PLAYGROUND
        }
    }),
    dbProxy({ functionName: process.env.DB_PROXY_FUNCTION }),
    settingsManagerPlugins({ functionName: process.env.SETTINGS_MANAGER_FUNCTION }),
    securityServicePlugins({
        token: {
            expiresIn: process.env.JWT_TOKEN_EXPIRES_IN,
            secret: process.env.JWT_TOKEN_SECRET
        },
        validateAccessTokenFunction: process.env.VALIDATE_ACCESS_TOKEN_FUNCTION
    }),
    pageBuilderPlugins(),
    useSsrCacheTagsPlugins(),
    pageBuilderResolvers(),
    googleTagManagerPlugins(),
    mailchimpPlugins(),
    cookiePolicyPlugins(),
    {
        type: "graphql-schema",
        schema: {
            typeDefs: gql`
                # Need to define a dummy type to make GraphQL happy about mandatory typeDefs
                type Dummy {
                    dummy: String
                }
            `,
            resolvers: {
                PbQuery: {
                    // This will provide a new resolver for 'listPublishedPages'
                    listPublishedPages(root, args, context, info) {
                        // 1. Perform your custom security checks here
                        
                        // 2. Call default resolver
                        return listPublishedPages(root, args, context, info);
                    }
                }
            }
        }
    }
);
```

Note the custom plugin at the bottom which overrides the default resolver.
The rest is completely up to you on both API and React side. If you have further questions, feel free to post them. Also, join our Community Slack, it's easier to communicate there: https://www.webiny.com/slack

Cheers!

**Comment by Th-Os** [comment]
Thank you very much! I will get back to you, when i tried it.
