### ISSUE TITLE
Update `api-files` package to `api-file-manager`

### ISSUE THREAD

**Issue by Ashu96** [webiny/webiny-js#1266]
## This is:
- Feature request

### About the issue:

How about we update `api-files` package to `api-file-manager`. We already have the [`app-file-manager`](https://github.com/webiny/webiny-js/tree/master/packages/app-file-manager) package.
This way it will be consistent with our other packages. For example:

-  [`api-page-builder`](https://github.com/webiny/webiny-js/tree/master/packages/api-page-builder)
-  [`app-page-builder`](https://github.com/webiny/webiny-js/tree/master/packages/app-page-builder)
-  [`api-form-builder`](https://github.com/webiny/webiny-js/tree/master/packages/api-form-builder)
-  [`app-form-builder`](https://github.com/webiny/webiny-js/tree/master/packages/app-form-builder)

Also, how about changing the GraphQL service name from `files` to `fileManager`. Starting with, for example, 
changing GraphQL [schema](https://github.com/webiny/webiny-js/blob/master/packages/api-files/src/plugins/graphql.ts#L173)

This way all file manager schema will be namespace `fileManager` instead of `files` like what we have for [`pageBuilder` ](https://github.com/webiny/webiny-js/blob/master/packages/api-page-builder/src/plugins/graphql.ts#L62)

Of course, this means we'll need to update all schema references in the client/app. For example:
- [`app-file-manager`](https://github.com/webiny/webiny-js/blob/master/packages/app-file-manager/src/admin/graphql.ts)
- [`app-admin`](https://github.com/webiny/webiny-js/blob/master/packages/app-admin/src/components/FileManager/graphql.ts)

 @webiny/developers What do you think guys?

### Things to work on

**File manager app**
- [ ] Update file manager GraphQL schema to use `fileManager` namespace instead of `files`.
- [ ] Update file manager client to use updated GraphQL schema.
- [ ] Update file manager permissions to use `fm` instead of `files`.

**Form builder app**
- [ ] Update form builder GraphQL schema to use `formBuilder` namespace instead of `forms`.
- [ ] Update form builder client to use updated GraphQL schema.
- [ ] Update form builder permissions to use `fb` instead of `forms`.

**Comment by doitadrian** [comment]
@Ashu96 Did you work on this already? Asking because I have some of these done in my feat/v5/pulumi branch (I just changed the package name to `api-file-manager`).

**Comment by Ashu96** [comment]
No @doitadrian  I haven't started working on it. 🙂
Just created the issue so that we can discuss about it and write down more details if needed.
