### ISSUE TITLE
Question: AWS region not everywhere the same

### ISSUE THREAD

**Issue by Th-Os** [webiny/webiny-js#1268]
## This is:

- Question

When I deploy the API with ```yarn deploy api --env=dev``` and set the AWS region to eu-central-1, I see this region everywhere but in these last lines. This could possibly lead to some overhead. Is this the expected behavior? If it is, then please close this issue.

```
...
  webiny:api Starting API Gateway deployment with name '[]_api_dev_api' in the 'eu-central-1' region +0ms
...
  webiny:cdn Starting deployment of CloudFront distribution to the us-east-1 region. +0ms
  webiny:cdn Creating CloudFront distribution in the us-east-1 region. +12ms
  webiny:cdn CloudFront deployed successfully with URL: https://[].cloudfront.net. +1s
  webiny:cdn Adding "X-Cdn-Deployment-Id" forwarded header... +468ms
  webiny:cdn Creating custom error responses... +1ms
  webiny:cdn Updating CDN with forwarded headers... +0ms
```

**Comment by Pavel910** [comment]
@Th-Os interesting, this doesn't look right; we haven't noticed that before. @doitadrian you are deploying to `eu-central-1`, could you please double-check that you're getting the same output, when you get a spare minute? Thanks

**Comment by doitadrian** [comment]
I'm using `eu-central-1`, works correctly all the time.

Where did you change the region?

**Comment by Th-Os** [comment]
I changed it in the root ```.env.json``` and in my ```~/.aws/credentials```.
Can I change the Cloudfront integration without doing a full refresh of the site?

**Comment by doitadrian** [comment]
Not sure if this is possible, because when you deploy stuff, all of the resources deployed are written in the `.webiny` folder.

I think deploying from scratch might be the best option here. Maybe there was a bad config while the initial deployment was made.

**Comment by Th-Os** [comment]
Ok, I had to start from scratch and now it works. Thank you for you help!
