### ISSUE TITLE
Pagination with date sorting fails

### ISSUE THREAD

**Issue by latotty** [webiny/webiny-js#1271]
## This is:

- Bug

## Specifications
  - version: 4.12.1

## Expected Behavior

Sorting an entity by createdOn (or savedOn), and paging it should work.

## Actual Behavior

It throws an error. `Cannot read property 'id' of undefined`

## Steps to Reproduce the Problem

1. Create 10+ Form
2. Set page size to 10
3. Click on the next page button

## Detailed Description

This line throws an error: https://github.com/webiny/commodo/blob/next/packages/fields-storage/src/withStorage.js#L395
Because the results are empty.

@Pavel910 already tried to debug it, the query created with the cursor returns an empty list.

Maybe related:
https://github.com/webiny/webiny-js/issues/821#issuecomment-646847169

**Comment by Pavel910** [comment]
Our unit tests are missing the test case where data is sorted by date. We should start by adding a test case, and see if we can reproduce it in `commodo` itself.

**Comment by doitadrian** [comment]
This was resolved with the Webiny `4.13.0` / `@commodo/fields-storage` `2.1.2` releases.

Closing.
