### ISSUE TITLE
Page Builder / Recoil - Error Handling

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#1288]
Once we start with the Recoil implementation for the Page Builder's editor, let's immediately plan for proper error handling.

The thing is, right now, when errors occur in React components, sometimes, users just see a blank screen.

This:
1) Completely prevents them from editing the page they might have been working on for a long time.
2) Doesn't output any helpful error message, leaving the users confused.

Although there were some attempts at making this better (https://github.com/webiny/webiny-js/pull/726), it seems that there are still some cases in which this doesn't work.

A good example are these two lines here (in `packages/app-page-builder/src/editor/plugins/elements/row/RowChild.tsx:88`):

![image](https://user-images.githubusercontent.com/5121148/95111863-66dd1b80-0740-11eb-9f28-d25ca286e188.png)

In some weird scenario, the `data` property ends up being empty, thus causing accessing a property of `undefined`, and throwing an error on the screen, and yes, just rendering a blank screen.

I did some debugging but did not find the exact reason why the existing `tryRenderingPlugin` function did not catch this. It may be due to some asynchronous operations in one of the components. But still, not sure, I didn't find any async operations there. There are some resizing / drag-n-dropping handlers in there, it's probably something there.

After an hour, hour and a half of debugging, I just decided to not continue, since the Recoil implementation will totally revamp everything, and hopefully, we'll be able to maybe do some improvements in the error reporting area as well.

Key things to note:
1. The existing [React ErrorBoundary](https://reactjs.org/docs/error-boundaries.html) won't catch async errors (e.g. HTTP requests, event handlers, ...). Only errors that happen during the execution of render code.

2. I found this article, which mentions an interesting solution https://medium.com/trabe/catching-asynchronous-errors-in-react-using-error-boundaries-5e8a5fd7b971.

Nothing revolutionary, but might help.

**Comment by brunozoric** [comment]
@doitadrian we removed the row/cell elements from the page builder. we can introduce some kind of error handling/reporting in Recoil event action handler
