### ISSUE TITLE
Grammatical errors in contributing.md file

### ISSUE THREAD

**Issue by Yash-pardeshi** [webiny/webiny-js#1290]
On the first important paragraph there's written invaluable instead of valuable. I am adding a PR for it

**Comment by Ashu96** [comment]
Hey @Yash-pardeshi, I appreciate your enthusiasm. :)
But, there is no **grammatical** error in that line. 

**Invaluable** means **extremely useful** not the other way around.

If you're new to open source and looking to contribute, I would suggest you check the issues labeled [Good first issue](https://github.com/webiny/webiny-js/issues?q=is%3Aissue+is%3Aopen+label%3Agood-first-issue)
On this note, I'm closing this issue.

**Comment by Yash-pardeshi** [comment]
> Hey @Yash-pardeshi, I appreciate your enthusiasm. :)
> But, there is no **grammatical** error in that line.
> 
> **Invaluable** means **extremely useful** not the other way around.
> 
> If you're new to open source and looking to contribute, I would suggest you check the issues labeled [Good first issue](https://github.com/webiny/webiny-js/issues?q=is%3Aissue+is%3Aopen+label%3Agood-first-issue)
> On this note, I'm closing this issue.

Oh. No idea why my brain worked so interpreting invaluable as not valuable even when I already know that it doesn't mean so.
