### ISSUE TITLE
Adding Table of Content to Readme.md

### ISSUE THREAD

**Issue by ng29** [webiny/webiny-js#1295]
@Pavel910 / @doitadrian 
The idea for Adding Table of Content to Readme.md to add additional enhancement and readability to the docs file.

I would like to work on this issue.
## This is:

- Idea

**Comment by Ashu96** [comment]
Hey @ng29, I appreciate your enthusiasm. :)

But, I strongly believe that the project Readme is quite comprehensible :slightly_smiling_face: 
In the future, it might need restructuring and will reconsider then but for now, it won't be a valuable addition.
On this note, I'm closing this issue.

If you're new to Webinyand looking to contribute, I would suggest you check the issues labeled [Good first issue](https://github.com/webiny/webiny-js/issues?q=is%3Aissue+is%3Aopen+label%3Agood-first-issue)
