### ISSUE TITLE
Fix PluginsContainer.byType method arg and return

### ISSUE THREAD

**Issue by brunozoric** [webiny/webiny-js#1308]
## This is:
- Bug

## Specifications

  - version: all
  - OS: all
  - Browser: all

## Expected Behavior
`byType` method returns all plugins if type is undefined

## Actual Behavior
Method returns all plugins if no type is sent which is not a good thing to do.
It is called `byType` so returning all plugins when type is undefined is wrong.
Check in: https://github.com/webiny/webiny-js/blob/master/packages/plugins/src/PluginsContainer.ts#L48

## Possible Solution
`byType()` method should accept type argument that must be a string, cannot be undefined.
Introduce `all()` method that will return all plugins - return type should be `Plugin[]`.
While already working on this:
* add access modifiers to methods and to plugins attribute
* switch plugins property to Map (of type `Map<string, Plugin>`) and refactor PluginsContainer and assign function accordingly

## Note
Beware that changing byType behaviour there will be issues when someone wanted to get all the plugins with that method so check everything

**Comment by jmakhack** [comment]
Hi @brunozoric, I'd like to work on this issue. Can you assign it to me?

**Comment by brunozoric** [comment]
@jmakhack there you go :)
