### ISSUE TITLE
An error occured when deploying api in local environment

### ISSUE THREAD

**Issue by mehang** [webiny/webiny-js#1315]
I tried following the steps of webiny app

## This is:

- Bug

## Specifications

  - node version: 12.19.0
  - Database: MongoDB hosted in Atlas
  - yarn version: 1.22.10 
  - OS: macOS Catalina 10.15.7
  - Browser: Chrome

## Expected Behavior
The api should deploy to AWS.

## Actual Behavior
Got AccessDenied Exception
 ```
 webiny Collecting components from the template. +0ms
  webiny Executing the template's components graph. +447ms
  webiny:lambdaRole Role 'fc520585_new-project_api_local_lambdaRole' was successfully deployed to region 'us-east-1'. +0ms
  webiny:cognito Input was not changed, no action required. +0ms
  webiny:databaseProxy Building 'databaseProxy' +0ms
  webiny:databaseProxy Finished building 'databaseProxy' +16s
  webiny:databaseProxy Starting deployment of lambda 'fc520585_new-project_api_local_databaseProxy' to the 'us-east-1' region. +6s
  webiny:databaseProxy Packaging lambda code from './databaseProxy/build' +55ms
  webiny:databaseProxy Creating lambda 'fc520585_new-project_api_local_databaseProxy' in the 'us-east-1' region. +578ms
  webiny An error occurred during deployment of databaseProxy +24s
AccessDeniedException: Cross-account pass role is not allowed.
    at Object.extractError (/Users/rai/Code/new-project/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.extractError (/Users/rai/Code/new-project/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/Users/rai/Code/new-project/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/rai/Code/new-project/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/rai/Code/new-project/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/Users/rai/Code/new-project/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/rai/Code/new-project/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/rai/Code/new-project/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/rai/Code/new-project/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/rai/Code/new-project/node_modules/aws-sdk/lib/request.js:690:12) {
  code: 'AccessDeniedException',
  time: 2020-10-19T22:34:09.772Z,
  requestId: '63641f4c-b80b-426d-a9f2-1e8d8a0c01b3',
  statusCode: 403,
  retryable: false,
  retryDelay: 84.240642279624
}
error Command failed with exit code 1.
```

## Steps to Reproduce the Problem

Basically the same step in quick-start [https://docs.webiny.com/docs/get-started/quick-start
](https://docs.webiny.com/docs/get-started/quick-start)
1. Install yarn and node.js. Create AWS account with an IAM user for programmatic usage
2. Created MongoDB database in the cloud
3. Created webiny project using npx
4. Setup database connection 
5.  Deploy API

## Detailed Description
I installed aws cli and tried `aws sts get-caller-identity` which works. But upon deployment it just gives me the error without much detail about it. I tried with SSO, administrator access, IAM, but nothing seems to work.

**Comment by mehang** [comment]
It turned out that when I created the app it stored my another account credentials, so even changing the credentials after that did not seem to work. So reinstalling the app after wiping out old account credentials file seemed to work for me.

**Comment by pitipatdop** [comment]
@mehang So how did you solve this problem? What do you mean be "wiping out old account"

**Comment by mehang** [comment]
@pitipatdop First, I deleted the credential file associated with my old account and then reinstalled webiny.
