### ISSUE TITLE
I'm getting SPAM emails from Sven

### ISSUE THREAD

**Issue by cullylarson** [webiny/webiny-js#1332]
I just got an unsolicited email from @SvenAlHamad, advertising Webiny. I'm not sure how you got my email address, but it seems like a pretty sketchy marketing strategy. I'm definitely taking Webiny off my list of recommended services.

**Comment by cullylarson** [comment]
<img width="1103" alt="Screen Shot 2020-11-11 at 11 33 55 AM" src="https://user-images.githubusercontent.com/10721380/98856475-73752380-2412-11eb-9603-3204689bf3e3.png">

**Comment by SvenAlHamad** [comment]
Hi Cully, sorry you feel it this is SPAM. This is not my intention. I was only looking for feedback. If you feel like I offended you in any way, I apologise.
