### ISSUE TITLE
Feature Request: Webiny Multi-Tenant App and Database Design (Discussion)

### ISSUE THREAD

**Issue by shubham-kaushal** [webiny/webiny-js#1346]
## This is:

- Feature request

## Specifications

  - Webiny Multi-Tenant App and Database Design

## Challenge

The major architectural concern with multi-tenant apps is the database layer, which is also called the persistence layer. There are three aspects of database design that we’ll address:

- The level of tenant data isolation;
- Difficulties with restoring data;
- Difficulties with data encryption.

## Approach

- Single Database for Single Tenant
- Separate Schema for Each Tenant
- Shared Schema for Tenants

We, Will, try to focus our discussion mainly on the best approach i.e. Single Database for Single Tenant.

## Other Challenges

- Optimize cost and performance.

(In most of the cases I noticed when the traffic starts getting ahead of 3 million they are getting charged huge for API requests. We need to pick a good case study to optimize the cost and performance of both. Maybe a hybrid solution is a way to go.) https://twitter.com/coryodaniel/status/1029414668681469952

RSVP: @Pavel910 @doitadrian @SvenAlHamad

**Comment by Pavel910** [comment]
@shubham-kaushal we're already implementing v5 as a multi-tenant system with single DB and single-table design.
DynamoDB is our primary database, but it will also work with other databases. All PKs have a `T#{id}` prefix to differentiate between tenants. Regarding ElasticSearch, which is a crucial part of our system now, we are creating a separate index per-tenant.

For now, with the soon-to-be released v5 `beta`, we'll still only have 1 tenant by default, but tenant management will be developed in 2021, and that is why we already have these basics of data separation baked into the system.

**Comment by shubham-kaushal** [comment]
@Pavel910 v5 sounds very promising and I think it will simplify our work with respect to multi-tenant. Could you plz. align the doc, guide, or repo for multi-tenant with us, so that we can collaborate with you guys on this to release it with v5 only. We are specifically going to start working on this portion from coming Monday so it will help us. The major challenge I am looking at as of now is once we scale, the API request will cost a lot, so how you are looking on to this part because at that moment serverless will be not a good choice with respect to cost.

@narender2031 will also be going to contribute to this. Plz. participate in this discussion with your query and feedback.

**Comment by Pavel910** [comment]
@shubham-kaushal we're glad you're interested in contributing, but until v5 beta is out by the end of December, we won't be taking any contributions on this. It would greatly slow us down and we still haven't touched the documentation of everything, so you can imagine how this makes it impossible for outside contributors to participate.

Once `beta` is out, it will be a lot easier for us to guide the community and document the internals, etc. We'll create a separate plan for implementation of tenancy management UI and API and then we can all discuss it an contribute with code.

See you very soon in the v5 era!! 🚀 ❤️

**Comment by narender2031** [comment]
> The major challenge I am looking at as of now is once we scale, the API request will cost a lot, so how you are looking on to this part because at that moment serverless will be not a good choice with respect to cost.

yes agree I agree with the @shubham-kaushal regarding the cost. I think we need think an alternative or come up with a architecture that can solve this issue.

**Comment by Pavel910** [comment]
@narender2031 @shubham-kaushal Webiny is a serverless platform, and we won't be looking into anything server related as our main course of development. I'm not sure about what you're aiming at, but just wanted to make it clear. 

If you have some concrete ideas, feel free to flush them out, and we can discuss the potential and validity of those ideas. If you  feel that your project will be too expensive, maybe Webiny is just not the right tool for the job.

**Comment by shubham-kaushal** [comment]
**High Compute Use Case:** For high compute use cases (such as ETL jobs, real-time data processing & video processing) consider the following scenario for application:

Allocated memory 2496 MB
No. of invocations: 30,000,000 times/month
Execution duration: 500 sec

**AWS Lambda Pricing Calculation:**
GB-sec = 30,000,000 * 0.5s * 2496/1024 = 36,562,500 GB-sec
Compute charges = 36,562,500 * $0.00001667 = $609.5
Request charges =  (30,000,000/1,000,000) * $0.2/Million = $
Total charges = $609.5 + $6 = $615.5

**EC2 Pricing Calculation:**
Considering this as a high-end compute work, even if we consider m4.large with 8GB memory, the monthly cost would be $138.2424

@Pavel910 Will love to know our feedback on this use case.

**Comment by shubham-kaushal** [comment]
My observation Lambda works best around and below 3 million function executions per month ([source](https://cloudserviceevaluation.com/2017/02/02/lambda-or-ec2-which-one-do-you-use-to-save-the-most-money/)) since we’d want to operate in the range where the free executions that come with Lambda still have a noticeable impact on the bill.

However, if the traffic starts getting ahead of 3 million, the cost will be very very high.

@Pavel910

**Comment by Pavel910** [comment]
Video processing is definitely not something you should run on Lambdas. Functions are not a solution for every problem in your life. But they are for a vast range of business scenarios. Looks like your case is just not suitable to be run on top of Lambdas. Another thing that is very clumsy with serverless - websockets. If you need websockets - don't go the Lambda way.

But - that doesn't mean you can't combine Webiny in a serverless environment, with EC2 workers for your heavy data processing. Webiny is and serverless is great for business applications development, and any kind of application that is suitable for a serverless environment.

So I think you just need to weigh what is worth running on serverless, and what is not. Webiny is not the problem here, but the actual technology. You must find what suits your project best.

**Comment by shubham-kaushal** [comment]
So, I think the hybrid approach will be better, Lambda with EC2.

If I will consider Shopify (eCommerce SaaS) then how do you suggest to implement the Architecture with Webiny?

@Pavel910

**Comment by shubham-kaushal** [comment]
https://github.com/webiny/webiny-js/blob/v5/packages/api-security-tenancy/src/context.ts#L13
It looks like we can connect to any database that includes in the header

Today I think we should verify whether that database belongs_to the user or not

Also, I was checking the latest doc but didn't found the Diagram for Tenancy. Could you plz. share the diagram fo tenancy.

cc: @Pavel910 @doitadrian

**Comment by Pavel910** [comment]
@shubham-kaushal multi-tenancy will be rolled out as an enterprise-only feature. We took this direction as many clients wanted to have a ready-made solution for SaaS applications out of the box and the multi-tenancy deployment has to be tailor made to many individual cases and we’re only able to provide that through our enterprise support model (there are many technical challenges that vary depending on the use-case). 

Having it as part of the open-source model would make Webiny installation and configuration experience a lot more complicated and we didn’t want to do that. Finally, it’s a way for us to make revenue and keep the project alive.

Regarding the database: yes you can have as many DB connections (in case of Mongo/SQL) or use as many Dynamo tables as you need. The user, as in "Webiny security user", has no relation to the DB. Database is an infrastructure resource and access to it is configured however you want (IAM role, credentials, whatever it is the DB needs). Once the Lambda is executed, no matter which user is authenticated via `Authorization` token, everybody uses the same DB.

**Comment by geekyayush** [comment]
> @shubham-kaushal multi-tenancy will be rolled out as an enterprise-only feature. We took this direction as many clients wanted to have a ready-made solution for SaaS applications out of the box and the multi-tenancy deployment has to be tailor made to many individual cases and we’re only able to provide that through our enterprise support model (there are many technical challenges that vary depending on the use-case).

Is there any way an individual can integrate multi-tanency?
Sorry for commenting on an old issue.

**Comment by SvenAlHamad** [comment]
Hey @geekyayush - the multi-tenancy options are available in our business and enterprise tiers. More on the multi-tenancy features: https://www.webiny.com/docs/overview/features/multi-tenancy

I don't think the system would work with a custom multi-tenancy implementation given that all apps and the database is architected towards our built-in implementation. If you would roll out a custom implementation, it would be a single-tenanted setup from Webiny's side with then a custom tenancy module on top, which wouldn't work efficiently. The only way I see that to work would be a custom fork with a lot of changes to the core which would in my view be a very hard thing to maintain on an ongoing basis.
