### ISSUE TITLE
Using Webiny without AWS?

### ISSUE THREAD

**Issue by excitedbox** [webiny/webiny-js#1347]
Webiny looks like a great platform but if using any AWS services is a requirement that eliminates many use cases out of privacy and security concerns. Any privacy sensitive APP should not be using any services hosted by Amazon or Google because of their blatant disregard for customer privacy and data harvesting. We have all heard of the cases where a pregnant teen gets advertisements for pregnancy test/products due to her online behavior but there are other security issues as well.

ALL these companies that harvest data present an extreme security risk as hackers have been using databases of personal information to crack security questions. When some marketing partner gets hacked or exposes their db you may not hear about it or care if it is a company you don't use. Those companies may have been storing private information such as Pets, Mothers maiden name, hair color and old address information. (Ever wonder what those "what dragon are you" FB quizzes are used for?) Hackers are building relational DBs and profiles on people to match their social circles and attack their email and banking.

When Yahoo got hacked and exposed millions of addresses and emails you may not have cared because you don't use Yahoo but what if Yahoo bought your data from someone else? Or if some random developer misconfigured their cloud instance? A recent scan of AWS showed thousands of exposed drives containing everything from password lists to databases of customer banking records.

Obviously all this spying companies are doing and actively trying to prevent users from opting out should be illegal, but until it is ANY ethical and customer minded App or Website needs to be 100% self hosted. There are plenty of Open Source alternatives such as OpenAuth.

**Comment by SvenAlHamad** [comment]
Hi @excitedbox thanks for raising those concerns. At the moment Webiny is AWS only, but there are potentials to get it working with something like kubernetes, which in theory would allow you to self host Webiny on private infrastructure. 
However at the moment we’re quite constrained with engineering resources and are not able to focus on that. If you’re interested in doing this work and contributing to the project, we can provide references and guidance.

**Comment by excitedbox** [comment]
I would love to help but I am always quick to jump onto a project and am way to overloaded at the moment. I am gonna look at the code and see if I find a solution I can integrate without too much work. If it is still needed when I get some free time I will try and work on it but I can't make any promises right now.

**Comment by SvenAlHamad** [comment]
Sounds good ... I'll close the issue for now and if you decide to tackle it at a later point feel free to reopen it.
