### ISSUE TITLE
Automating the webapp

### ISSUE THREAD

**Issue by himanshu007-creator** [webiny/webiny-js#1367]
I would like to work on this issue.I will create a script that will enable opening website from CLI.
Please add DWOC label to it and assign me this issue.

**Comment by Pavel910** [comment]
@himanshu007-creator please follow the issue template and describe what the issue is, and how you plan to solve it.

**Comment by himanshu007-creator** [comment]
Bash script to open the website using CLI

## This is:
- Feature request




## Specifications

  - version:
  - OS:
  - Browser:

## Expected Behavior


## Actual Behavior


## Steps to Reproduce the Problem
try to open website in UBUNTU. It takes some time.

## Detailed Description
Id a developer is working on operating systems like UBUNTU , where all work is dont through CLI, opening the website is quite difficult. 
## Possible Solution
So i will make a bash script.Running it will open the website instantaneously

**Comment by Ashu96** [comment]
hey @himanshu007-creator can you please provide a screen recording of the what exactly is the issue. The steps to reproduce it.
Please also mention the **Specifications** details like `version, OS and Browser`.
Thanks

**Comment by himanshu007-creator** [comment]
I will work on it, I am having exams rn.

**Comment by Pavel910** [comment]
@himanshu007-creator if you plan to contribute, please read the [guide on contributing first](https://github.com/webiny/webiny-js/blob/next/docs/CONTRIBUTING.md#working-on-an-issue). PRs without a connected issue will not be accepted. Make sure you open an issue first and describe the exact problem in details. If possible, attach screenshot to better illustrate your problem.
