### ISSUE TITLE
New Feature: Plugin for subFooter

### ISSUE THREAD

**Issue by shubham-kaushal** [webiny/webiny-js#1371]
## This is:
- Feature request for customize ability of subFooter by creating plugin for the same.

## Specifications
N/A

## Expected Behavior
Customize the subFooter

## Actual Behavior
non-customizable

## Steps to Reproduce the Problem
N/A

## Detailed Description
N/A

## Possible Solution
Instructions to create plugin for customizing ability of subFooter.

cc @doitadrian

**Comment by doitadrian** [comment]
Just checking, is this still relevant? 

Not sure how you're going to proceed, since you mentioned a complete from-scratch UI creation is possible on your end.

**Comment by shubham-kaushal** [comment]
> Just checking, is this still relevant?
> 
> Not sure how you're going to proceed, since you mentioned a complete from-scratch UI creation is possible on your end.

Yes, we decided to create the UI from scratch but this will be still relevant as we will trying to experiment & learn more with Webiny so the instructions will be helpful. Also, if you can give us a little insight on replacing the UI from scratch what are the parts that need to look into deep then it will be a great help.

**Comment by shubham-kaushal** [comment]
@doitadrian Still waiting for your update on this.
