### ISSUE TITLE
Deploy with no AWS credentials redirects to wrong url

### ISSUE THREAD

**Issue by ElianVanCutsem** [webiny/webiny-js#1396]
## This is:

- Question

When running the deploy command without valid AWS credentials, the info/error msg redirects you to a non existing page: [https://docs.webiny.com/docs/guides/aws-credentials
](https://docs.webiny.com/docs/guides/aws-credentials). It should be changed to: [https://docs.webiny.com/docs/how-to-guides/deployment/configure-aws-credentials](https://docs.webiny.com/docs/how-to-guides/deployment/configure-aws-credentials)

**Comment by bulentaltay** [comment]
second link above is also invalid.
