### ISSUE TITLE
Allow querying by entryId in headless CMS read api.

### ISSUE THREAD

**Issue by econtentmaps** [webiny/webiny-js#1404]
- Feature request

## Detailed Description
Let’s say I’m using getArticles query (to get a single item from my Articles model).
Get queries expect a primary key so they can fetch the specific item.

With articles etc, title etc can be changed by the user, and the CMS modifies the ID on each publish/save. We need a way to uniquely identify an article for the purposes of the query, that doesn’t change when changes are saved/published

## Possible Solution
As discussed, allow query by entryId via the read API.

**Comment by Pavel910** [comment]
To add more context to this issue, here's an example from the Playground:
![image](https://user-images.githubusercontent.com/3920893/114362311-7a49c300-9b77-11eb-9742-f746895c4955.png)

I think we should simply allow querying by `entryId`, without the revision part. It should return the latest published record.
Also, it would be useful to expose some kind of `_entryId` field, so consumers of the API don't have to manipulate the `id` string themselves.

**Comment by jimjoes** [comment]
Hello! Do you have an idea yet what release, if any, this might end up in?

**Comment by Pavel910** [comment]
@econtentmaps no idea :) It will eventually.

**Comment by brunozoric** [comment]
This is resolved with https://github.com/webiny/webiny-js/pull/1660.

**Comment by yk-company** [comment]
I have the same problem in v5.39.2

**Comment by brunozoric** [comment]
hi @yk-company 
it is possible to filter by `entryId` or `id`. contact us on https://webiny-community.slack.com/ if you have problems with this filter.

**Comment by yk-company** [comment]
I do not have access to the slack, but it worked with entryId, sorry for wasting your time. (I thought entryId was a free text field to set our own Id system)

**Comment by brunozoric** [comment]
@yk-company 
you can register and ask questions there.

**Comment by yk-company** [comment]
I would be able to register if I had an email coming from these domaines :  
- webiny.com
- musth.io
- guildeducation.com
- groundfog.cloud
- influencemachines.com
- asco.org
- panasonic.aero
- robotsandpencils.com
- freshcells.de


But I don't, so I have te ask an administrator to send me an invitation (it's the message that I got when trying to register).
But thank you very much for your help.

**Comment by SvenAlHamad** [comment]
@yk-company just use this link to register, all domains are accepted: https://www.webiny.com/slack
