### ISSUE TITLE
Improve scaling of block preview

### ISSUE THREAD

**Issue by Pavel910** [Webiny/webiny-js#141]
There is a dedicated scaling component: `webiny-app-cms/src/editor/plugins/blockEditing/AutoScale.js`.

![image](https://user-images.githubusercontent.com/3920893/45749970-a2febb80-bc0d-11e8-95d3-346aeb1f34a6.png)

**Comment by SvenAlHamad** [comment]
The scaling is fixed with the new "image" approach. Closing this issue.
