### ISSUE TITLE
Setting width of grid in Page Builder affects child cells, too.

### ISSUE THREAD

**Issue by jimjoes** [webiny/webiny-js#1412]
## This is:

- Bug

## Specifications

  - version: 5.beta.4
  - OS: MacOs
  - Browser: Chrome 88.0.4324.96

## Actual Behavior
Setting the width of a grid to 50% makes the width of a child cell also 50% (i.e. the cell becomes 25%, rather than just 50% (minus a little)).

## Expected Behavior
Setting the width of a grid to 50% shouldn't directly affect the width % of its children.

## Steps to Reproduce the Problem

1. Create page
2. Create block 
3. Create grid
4. Set grid to 50%.
5. The cell also gets set to 50%.

**Comment by jimjoes** [comment]
This is still a problem in 5.4.0.

**Comment by Pavel910** [comment]
@econtentmaps thanks for the bump. Need to reconfigure the stale bot... Reopening this.

**Comment by Ashu96** [comment]
@econtentmaps Can you please provide some screenshots? It will help in reproducing the bug.
Thanks :+1:

**Comment by jimjoes** [comment]
Hi. Sorry. Missed the screenshot request.

It's pretty simple. create a grid. add an element to it. Set the grid to 50% width. The grid is 50%, but its contents are also 50% *of the grid's width* - they should remain at 100% of the grid, regardless of the grid's width.

![image](https://user-images.githubusercontent.com/61049336/135049524-697e5a09-c6da-436f-8004-33d534ab0158.png)

**Comment by Pavel910** [comment]
@econtentmaps thanks, screenshots help a lot. Keep in mind that we work on dozens of completely unrelated features every week and context switching is difficult if not enough information is provided in the issue. A screenshot tells a thousand words.

This makes sense, we'll keep track of this and see when we can squeeze this in our product cycles. 🍻

**Comment by jimjoes** [comment]
Yea - I raised this when 5 came out and I did a load of testing but I omitted the screenshots in many cases. Sorry :)
