### ISSUE TITLE
Headless CMS: Setting a before or after validator when creating/editing date field causes blank page

### ISSUE THREAD

**Issue by jimjoes** [webiny/webiny-js#1419]
## This is:

- Bug

## Specifications
  - version: 5.beta.4
  - OS: MacOS Catalina
  - Browser: Chrome 88.0.4324.146

## Expected Behavior
You should be able to set a "before" or "after" validator on a date field and configure its options.

## Actual Behavior
As soon as you set the switch to 'on' in the validator tab, the page goes blank.

## Steps to Reproduce the Problem
1. create new model
2. add date field
3. set before or after validator to 'on'
4. screen goes blank

**Comment by brunozoric** [comment]
Hi @econtentmaps 

Can you provide console error? Did it happen again in the 5.0.0?
