### ISSUE TITLE
Headless CMS: Modifying a date that is already set causes blank page 

### ISSUE THREAD

**Issue by jimjoes** [webiny/webiny-js#1420]
## This is:

- Bug
- 
## Specifications
  - version: 5.beta.4 
  - OS: MacOS Catalina
  - Browser: 88.0.4324.146

## Expected Behavior
You should be able to modify the date by typing

## Actual Behavior
The page goes blank as soon as you start typing in a date field that's already got a value

## Steps to Reproduce the Problem

1. create model
2.create date field
3. set date field value
4. edit date field value by typing
5. page goes blank

**Comment by brunozoric** [comment]
Hi @econtentmaps 

Can you provide more info about the error? Did it happen again in the 5.0.0?

**Comment by Pavel910** [comment]
@econtentmaps can you still reproduce this issue? There were many releases since this was reported, just wondering if you're still running into this. Cheers!
