### ISSUE TITLE
Headless CMS: Can't add items to a model with a date/time (no timezone) field

### ISSUE THREAD

**Issue by jimjoes** [webiny/webiny-js#1422]
## This is:
- Bug

## Specifications
  - version: 5.beta.4
  - OS: MacOS Catalina
  - Browser: 88.0.4324.146

## Expected Behavior
You should be able to add the item.

## Actual Behavior
Save gives an error: "mapper_parsing_exception". The item seems to have been sort of saved because, even though I've not been able to save the item and it doesn't appear in the list of content items for the model, when I try and delete a field from the model, it gives me this error: "Cannot remove the field "date" because it's already in use in created content.".

## Steps to Reproduce the Problem

1. Attempt to add an item
2. Get error "mapper_parsing_exception"

## Detailed Description.

I think this happens when there is a date/time (no timezone) field and at least one other field.

The snackbar error is:  "mapper_parsing_exception"

The console error is: 
`2.724ef4bf.chunk.js:2 Uncaught (in promise) TypeError: Cannot read property 'reduce' of null
    at k (2.724ef4bf.chunk.js:2)
    at 2.724ef4bf.chunk.js:2
    at l (2.724ef4bf.chunk.js:2)
    at Generator._invoke (2.724ef4bf.chunk.js:2)
    at Generator.next (2.724ef4bf.chunk.js:2)
    at n (2.724ef4bf.chunk.js:2)
    at c (2.724ef4bf.chunk.js:2)`

The CMS mutation payload is:
```
[{
	"operationName": "CmsEntriesCreateTimelineEvents",
	"variables": {
		"data": {
			"title": "Step 1 Demo",
			"date": "2021-01-04 00:00:00",
			"dateType": "first",
			"reference": "pilot",
			"content": [{
				"type": "paragraph",
				"data": {
					"text": "In as little as an hour, we can remotely present the Skuup solution and demonstrate the high-level features of our platform, explaining in clear terms how it all works and what you are being promised.",
					"textAlign": "left",
					"className": ""
				}
			}],
			"color": "white",
			"backgroundColor": "grey",
			"icon": "preview"
		}
	},
	"query": "mutation CmsEntriesCreateTimelineEvents($data: TimelineEventsInput!) {\n  content: createTimelineEvents(data: $data) {\n    data {\n      id\n      savedOn\n      title\n      date\n      dateType\n      reference\n      content\n      color\n      backgroundColor\n      icon\n      meta {\n        title\n        publishedOn\n        version\n        locked\n        status\n        __typename\n      }\n      __typename\n    }\n    error {\n      message\n      code\n      data\n      __typename\n    }\n    __typename\n  }\n}\n"
}]
```

The response from the CMS mutation is:
```
[{
	"data": {
		"content": {
			"data": null,
			"error": {
				"message": "mapper_parsing_exception",
				"code": "",
				"data": null,
				"__typename": "CmsError"
			},
			"__typename": "TimelineEventsResponse"
		}
	},
	"extensions": {
		"console": []
	}
}]
```

**Comment by brunozoric** [comment]
Hi @econtentmaps!

That was a beta bug where Elasticsearch mapping was wrong. It was fixed in 5.0.0.
