### ISSUE TITLE
Headless CMS: Using (sort: field_ASC) or (sort: field_ASC), where 'field' is a number, returns no results and no error

### ISSUE THREAD

**Issue by jimjoes** [webiny/webiny-js#1433]
## This is:
- Bug
- 
## Specifications

  - version: 5.beta.4
  - OS: MacOD
  - Browser: Chrome 88.0.4324.146

## Expected Behavior
The query should return results in order.

## Actual Behavior
The query returns no results and no error

## Steps to Reproduce the Problem

1. Create model with a text, richtext and a number field
2. Create some items
3. example query sorting by the number field:

```
query {
  listTabordions(sort: priority_ASC) {
    data {
    heading
    content
  }}
}
```

4. response: 

```
{
  "data": {
    "listTabordions": {
      "data": null
    }
  },
  "extensions": {
    "console": []
  }
}
```

**Comment by brunozoric** [comment]
Hi @econtentmaps!

I will take a look and write a test for it just in case.

Btw. I noticed that you are sorting with `sort: priority_ASC`, it should be `sort: [priority_ASC]`.

best regards

**Comment by brunozoric** [comment]
Hi @econtentmaps!

Sorting is working. PR with the test for number sorting is here: https://github.com/webiny/webiny-js/pull/1516

Can you query with this:
```
query {
  listTabordions(sort:[priority_ASC]) {
    data {
      heading
      content
    }
    error {
      message
      code
      data
    }
  }
}
```

**Comment by Pavel910** [comment]
@brunozoric what's the status of this issue?

**Comment by brunozoric** [comment]
@Pavel910 I don't think it is an issue, sort value was not an array and @econtentmaps did not fetch errors to see what is wrong. I will close.
