### ISSUE TITLE
Replacing Cognito with Ory IDaaS Solution in Webiny

### ISSUE THREAD

**Issue by shubham-kaushal** [webiny/webiny-js#1456]
## This is:

- Question

## Specifications

  Guide for replacing Cognito with Ory IDaaS Solution in Webiny.

## Expected Behavior

Use Ory

## Actual Behavior

Using Cognito

## Steps to Reproduce the Problem

N/A

## Detailed Description

Use Ory as an IDaaS (Identity Provider as a Service) Solution
ORY Hydra for OAuth 2.0 and OpenID Connect provider.
ORY Oathkeeper for Identity and Access Proxy.
ORY Keto for access control server.
ORY Kratos for the identity management server.
Combine them to get the full feature set. 

## Possible Solution

Guide for replacing Cognito with Ory IDaaS Solution in Webiny.

cc @Pavel910 @doitadrian

**Comment by Pavel910** [comment]
Reopened the issue: security articles are WIP and should be available shortly. Then you can work on ORY integration.

**Comment by Pavel910** [comment]
In Webiny 5.9.0, security packages were reorganized and refactored to be more approachable, and you can now use them as a reference for integrating any identity provider. Docs are still not not available, but the general concepts are described in the key topics articles about [Webiny Security Framework](https://www.webiny.com/docs/key-topics/security-framework/introduction).

The following are the relevant packages you can study for examples:
- [api-security](https://github.com/webiny/webiny-js/tree/next/packages/api-security/src)
- [api-security-cognito-authentication](https://github.com/webiny/webiny-js/tree/next/packages/api-security-cognito-authentication/src)
- [api-security-admin-users](https://github.com/webiny/webiny-js/tree/next/packages/api-security-admin-users/src)
- [api-security-admin-users-cognito](https://github.com/webiny/webiny-js/tree/next/packages/api-security-admin-users-cognito/src)

And the relevant React packages:
- [app-security](https://github.com/webiny/webiny-js/tree/next/packages/app-security/src)
- [app-security-cognito-authentication](https://github.com/webiny/webiny-js/tree/next/packages/app-security-cognito-authentication/src)
- [app-security-admin-users](https://github.com/webiny/webiny-js/tree/next/packages/app-security-admin-users/src)
- [app-security-admin-users-cognito](https://github.com/webiny/webiny-js/tree/next/packages/app-security-admin-users-cognito/src)
