### ISSUE TITLE
How to rollback a deploy on AWS?

### ISSUE THREAD

**Issue by serban-mihai** [webiny/webiny-js#1467]
Awesome project first of all but I was wondering, how can we rollback a deploy on AWS if we can?

I deployed on the `dev` environment just for testing and now I would like to cleanup everything that has been created there (DynamoDB Table, Cloudfront Distributions, S3 Buckets and so on)
I read the docs but I didn't find any other command for webiny besides `deploy`, do I have to delete everything by hand?

Also is there a way to deploy just the API and the Admin without the Website itself?

## This is:
- Question

**Comment by Pavel910** [comment]
@serban-mihai Thanks, glad you dig it:) 

For granular deploy: https://docs.webiny.com/docs/how-to-guides/deployment/deploy-your-project#the-app-deploy-command
For removal of resources: https://docs.webiny.com/docs/how-to-guides/deployment/destroy-your-project

Also, feel free to join our [Slack Community](https://www.webiny.com/slack), it's a great place to ask question and go deeper with discussions.
Cheers!

**Comment by serban-mihai** [comment]
I don't know how I missed those :)
Thanks a lot for the quick reply!
