### ISSUE TITLE
Page Builder: Improvements to saved block management

### ISSUE THREAD

**Issue by jimjoes** [webiny/webiny-js#1518]
## This is:
- Feature request

## Detailed Description
The following improvements/features would make the use of Blocks much easier:

1. Allow the user to change which group a block is a member of (e.g. content, header etc)
2. Allow existing blocks to be updated/saved over
3. The list of blocks appears to be cached locally. If a block is deleted, the cache is not invalidated, so the deleted block is still listed. Allowing editing will make this less of an issue, but if you have to delete and recreate blocks to edit them, this behaviour is problematic as saving an item with the same name as a deleted one seems to fail.

**Comment by Ashu96** [comment]
Hi @econtentmaps,

The requested improvements/features already exist in the Page Builder app.

Although, there is a bug whereby the preview of the updated block doesn't get stored properly which makes that operation look broken.
We're aiming to resolve that bug in the upcoming release. Please check out the linked PR for more detail.
