### ISSUE TITLE
Cannot create scaffold other than default example (Books)

### ISSUE THREAD

**Issue by davea38** [webiny/webiny-js#1522]
## This is:

- Bug

## Specifications

  - Version: 5.2.0
  - OS: Ubuntu 20.04
  - Browser: N/A

## Expected Behavior

CLI scaffold should create a custom GraphQL type

## Actual Behavior

Scaffold crashes with exception

```bash
yarn webiny scaffold
? Pick a template to scaffold GraphQL API package
? Enter the name of the initial data model Session
? Enter the package location packages/sessions/api
? Enter the package name @sessions/api
✔ Service files created in /home/dev/webiny-test/packages/sessions/api.
✔ Added @sessions/api to api package.json.
✔ Workspace packages/sessions/api added in root package.json.
✔ Package name set into package.json.
✔ Update package tsconfig extends path.
✔ Update package tsconfig.build extends path.
✔ Updated base tsconfig compilerOptions.paths.
✔ Dependencies installed.
WError: Unable to install dependencies. Try running "yarn" in project root manually.
    at Object.generate (/home/dev/webiny-test/node_modules/@webiny/cli-plugin-scaffold-graphql-service/index.js:359:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async scaffold (/home/dev/webiny-test/node_modules/@webiny/cli-plugin-scaffold/scaffold.js:54:5) {
  code: 'Command failed with exit code 1: yarn build\n' +
    'Successfully compiled 14 files with Babel (1378ms).\n' +
    `src/es.ts(1,10): error TS2305: Module '"./types"' has no exported member 'ListBooksWhere'.`,
  data: null
}
```

## Steps to Reproduce the Problem

1. Run ```yarn webiny scaffold```
2. Select ```GraphQL API package```
3. Enter anything other than Books for the initial data model
4. Accept defaults for further prompts

## Detailed Description

As above

## Possible Solution

This is probably a problem with the Books example being hard-coded? I haven't checked the code so that's my first guess.

**Comment by adrians5j** [comment]
I can confirm this happening on my end too:
![image](https://user-images.githubusercontent.com/5121148/111814831-3bf41780-88db-11eb-92c9-1d27b2aac62a.png)

**Comment by StefanoAgazzi** [comment]
Same for me, I had to manually fix the following import while build is running:
<img width="792" alt="image" src="https://user-images.githubusercontent.com/2686945/111837096-a4e98880-88f7-11eb-9e25-3d0e6bd2b9ff.png">

I could only do this becuase I had an antivurs that pause the scaffold script asking for permission, otherwise the scaffold would run quickly and I could not fix it manually. 

In addiction, dunno if it is related or not, but the Main GraphQL playground endpoint is not working:
<img width="440" alt="image" src="https://user-images.githubusercontent.com/2686945/111837764-a8c9da80-88f8-11eb-81be-96c496cacedf.png">
When browsing to the provided URL, I get the following response:
`{"message":"Not Found"}`

**Comment by Pavel910** [comment]
@StefanoAgazzi the playground is not served from the API. Playground is embedded into the `admin` app and it handles the authorization tokens for you. If you want to access it externally, use https://www.electronjs.org/apps/graphql-playground and use one of the API endpoints, but in this case you'll need to add an Authorization header with an API Key created in the Security module in the `admin` app.

The easiest way is to just use use it via the admin app.

**Comment by brunozoric** [comment]
@StefanoAgazzi yes, unfortunately there is ListBooksWhere left hardcoded in the code. Its something I missed from before v5.0.0 it seems. Change the ListBooksWhere to `ListSessionsWhere` and start the build process again.
Fix is on the way.
