### ISSUE TITLE
Just wanted to show you the amazing Webiny stickers !!!

### ISSUE THREAD

**Issue by jbampton** [webiny/webiny-js#1527]
Close this issue whenever.

I got the picture on my GitHub profile too -> https://github.com/jbampton

Hope to soon have more swag stickers.

The big Webiny sticker is great 👍 

The side of my dusty old bookshelf showing swag:

![bookshelf](https://user-images.githubusercontent.com/418747/111987661-3573d300-8b5b-11eb-884e-ec68658200d0.png)

**Comment by SvenAlHamad** [comment]
@jbampton we can always make them bigger :D 
Thanks for sharing this, looks great and an amazing company to be in!
