### ISSUE TITLE
Deploy Webiny to Local System instead of Aws? 

### ISSUE THREAD

**Issue by dukesx** [webiny/webiny-js#1528]
### This is:
- Question

### Question
Isnt there a way that I can use webiny and build my application  without pushing to amazon aws? Just deploy on my local system.

**Comment by Pavel910** [comment]
@dukesx in short - no. Webiny is a cloud-native system which relies on many cloud services that can't be emulated locally. It's not just Lambda we use, it's also Dynamo Streams, S3 events, Cognito, soon to come SQS. We are focused on serverless, and don't plan to support servers/containers.
