### ISSUE TITLE
404 when visiting link after failed deployment

### ISSUE THREAD

**Issue by knollfear** [webiny/webiny-js#1553]
The link listed in this error message (I was to blame for the error) points to a page that currently gives me a 404 error
```
webiny info: Running "hook-before-deploy" hook...

webiny error: Looks like your AWS credentials are not configured correctly!
webiny info: To learn how to configure your AWS credentials, visit https://docs.webiny.com/docs/how-to-guides/deployment/configure-aws-credentials
```

## This is:

- Bug

## Specifications

  - version:
  - OS:
  - Browser:

## Expected Behavior

The link should go to a page with documentation on how I should configure my credentials.
## Actual Behavior

I get a 404 page not found error
## Steps to Reproduce the Problem

1. [Click on this link](https://docs.webiny.com/docs/how-to-guides/deployment/configure-aws-credentials)
2. 
3.

## Detailed Description

The link provided just isn't right.  I think the website may have just been remodeled and this artifact got left.
## Possible Solution

I think this is the right page.  https://www.webiny.com/docs/how-to-guides/deployment/aws/configure-aws-credentials  You may need to look for other instances of docs.webiny.com or maybe just put in a DNS redirect to webiny.com/docs?

**Comment by adrians5j** [comment]
This was fixed, just not yet released (https://github.com/webiny/webiny-js/pull/1539).

Thanks for reporting anyways! 🚀
