### ISSUE TITLE
Warn users before creating aws resources

### ISSUE THREAD

**Issue by braco** [webiny/webiny-js#1563]
It was a surprise to me that all the aws services were being created. I'm sure I didn't read the docs carefully enough, but this is a huge point that I think deserves a warning in the command line.

"yarn webiny deploy" doesn't hint that it's going to use the system's aws credentials to create so many resources.

A simple "This is going to create resources on aws using your default account, is this ok? [y/N]" would go a long way.

**Comment by Pavel910** [comment]
@braco thanks for stopping by!
To be honest, I'm not sure how it can be a surprise. AWS and cloud infrastructure is mentioned several times at the very beginning of the [Install Webiny](https://www.webiny.com/docs/tutorials/install-webiny) tutorial. [AWS account](https://www.webiny.com/docs/tutorials/install-webiny#aws-account-and-user-credentials) is in the `prerequisites` section. [First Deployment](https://www.webiny.com/docs/tutorials/install-webiny#first-deployment) has this in the first sentence: `it's time to deploy it into your AWS account`.

Just by looking at the content above the fold, AWS is mentioned 3 times:
![image](https://user-images.githubusercontent.com/3920893/114853568-34ddfd80-9de4-11eb-9d14-216be7f53499.png)

It's kind of hard to miss. Besides, the word `serverless` is mentioned so many times all over our website, and docs, it can't be a surprise that you'll be deploying resources to the cloud.

---
To remove all the resources from your AWS account, see this article: https://www.webiny.com/docs/how-to-guides/deployment/destroy-cloud-infrastructure/#the-destroy-command

**Comment by braco** [comment]
The surprise wasn't that those things are in use at some point, the surprise was that command begins deploying remote services immediately. Like I said, surely it's my fault for not reading more carefully, just want to point out that the severity of that command in my opinion warrants an "are you sure?" on the first run.

(This is an aside, but I actually think it's a big security issue on the part of aws cli tooling that there are no application-level permissions needed)

Thank you for your thorough reply
