### ISSUE TITLE
Discussion on Vite (unbundled development) with Webiny

### ISSUE THREAD

**Issue by shubham-kaushal** [webiny/webiny-js#1568]
## This is:

- Idea

## Specifications

  Vite for build tools

## Expected Behavior

Vite (unbundled development) with Webiny

## Actual Behavior

Webpack with Webiny

## Steps to Reproduce the Problem

Run the Webiny project for build and experience slow build process.

## Detailed Description

The current build of Webiny with Webpack is very slow and time-consuming.

## Possible Solution

Use Vite and improve the build from hrs. to a few min./sec.
Looking forward to discussions on this.
cc @Pavel910

**Comment by Pavel910** [comment]
@shubham-kaushal

I see Vite is a frontend tool, so you can easily integrate it into your Webiny project yourself. See this https://www.webiny.com/docs/how-to-guides/webiny-cli/working-with-workspaces#how-it-works. 

This is the place in your project where you can replace webpack with any other tool:
- for `admin` - `apps/admin/code/webiny.config.js`
- for `website` - `apps/website/code/webiny.config.js`

We also did some research on Webpack 5, it's a lot faster than Webpack 4, but it's not a 10 minute task to upgrade. With all the other top-priority tasks, this one is not the highest priority for us. 

If you do get to try Vite with Webiny, and run into problems, let us know, we may be able to assist with insight and potential changes in the actual code.
