### ISSUE TITLE
Error occurs during upgrade from 5.4.0 to 5.5.0

### ISSUE THREAD

**Issue by taifok** [webiny/webiny-js#1574]
## This is:

- Bug

## Specifications

  - version: 5.4.0
  - OS: Windows WSL

## Expected Behavior

upgrade from 5.4.0 to 5.5.0

## Actual Behavior

error

## Steps to Reproduce the Problem

1. `yarn webiny upgrade 5.5.0`

## Detailed Description

Missing `webiny.application.js` in `@webiny/cli/commands/upgrade/upgrades/5.5.0/templates/webinyApplication/api/`

```
Step 3 of 6:
webiny info: Creating webiny.application.js files...
webiny error: An error occurred while executing the Webiny 5.5.0 project upgrade script:
Error: ENOENT: no such file or directory, copyfile '/home/taifok/projects/my-new-project2/node_modules/@webiny/cli/commands/upgrade/upgrades/5.5.0/templates/webinyApplication/api/webiny.application.js' -> '/home/taifok/projects/my-new-project2/api/webiny.application.js'
    at Object.copyFileSync (fs.js:1991:3)
    at createWebinyApplication (/home/taifok/projects/my-new-project2/node_modules/@webiny/cli/commands/upgrade/upgrades/5.5.0/index.js:194:16)
    at Object.upgrade (/home/taifok/projects/my-new-project2/node_modules/@webiny/cli/commands/upgrade/upgrades/5.5.0/index.js:43:19)
    at Object.handler (/home/taifok/projects/my-new-project2/node_modules/@webiny/cli/commands/upgrade/index.js:37:21) {
  errno: -2,
  syscall: 'copyfile',
  code: 'ENOENT',
  path: '/home/taifok/projects/my-new-project2/node_modules/@webiny/cli/commands/upgrade/upgrades/5.5.0/templates/webinyApplication/api/webiny.application.js',
  dest: '/home/taifok/projects/my-new-project2/api/webiny.application.js'
}
```

**Comment by adrians5j** [comment]
Hey @taifok, thanks for reporting, we'll release a fix for this during the day, and notify you once it's up.

**Comment by adrians5j** [comment]
We've updated the upgrade docs (https://www.webiny.com/docs/how-to-guides/upgrade-webiny/5.4.0-to-5.5.0/#upgrade-webiny-project).

Basically, before running the `yarn webiny upgrade 5.5.0`, please run the following:

```bash
npx https://gist.github.com/doitadrian/80c1407e3b513f8e1daaf77ae9e4703b
``` 
This will apply a small patch to the upgrade command. 

Once you've run it, feel free to proceed by running the `yarn webiny upgrade 5.5.0` command again.

Please close this issue if this resolves the error you reported. Thanks!
