### ISSUE TITLE
Form Builder is not redirecting

### ISSUE THREAD

**Issue by damianesteban** [webiny/webiny-js#1581]
## This is:

- Bug

## Specifications

  - version: most recent
  - OS: macOS 11.2.3
  - Browser: Chrome

## Expected Behavior
When I add a redirect URL to form builder, the user should be redirected to that URL after clicking "Submit"

## Actual Behavior
Nothing happens.

## Steps to Reproduce the Problem

1. Make a form
2. Add a redirect url and save it
3. Test it.

**Comment by damianesteban** [comment]
I had to enable the redirection plugin. I wish the documentation was clearer about this.

**Comment by Pavel910** [comment]
@damianesteban you mean like `enable in the form settings` or `import in code` ?
