### ISSUE TITLE
Page Builder: Ability to modify a grid's configuration in different responsive views.

### ISSUE THREAD

**Issue by jimjoes** [webiny/webiny-js#1583]
## This is:

- Feature request

## Detailed Description
It would be useful to be able to add/remove cells in a grid in different responsive viewports.

## Possible Solution
Make the grid settings persist per viewport, in the same way other properties such as width etc can be set differently for the same element in different viewports.

**Comment by jimjoes** [comment]
Bumping this

**Comment by SvenAlHamad** [comment]
Closing this -> this is possible by navigating to the required device view and just activating the "hide" option on the selected cell that you wish to hide on that particular device.
