### ISSUE TITLE
Project Initialization : Yarn setup-project not building in Linux environment

### ISSUE THREAD

**Issue by SyedUmerHasan** [webiny/webiny-js#1598]
## On Linux Environment - yarn setup-project is not working

I have cloned a new repo from webiny (specifically next branch)

## Specifications

  - version: 5.5
  - OS: Linux/Ubuntu 20.04
  - Browser: Google Chrome

## Expected Behavior
The build should pass without anything 

## Actual Behavior
I need to run sudo command to install anything first and another 'webiny' command is not found either

## Steps to Reproduce the Problem

![image](https://user-images.githubusercontent.com/24965764/117579251-83449a80-b10b-11eb-9776-1ef653c1a07f.png)

**Comment by SyedUmerHasan** [comment]
Hi @Pavel910, Can you please look into this. 
Created this issue 
Thanks

**Comment by Pavel910** [comment]
@SyedUmerHasan it should be fixed now. Please pull the `next` branch and run `yarn && yarn setup-project`. And never use `sudo` with anything, as it will cause problems down the line.
