### ISSUE TITLE
File Manager - Incorrect tooltip in file details sidebar

### ISSUE THREAD

**Issue by Ashu96** [webiny/webiny-js#1604]
## This is:
- Bug

## Expected Behavior
In the case of a file, the tooltip should show `Delete File`:

<img width="1424" alt="File manager: delete file action" src="https://user-images.githubusercontent.com/13612227/117658820-d163a780-b1b8-11eb-9b74-17df91c30895.png">

## Actual Behavior
In the case of a file, the tooltip is showing `Delete Image`:

![File manager: delete image action](https://user-images.githubusercontent.com/13612227/117658349-408ccc00-b1b8-11eb-9ace-82aef46debbb.png)

## Steps to Reproduce the Problem
1. Visit the admin app and navigate to the `File Manager` view by clicking the link in the drawer:
<img width="602" alt="Screenshot 2021-05-10 at 5 57 52 PM" src="https://user-images.githubusercontent.com/13612227/117659322-71213580-b1b9-11eb-9330-c20cf2835bfd.png">
 
2. In the file manager view, upload at least one image and a non-image file if there isn't already.
3. Click on the gear/clog icon to open up the file details sidebar and hover on the delete icon to activate the tooltip.

## Detailed Description
We need to make the delete action tooltip's content dynamic with respect to the file type. If the file is an image (based on type/extension) use `Delete Image` otherwise use `Delete File`.

The code responsible for rendering delete action in file detail sidebar is located at: https://github.com/webiny/webiny-js/blob/next/packages/app-admin/src/components/FileManager/FileDetails.tsx#L267

## Action Items:
- [ ] Update tooltip's content based on file type (image or non-image) for delete action in file details sidebar

**Comment by imrishabh18** [comment]
Hey @Pavel910, I would like to take up this issue.

**Comment by Pavel910** [comment]
@imrishabh18 Lovely! Go ahead, I'll assign you to the issue. If you need help, leave a comment here or join our Slack.
