### ISSUE TITLE
Can deploy webiny to aws china region？

### ISSUE THREAD

**Issue by myfreax** [webiny/webiny-js#1615]
## This is Question
Can deploy webiny to aws china region？

**Comment by Pavel910** [comment]
@huangyanxiong01 yes, but you need to verify that all the services we deploy are supported in that region. Like Cognito, DynamoDB, etc. To change the region:
1) create a Webiny project and select any region
2) edit `.env` file, and modify the AWS_REGION to whatever you need.
3) Run deploy.

Be careful not to change the region between deployments. Once you deploy to a certain region, and decide to change the region, destroy the  infrastructure first, then change the region.

**Comment by myfreax** [comment]
@Pavel910 Thinks. I will try it.

**Comment by myfreax** [comment]
Amazon Cognito User Pools are not currently available in the Beijing Region.
