### ISSUE TITLE
What is typescript type CmsEditorFieldTypePlugin?

### ISSUE THREAD

**Issue by myfreax** [webiny/webiny-js#1616]
Follow this docs [Create headless cms plugin](https://www.webiny.com/docs/tutorials/headless-cms/create-a-webiny-headless-cms-address-field-plugin).I can not import typescript type `CmsEditorFieldTypePlugin`  and at last steps i can not run `yarn webiny ws run build --folder=packages/api-headless-cms`. The `packages/api-headless-cms` folder is not exist. 
```typesctipt
export default(): CmsEditorFieldTypePlugin => ({
    type: "cms-editor-field-type",
    name: "cms-editor-field-type-address",
    field: {
        type: "address",
        label: "Address",
        description: "Search for the address",
        icon: <AddressIcon />,
        allowMultipleValues: false,
        allowPredefinedValues: false,
        multipleValuesLabel: "Use as list of addresses",
        createField() {}
    }
});
```
## Specifications

  - version: 5.5.0
  - OS: Ubuntu 20.04 LTS
  - Browser: Chrome

## Expected Behavior

Can import typescript type `CmsEditorFieldTypePlugin` and rebuild with deploy

## Steps to Reproduce the Problem

1.
2.
3.

**Comment by brunozoric** [comment]
Hi @huangyanxiong01 !
CmsEditorFieldTypePlugin is imported from the `@webiny/app-headless-cms` package.
```
// put on the top of the file
import {CmsEditorFieldTypePlugin} from "@webiny/app-headless-cms/types";
```
I have added missing imports in the example code and modified the deploy/run commands.
PR for that is [here](https://github.com/webiny/docs.webiny.com/pull/282), going to merge today after I double check everything.

**Comment by myfreax** [comment]
@brunozoric thanks. It work well
