### ISSUE TITLE
How add custom field to database user table?

### ISSUE THREAD

**Issue by myfreax** [webiny/webiny-js#1620]
## This is Question
I think webiny manage user by this package [api-security-user-management](https://github.com/webiny/webiny-js/tree/54ab395e45773ed98814bf2339c4a9166bd234d1/packages/api-security-tenancy). The package as node_module install. How add field to user table by modify this package user gql? 

In docs, I can not find about custom user field infomation

**Comment by Pavel910** [comment]
@huangyanxiong01 can you describe a little bit more what exactly are you trying to achieve in your application? The package you're mentioning is only meant for `admin` app. 

Btw. we need to update the README, as it's not called `api-security-user-management` anymore 🤦

**Comment by myfreax** [comment]
@Pavel910 I want implements VIP function for user module。 The way I thought of is to add a field vip in the user table to determine whether the logged-in user is a vip

**Comment by Pavel910** [comment]
@huangyanxiong01 I checked the code and currently it's not possible to add new data to the user model. It's too restrictive. We encountered the same problem with the Page Builder. 

I'll open an issue related to this question and once I sort out the Page Builder (same problem), maybe someone from the community will be able to implement the same solution for the user module.
