### ISSUE TITLE
If entering single letter in last name on signup then whole system stops working.

### ISSUE THREAD

**Issue by ankurvr** [webiny/webiny-js#1621]
## This is:

- Bug

## Specifications

  - version: 5.6.*
  - OS: MacOS Bigsur
  - Browser: Chrome Version 90.0.4430.212

## Expected Behavior

It should work normally if i enter 1 character in last name or first name

## Actual Behavior

It's not working normally if i enter 1 character in last name or first name. The login page keeps loading and giving JS error in console.

## Steps to Reproduce the Problem

1. After successful deployment on AWS infrastructure open the admin page link. 
2. Fill first-name with 5 chars, last-name with 1 char and fill rest of the fields too.
3. Click on Sign up.
4. After that you will see some error in form but still the user will get created and on clicking Signup multiple times it will give data existing kind of error.
5. Refresh the page, now you will see login form.
6. Now do login with credentials you have used on signup.
7. Here you will see login page will keep loading due to JS error attached in below screenshot.
<img width="558" alt="Screenshot 2021-05-14 at 2 15 45 PM" src="https://user-images.githubusercontent.com/3338156/118430728-550a2080-b6f2-11eb-973f-654b7510f414.png">
<img width="467" alt="Screenshot 2021-05-14 at 2 15 52 PM" src="https://user-images.githubusercontent.com/3338156/118430735-58051100-b6f2-11eb-897f-4349ca580aeb.png">

**Comment by adrians5j** [comment]
Thanks for opening the issue @ankurvr. I'll see that I provide instructions on how to solve this issue and maybe somebody from the community would be able to tackle it.

**Comment by ankurvr** [comment]
@doitadrian I am ready to tackle it if you can guide me.

**Comment by adrians5j** [comment]
Cool @ankurvr!

It should be relatively easy to fix it.

So, I was looking at the backend code and saw the [following validators](https://github.com/webiny/webiny-js/blob/next/packages/api-security-tenancy/src/crud/users.crud.ts#L22-L23) applied on `firstName` and `lastName` fields:

```ts
firstName: string({ validation: validation.create("required,minLength:2") }),
lastName: string({ validation: validation.create("required,minLength:2") }),
```

And this is why the process failed. The frontend allows for one char to be entered into the first name and last name fields, and the backend doesn't. So, it's just a matter of syncing the code in [`@webiny/api-security-tenancy`](https://github.com/webiny/webiny-js/blob/next/packages/api-security-tenancy) and [`@webiny/app-security-tenancy`](https://github.com/webiny/webiny-js/blob/next/packages/app-security-tenancy) packages.

Let's add the missing `minLength:2` validator to the frontend input fields. We can do that [here](https://github.com/webiny/webiny-js/blob/next/packages/app-security-tenancy/src/plugins/installation.tsx#L105).

**Comment by ankurvr** [comment]
I understood. I will make that change.

Thanks
