### ISSUE TITLE
Script missing in Contribution readme file

### ISSUE THREAD

**Issue by imrishabh18** [webiny/webiny-js#1627]
## This is:

- Documentation

## Detailed Description
This README file https://github.com/webiny/webiny-js/blame/next/docs/CONTRIBUTING.md#L88 
In the 3rd step says to use command `yarn setup-repo` but that command is not present in the package.json.

## Possible Solution
I am not sure but is `yarn setup-project` is the command that needs to be used here?

**Comment by Pavel910** [comment]
@imrishabh18 you're correct! It was renamed to `setup-project`. Feel free to open a PR to fix the command in the CONTRIBUTING.md file. Thanks!
