### ISSUE TITLE
Preview plugins must trigger media-queries

### ISSUE THREAD

**Issue by Pavel910** [webiny/webiny-js#163]
Maybe creating an iframe should do the trick?

**Comment by Pavel910** [comment]
This issue is postponed by #164

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
