### ISSUE TITLE
Http method check in contextSetup should be null safe

### ISSUE THREAD

**Issue by xintellion** [webiny/webiny-js#1635]
## This is:

- Bug

## Specifications

  - version: 5.6.0
  - OS: *
  - Browser: none

## Expected Behavior
The method check should pass successfully even if there is no request present.

## Actual Behavior
The check fails with:
`TypeError: Cannot read property 'request' of undefined`

## Steps to Reproduce the Problem
1. Create a lambda function that include the plugins from [here](https://github.com/webiny/webiny-js/blob/next/packages/api-headless-cms/src/content/index.ts)
2. Deploy the lambda
3. Execute the lambda with arbitrary event

## Detailed Description
When the plugin middleware reaches [here](https://github.com/webiny/webiny-js/blob/next/packages/api-headless-cms/src/content/contextSetup.ts#L39)
```
export default (options: any = {}): ContextPlugin<CmsContext> => ({
    type: "context",
    apply: async context => {
        if (context.http.request.method === "OPTIONS") {
            return;
        }

        const { type, locale } = extractHandlerHttpParameters(context);

        context.cms = {
            ...(context.cms || ({} as any)),
            type,
            locale,
            READ: type === "read",
            PREVIEW: type === "preview",
            MANAGE: type === "manage"
        };

        await setContextCmsVariables(context);
    }
});
```

## Possible Solution
I guess some optional chaining would be sufficient.
```
if (context.http?.request?.method === "OPTIONS") {
            return;
}
```

**Comment by Pavel910** [comment]
@xintellion That's not the only thing that will fail if you don't send a proper HTTP event. Security depends on HTTP headers, so HTTP event is what we expect to be triggering the Lambda.

I guess you're trying to invoke your custom Lambda from another Lambda using AWS SDK? What are you trying to achieve?

**Comment by xintellion** [comment]
@Pavel910 That's right. But I'm not using the AWS SDK. Details can be found in your slack [thread](https://webiny-community.slack.com/archives/C0147R8166P/p1621572219004400)
