### ISSUE TITLE
Dynamodb latest content entry record not updated after save

### ISSUE THREAD

**Issue by taifok** [webiny/webiny-js#1640]
## This is:

- Question / Bug

## Specifications

  - version: 5.6.0

## Description
When a content entry is updated, only the latest record in `esDb` but not the one in the default `db`.
And when I called `cms.entries.getLatestByIds()` will return the non-updated result.

Is it a expected behavior or is it a bug?

### related code
https://github.com/webiny/webiny-js/blob/ecdee2336e1a983083c31f48cb5c60c796d08883/packages/api-headless-cms/src/content/plugins/crud/contentEntry.crud.ts#L544-L576

**Comment by brunozoric** [comment]
Hi @taifok !
I will look into it and apply a fix.
