### ISSUE TITLE
Update Webiny info command

### ISSUE THREAD

**Issue by Ashu96** [webiny/webiny-js#1649]
## This is:
- Improvement

## Detailed Description:
At the moment when we run the Webiny info command using:
```
yarn webiny info --env=<ENV>
```
we only display the URLs and the environment name.
With this task, we want to expand that and add `AWS region` and `project name` to the list.

## Possible Solution:

We need to make the necessary changes in the [packages/cwp-template-aws/cli/info/index.js](https://github.com/webiny/webiny-js/blob/next/packages/cwp-template-aws/cli/info/index.js#L6) file.

Inside `printEnvOutput` function, we can do the following:
- get the AWS region from the output of `await getStackOutput("api", env)` call, for example, `output.region`
- get the project name from the `context` argument, for example, `context.project.name`

After that, we can simply log them after `Environment`.

--- 
**Here is how it should look:**

<img width="794" alt="Screenshot 2021-05-25 at 10 34 45 AM" src="https://user-images.githubusercontent.com/13612227/119443247-e60e7680-bd46-11eb-9a7f-c36335e6582f.png">

**Comment by NomanGul** [comment]
can I pick up this issue?

**Comment by adrians5j** [comment]
Sounds great @NomanGul. Let us know if you'll need any assistance along the way. 🙂

**Comment by NomanGul** [comment]
@Ashu96 @doitadrian The `output.region` is undefined when we didn't deploy API yet.

![image](https://user-images.githubusercontent.com/39244918/126145007-f1568fe0-a24f-4a25-a3b8-a96e953d594a.png)

so what do you think if we show output like this:

if 0 deployment counts:
![image](https://user-images.githubusercontent.com/39244918/126151359-8f093480-c79c-480a-be82-8e710377d4b3.png)


if >0 deployments:
![image](https://user-images.githubusercontent.com/39244918/126147828-3e523211-5610-47df-87d5-30cf6228a571.png)

**Comment by adrians5j** [comment]
I'd definitely put the AWS region above, within the Environment / Project name section.

We can print that label always. And, in case the project wasn't yet deployed, we can just say it. So, instead of `undefined`, maybe we could just go with `not deployed yet`.

So, it's either `AWS region: us-west-2` or `AWS region: not deployed yet`.

I think that would be clear enough for the user.  I hope I've managed to explain it :)

Thanks!
