### ISSUE TITLE
head scripts are executed 3 times on webiste render

### ISSUE THREAD

**Issue by AndriiUhryn** [webiny/webiny-js#1651]
## This is:

* Bug

## Specifications
* version: 5.4.0
* OS: any
* Browser: any

## Expected Behavior

custom scripts should be executed 1 time on browser load

## Actual Behavior

custom scripts are executed 3 times

## Steps to Reproduce the Problem

1.Just add some console.log script into the website head 
2.Open live website
3.Check console

## Detailed Description

![Screen Shot 2021-05-25 at 12 32 49 PM](https://user-images.githubusercontent.com/22635238/119485839-39d98980-bd60-11eb-9397-dc393c386540.png)

**Comment by AndriiUhryn** [comment]
I managed to fix this by wrapping my js code into if statement like this 

<script>
  if (!navigator?.webdriver) {
   execute code you need
  }
</script>

this will prevent code executing on prerendering stage in headless chrome and simply run it on real browser.

**Comment by adrians5j** [comment]
Cool.

BTW you added this in your `index.html` file or ?

**Comment by AndriiUhryn** [comment]
Yes
<img width="889" alt="Screen Shot 2021-06-10 at 3 48 06 PM" src="https://user-images.githubusercontent.com/22635238/121527712-60a3eb00-ca03-11eb-9323-6dc59f9db8dc.png">
