### ISSUE TITLE
Improve DX and existing GraphQL / Admin Area scaffolds

### ISSUE THREAD

**Issue by adrians5j** [webiny/webiny-js#1653]
Existing GraphQL / Admin Area scaffolds work, but over time, we've noticed a couple of things that could be improved.

## Changes

x. Improved GraphQL scaffold

x. Improved Admin Area scaffold

x. getStackOutput is now sync

x. Added `jest.config.base.js` / `.babelrc` to `api` folder 

x. Synced changes in infrastructure code (ES-realted env variables)

x. Scaffolding Utilities

### GraphQL Scaffold
- [x] Needs to be simplified - remove ElasticSearch-related code (use DynamoDB only)	
- [x] For GraphQL resolvers, use TS classes instead of plain objects	
- [x] With the changes listed above, we're going to need make adjustments to generated tests
- [ ] Adjust CLI Messaging (success messages, change name to Extend GraphQL API)	
- [ ] Adjust pagination to work with Dynamo	

### Admin Area Scaffold

- [ ] Check for URLs creation (use `/car-manufacturers`, not `/carManufacturers`)
- [x] Remove i18n usage, not needed at this point
- [ ] Add pagination (cursor based) controls (must be synced with GraphQL API functionality)

### Other

- [x] Check for grammar mistakes in variable names / comments / etc.
- [x] Simplify package name - use api-{name}, instead of @{package-name}/api-{name}
- [ ] Docs - revisit tutorials - update where necessary
- [ ] Review with @Pavel910 
- [x] Refactor React hooks into separate files (more clarity)
- [ ] make sure to run prettier on generated code
- [ ] https://github.com/webiny/webiny-js/issues/1653

**Comment by pavel** [comment]
@doitadrian Thanks for notifying me, but it does not seem that I'm involved in this project in any way.

https://blog.github.com/2011-03-23-mention-somebody-they-re-notified/

**Comment by Pavel910** [comment]
@pavel sorry, that was a typo, @doitadrian meant to tag me :) Our apologies 🍻
