### ISSUE TITLE
Add a Latitude/Longitude field to CMS

### ISSUE THREAD

**Issue by anthonycmain** [webiny/webiny-js#1654]
## This is:
- Feature request

## Detailed Description
It would be great if we had a field for latitude/longitude in the CMS, with both input text and a map pin location (nice to have).

This would then output as a GraphQL spatial Point type

**Comment by Pavel910** [comment]
Adding a new field is fairly straightforward: [Create a Webiny Headless CMS address field plugin](https://www.webiny.com/docs/tutorials/headless-cms/create-a-webiny-headless-cms-address-field-plugin)

Elasticsearch also supports [Geo-Point field type](https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-point.html) so creating a field following that tutorial shouldn't be a problem.
