### ISSUE TITLE
Cannot unset, or have a null content group once a single group has been greated

### ISSUE THREAD

**Issue by anthonycmain** [webiny/webiny-js#1655]
## This is:
- Feature request

## Expected/Actual Behavior
Prior to creating a content group, models do not need to be associated with a content group, but once one is created, you must assign it, rather than leave it as null. 

In most cases though you wont likely have created a new content group for the new model yet. So you have to assign it to an existing one then change it later.

## Steps to Reproduce the Problem
In a new environment create a model, you will see that it has no content group (because none exist)

Now create a content group and then either edit the previous model or create a new one, it is automatically assigned to the only content group

## Possible Solution
Minimum option - simply add an empty field to the Select picker for Content Group

Better option - add the ability to quickly create a content group from the new model form

**Comment by Pavel910** [comment]
@anthonycmain, could you please clarify what do you mean by `new environment`?
Usually we have the `Ungrouped` group. We never planned to allow models be without a specific group assigned.

How did you manage to get into an environment where you don't have the default `Ungrouped` group? Was it a new locale maybe? 🤔 

And we should definitely create the `Quick create` a group to avoid this problem in the first place.

**Comment by anthonycmain** [comment]
I guess I mean Ungrouped in response to your question then.

As I'm not sure I would always need to create a group, but I guess we could create a misc group.

**Comment by Pavel910** [comment]
For menu (navigation) organization purposes and access control (permissions) we always require a model to belong to a group. That's why we have the default `Ungrouped` group (that's the Misc in other words).

And also, if you can provide some info on this:
> How did you manage to get into an environment where you don't have the default Ungrouped group? Was it a new locale maybe? 🤔

Cheers!

**Comment by anthonycmain** [comment]
I've just started playing with Webiny so it was a clean deployment hence why I had Ungrouped models.

**Comment by Pavel910** [comment]
@anthonycmain in your steps to reproduce you stated
> In a new environment create a model, you will see that it has no content group (because none exist)

This is the part that sounds odd, because `Ungrouped` group should always exist.

**Comment by anthonycmain** [comment]
Sorry I see, miss communicating here. But sadly no it doesn't, see the screenshot below...

<img width="1680" alt="Screenshot 2021-05-25 at 15 12 49" src="https://user-images.githubusercontent.com/950131/119513322-07358e00-bd6c-11eb-8d05-d8daee033081.png">
