### ISSUE TITLE
feat(pulumi-sdk): Migrate to Pulumi 3.x

### ISSUE THREAD

**Issue by ceefour** [webiny/webiny-js#1677]
## This is:

- Feature request

## Detailed Description

Currently @webiny/pulumi-sdk uses 2.21.2 (#1678). I propose migrating to Pulumi 3.x.

## Possible Solution

- [Pulumi 3.0 new features](https://www.pulumi.com/blog/pulumi-3-0/)
- [How to migrate to Pulumi 3.0](https://www.pulumi.com/docs/get-started/install/migrating-3.0/)

**Comment by adrians5j** [comment]
Hey @ceefour, 

yes, that sounds good, we'll see if we can prioritize that in the upcoming weeks. Note that if it turns out that this will introduce breaking changes, there's a chance we might postpone this. 

Writing this down... ✍🏻 

Thanks for the feedback!

**Comment by adrians5j** [comment]
Just a small update here.

There's a chance that we'll actually be forced to migrate to v3 in the near future, because of a couple of project-level / development-related changes we're currently working on.

I'll update here along the way.

**Comment by adrians5j** [comment]
Will close this one as we already have it here #1696.
