### ISSUE TITLE
Deprecated AWS Lambda runtime node.js 10

### ISSUE THREAD

**Issue by briannd81** [webiny/webiny-js#1684]
## This is:

- Idea

AWS lambda will stop supporting runtime Node.js 10.x at the end of July 2021. Currently webiny creates lambda function fm-image-transformer-xxxxx that uses this version.

https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html

**Comment by Pavel910** [comment]
@briannd81 thanks, we're already informed about this and will address the update in one of the upcoming releases. In that `transform` lambda, we're using the `sharp` library for image manipulation, and that binary is specifically built for node10. Other Lambdas are already using node12.

**Comment by ianvonholt** [comment]
@Pavel910 

The `CHANGELOG` for Sharp doesn't illuminate any breaking changes. This may be as simple as just updating the library, building new layers, and updating the functions. 

Would there be any objection to updating things to `node14` or is the plan to wait until the fall for the new LTS at `node16`?

- https://sharp.pixelplumbing.com/changelog

**Comment by ianvonholt** [comment]
@Pavel910 

I utilized https://github.com/bubblydoo/lambda-layer-sharp with the most recent `0.28.3` build, updated a set of layers and tested the `fm-image-transformer` function at NodeJS 14.x. I have yet to run into any problems.

**Comment by Pavel910** [comment]
@ianvonholt great, thanks for testing it, saved us some time :)
We'll see to update it for the 5.9.0 release (5.8.0 is landing tomorrow so we won't have enough time to squeeze it in).

As for `node16`, we tend to stick to what AWS supports for Lambdas (so 12 and 14). Updating the runtime is as easy as changing the runtime config in your pulumi files, so you can easily upgrade to node 14 independently of Webiny. And for creation of new projects we require either node 12 or 14. We could drop node 12 at this point I assume, and have everything on node14 by default.

So in your case, if you use node 14 and want your Lambdas to be on node 14, just update the runtimes by searching for `aws.lambda.Function` in your `api/pulumi`.

**Comment by ianvonholt** [comment]
Yup, I've upgraded everything to Node 14. The last lingering piece was the functions utilizing the Sharp library. 

The only problem I ran into was having to manually update the Layer version, Pulumi didn't seem to recognize the new version and update the configuration.

**Comment by Pavel910** [comment]
@ianvonholt our layers are pulled from [here](https://github.com/webiny/webiny-js/blob/next/packages/aws-layers/layers.json) and are managed by us, unless you manually replaced `layers: [getLayerArn("webiny-v4-sharp", String(process.env.AWS_REGION))],` with your own layer ARN.

And funny it's still called `webiny-v4-sharp` :D

**Comment by ianvonholt** [comment]
@Pavel910 Yup, and the layers are built [here](https://github.com/webiny/webiny-js/tree/next/scripts/layers). In my test stack I built layers that were within my own account and updated the variables, Pulumi just didn't pick it up and I had to manually change it myself. Nothing huge, just noticed it.

**Comment by Pavel910** [comment]
Cool, we'll pay attention to that when we get to upgrading the layer. It's weird Pulumi didn't detect the change.

**Comment by zoezoezoe** [comment]
any update on getting the new layer up?

**Comment by adrians5j** [comment]
Sorry @zoezoezoe, not at the moment.

If somebody from the team or our community could check this out, that would be cool (we can guide through the process). 

I'd personally love to do it, but I already have too much extra stuff going on for the upcoming `5.10.0` release ☹️

**Comment by zoezoezoe** [comment]
Okay. Just so you're aware, the deadlines are kind of aggressive. After the end of July, we won't be able to create new functions with node 10, and after end of August, updates to existing functions won't work either. 

We will likely spend some cycles at some point to deal with this on our side at some point. Will reach out at that time to see if we could help in some way.

**Comment by Pavel910** [comment]
@zoezoezoe Oh we _are_ aware :). I'll try to squeeze this in the upcoming release, testing it as we speak. With the team of our size, every release is an "aggressive deadline" because every team member has 2-3 high-priority super-urgent tasks to deliver, so it's becoming hard to prioritize anything.

**Comment by Pavel910** [comment]
@zoezoezoe Looking at layer definition, it does support node 12. So you should be able to just update the runtime of those existing node 10 lambdas. I'll update the project template so all functions use node 12 runtime.

![image](https://user-images.githubusercontent.com/3920893/123508671-12345480-d671-11eb-8770-a67321564026.png)

I'm publishing the new layer, with support for node 14, and a lot smaller bundle. It will also be called just `sharp`.

**Comment by zoezoezoe** [comment]
Thanks @Pavel910 just tested it with node 12. It seems to work. Thanks for the quick response.
