### ISSUE TITLE
create-webiny-project failing due to public-ip package issue

### ISSUE THREAD

**Issue by drmmarsunited** [webiny/webiny-js#1688]
## This is:
- Bug

## Specifications
  - version: node 14.3.0, yarn 1.22.10
  - OS: Mac Mojave 10.14.6
  - Browser: N/A

## Expected Behavior
When following the Webiny installation instructions found [here](https://www.webiny.com/docs/tutorials/install-webiny), during the `npx create-webiny-project my-new-project` step, a new folder should appear bootstrapped for a templated Webiny app.

## Actual Behavior
When running the `npx create-webiny-project my-new-project` command, I am receiving the following unhandled promise rejection warning:

```
▶ npx create-webiny-project my-new-webiny-project
(node:23669) UnhandledPromiseRejectionWarning: Error: Couldn't find your IP
    at /Users/i1mar01/.npm/_npx/4472eac8a7b44eda/node_modules/public-ip/index.js:172:10
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /Users/i1mar01/.npm/_npx/4472eac8a7b44eda/node_modules/public-ip/index.js:199:15
    at async module.exports (/Users/i1mar01/.npm/_npx/4472eac8a7b44eda/node_modules/create-webiny-project/utils/verifyConfig.js:18:42)
    at async /Users/i1mar01/.npm/_npx/4472eac8a7b44eda/node_modules/create-webiny-project/bin.js:44:5
(Use `node --trace-warnings ...` to show where the warning was created)
(node:23669) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:23669) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Steps to Reproduce the Problem
1. Navigate into any folder where you want to create a test Webiny app
2. Run `npx create-webiny-project my-new-project`
3. Observe the error

## Possible Solution
The error message suggests that a downstream library, `public-ip`, cannot figure out the IP address on my local machine.  I would guess this might be due to VPN usage, etc, but I've tried installing both while on and off VPN and get the same result.

**Comment by Pavel910** [comment]
@drmmarsunited nice one! The [library](https://www.npmjs.com/package/public-ip) says:
```
In Node.js, it queries the DNS records of OpenDNS, Google DNS, and HTTPS services to determine your IP address. 
```

Is it possible that your machine can't reach any of that? Sounds improbable 🤔

**Comment by drmmarsunited** [comment]
While on VPN, I am definitely in a heavily restricted environment that probably disallows reaching those services.  I would have to play around while off VPN to figure out what is causing the heartache, as there should be no restrictions at that point.

Let's assume for a moment that I can't work my way out of the restrictions I have there, are there alternate Getting Started type instructions I could follow using the Webiny CLI or something.  I've got some use cases I'd like to test Webiny against, installation woes aside.

**Comment by Pavel910** [comment]
To be honest, this is the first time we see such a problem. We don't have an alternative way of setting this up, but - next release is landing on Monday, and we can implement a fallback for these rare cases when IP address is not obtainable.

**Comment by drmmarsunited** [comment]
@Pavel910 - thanks for that.  I'm betting environments like ours are edge case for pretty much all software out there!  I will keep my eyes open for a new drop next week and try again.  Thanks for the quick engagement!

**Comment by Pavel910** [comment]
@drmmarsunited there will be an announcement on our [community Slack](https://www.webiny.com/slack), so feel free to join to stay up to date on everything we do :)

**Comment by Pavel910** [comment]
@drmmarsunited v5.8 is live and your IP will not matter any more, so feel free to give it a try :)
