### ISSUE TITLE
Spezial characters in email address causes error

### ISSUE THREAD

**Issue by xintellion** [webiny/webiny-js#1691]
## This is:
- Bug

## Specifications

  - version: 5.7.0
  - OS: any
  - Browser: Chrome

## Expected Behavior
Users with a plus sign in their email address should work.

## Actual Behavior
If you create a user with e.g. a plus sign (user+support@example.com) in their email address this user is unaccessible. The email  address as it is part of the url when navigating to the user should be url encoded and decoded in the corresponding component.  
The current behavior is that the plus sign is remove when passing the email address to graphql and results in a 404.

## Steps to Reproduce the Problem

1. create a user with a plus sing in the email address (e.g.: user+support@example.com)

## Possible Solution
Email address as part of the url should be encoded and later decoded

**Comment by Pavel910** [comment]
Nice one, thanks for reporting @xintellion!
