### ISSUE TITLE
Upgrade Pulumi to version 3

### ISSUE THREAD

**Issue by adrians5j** [webiny/webiny-js#1696]
Pulumi version 3 is out, so it's in our best interest to upgrade too.

First, let's see what the new version brings. Are there any breaking changes? Are there any template adaptations that we need to? Will users still be able to continue working with Pulumi v2? 

These are just some of the things we need to inspect before we start working on the actual implementation.

**Comment by ceefour** [comment]
Yay! :+1:

**Comment by adrians5j** [comment]
Going off next week, so I'm just writing a couple of notes here regarding the initial research and testing... 

Upgraded to 3.6.0 locally, and at first, I had an issue, where the Pulumi CLI was telling me it cannot find the necessary plugins in my home (`~`) folder. But the thing is, via the `PULUMI_HOME` env variable, we're setting the home folder to be within the user's project.  So that was weird...

An even weirder thing was that after some fiddling with the CLI, setting different home folders, installing the 3.6.0 in a regular way (via `brew`), the thing started working :|

Not sure why it's working now... gotta try and repeat the steps... maybe it was the standalone Pulumi install that did something? I don't think that was the case.

Tried redeploying and got this:
![image](https://user-images.githubusercontent.com/5121148/124225954-94f15f80-db08-11eb-8c6e-84a101fae5dc.png)

So as we can see, only provider has changed on every resource. Basically new AWS provider, because of the new Pulumi CLI version.

Doing another deploy... no changes this time, which is good:

![image](https://user-images.githubusercontent.com/5121148/124226036-b9e5d280-db08-11eb-9f09-c7f903dc0410.png)

**Comment by adrians5j** [comment]
Done in 5.10.0, closing.
