### ISSUE TITLE
Error on new deployment (V5.8) creating / editing pages.

### ISSUE THREAD

**Issue by arepageek** [webiny/webiny-js#1701]
## This is:
- Bug

## Specifications

  - version: 5.8

## Expected Behavior
View static page loaded from s3

## Actual Behavior
In a new Webiny deployment, when editing and pages are not displayed because the rendering lambda fails and therefore the pages are not saved in s3

## Steps to Reproduce the Problem
1. Install clean version of webiny 5.8
2. Try to view page
3. Edit or create new pages

## Detailed Description
This is the log generated by the render lambda.

```
2021-06-08T00:34:59.113Z	71e560ea-6f2d-4968-86c1-300ee270e17b	INFO	"Evaluation failed: TypeError: window.getApolloState is not a function\n    at __puppeteer_evaluation_script__:3:19"
```

And also this
```
2021-06-08T00:42:03.369Z	e487cecc-52c9-4555-b893-4b9501bf56fa	INFO	An error occurred while prerendering... Error: Evaluation failed: TypeError: window.getApolloState is not a function
    at __puppeteer_evaluation_script__:3:19
    at ExecutionContext._evaluateInternal (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
    at async defaultRenderUrlFunction (/var/task/handler.js:7076:23)
    at async _default (/var/task/handler.js:6955:18)
    at async handle (/var/task/handler.js:4534:25)
    at async /var/task/handler.js:5457:28
```

Thanks

**Comment by Pavel910** [comment]
@arepageek could you please open `apps/website/code/src/components/apolloClient.ts` and post the contents of that file? There should be this in the code:

```ts
    window.getApolloState = () => {
        // @ts-ignore
        return cache.data.data;
    };
```

**Comment by arepageek** [comment]
@Pavel910 it is exactly what I have, I have not modified anything, I have only deployed version 5.8

**Comment by Pavel910** [comment]
Ok, I'll bring @doitadrian in the loop to check this out. Thanks for reporting! We'll get back to you when we find out anything new.

**Comment by adrians5j** [comment]
Weird... I tried it on my end with a brand new 5.8.0 too, all worked.

Can you check if, at least, the default `/welcome-to-webiny` page has been rendered?

**Comment by adrians5j** [comment]
Another thing to check could be... in your Admin Area, on the following link: https://xyz.cloudfront.net/settings/page-builder/prerendering....  are the inputs blank? And, you can see the default values being used (show in the description of each field)?

![image](https://user-images.githubusercontent.com/5121148/121293352-c69d4f00-c8eb-11eb-8c26-ce2aeebc8be7.png)


I'd also like to see the actual URLs, so if you want, you can ping me privately on Slack (`@Adrian Smijulj`).

**Comment by xintellion** [comment]
I'm getting this error too.

**Comment by xintellion** [comment]
> Another thing to check could be... in your Admin Area, on the following link: https://xyz.cloudfront.net/settings/page-builder/prerendering.... are the inputs blank? And, you can see the default values being used (show in the description of each field)?
> 
> 
> I'd also like to see the actual URLs, so if you want, you can ping me privately on Slack (`@Adrian Smijulj`).

For me these inputs are blank and the default values are used. But I changed the default value for APP URL

**Comment by xintellion** [comment]
The problem is caused by the deployment. The new `uploadFolderToS3` produces, when the deployment is triggered on Windows with powershell or cmd, a flat folder structure with windows path separaters within the s3 object key.
![image](https://user-images.githubusercontent.com/4627915/121765742-83dab180-cb4d-11eb-9415-c416bfc77154.png)

This results in the application not beeing loaded.

**Comment by adrians5j** [comment]
Woah very nice @xintellion.

Will definitely check this out! 

Thank you! 🙏🏻

**Comment by Pavel910** [comment]
Nice catch. We don't use cmd nor powershell. And even though I'm a Windows user, I run Git Bash in Windows Terminal. But this should be an easy fix 👍 

Thanks for looking into it, it definitely saves us some time! 🙌

**Comment by arepageek** [comment]
Thanks @xintellion  cmd / powershell was the problem!

**Comment by adrians5j** [comment]
Reopening this, we'll still need to fix this.
