### ISSUE TITLE
"Missing compression in "fromStorage" function" error in richTextField after upgrading to 5.8

### ISSUE THREAD

**Issue by zoezoezoe** [webiny/webiny-js#1702]
## This is:

- Bug

## Specifications

  - version: 5.8.0

## Expected Behavior

Be able to update entries (containing richText field) created prior to migration.

## Actual Behavior

Updating entries containing richTextField created prior to the upgrade to 5.8 fails due to an error coming from `CmsModelFieldToStoragePlugin`. The exact error is:
`Missing compression in "fromStorage" function in field <field name>`.
This error does not occur with entries created _after_ the migration.

## Steps to Reproduce the Problem

1. install webiny at 5.6
2. create an entry containing richText field.
3. upgrade to webiny 5.7 and then to 5.8 following the upgrade instructions.
4. update the entry from step 2 and click "save" or "publish".
5. error `Missing compression in "fromStorage" function in field <field name>` in either browser console or UI.

Note the code change seems to have been introduced in 5.8, so upgrading from 5.7 probably creates the same problem.

## Possible Solution

Seems like the introduction of the `cms-model-field-to-storage-rich-text` plugin is not backwards compatible. You might need to a step to re-store the values with compression in the migration script.

**Comment by brunozoric** [comment]
Hi @zoezoezoe
Plugin should be backwards compatible, we just added a check for the compression on the stored data value.
Possibly something entered into storage without the compression on the last version.
I will need to see the data from the storage. You can catch me on our Community Slack, we can go through the data in private.

**Comment by zoezoezoe** [comment]
Hi @brunozoric , not sure if this would be fixed by the bug fix, but just FYI -- in a vanilla 5.8.0 install, we can "save" an entry containing a richText field (verified in the DDB table as having a `{compression, value}` object); but when we "publish" that same entry, the same richText field got updated to the uncompressed version `{data, id, type}[]`, which causes the admin UI will throw the same error as described above.

We can help verify whether the bug fix would work when it's released. (would be helpful to let us know when it will be released, thanks!)

**Comment by brunozoric** [comment]
Hi @zoezoezoe 
Fix is ready (for to storage [check here](https://github.com/webiny/webiny-js/blob/next/packages/api-headless-cms-ddb-es/src/dynamoDb/storage/richText.ts#L71) and from storage [check here](https://github.com/webiny/webiny-js/blob/next/packages/api-headless-cms-ddb-es/src/dynamoDb/storage/richText.ts#L108)). Basically there will be no attempt to decompress if compression is not found as we throw an error usually since that really is unexpected behaviour.
This code will ship in 5.9.0 - beta is this Friday. Full release is next Monday.
