### ISSUE TITLE
Files with .ico or .woff or any other font extension are loaded with 301 redirect on live website.

### ISSUE THREAD

**Issue by AndriiUhryn** [webiny/webiny-js#1705]
Files with .ico or .woff or any other font extension are loaded with 301 redirect on live website.

## This is:

- Bug

## Specifications

  - version: 5.8.0
  - OS: any
  - Browser: any

## Expected Behavior

File should be loaded without 301 redirect to aws location

## Actual Behavior

Files with any font or .ico extensions are loaded with 301 redirects

## Steps to Reproduce the Problem

1. Add favicon logo to your project with .ico extension or any custom font family file.
2. Check live website, it will be loaded with 301 redirect

## Possible Solution

It should be something related to the file extension and not to the file limit, because files does not weight more than 5 mb.

Screenshot with 301 redirects to aws location
<img width="1091" alt="Screen Shot 2021-06-09 at 7 20 40 AM" src="https://user-images.githubusercontent.com/22635238/121302630-a75dec00-c902-11eb-8a5e-27934426a9d1.png">

**Comment by adrians5j** [comment]
Found the bug, will include the fix in the upcoming `5.9.0` release. In any case, once the fix is up, you won't see redirects anymore.
