### ISSUE TITLE
Content blinks on webiny page builder default page initial open

### ISSUE THREAD

**Issue by AndriiUhryn** [webiny/webiny-js#1707]
## This is:

- Bug

## Specifications

  - version: 5.8.0
  - OS: any
  - Browser: any

## Expected Behavior

It should return fully prerendered page with included css and images so it does not blink when user opens it.

## Actual Behavior

When user opens webpage built with webiny he get html without css or images and after a while they loads and content blink to a styled version

## Steps to Reproduce the Problem

1. create home page in a page builder
2. open that page
3. open console and view initial html request response or you will experience content blink at a first point when open website

## Detailed Description

<img width="1777" alt="Screen Shot 2021-06-09 at 1 59 39 PM" src="https://user-images.githubusercontent.com/22635238/121355946-13f3dd80-c939-11eb-912e-b2a18912222b.png">

## Possible Solution

prerendering is constructed in the way that it omits all images or css files
<img width="582" alt="Screen Shot 2021-06-09 at 3 33 44 PM" src="https://user-images.githubusercontent.com/22635238/121355902-09d1df00-c939-11eb-9075-a2392145a7ae.png">

**Comment by AndriiUhryn** [comment]
If possible, please make this configurable so than I or any other developer can decide if I need a whole page prerendering or pass an array of skipResources.

**Comment by adrians5j** [comment]
Sure, it shouldn't be hard to expose this.

On the other hand, can you describe a use case for this? Why would you want to control this?

Note that, in case you're referring to the CSS-in-HTML issue we talked about yesterday, this won't help. This only instructs the Puppeteer to ignore any fetching of CSS/images, which is a recommended configuration if you only care about the end HTML that gets generated by JS.

Sure, if we decide to go with the route you yesterday mentioned - having the CSS baked into the HTML - then we'll remove `stylesheet` from the  array. But additional steps will need to be taken here as well. Removing this won't be enough - there's still no code that basically does the step of baking the CSS into rendered HTML.

**Comment by adrians5j** [comment]
Just wanted to let you know that we've talked about the CSS-in-HTML briefly yesterday, and it's gonna take some time for us to tackle this. We'd still like to do a bit of research on the topic and see if there are any other ways to do it.

On the other hand, PRs are always welcome and we're ready to provide guidance.

**Comment by AndriiUhryn** [comment]
I see, the use case is that from my view I want a ready html baked with css served to my end users so than they can use platform right after it loads and so they will not experience this blink effect that I have covered for now with custom inline loader.
I understand that it will take some time for you to fix this, but just from my experience I used this headless chrome and it worked fine without this skipResources, html was rendered with css onboard and I used it to generate .pdf file.
Unfortunately I can't try it and check if this will fix issue because this is on your end.

**Comment by Pavel910** [comment]
Headless Chrome will not inline CSS just because you load a file. If that's what you experienced, there had to be some post processing to create <style> elements from the loaded files. If you could share that code you used, it would be great to see the full setup.


The `skipResources` you see in our code makes no difference, it just tells pupetteer to not load CSS and Image URLs, because it's pointless - you can't see css or images in a headless browser and it doesn't affect the HTML output.

So, we'll need to see how we can inline the css from remote urls. Maybe pupetteer has some plugins available, or maybe we'll need to do it manually ourselves. But that's outside of our current milestone scope.

**Comment by AndriiUhryn** [comment]
<img width="593" alt="Screen Shot 2021-06-10 at 4 20 15 PM" src="https://user-images.githubusercontent.com/22635238/121532229-d316ca00-ca07-11eb-8c42-151068c3b422.png">
<img width="568" alt="Screen Shot 2021-06-10 at 4 20 29 PM" src="https://user-images.githubusercontent.com/22635238/121532247-d6aa5100-ca07-11eb-8f7f-b93df36eb471.png">

This generates me pretty much styled pdf file with css aplied from that page. I don't think you need to generate inline styles to make it work. If you can try and check what will be returned if you will remove that stylesheet and image from excluded.

**Comment by Pavel910** [comment]
Nice! Will try exactly that, using PDF. But I can't do this now, as I'm deep in other stuff. Will let you know when I test this.

Also, I'm quite sure generating a PDF is not the same as loading an HTML snapshot, because once the snapshot is in your browser, it still has to load CSS if it's not inlined.

**Comment by AndriiUhryn** [comment]
Ok, please try
Just to be clear what I want to get as a result, check please this url https://www.webiny.com/ -> network ->  initial html response, you will see that the response is a website fully prebuilt.

<img width="1789" alt="Screen Shot 2021-06-10 at 4 30 19 PM" src="https://user-images.githubusercontent.com/22635238/121533661-2b9a9700-ca09-11eb-8269-cf6cfdc8588c.png">

**Comment by Pavel910** [comment]
Yeah, I understand. That's how Gatsby works out of the box, it inlines CSS at build time. Webiny doesn't. But it's possible to add, just not _right away_ :)

**Comment by AndriiUhryn** [comment]
I see, great than I will wait when it will be available and for now will just use loader :) thanks guys

**Comment by adrians5j** [comment]
Note that you're using the `.pdf` method here which probably has this functionality built-in.

https://pptr.dev/#?product=Puppeteer&version=v10.0.0&show=api-pagepdfoptions

It's different from what we're doing here. We're not using the `.pdf` method (nor we need to), hence the difference in behaviour.

**Comment by adrians5j** [comment]
Closing as several improvements were introduced in one of our previous releases.

For new issues / improvements in this department, let's create new issues.
