### ISSUE TITLE
pulumi s3 backend is not correcty working on windows

### ISSUE THREAD

**Issue by xintellion** [webiny/webiny-js#1798]
pulumi s3 backend is not correcty working on windows

## This is:

- Bug

## Specifications

  - version: 5.10.0
  - OS: Windows
  - Browser: none

## Expected Behavior
The pulumi backend files stored in s3 should be in the subpath `apps->admin`

## Detailed Description
Just tried to run
`yarn webiny deploy .\apps\admin --env dev`
on Windows I have switched to pulumi s3 backend. For the api everything works fine but trying to run above command pulumi doesn't seem to find the files in s3. The command starts creating new resources as it assumes the files being located in a folder named `apps\admin` instead of the subfolder` apps->admin` . Is this a pulumi bug (or feature)?

Already tried the following commands
```
yarn webiny deploy apps/admin --env dev
yarn webiny deploy ./apps/admin --env dev
yarn webiny deploy .\apps\admin --env dev
```

**Comment by adrians5j** [comment]
Thanks for the feedback @xintellion.

For starters, can you explain how you set the S3 as the Pulumi backend?

**Comment by xintellion** [comment]
I simply upload the .pulumi folder into a s3 bucket as discussed in #1796 and added 
`WEBINY_PULUMI_BACKEND=s3://BUCKET_NAME`
to the .env file

**Comment by adrians5j** [comment]
Hey @xintellion, can you try opening this file:

```bash
node_modules/@webiny/cli-plugin-deploy-pulumi/utils/login.js:45
```

Change this line:

```ts
login = trimEnd(login, "/") + "/" + relativeProjectApplicationPath;
```

to 

```ts
login = trimEnd(login, "/") + "/" + relativeProjectApplicationPath;
login = login.replace(/\\/g, "/"); // So basically, we just added this replacement (all "\" to "/")
```

Once you did this change, did it start working?

If you can confirm by today/tomorrow, I believe we'll be able to slip this one into the upcoming release, which we're planning tomorrow / Wednesday.

Thank you!

P.S. Feel free to ping me privately via Slack too.
