### ISSUE TITLE
settings/form-builder/recaptcha: Uncaught (in promise) Error: GraphQL error: Unknown type "FormsSettingsInput".

### ISSUE THREAD

**Issue by facorread** [webiny/webiny-js#1799]
Hi all,

I am very impressed by webiny. I look forward to benefiting from everything it offers. I was trying out the reCAPTCHA functionality at settings/form-builder/recaptcha and it gave me the following error message:

Uncaught (in promise) Error: GraphQL error: Unknown type "FormsSettingsInput". Did you mean "FbFormSettingsInput", "FbSettingsInput", "PbSettingsInput", "PbPageSettingsInput", or "FbFormSettingsType"?

## This is:
- Bug

## Specifications

  - version: 5.10.0
  - OS: Windows 10; deployed on AWS
  - Browser: Firefox 90.0 and Chrome 91.0.4472.164 (Build oficial) (64 bits)
  - Clean browser profiles
  - Brand new webiny installation 

## Expected Behavior
The website should have accepted the new value of the "Domain" field. It should also accept the change to the "Enable Google reCAPTCHA" checkbox and the new values for the key and secret.

## Actual Behavior
The browser console produces the error,

Uncaught (in promise) Error: GraphQL error: Unknown type "FormsSettingsInput". Did you mean "FbFormSettingsInput", "FbSettingsInput", "PbSettingsInput", "PbPageSettingsInput", or "FbFormSettingsType"?

Uncaught (in promise) Error: GraphQL error: Unknown type "FormsSettingsInput". Did you mean "FbFormSettingsInput", "FbSettingsInput", "PbSettingsInput", "PbPageSettingsInput", or "FbFormSettingsType"?
    t https://SOMERANDOMSTRING.cloudfront.net/static/js/ANOTHERRANDOMSTRING.chunk.js:2
    next https://SOMERANDOMSTRING.cloudfront.net/static/js/ANOTHERRANDOMSTRING.chunk.js:2
    y https://SOMERANDOMSTRING.cloudfront.net/static/js/ANOTHERRANDOMSTRING.chunk.js:2
    w https://SOMERANDOMSTRING.cloudfront.net/static/js/ANOTHERRANDOMSTRING.chunk.js:2
  (....)
ANOTHERRANDOMSTRING.chunk.js:2:760871

## Steps to Reproduce the Problem
1. Follow the Webiny installation tutorial https://www.webiny.com/docs/tutorials/install-webiny/
2. Navigate to https://SOMERANDOMSTRING.cloudfront.net/settings/form-builder/recaptcha
3. Change anything and then click next

**Comment by Ashu96** [comment]
Hey @facorread, we're glad to know that you like what Webiny has to offer 💯 
Thank you for reporting this issue in such great detail.

If you like to contribute the solution is very simple. We just need to update the `updateSettings` Graphql mutation.
Precisely replace `FormsSettingsInput` with `FbSettingsInput` in both the files:
- [Form Settings in Editor](https://github.com/webiny/webiny-js/blob/next/packages/app-form-builder/src/admin/plugins/editor/formSettings/components/graphql.ts#L27)
- [Form Builder Settings](https://github.com/webiny/webiny-js/blob/next/packages/app-form-builder/src/admin/plugins/settings/components/graphql.ts#L29)

If you need help, leave a comment here or join our Slack 🙂
