### ISSUE TITLE
Headless CMS: single-value ref field missing validator

### ISSUE THREAD

**Issue by zoezoezoe** [webiny/webiny-js#1803]
## This is:

* Bug

## Specifications
* version: 5.10.0

## Expected Behavior

When configuring a single value reference field in CMS content model, one should be able to specify validators for the field. There should be a `required` validator for single-value reference fields.

## Actual Behavior

No "validators" tab when the reference field is _not_ a list.

## Steps to Reproduce the Problem

1. create a new content model
1. add a reference field
1. no "validators" tab appears 

## Detailed Description

![](https://user-images.githubusercontent.com/5498731/126187407-e8b4fbad-11ea-480b-9e00-466c610cadfe.png)

## Possible Solution

add the `"required"` validator [here](https://github.com/webiny/webiny-js/blob/next/packages/app-headless-cms/src/admin/plugins/fields/ref.tsx#L22)

**Comment by dzervoudakes** [comment]
Expressing renewed interest in this issue per the Slack thread here:
https://webiny-community.slack.com/archives/C023WPBK6BS/p1637124516066800

My team and I would find this very beneficial.
