### ISSUE TITLE
Headless CMS - file field missing helpText

### ISSUE THREAD

**Issue by zoezoezoe** [webiny/webiny-js#1804]
## This is:

- Bug

## Specifications

  - version: 5.10.0

## Expected Behavior

file field renderer doesn’t currently display `helpText` even though you can configure it for the field.

## Actual Behavior

display the `helpText` like other fields do.

## Steps to Reproduce the Problem

1. create a content model.
2. add a `file` field, specify some help text.
3. preview the content editor.

## Detailed Description

<img width="727" alt="file-editor" src="https://user-images.githubusercontent.com/5498731/126192403-2903d8a3-9829-4113-a682-20cd54f71139.png">

**Comment by IzioDev** [comment]
Hey, I would love to work on this one, is there anything I should know before starting besides reading the contribution guide ?
