### ISSUE TITLE
Bug: reCAPTCHA keys are not stored; silent fail

### ISSUE THREAD

**Issue by facorread** [webiny/webiny-js#1812]
## This is:
- Bug

## Specifications

  - version: 5.10.0
  - OS: Windows 10; deployed on AWS
  - Browser: Firefox 90.0 and Chrome 91.0.4472.164 (Build oficial) (64 bits)
  - Clean browser profiles
  - Brand new webiny installation

## Expected Behavior
The backend should store the keys; reCAPTCHA should be enabled

## Actual Behavior
The message "Settings updated successfully." appears at the bottom, but the settings are not truly saved. No error message in the browser console.

## Steps to Reproduce the Problem
1. Follow the Webiny installation tutorial https://www.webiny.com/docs/tutorials/install-webiny/
2. Apply the fix to issue #1799
3. Navigate to https://SOMERANDOMSTRING.cloudfront.net/settings/form-builder/recaptcha
4. Enter a valid reCAPTCHA key and secret
5. Save, navigate away, and get back to the settings page

**Comment by Ashu96** [comment]
@facorread I've verified and am happy to report that everything is working fine 💯 
One thing to note here is that you need to re-deploy the **Admin** application `(apps/admin)` after applying any changes.

I'm closing this issue, but feel free to reopen it if needed.
