### ISSUE TITLE
List of pages doesn't show the author of the page

### ISSUE THREAD

**Issue by Pavel910** [webiny/webiny-js#1823]
## This is
- Bug

## Expected Behavior
When a page is created in Page Builder, the list of pages should correctly show the `Created by` label, showing the author of the page.

## Actual Behavior
The label says `N/A`.

![image](https://user-images.githubusercontent.com/3920893/127161189-a6d54de2-82cb-47a9-9632-d623c5a7863e.png)

The API call however, returns the data correctly:
![image](https://user-images.githubusercontent.com/3920893/127161516-375a35f2-8947-45ce-994b-a98f3f7807b2.png)

## Steps to Reproduce the Problem
1. Create a page in Page Builder
2. Go to the list of pages

## Possible Solution
Check how the label is rendered on React side. It's most likely accessing the wrong keys.

**Comment by Patil2099** [comment]
I would love to work on this

**Comment by Pavel910** [comment]
> I would love to work on this

Great! Feel free to open a draft PR  and I'll assign you to the issue then. Let us know if you need any assistance.
