### ISSUE TITLE
Content locked with error after request review status

### ISSUE THREAD

**Issue by cemreinanc** [webiny/webiny-js#1833]
## This is:
- Bug

## Specifications
  - version: 5.11.0
  - OS: MacOS
  - Browser: Chrome 91

## Expected Behavior
After requesting review for a cms entry, any user with the required permissions should be able to edit, save, publish or delete the entry.

## Actual Behavior
Entry is locked. Any operation (edit, save, publish or delete) fail with an error.
` {message: "Cannot read property 'title' of undefined", code: "", data: null, __typename: "CmsError"}`
(title here is just the first property of a model. It also behaves similiarly in all models.)

## Steps to Reproduce the Problem
1.create a model in the headless cms admin panel.
2.create an entry. save it. and then click the request review button.
3. try to take any action. (save, publish, delete)

**Comment by brunozoric** [comment]
I will write a test case for this, but I can confirm it by clicking through the app. Entry is locked and cannot be changed.
Fix will be up in 5.12.0
