### ISSUE TITLE
Yarn 3 support

### ISSUE THREAD

**Issue by adrozdenko** [webiny/webiny-js#1834]
## This is:

- Idea

## Specifications
  - version: 5.11.0
  - OS: MacOS

## Expected Behavior

yarn webiny deploy should work with Yarn 3 https://github.com/yarnpkg/berry
## Actual Behavior

"@webiny/cli” requires yarn@^2 to be installed! 
## Steps to Reproduce the Problem

1. npx create-webiny-project my-new-project
2. yarn webiny deploy

## Detailed Description

Error: "@webiny/cli” requires yarn@^2 to be installed! 
Yarn version 3.0.0 not supported had to roll back to yarn version 2.4.2

**Comment by Pavel910** [comment]
Checked the changelog here: https://github.com/yarnpkg/berry/blob/master/CHANGELOG.md#300
Looks like there is no reason not to support Yarn 3. We'll give it a try in development, and if everything works, we can potentially add it to the next release.
