### ISSUE TITLE
Webiny support for Yarn version 3.0.1

### ISSUE THREAD

**Issue by SyedUmerHasan** [webiny/webiny-js#1856]
## This is:

- Bug
Webiny currently does not support Yarn 3.0.1
@doitadrian  Kindly look into this.
it shows  ``` "@webiny/cli" requires yarn@^2 to be installed! ```

## Specifications

  - version: Version 91.0.4472.114 (Official Build) (64-bit)
  - OS: Linux
  - Browser: Google Chrome/ Mozilla

## Steps to Reproduce the Problem

1.Install latest yarn berry version i,e, v3.0.1
2. try to run any webiny command
3. it will throw error saying ```"@webiny/cli" requires yarn@^2 to be installed!```

**Comment by Pavel910** [comment]
Closing as a duplicate of #1834.
