### ISSUE TITLE
I cannot delete a specific field from one of my models in the CMS, even though I removed all entries of that model

### ISSUE THREAD

**Issue by nelsonchen5** [webiny/webiny-js#1858]
## This is:
* Bug

## Specifications
* version: 5.6.0
* OS: Mac
* Browser: Chrome

## Expected Behavior
I expect when I delete all entries of a content model, it will allow me to delete fields from that content model

## Actual Behavior
I cannot delete fields from a content model, even though all entries are deleted

## Steps to Reproduce the Problem
1. Create model
1. Create Entry
1. Delete Entry
1. Attempt to delete field from model

**Comment by brunozoric** [comment]
@nelsonchen5 this was fixed in 5.19.0
