### ISSUE TITLE
Refresh CMS records after record creation - without having to reload the page

### ISSUE THREAD

**Issue by plsalvado** [webiny/webiny-js#1863]
## This is:

* Feature request

## Specifications
* version: all
* OS: all
* Browser: all

## Expected Behavior
After creating a CMS record on the Admin App, I'd like the list of records on the left hand side to automatically update without having to refresh the page.

## Actual Behavior
The list of records doesn't update unless I refresh the page. The screenshot below shows an empty list of records even after having Saved and Published the new entry.

![](https://user-images.githubusercontent.com/8825508/129386182-bede6922-967d-4380-a4e9-51bdcc6c425d.png)

## Steps to Reproduce the Problem

1. Create a new record in the CMS via the Admin App
1. You won't see the new record on the panel on the left hand side unless you refresh the screen

## Detailed Description

Proposing the list of records updates automatically either when a new record is created, or even deleted.

## Possible Solution

Not explored.

**Comment by brunozoric** [comment]
@plsalvado I cannot reproduce the bug. I tried on my existing models and created a new one, same as yours.
