### ISSUE TITLE
Rich Text elements that can have their alignment set do not render correctly using Rich Text Renderer when the direction property is set to `rtl` on the HTML tag.

### ISSUE THREAD

**Issue by jimjoes** [webiny/webiny-js#1892]
### Version

5.14

### What steps will reproduce the bug?

1. create an article in an RTL language
2. pass the article content to the Rich Text Renderer component.
3. add the dir="rtl" property to the HTML tag 
4. see the content remain stuck with ltr alignment.

### What is the expected behavior?

Text alignment should 'just work' when using the dir tag.

### Possible solution

If the rich text rendered uses "start" and "end" instead of "left" and "right" for the textAlign property, it works as expected, but this isn't the right place for the update - it should be made in the editor, I think. There may be consequences to that I am unaware of however!

**Comment by Pavel910** [comment]
@econtentmaps not sure this is even related to Webiny. Can you verify if this works correctly in plain https://editorjs.io/ ? Because that's the editor we're using.

**Comment by jimjoes** [comment]
Aren't you using a custom "text alignment" plugin/tool or manipulating the block settings directly in webiny? I didn't think vanilla editorjs had a textAlign feature? I'm struggling to decypher the webiny code in this area so I can't really work out how you're defining and then passing plugins/tools to it?

**Comment by Pavel910** [comment]
@econtentmaps All tools are registered here, in your project: https://github.com/webiny/webiny-js/blob/next/apps/admin/code/src/plugins/headlessCMS/richTextEditor.ts

**Comment by jimjoes** [comment]
Ok... in this file [https://github.com/webiny/webiny-js/blob/b66cb50db802ddeeefe7c789cecc7496456ee5c5/packages/app-admin/src/components/RichTextEditor/tools/paragraph/index.ts#L2](url) you're defining a custom paragraph in which you're importing an enum (left/right/center), which I imagine is what's used to define what gets stored in the textAlign key in the paragraph's content block. The rich text renderer then applies inline CSS to all paragraph elements based on that value. So if the values here are changed to start/end/center instead of left/right/center, then the CSS will be applied in an rtl/ltr safe manner? Unless they're used somewhere else and that will break something, of course?

**Comment by Pavel910** [comment]
@econtentmaps we never tried RTL content, so I really have no idea what will make it work. Also, there's no magic about that  `react-rich-text-renderer`: it produces simple JSX output + there's an `scss` file, so you will have to add new CSS rules to handle new class names. 

If you get it to work, we'd appreciate the instructions on how to improve the current implementation, or even a PR.

**Comment by jimjoes** [comment]
Yep, it's definitely not magic :) What it's doing is applying whatever value it finds in the alignText property of a paragraph's content block (i.e. the raw content block that's saved by the editor and that gets sent from the API) to an inline textAlign CSS property directly in the JSS - I don't *think* it's using the SCSS styles for that. There's a bit of webiny-specific customisation to editor.js whereby, when paragraphs are created in a richtext field in the admin headless CMS editor, they're all created with that alignText property and it looks like the default is set to 'left'. Now, with rtl languages, I think the most sensible approach is to define the content's direction in the HTML and let CSS manage what alignment makes sense for text. To that end, you can use 'virtual' values for the alignText CSS property: 'start' instead of 'left' and 'end' instead of 'right'. In that way, to realign all text properly according to the language, you just set the dir property once in your HTML tag in the markup, and, boom, the css just interpets end as left now instead of right, and vice versa. Now, because the richtext editor is setting that alignText property at source, and it's making its way unmolested all the way through to the alignText inline CSS property in the JSX in the richtext renderer, if we just change left/right to start/end in the paragraph/index.js file and its dependencies (i.e. where you've defined the custom editorjs behaviour I've described above) I think it will 'just work'.  I will have a go at a PR but there may well be far broader implications to this small change than I'm considering here. Let's see.

**Comment by Pavel910** [comment]
I will add @Ashu96 to this conversation, as he's the original author of that component, and he may be able to provide more information and help you out with PR.

**Comment by jimjoes** [comment]
I'll ignore the challenge of RTLing the admin app itself for now and just look into the alignText thing :)
