### ISSUE TITLE
Searching by tag doesn't work

### ISSUE THREAD

**Issue by andrewmcoupe** [webiny/webiny-js#1908]
### Version
5.14.0

### Operating System
N/A

### Browser
N/A

### What steps will reproduce the bug?
Try to search in the file manager section of the admin UI or via the GraphQL playground.

![Screenshot 2021-09-16 at 08 10 57](https://user-images.githubusercontent.com/24691226/133566564-602c3902-90b5-4567-9789-f52f89ebddf2.png)

![](https://user-images.githubusercontent.com/24691226/133566259-186a4f56-6858-46cb-bc52-c3c6658d9e89.png)

### What is the expected behavior?
Searching should return files with tags or name which include the search term.

### What do you see instead?
No results.

### Possible solution
A nice feature would be to allow a filter? Where tag includes "this string" and/or "this string".

**Comment by brunozoric** [comment]
Hi @andrewmcoupe 
Just to say something: "It is not a bug, it is a feature" :)
I have added a PR that will enable to you send in tag_and_in which will match all the tags you send.
