### ISSUE TITLE
Reordering Ref Field with multiple Content Models automatically does it's own reorders upon save/publish, and groups the same model together

### ISSUE THREAD

**Issue by nelsonchen5** [webiny/webiny-js#1913]
### Version

5.6.0

### Operating System

Mac OS

### Browser

Chrome

### What steps will reproduce the bug?

1. Create a CMS entry with a ref field that contains multiple content models
2. Add multiple entries to the ref field with different models, and order the model the way you want it. For example:
```
Card 1 -- Model Type A
Card 2 -- Model Type B
Card 3 -- Model Type A
Card 4 -- Model Type B
Card 5 -- Model Type A
```
3. Save and Publish the Entry
4. The ref field automatically reorder itself to:

```
Card 1 -- Model Type A
Card 3 -- Model Type A
Card 5 -- Model Type A
Card 2 -- Model Type B
Card 4 -- Model Type B

```

### What is the expected behavior?

1. Add multiple entries to the ref field with different models, and order the model the way you want it. For example:
```
Card 1 -- Model Type A
Card 2 -- Model Type B
Card 3 -- Model Type A
Card 4 -- Model Type B
Card 5 -- Model Type A
```
2. Save and Publish the Entry and the ordering does not changge

### What do you see instead?

https://user-images.githubusercontent.com/31781643/133800213-b7a95aa0-7e71-4e41-b56a-826a9b58d955.mov

### Additional information

Slack discussion:

https://webiny-community.slack.com/archives/C014Y0HGJ0Y/p1631823845299300

Uploading Screen Recording 2021-09-16 at 1.44.07 PM.mov…

https://user-images.githubusercontent.com/31781643/133800226-8b4a1a4a-1610-4928-bca7-92d0ab794dba.mov

**Comment by adrians5j** [comment]
Hey @nelsonchen5,

what I was able to discover is the following...

First, after saving, in the DynamoDB table, the values are actually correctly sorted/ordered:

![image](https://user-images.githubusercontent.com/5121148/133816992-68f9fd26-2045-4871-8cbf-1adf6e11b590.png)

The problem probably happens because of the the way these references are loaded, starting from here:
https://github.com/webiny/webiny-js/blob/next/packages/api-headless-cms/src/content/plugins/graphqlFields/ref.ts#L62

So, I'd suggest doing some debugging here. A fix would probably entail leaving the database loading strategy as-is, but then sorting the received data based on the initial order that was received from the database.

Note that in order to debug this, and potentially submit a PR, you'll have to clone this `webiny-js` repo.

Once you have that, you can basically start debugging this through tests. The best way would be to copy and paste an existing test, and start writing a test case, and debugging.

This test looks like something that could get you started quickly:
https://github.com/webiny/webiny-js/blob/next/packages/api-headless-cms/__tests__/contentAPI/refField.test.ts

In any case, let us know once you have something and if you'll need further assistance.

Thanks 🍻 

P.S. Contributing guide can be found here https://github.com/webiny/webiny-js/blob/next/docs/CONTRIBUTING.md.

**Comment by adrians5j** [comment]
BTW just wanted to give you a heads up and let you know that if we merge a PR for this, the changes that it contains will be released as part of the upcoming 5.15.0 version.

Since you're on 5.6, in order to get the change in your project, you'll need to do some upgrading first.

**Comment by nelsonchen5** [comment]
hey @doitadrian 

Been trying to debug this issue with not much success, one thing I've noticed is that when you press `Save and Publish`, it only makes request to the `Manage API`

however, I noticed that the file you linked: `https://github.com/webiny/webiny-js/blob/next/packages/api-headless-cms/src/content/plugins/graphqlFields/ref.ts#L62` is only invoked when theres a request for the `Read API`

Is this how it's supposed to work or am I missing something?

**Comment by adrians5j** [comment]
> Been trying to debug this issue with not much success, one thing I've noticed is that when you press `Save and Publish`, it only makes request to the `Manage API`

That's correct. The manage API is what's used to manage (create, read, update, delete) content.

> however, I noticed that the file you linked: `https://github.com/webiny/webiny-js/blob/next/packages/api-headless-cms/src/content/plugins/graphqlFields/ref.ts#L62` is only invoked when theres a request for the `Read API`

That's weird, I think this should be invoked there as well.

---

Can you tell me one thing, where are you reading the logs from?

**Comment by nelsonchen5** [comment]
hey @doitadrian 

I'm looking in the Network tab with chrome Devtools when I press `Save and Publish`


https://user-images.githubusercontent.com/31781643/134385005-07e7644b-6f1e-4968-b55f-34df458b7e8e.mov



I'm looking at console.logs in CloudWatch and my console logs only show up when I invoke the `Read API` in the Playground



~~EDIT: There's a chance that my deployments are not reflecting any changes as well, I've been running `yarn webiny deploy api --env=dev` after changes in the API, and sometimes I'm not sure if my code got deployed~~

EDIT2: Apparently I have to be running `yarn webiny ws run watch --folder=./packages/api-headless-cms` when I deploy? That's the only way I've been able to see my relevant changes in CloudWatch

**Comment by adrians5j** [comment]
Well, you can always inspect the `build` folder (`api/code/headlessCMS/build`) and search the console.log statement you added. Also, after you deploy, in the terminal, you should be able to see the change highlighted by Pulumi (it will say something like `~code`).

But what I'd also recommend you try is running the `yarn webiny watch api/code/headlessCMS --env dev --logs`, this will stream the logs into your console, and also continusly deploy changes into the cloud for you. No need for full deployments = faster iterations.

You should have the watch command available, it was introduced in 5.5:

https://www.webiny.com/docs/release-notes/5.5.0/changelog#brand-new-webiny-watch-command-1540
https://www.webiny.com/docs/how-to-guides/use-watch-command

**Comment by adrians5j** [comment]
Yes that's true. 

If you're making changes on code in `packages` folder, you need to run a separate watch session on those too.

You can use the above command. But the following one will work too:
`yarn webiny watch -p @webiny/api-headless-cms`

So, run these two in two separate terminal sessions, and you should be good.

**Comment by nelsonchen5** [comment]
@doitadrian 

When I run `yarn webiny watch api/code/headlessCMS --env dev --logs` I get this:
<img width="675" alt="Screen Shot 2021-09-22 at 10 11 33 AM" src="https://user-images.githubusercontent.com/31781643/134390152-82d77414-a05b-422d-97b2-1e3d5bf7a62b.png">

**Comment by adrians5j** [comment]
Oh yeah... we have an issue at the moment (only present in webiny-js repo, not in real CWP projects).

Circumvent it by running the `webiny watch` command with the following:

```bash
yarn webiny watch api/code/headlessCMS --env dev --logs -p api-headless-cms -p @webiny/api-headless-cms
```

> TIP: `-p` stands for `package`, so you're actually specifying multiple package names here.  `api-headless-cms` is the name of the package in the `api/code/headlessCMS` folder.

With this approach you'll be able to run all needed watches with a single watch command.

**Comment by nelsonchen5** [comment]
awesome, thanks Adrian, this will speed up debugging immensely!

with that being said, do you know why `Save and Publish` isn't invoking the `Read API` at all? Or is it being invoked somewhere that I can't see

**Comment by adrians5j** [comment]
NP :)

`Save and Publish` should not invoke Read API, only manage. Actually, all operations in the admin area are interacting with the Manage API. 

BTW you can also use API Playground for executing GQL queries in a more controlled fashion:
https://www.webiny.com/docs/how-to-guides/webiny-applications/admin-area/api-playground/

**Comment by nelsonchen5** [comment]
That makes sense, however; I'm confused because I've been working in the API Playground and when I use the `Manage API`, the order that I'm expecting is **correct**. However the order is only wrong in the response when I invoke in `Read API`, 

From the code, it looks like the order is mangled in here as you mentioned: https://github.com/webiny/webiny-js/blob/next/packages/api-headless-cms/src/content/plugins/graphqlFields/ref.ts#L62

However, it appears this plugin is only invoked when utilizing the `Read API`, I can't find where this plugin is used in the `Manage API`

**Comment by nelsonchen5** [comment]
The response I get from the Network tab in Chrome DevTools is

```
[
  {
    "data": {
      "content": {
        "data": {
          "id": "614a1e180616cf00058e3eb8#0021",
          "createdBy": {
            "id": "nchen@seattlekrakenhockey.com",
            "__typename": "CmsCreatedBy"
          },
          "ref": [
            {
              "modelId": "modelC",
              "entryId": "614931dcca7cd50009e644c8#0001",
              "__typename": "RefField"
            },
            {
              "modelId": "modelB",
              "entryId": "614931c3ca7cd50009e644c6#0002",
              "__typename": "RefField"
            },
            {
              "modelId": "modelC",
              "entryId": "614931e9ca7cd50009e644ca#0001",
              "__typename": "RefField"
            },
            {
              "modelId": "modelB",
              "entryId": "614931d1ca7cd50009e644c7#0001",
              "__typename": "RefField"
            }
          ],
          "savedOn": "2021-09-22T17:16:33.229Z",
          "meta": {
            "title": "614a1e180616cf00058e3eb8#0021",
            "publishedOn": null,
            "version": 21,
            "locked": false,
            "status": "draft",
            "__typename": "MultipleRefModelMeta"
          },
          "__typename": "MultipleRefModel"
        },
        "error": null,
        "__typename": "MultipleRefModelResponse"
      }
    }
  },
  {
    "data": {
      "content": {
        "data": {
          "id": "614a1e180616cf00058e3eb8#0021",
          "meta": {
            "title": "614a1e180616cf00058e3eb8#0021",
            "publishedOn": "2021-09-22T17:16:34.743Z",
            "version": 21,
            "locked": true,
            "status": "published",
            "__typename": "MultipleRefModelMeta"
          },
          "__typename": "MultipleRefModel"
        },
        "error": null,
        "__typename": "MultipleRefModelResponse"
      }
    }
  }
]

```

which shows that the correct order (since it's the response from the `Manage API`:
```
Model Type C
Model Type B
Model Type C
Model Type B

```
and in the API Playground:
![image](https://user-images.githubusercontent.com/31781643/134392478-d4c02390-22a8-48d5-b830-1d2d53583ba6.png)


however it reflect incorrectly in the `Admin Area` and `Read API`:

![image](https://user-images.githubusercontent.com/31781643/134391951-3514c777-a940-4146-92c1-0c593d062f25.png)


![image](https://user-images.githubusercontent.com/31781643/134392101-781d6bcf-9962-407a-b7db-2d3f9adf1bcf.png)


This makes me come to the conclusion that the Admin Area is using the Read API _somewhere_, though I don't know where/how it's happening

**Comment by adrians5j** [comment]
> That makes sense, however; I'm confused because I've been working in the API Playground and when I use the Manage API, the order that I'm expecting is correct. However the order is only wrong in the response when I invoke in Read API,

> From the code, it looks like the order is mangled in here as you mentioned: https://github.com/webiny/webiny-js/blob/next/packages/api-headless-cms/src/content/plugins/graphqlFields/ref.ts#L62

You say the order on the Manage API is correct and on Read API - not. That's actually the same thing I'm seeing on my end. Good catch 👍🏻 


> However, it appears this plugin is only invoked when utilizing the Read API, I can't find where this plugin is used in the Manage API

What I don't understand here is ..... why would you then try to find where this plugin is used on the Manage API? Based on the new discovery, we're debugging the Read API.

BTW note that the code I referenced is part of the `read` property:
https://github.com/webiny/webiny-js/blob/next/packages/api-headless-cms/src/content/plugins/graphqlFields/ref.ts#L32

So, the other, `manage` property most probably doesn't need to concern us:
https://github.com/webiny/webiny-js/blob/next/packages/api-headless-cms/src/content/plugins/graphqlFields/ref.ts#L138

Can you try putting a console.log statement somewhere at the beginning, like here:
https://github.com/webiny/webiny-js/blob/next/packages/api-headless-cms/src/content/plugins/graphqlFields/ref.ts#L42

Do you get anything out after you execute a query that includes a ref field with multiple values enabled?

I'll have to go AFK now until tomorrow. In the meantime, please check ⬆️ .

P.S. The image below the `however it reflect incorrectly in the Admin Area and Read API:` sentence doesn't prove it's Read API we're working with. How did you determine it's the Read API? The only thing I see in the sshot is `en-US`, which could also pretty much be the Manage API. 

P.S.2 - thanks for all of the detailed explanations and sshots. 🍻

**Comment by nelsonchen5** [comment]
hey @doitadrian 

really appreciate the quick response

only reason I think it's on the `Manage API` is because every time I `Save and Publish` I only see network requests on the `Manage API`

I added a console.log statement in the beginning of the `ref.ts` file, however, I only get something if I execute a query in the API Playground on the `Read API` and nothing when I use the `Manage API` or `Save and Publish` in the admin area

I guess my question boils down to, where does the data shown in the Admin Area with the incorrect order come from?
![image](https://user-images.githubusercontent.com/31781643/134391951-3514c777-a940-4146-92c1-0c593d062f25.png)

Is it the `Read API` or  `Manage API`? I was assuming it was the `Manage API` from the network requests I see in chrome devtools, but is it actually pulling data from the `Read API` somehow? Since you said all operations in the Admin Area should be coming form the `Manage API`, I assume the UI in the image below should also be pulling the response from the `Manage API`

<img width="1401" alt="Screen Shot 2021-09-22 at 10 24 15 AM" src="https://user-images.githubusercontent.com/31781643/134418637-eb428741-534b-452e-87c3-a13b1dce7d5f.png">

**Comment by nelsonchen5** [comment]
I dug a little more and found that there is a bug in the `Manage API` when it runs a `getContentEntries` query which returns it in the wrong order:

![image](https://user-images.githubusercontent.com/31781643/134420824-21f2268e-cab0-4001-9877-dbff6ca1302b.png)

**Comment by nelsonchen5** [comment]
hey @doitadrian ,

Think I fixed the issue! Looks like it was happening in two places, one that affects the `Manage API` and one that affects the `Read API`

Hope it's possible to get this in by next release!

https://github.com/webiny/webiny-js/pull/1922
