### ISSUE TITLE
Can't manage File Manager srcPrefix from Admin Area

### ISSUE THREAD

**Issue by coderhglee** [webiny/webiny-js#1923]
### Is your feature request related to a problem? Please describe.
Regarding the FileManager still returning CloudFront URLs for newly uploaded/selected files, that’s something that can be changed, although you’ll need to adjust this via database for the moment.

the `uploadMaxFileSize` and `uploadMinFileSize` and these are actually possible to edit via Admin Area / Main Menu / Settings / File Manager, but the `srcPrefix` is something that isn’t there

### Describe the solution you'd like.
the Form Builder’s settings form should also contain a simple text field that will enable users to adjust the `srcPrefix` setting

**Comment by Pavel910** [comment]
This is solved in 5.24. `srcPrefix` is now available in the File Manager settings form. Closing.
