### ISSUE TITLE
Updating an API token invalidates it

### ISSUE THREAD

**Issue by snstanton** [webiny/webiny-js#1941]
### Version
5.15.0

### Operating System
MacOS

### Browser
Firefox

### What steps will reproduce the bug?
* Create an API token with CMS full access.
* Use it in a curl call
* Verify the request succeeds
* Change the name of the token and save
* Use it in a curl call
* The call will fail with a permission denied error

### What is the expected behavior?
Updating an api token should not invalidate it

**Comment by Pavel910** [comment]
That's weird. Definitely should not be happening. I'm working on security layer upgrades at the moment, and will add tests for this. Thanks for reporting! 🙌

**Comment by Pavel910** [comment]
This was fixed some time ago. Closing.
