### ISSUE TITLE
Cursor is invalid if the value is non-ascii

### ISSUE THREAD

**Issue by snstanton** [webiny/webiny-js#1956]
### Version

5.15.0

### Operating System

MacOS

### Browser

Firefox

### What steps will reproduce the bug?

- Create a CMS table name field containing a value like: `"Graham O’Keeffe" `(note the non-ascii apostrophe).
- Issue a list query where the returned cursor value for the end of the page is that value.
- Attempt to issue a query for the next page of results using that cursor

Example cursor value: `"WyJHcmFoYW0gT+KAmUtlZWZmZSJd"`

### What is the expected behavior?

Get the next page of results.

### What do you see instead?

The original page of results is returned again with the same cursor value.  There is an error in the logs:

```
 "extensions": {
    "console": [
      {
        "method": "log",
        "args": [
          "Unexpected token \u0000 in JSON at position 11"
        ]
      }
    ]
  }
```

### Additional information

Unpacking the cursor yields:  
```
["Graham O\342\200\231Keeffe"]
﻿﻿```


### Possible solution

The cursor value should be encoded/decoded in a way that doesn't break in the face of unicode characters above the ascii range.

**Comment by brunozoric** [comment]
Jest tests shows that there is nothing wrong with the decoding a string with special character in it.
