### ISSUE TITLE
Cannot search for references by entryId

### ISSUE THREAD

**Issue by snstanton** [webiny/webiny-js#1972]
### Version
5.15.0

### Operating System
MacOS

### Browser
Firefox

### What steps will reproduce the bug?
Create a model A that has a reference to model B
Create and publish B1
Create and publish A1 with a reference to B1
Update and publish B1

Run the query :
`listBs { data { id } }`
Retrieve `B.id`, which should be `...#0002`
Query for A that contains B.id
`query AQuery($id: String!) listAs(where: { ref: $id }) { data { id } }   # Vars { id: B.id } `

The query will return an empty list because `A1.ref `== `B1.id#0001`, but the current value is` B1.id#0002`.
However, performing a projection A1.B1 will return the published values of B1.

### What is the expected behavior?
Searching via the read api for a reference should ignore the version suffix and query by entryId only.

### What do you see instead?
The entry is only matched if the reference revision exactly matches.

**Comment by brunozoric** [comment]
Hi @snstanton 
For that to work we would need to have filtering by reference. Query would look something like this:
````
listArticles(where: {
    category: {
        id: "xyz#1"
        id_in: ["xyz#1"]
        entryId: "xyz"
        entryId_in: ["xyz"]
        // ... more fields from category model
    }
}) {
    data {
        id
        title
        category {
            id
            title
        }
    }
}
````
It is in our pipeline, just didn't get time yet to build it. You can always give it a go and contribute.
We can help along the way and there are a lot of tests to make sure nothing gets broken.

**Comment by brunozoric** [comment]
Here is a PR that adds tests for searching by entryId (and some other options).
https://github.com/webiny/webiny-js/pull/1973
Currently it is being skipped, but upon implementation of the search, it can be ran.
