### ISSUE TITLE
Any way to deploy anywhere else, except for AWS?

### ISSUE THREAD

**Issue by alexander-potemkin** [webiny/webiny-js#1985]
### Is your feature request related to a problem? Please describe.
I'm looking to be able to use Webiny on providers different from AWS - is there such an option? If not, any chance this could end being on roadmap anytime soon?

### Describe the solution you'd like.
Webiny can be easily installed in any environment with Docker. It's Ok, if some functionality (I guess, it's search?) won't be available.

### Describe alternatives you've considered.
Other open source WYSIWYG builders.

**Comment by Pavel910** [comment]
@alexander-potemkin Microsoft Azure is on the roadmap for the next year. Currently, the focus is on AWS and getting it right on one cloud, before conquering others.

If you're interested in Docker, that would have to be a community driven project. We're not considering Docker for the forseeable future , unless you have a replica of AWS sitting around in containers ;)

**Comment by alexander-potemkin** [comment]
@Pavel910 , thanks!

> unless you have a replica of AWS sitting around in containers

Depending on the demand, it's not an impossible task - do you see any demand on that?

And what are the AWS resources that required for the app to run, except for the serverless platform?

**Comment by Pavel910** [comment]
@alexander-potemkin for us, it's far from being a priority, as we are a serverless-oriented company, and we don't plan to manage and maintain docker images. People do ask about it every now and then, but less and less as the time progresses.

Here you can find breakdown of the infrastructure resources we use, per app, with diagrams: https://www.webiny.com/docs/key-topics/cloud-infrastructure/api/overview

As an experiment, it would probably be cool, and we could provide some support with details on how stuff operates  within Webiny, if someone was to actually do the heavy lifting.

**Comment by alexander-potemkin** [comment]
Got it, thank you.
If you will have any commercial supported query, I might be interested to port things over: I can things are quite connected to AWS, indeed, but not something that can't be decoupled and migrated to other cloud providers / on premises.
