### ISSUE TITLE
Extra underline in User Profile account details

### ISSUE THREAD

**Issue by plsalvado** [webiny/webiny-js#1986]
### Version
5.14

### Operating System
macOS

### Browser
Safari

### What steps will reproduce the bug?
1. Open the Admin App,
1. Navigate to the top right of the screen - the user avatar - and click on the icon,
1. On the expanded modal hover the mouse over "Account details" -> you will see an underline below the text,
1. Now hover the mouse over "Sign out", and you won't see the underline.

### What is the expected behavior?
Consistent styling, we don't seem to be applying underlines for hovering events, except for that "account details" link.

### Extra underline
![](https://user-images.githubusercontent.com/8825508/138423404-8b33b9e9-f93d-4751-ad66-af85c219854b.png)

### Entry in the same list without an underline
![](https://user-images.githubusercontent.com/8825508/138423469-ca305c77-ea24-4a52-a6ed-ca503ab44935.png)

### Possible solution
This seems to be happening because the account details `<div>` is inside an `<a>` tag. And `<a>` tags are taking the styling below. Note: On the opposite side, the "Sign out" entry is not inside and `<a>` tag, neither are the entries in the Navbar in general.

```
a:hover {
    text-decoration:underline
}
```

**Comment by Pavel910** [comment]
Resolved in the `next` branch. Closing.
