### ISSUE TITLE
Adding an empty object field as the first field breaks listContentModels

### ISSUE THREAD

**Issue by snstanton** [webiny/webiny-js#2001]
### Version

5.16.0

### Operating System

MacOS

### Browser

Firefox

### What steps will reproduce the bug?

Create a new model and add an object field as the only field.  Save the model.  At this point listContentModels will be broken and the admin UI will no longer function.

### What is the expected behavior?

The editor should require a text field as the title field and prevent attempts to save the model without one.  The listContentModels api should not break in any case.

### What do you see instead?

`Object { name: "GraphQLError", message: "Syntax Error: Expected Name, found }", stack: "GraphQLError: Syntax Error: Expected Name, found }
`

**Comment by Pavel910** [comment]
Thanks @snstanton, that one was already reported, basically we need to skip object fields that don't have any child field during schema generation. To fix your schema, you need to delete that field manually from DynamoDB console.
