### ISSUE TITLE
Page builder button is not working

### ISSUE THREAD

**Issue by AmamDewan** [webiny/webiny-js#2061]
### Version

5.18.1

### Operating System

Artix Linux

### Browser

Waterfox

### What steps will reproduce the bug?

After version upgrading from `5.17` to `5.18` I have noticed that all the page builder button element link is not working. I have found button link in graphql response but not rendered in HTML. I have tried with fresh installation. The problem remains the same
I am using Dynamodb+Elasticsearch version

### What is the expected behavior?

After updating page builder button link It should render in front-end website.

**Comment by adrians5j** [comment]
I'll take a look at this @AmamDewan.

Will give you an update tomorrow.

Thanks for reporting!

**Comment by adrians5j** [comment]
A fix for this has been released. 

Please update to `5.18.2` when you get the chance @AmamDewan (`yarn up "@webiny/*@5.18.2"`).
