### ISSUE TITLE
Allow more customization of search behavior

### ISSUE THREAD

**Issue by snstanton** [webiny/webiny-js#2122]
### Is your feature request related to a problem? Please describe.

I built a new headlessCMS query like this:

```
extend type Query {
    searchArticles(after: String, limit: Int, sort: [ArticleListSorter], where: ArticleListWhereInput,
        search: String): ArticleListResponse
}
```

The behavior is identical to listArticles with the addition of a `search` term that performs a cross-field full text search.  The resulting query has a clause like:
```
simple_query_string: {
      fields: ['values.title^5', 'values.summary', 'values.searchTerms'],
      query: search,
      default_operator: 'or'
}
```

However, to make this work, I needed to write a pretty ugly kludge where the `SearchArticlesSchemaPlugin` uses a shared global variable to pass the search string to `ArticleModifyQueryPlugin`. 

### Describe the solution you'd like.

If there was a way to pass custom parameters to the `cms.listEntries` that could be picked up by the cms plugins, that would resolve the problem. 

### Describe alternatives you've considered.

I initially attempted to add extra state to the list parameters (e.g. an extra `where` element), but I couldn't find anything that would get passed down without triggering some error.  

Also, my original design was to add `search: String, fields: [String]` so you could select which fields to include in the full text query, but we wound up passing the same list everywhere, so I just inlined it.

I've attached the plugins for reference

[search.zip](https://github.com/webiny/webiny-js/files/7722922/search.zip)

**Comment by brunozoric** [comment]
We could extend the GraphQL schema to look something like this:
```graphql
query listArticles(
    search: {
        fields: ["title", "body", "description"]
        operator: "contains"
        value: "some search text"
    }
) {
    data {
        id
    }
}
```

I think we will need to refactor how our Elasticsearch query building works to support more possibilities.

**Comment by plsalvado** [comment]
@snstanton we're going to be looking into this during Q1. It'd be great to get your feedback once we have a design in place.
