### ISSUE TITLE
Add version to api response headers

### ISSUE THREAD

**Issue by snstanton** [webiny/webiny-js#2134]
### Is your feature request related to a problem? Please describe.

Incompatible api changes require the client to reload the page or it will get errors when making some calls. To allow the client to detect a version change, all api responses should include the api version. The client can detect this on any response (including errors) and force a page reload or internally switch between api versions if it supports both old and new api calls.

### Describe the solution you'd like.

Add the api version to a header in every api response.

**Comment by brunozoric** [comment]
PR for this is up. It will be required by the user to turn on the version header. Docs will be in 5.21.0, as will this feature.
