### ISSUE TITLE
[SOLVED kind of] new project deployment not working

### ISSUE THREAD

**Issue by goldwareJapan** [webiny/webiny-js#2148]
### Version

5.20.0

### Operating System

OSX 12.1

### Browser

Chrome

### What steps will reproduce the bug?

npx create-webiny-project my-new-project

yarn webiny deploy

### What is the expected behavior?

Just deploy

### What do you see instead?

```
webiny info: Using profile pinto in ap-northeast-1 region.
webiny success: Hook "hook-before-deploy" completed.

webiny info: Deploying...

Updating (dev):

    pulumi:pulumi:Stack api-dev running
    pulumi:providers:aws default_4_28_0  error: no resource plugin 'aws-v4.28.0' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource aws v4.28.0`
    pulumi:pulumi:Stack api-dev
    pulumi:providers:aws default_4_28_0 **failed** 1 error

Diagnostics:
  pulumi:providers:aws (default_4_28_0):
    error: no resource plugin 'aws-v4.28.0' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource aws v4.28.0`

Resources:
    1 unchanged

Duration: 3s
```

### Additional information

pulumi plugin is already there

```
 pulumi plugin ls                                                                                                                                        master ◼
NAME    KIND      VERSION  SIZE    INSTALLED       LAST USED
aws     resource  4.33.0   354 MB  22 minutes ago  now
aws     resource  4.28.0   344 MB  1 month ago     now
aws     resource  4.27.2   343 MB  1 month ago     1 month ago
docker  resource  3.1.0    40 MB   1 month ago     now
random  resource  4.3.1    32 MB   1 month ago     now

TOTAL plugin cache size: 1.1 GB
```

**Comment by goldwareJapan** [comment]
OK. Worked it out.

1. removed pulumi plugins with other version
2. deleted these two folder `.pulumi` and `.webiny`
It worked

In the future, we need to fix this. 
( sorry this is my first time with new to pulumi and webiny. So I can't help )

**Comment by adrians5j** [comment]
Thanks for reporting @goldwareJapan.

Just wondering...did you maybe had the Pulumi CLI globally installed? 

BTW, we have a couple of things we want to do here, and one of the thing is the integration of Pulumi's Automation API, which will hopefully probably play better with Webiny (for now no ETAs).

**Comment by goldwareJapan** [comment]
Oh yeah. It looks like I have installed it globally

❯❯❯ pulumi version
v3.20.0
❯❯❯ which pulumi
/usr/local/bin/pulumi

**Comment by adrians5j** [comment]
Cool, thanks for the answer.

We'll definitely think about this scenario when we start working on the Automation API.
