### ISSUE TITLE
Duplicate page slugs/url

### ISSUE THREAD

**Issue by luckoseb** [webiny/webiny-js#2152]
### Version

5.19.1

### Operating System

osx

### Browser

chrome

### What steps will reproduce the bug?

Create a page `/main` add content, publish.

Create a different page with the same `/main` slug

### What is the expected behavior?

I can not overwrite original page with the same url. This is important for use cases when more than one user is editing them.

### What do you see instead?

I am able to publish multiple pages on the same url

### Possible solution

The valid workflow would be -> create new document, do not publish it right away, ask for a `Title`. Once the title is provided the slug is generated, while checking database for the same url and altering it in case there was already a page with the same name. Currently new documents are looking strange with default urls like `/untitled-kxel43kc`

**Comment by brunozoric** [comment]
It is made on purpose that you can override one page with another via the slug. The reason for that flow is:
- create a page on "/main"
- publish it
- create another page on "/main" 
- publish it

Second page immediately replaces the first one. If there was a requirement to unpublish the page before setting a new one on the url, users will see a 404 page instead.

We will add a confirmation that page is already published on url that you are trying to publish on.
