### ISSUE TITLE
Attempted import error: 'SecurityIdentity' is not exported from '@webiny/app-security/types'.

### ISSUE THREAD

**Issue by goldwareJapan** [webiny/webiny-js#2155]
### Version

5.20.0

### Operating System

OSX 12.1

### Browser

Chrome

### What steps will reproduce the bug?

Followed this tutorial

https://www.webiny.com/docs/tutorials/create-custom-application/security/react-application/initial-setup

### What is the expected behavior?

tutorial should be working

### What do you see instead?

Attempted import error: 'SecurityIdentity' is not exported from '@webiny/app-security/types'.

**Comment by goldwareJapan** [comment]
tried to bypass like this 
```
        setIdentity(
          {
            login: user.email,
            firstName: user.given_name,
            lastName: user.family_name,
            logout: () => {
              Auth.signOut();
              setIdentity(null);
            },
          } as any
        );
```

But cognito fails
```
Request : 

https://c0935d3d11402f6e4bd588cb96c45e03.auth.ap-northeast-1.amazoncognito.com/error?error=redirect_mismatch&client_id=58llnjns2qsolpeod2iajvjn8m

Response : 

An error was encountered with the requested page.
```

**Comment by goldwareJapan** [comment]
tried this 
`import { SecurityIdentity } from "@webiny/app-security/types";`

but ts compiler gives error
`'SecurityIdentity' only refers to a type, but is being used as a value here.`

**Comment by goldwareJapan** [comment]
About `SecurityIdentity` problem looks like we need to use [this](https://github.com/webiny/webiny-examples/blob/master/create-custom-application/full-example/pinterest-clone/app/code/src/components/Authenticator.tsx) code for `Authenticator.tsx` file..

Now I have a `Cognito` redirect `An error was encountered with the requested page.` problem

**Comment by goldwareJapan** [comment]
Looks like my cognito client set to `localhost:3002` and my app was running `localhost:3000` changed cognito client redirect and UI works.

**Comment by goldwareJapan** [comment]
Also 1 problem. [Documentation](https://www.webiny.com/docs/tutorials/create-custom-application/security/react-application/integrating-hosted-ui-authentication-flow) have this code and this have a error.
`{identity.firstName.charAt(0)}`

this line should be 
`{identity.displayName.charAt(0)}`

Looks like example fixed it 
https://github.com/webiny/webiny-examples/blob/master/create-custom-application/full-example/pinterest-clone/app/code/src/components/Layout.tsx#L49

Sent pull request : https://github.com/webiny/docs.webiny.com/pull/373

**Comment by adrians5j** [comment]
I'll take a look at this.

**Comment by adrians5j** [comment]
Thanks for reporting and fixing @goldwareJapan. 

Yeah, the code snippets in the docs that you fixed were outdated, but the ones in the examples-repo weren't. So, updating the docs with the code from the examples-repo was the right thing to do. I must've missed these two snippets when I was doing the overall update of the articles.

In any case, awesome job @goldwareJapan! 🙂  Thanks a lot for the PRs, both were merged and deployed.
