### ISSUE TITLE
Crash when clearing a date field

### ISSUE THREAD

**Issue by snstanton** [webiny/webiny-js#2170]
### Version

5.19.1

### Operating System

MacOS

### Browser

Firefox

### What steps will reproduce the bug?

1. Create model with a field like

``` 
        {
            id: "publishDateTime",
            fieldId: "publishDateTime",
            label: "Publish DateTime",
            helpText: "This article will not be visible until this time.",
            type: "datetime",
            renderer: {name: "date-time-input"},
            settings: {type: "dateTimeWithTimezone"}
        },
```
2. Create a new instance of the model
3. Set the date and timestamp and save
4. After saving, now hit the 'x' next to the date to clear the field.  

### What is the expected behavior?

Either the date should be blank or both date and time should be blank.

### What do you see instead?

A crash trying to parse a timestamp with no date portion:
```
Uncaught Error: Could not extract date and time from "T00:00:00+01:00".
    Angular 2
    React 11
    unstable_runWithPriority scheduler.development.js:659
    React 10
    unstable_runWithPriority scheduler.development.js:659
    React 4
DateTimeWithTimezone.js:20
```

### Additional information

If you clear the time before the date, then the time shows --:--:--, but when you try to clear the date, you get a similar failure due to the timestamp.  

### Possible solution

The individual clear buttons should be replaced with a clear button for all three parts at once that sets the whole field to null.

**Comment by brunozoric** [comment]
I can confirm the bug. I will fix it.
