### ISSUE TITLE
Timezone field shows a default value of today with +01:00 timezone but actually saves null

### ISSUE THREAD

**Issue by snstanton** [webiny/webiny-js#2171]
### Version

5.19.1

### Operating System

MacOS

### Browser

Firefox

### What steps will reproduce the bug?

1. Create a model with a datetime field 
2. create a new entry

### What is the expected behavior?

The default time should either be:
* 00:00:00 today in UTC
* 00:00:00 today in browser timezone
* null

If either time or date are set to null, then all parts should be null.  Partial date times are not valid data.

### What do you see instead?

It uses +01:00 as the timezone.

### Additional information

It would be helpful to configure the behavior.  Sometimes I want the field to start with no value (null), and sometimes I want it to default to current timestamp, preserving the user's timezone.

**Comment by snstanton** [comment]
Actually, it's more confusing that I thought.  If you create an entry with a datetime field, it shows today's date and midnight London time, but it actually saves 'null' unless you happen to touch the fields and set some other value.  It's the worst of all worlds because it lies to you and does something surprising.

**Comment by brunozoric** [comment]
@snstanton this was solved  in 5.20.0
docs: https://www.webiny.com/docs/release-notes/5.20.0/changelog#fixed-an-admin-area-bug-where-date-field-value-was-set-as-null-2126

there was an issue for that: https://github.com/webiny/webiny-js/issues/1860

**Comment by snstanton** [comment]
Ok, I've reviewed the fix in 1.21 and I can confirm that the admin app is no longer sending 'null' for the value, but it is also not sending the value that is displayed in the UI.  It's using the current time rather than midnight of the current date in +0100 timezone.  This is surprising as well.   I think the value should be defaulted before loading into the form rather than on the way out so the visible time matches the value that is saved.
