### ISSUE TITLE
Issue with cursor in request

### ISSUE THREAD

**Issue by YaD13** [webiny/webiny-js#2182]
### Version

5.17.2

### Operating System

Windows

### Browser

Chrome

### What steps will reproduce the bug?

You should have enough items to use cursor 7-13 times with limit 2, 8 or 10 (it were my parameters). After random number of requests with cursor, data became empty. In my case I had 130 items and used limit 8. On the eighth request data in response was empty. The order in sets of data is different from got data by one request.

### What is the expected behavior?

cursor allows to divide data into sets, get all items and save order

**Comment by brunozoric** [comment]
Hi @YaD13 
I added a PR which tests a bit more complex paginations. There are 200 records in the database that tests are running on.
Could not find any error with the cursor. Maybe there was some bug in the version which you are using, but it has been fixed. Next step for you would be to upgrade the system to latest version and check the pagination.
Read more in the PR: https://github.com/webiny/webiny-js/pull/2208
