### ISSUE TITLE
Admin app AddLogo plugin should also apply the logo to the login page

### ISSUE THREAD

**Issue by jimjoes** [webiny/webiny-js#2186]
### Is your feature request related to a problem? Please describe.

The logo component provided to the AddLogo component only allows the authenticated UI to be branded, not the unauthenticated login page.

### Describe the solution you'd like.

The logo component provided to AddLogo component should be passed to the Login UI as well as the app bar.

### Describe alternatives you've considered.

At the moment, the only way I can see to just change the logo is to rebuild or copy the entire login UI, which seems excessive, given the process of branding the app bar is so trivial.

**Comment by Pavel910** [comment]
Ah thanks, missed that one! Will do my best to get this into 5.22.! 🍻
