### ISSUE TITLE
Headless CMS: The graphql schema type for a field with predefined values should be created as an enum

### ISSUE THREAD

**Issue by jimjoes** [webiny/webiny-js#2191]
### Is your feature request related to a problem? Please describe.

Currently, if a field is defined in the the CMS as: 

```
            {
                id: "type",
                fieldId: "type",
                type: "text",
                label: "Organisation Type",
                helpText: "The organisation type",
                predefinedValues: {
                    enabled: true,
                    values: [
                        { value: "supplier", label: "Supplier" },
                        { value: "client", label: "Client" }
                    ]
                },
                renderer: { name: "radio-buttons" },
                validation: [
                    {
                        name: "required",
                        message: "Value is required."
                    }
                ]
            },
```

then the field is typed in the graphql as string. 

### Describe the solution you'd like.

It would be great if the CMS could generate an enum for the allowed values and use that as the scalar for the field.

**Comment by brunozoric** [comment]
Hi @econtentmaps 
I think this is impossible.
Let's saye wou want to have predefined values:
```
[
    {
        value: "webiny",
        label: "Webiny"
    },
    {
        value: "feature-request",
        label: "Feature Request"
    },
    {
        value: "something that cannot be enum",
        label: "As value says"
    },
    {
        value: "あり",
        label: "Japanese characters"
    }
]
```

How would `feature-request` and `something that cannot be enum` be used? And the japanese characters `あり`? Those values are not allowed.
And I think we should not limit what people can put in the predefined values, if you have an idea to allow only alphanumeric characters :)

**Comment by jimjoes** [comment]
Ah - That’s me, Anglo-centric :)

That being said, as it’s a Graphql api, I wouldn’t consider it unreasonable to validate the value field to an enum-able type for the purposes of standards compliance, particularly as generating enums will aid discoverability and improve DX of the API.

Of course, the label is already there for the UX which is where those utf8 characters would go? Or have I missed something.

In any case, not a blocker for me, just an idea.

**Comment by brunozoric** [comment]
There is no problem with the label property, but with the value that would be converted to enum. Let's leave this idea to cook a bit and we can get back to it later.
