### ISSUE TITLE
DynamoDb only: admin app not working when deploying prod env

### ISSUE THREAD

**Issue by jcode-hub** [webiny/webiny-js#2199]
### Version

5.21.0

### What steps will reproduce the bug?

`npx create-webiny-project myproject`
`yarn webiny deploy --env prod`

### What is the expected behavior?

when opening the CloudFront distribution URL for the admin app the initial installation wizard should load

### What do you see instead?

the page is stuck at "checking apps"
![image](https://user-images.githubusercontent.com/63285938/149736938-4f579ba5-b8e9-4013-8a65-5a058b99be15.png)

### Additional information

there seems to be a problem with the connection to graphql

**Comment by adrians5j** [comment]
Hey @jcode-hub, can you double check what's going on in CloudWatch?

Any errors reported there maybe?

**Comment by jcode-hub** [comment]
Hey @doitadrian,
I have 4 Lambda CloudWatch log groups related to webiny. These are

*  ps-queue-add
* graphql
* update-settings
* ps-queue-process

none of these is throwing errors. The last runtime of them was right after I made the deployment (except for ps-queue-process which is triggered every 5 minutes). My guess would be that the request never made it to the lambda functions. Since the dev env deployment works fine and the lambdas are deployed in a vpc for prod maybe there is something up with the vpc configuration? 

It's a fresh webiny installation, you should be able to reproduce the issue. If not please let me know. Maybe there is something up with the region (my deployment is in eu-central-1)

**Comment by brunozoric** [comment]
Found a bug in production pulumi files. Upgrade thats comming with 5.22.0. will resolve the issue.
Commit: https://github.com/webiny/webiny-js/commit/320efdf4745fd46a1c442e554585e60179bce937
