### ISSUE TITLE
Can't add hyphens to page paths

### ISSUE THREAD

**Issue by plsalvado** [webiny/webiny-js#2224]
### Version

5.22.1

### Operating System

MacOS 12.1

### Browser

Safari 15.2

### What steps will reproduce the bug?

1. Open any page in Page Builder - or create a new one if one doesn't exist
2. Go to the Settings page
3. Try to change the path of that page

### What is the expected behavior?

It should be possible to add hyphens to the path. Actually the help text underneath is clear that hyphens are supported.
<img width="739" alt="Screenshot 2022-02-04 at 14 24 51" src="https://user-images.githubusercontent.com/8825508/152545431-3f09fdf0-fade-4351-93fa-563478505b25.png">

### What do you see instead?

You can't type hyphens. The system is rejecting the character as it being an invalid character.
Note: if you paste an hyphen the box will accept it!

**Comment by SvenAlHamad** [comment]
Reopening this one as it's still occurring in 5.24
