### ISSUE TITLE
File manager, references should not all have to be language specific

### ISSUE THREAD

**Issue by larissa-n** [webiny/webiny-js#2233]
### Is your feature request related to a problem? Please describe.

Images are often re-used across languages. There is no reason to force users to re-upload identical media to all different file managers for each language. At least there should be an option to reference the same files.

Yet, as it stands, both files and references are language-specific, cross-referencing is not possible.

### Describe the solution you'd like.

The option to show media from any language when selecting files.
Long-term, maybe a language-agnostic media directory that's accessible from model entries in any language.

### Describe alternatives you've considered.

To avoid duplicating images for each additional language, you would have to manage media outside of webiny and not use the file manager at all. Manually add the url, no preview. Having the option to use language-agnostic media inside webiny would be much preferred.

Another workaround is to edit different languages in parallel such that your browser remembers your primary language as selected while you're editing the foreign language content (I think webiny uses cookies for active language, so if you have multiple tabs open for different languages, they tend to interfere, but in this case it's more like a feature, just a little tricky to manage.)

**Comment by Pavel910** [comment]
Thanks @larissa-n, it makes sense. Btw. we don't use cookies, but local storage, but the end results is the same: you can't open 2 tabs with different languages :( We'll think about this problem, as we do have some planning going on related to multi-language content.

**Comment by larissa-n** [comment]
Any updates yet on something like a language-agnostic media directory? Thanks, @Pavel910!

**Comment by Pavel910** [comment]
@larissa-n no news here, right now it's not even being considered due to a big list of higher priorities.
