### ISSUE TITLE
Install node modules fails on arm architecture

### ISSUE THREAD

**Issue by BenjaminButon** [webiny/webiny-js#2263]
### Version

5.24.0

### Operating System

MacOS on Apple Silicon

### Browser

Not a browser issue

### What steps will reproduce the bug?

Install node modules. It fails due to `puppeteer` can't be build on arm architecture

### What is the expected behavior?

Node modules are installed successfully.

### What do you see instead?

Node module installation fails

### Additional information

Puppeteer npm package can't be built on arm architecture.
![image](https://user-images.githubusercontent.com/28841511/157433079-9fa6b35a-a602-4805-98ac-212f183921b9.png)

### Possible solution

There is an option to install packages using Rosetta2. To do so you can follow [this instruction](https://www.courier.com/blog/tips-and-tricks-to-setup-your-apple-m1-for-development/). But I think it's not the best solution because I'm sure a lot of people use the cmd line from IDE, for example, where you can't run it using Rosetta.

**Comment by endymion1818** [comment]
Hi! Thanks for submitting this issue ... could you give us a bit more information here ... I have successfully installed node modules a few times successfully on an M1 Mac, so I'm wondering if there's something else going on here.

**Comment by BenjaminButon** [comment]
@endymion1818 See this thread for more information https://webiny-community.slack.com/archives/C014Y0HGJ0Y/p1646675978020979

**Comment by timruppert** [comment]
> Hi! Thanks for submitting this issue ... could you give us a bit more information here ... I have successfully installed node modules a few times successfully on an M1 Mac, so I'm wondering if there's something else going on here.

Have you done it on 5.24.0?  It does not appear before this.

**Comment by endymion1818** [comment]
```
➜  blog-for-frontend-starter-kits git:(master) yarn webiny --version
5.24.0
```
![Screen Shot 2022-03-09 at 13 10 01](https://user-images.githubusercontent.com/2216344/157448080-1bff3946-c23c-4143-a863-492df74aa52b.png)

**Comment by endymion1818** [comment]
I have, but I believe its because I installed it whilst in a terminal running Rosetta

```
➜  ~ node -v
v14.19.0
➜  ~ node       
Welcome to Node.js v14.19.0.
Type ".help" for more information.
> require("process").arch
'x64'
```

Otherwise if you see `arm64` when you enter `require("process").arch` into the node repl you aren't running Rosetta. 

Here's how to open a terminal in Rosetta once its installed if it helps:

<img width="890" alt="Screenshot_2021-06-11_at_12 07 42_PM" src="https://user-images.githubusercontent.com/2216344/157456465-e224c71d-f4c9-49b7-bf43-2db62fab6fd3.png">

If you do that and then install the Node binary we believe you should be able to install dependencies.. I'm afraid the other solution is a lot more complex because we're not sure which dependency of puppeteer would need to be updated in order to work natively.

**Comment by timruppert** [comment]
> I have, but I believe its because I installed it whilst in a terminal running Rosetta
> 
> ```
> ➜  ~ node -v
> v14.19.0
> ➜  ~ node       
> Welcome to Node.js v14.19.0.
> Type ".help" for more information.
> > require("process").arch
> 'x64'
> ```
> 
> Otherwise if you see `arm64` when you enter `require("process").arch` into the node repl you aren't running Rosetta.
> 
> Here's how to open a terminal in Rosetta once its installed if it helps:
> 
> <img alt="Screenshot_2021-06-11_at_12 07 42_PM" width="890" src="https://user-images.githubusercontent.com/2216344/157456465-e224c71d-f4c9-49b7-bf43-2db62fab6fd3.png">
> 
> If you do that and then install the Node binary we believe you should be able to install dependencies.. I'm afraid the other solution is a lot more complex because we're not sure which dependency of puppeteer would need to be updated in order to work natively.

Thanks [endymion1818](https://github.com/endymion1818).  [Ostap](https://github.com/BenjaminButon) - let's discuss whether this can get you past this or it will have other ramifications elsewhere.

**Comment by blimmer** [comment]
Another option is to override Puppeteer's setup behavior as described in this [Slack Overflow answer](https://stackoverflow.com/a/66044814/808678).

1. Install chromium via homebrew: `brew install chromium`
2. Set the following environment variables in your shell config (e.g., `.zshrc` or` `.bashrc`)
```
export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
export PUPPETEER_EXECUTABLE_PATH=`which chromium`
```

Now the install should pass.

**Comment by Pavel910** [comment]
Instead of assigning ENV variables, I found a better way, using `puppeteer-core` package, which by definition doesn't download binaries. That's exactly what we need, since we don't even need those binaries locally.

**Comment by timruppert** [comment]
@BenjaminButon take a look at this and let's see if this gets you past it.
