### ISSUE TITLE
Page Builder - Text alignment in Heading element 

### ISSUE THREAD

**Issue by mislavstreicher** [webiny/webiny-js#2284]
### Version

5.24.0

### What steps will reproduce the bug?

In Page Builder:
- Add  a Heading element to your page and add some text to it
- Under STYLE formatting, try different text alignment options - all works as it should
- Enter PREVIEW mode, the text will always be centered. No matter what text alignment option you've selected in editor. 

Editor:
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/69899302/159744960-600e2f21-6843-46e8-a7f8-83a62ef69dd6.png">

Preview:
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/69899302/159745088-ba30bdcf-b268-47f0-9a2b-d57ebd04daf7.png">

**Comment by monikawebiny** [comment]
This is now working in v5.30

**Comment by m0nikaza** [comment]
![image](https://user-images.githubusercontent.com/106819205/181486495-84e093c0-3102-47b5-ade5-42db75fc6e50.png) This is now working in v5.30
