### ISSUE TITLE
Is "public-read" ACL for S3 objects justified?

### ISSUE THREAD

**Issue by o7g8** [webiny/webiny-js#2290]
### Version

5.24.0

### Operating System

Mac Os X

### Browser

Chrome

### What steps will reproduce the bug?

Deploy webiny `yarn webiny deploy` in an account with blocked public access to S3 objects.

### What is the expected behavior?

It should be possible to deploy webiny in accounts where public access to S3 objects is blocked.

### What do you see instead?

The deployment fails with S3 access error.

### Additional information

See also #1517 
It's quite common security control in many organizations to prohibit public S3 objects.
Therefore I wonder if the webiny's code can be changed to respect the "Block all public access" S3 setting?

**Comment by Pavel910** [comment]
@o7g8 same answer as here: #2387. We'll get to making it the default soon. We're doing some upgrades on Pulumi config setup, and once it's done we'll look into making buckets private. Thanks for opening an issue!
