### ISSUE TITLE
Checkboxes refresh the page removing every value in other fields.

### ISSUE THREAD

**Issue by sunnythelucky** [webiny/webiny-js#2306]
### Version

5.24.0

### Operating System

mac OS

### Browser

Chrome

### What steps will reproduce the bug?

When I click one of the values and publish it, it refreshes all the other values in other fields. The field looks like this. 

```
{
        id: "id",
        fieldId: "fieldId",
        label: "label",
        helpText: "helpText",
        multipleValues: true,
        type: "text",
        predefinedValues: {
            enabled: true,
            values: [
                { value: "1", label: "1" },
                { value: "2", label: "2" },
                { value: "3", label: "3" },
                { value: "4", label: "4" },
                { value: "5", label: "5" }
            ]
        },
        renderer: {
            name: "checkboxes"
        }
    },
```

### What is the expected behavior?

It doesn't refresh the form and keep all the values when I publish the asset.

### Additional information

I have found a solution to keep it from refreshing by adding defaultValue to settings. But I don't know if that's the best way.

**Comment by Pavel910** [comment]
@sunnythelucky it's not very clear what exactly you're doing, so please provide the following information:
- is this a content model created via UI, or via a plugin (code)
- if it's a model via plugin, please post the exact source code for us to inspect
- some screenshots or a short video demonstrating steps to reproduce and the problem itself, so we can clearly see how you encountered it

Thanks!

**Comment by sunnythelucky** [comment]
- it is a content model created via plugin
- this is the exact source code I have for the field

## Click the value and add a value to a title
![Screenshot 2022-03-31 at 09 43 05](https://user-images.githubusercontent.com/40551978/161069624-28ecb995-3486-4ab2-a9d4-fe8d6259b40b.png)
![Screenshot 2022-03-31 at 09 43 14](https://user-images.githubusercontent.com/40551978/161069623-7e6fb889-60a6-4b72-9e5b-41ab1b38af29.png)
## Submit
![Screenshot 2022-03-31 at 09 43 19](https://user-images.githubusercontent.com/40551978/161069621-3e777a70-f576-4966-a31e-0451962a9fa4.png)
## As other values are required, it refreshes all the values without saving the value already put earlier
![Screenshot 2022-03-31 at 09 43 26](https://user-images.githubusercontent.com/40551978/161069617-927fb8fc-465b-44ff-9000-944d6a168de9.png)

**Comment by Pavel910** [comment]
@sunnythelucky I'm confused, so let me explain:
In Webiny, you can create content models via the UI, using the visual editor, OR, you can create a plugin via code, which defines the content model. Which approach did you use?

If you used the plugin approach, can you share the source code?

**Comment by sunnythelucky** [comment]
I have created a plugin via code to make content models. It resides in `api/code/headlessCMS/src/plugins/models/projects`

**Comment by sunnythelucky** [comment]
`base.ts` has this code inside

```
export const baseFields= [{
        id: "id",
        fieldId: "fieldId",
        label: "label",
        helpText: "helpText",
        multipleValues: true,
        type: "text",
        predefinedValues: {
            enabled: true,
            values: [
                { value: "1", label: "1" },
                { value: "2", label: "2" },
                { value: "3", label: "3" },
                { value: "4", label: "4" },
                { value: "5", label: "5" }
            ]
        },
        renderer: {
            name: "checkboxes"
        }
    },
];

export const baseActivityLayout = [["fieldId"]]
```

**Comment by Pavel910** [comment]
Ok thanks, we'll have to try this code to see if we can replicate the issue.

**Comment by sunnythelucky** [comment]
Thank you so much @Pavel910 Let me know when more info is needed from my side!
