### ISSUE TITLE
Edit theme css without deploying

### ISSUE THREAD

**Issue by japomani** [webiny/webiny-js#2308]
### Is your feature request related to a problem? Please describe.

Not a technical problem, just web-development is several hundred times slower in Webiny than in other platforms. Most other platforms have similar tools like page builder, but in most other platforms I can edit the theme in the UI. 

### Describe the solution you'd like.

I wish there was a way to update theme css without deploying, most creators will be coming from a script environment where a simple save of a file and a page refresh will show what changes were made. I have to make a change, wait 3-5 min while it deploys, see that what I made was ugly, then try again. It is VERY slow to develop a theme in

### Describe alternatives you've considered.

Other CMS platforms

**Comment by Pavel910** [comment]
@japomani you don't have to redeploy React apps while developing. API is what needs to be redeployed if changed, but React apps work perfectly fine on localhost: https://www.webiny.com/docs/core-development-concepts/basics/watch-command#watching-project-applications

The commands you're looking for are: 

`yarn webiny watch apps/admin --env dev` for Admin app
`yarn webiny watch apps/website --env dev` for Website app

These start the traditional webpack dev server and it's basically localhost development.

And btw. we _are_ planning to move the theme to the database/UI, so it will no longer be code based in the near future. However, we don't have an exact timeline on it, since there's a lot going on product wise, and this is not the most urgent thing.

**Comment by japomani** [comment]
Thanks Pavel, however, this is not a solution I can hand to my marketing guy to tweak our theme design. I think I am simply the wrong audience for this tool. I need something that fits into my business processes. We are looking for a quick and simple tool for making marketing landing pages. Page builder requires too much backend coding to customize. My feature request is to move the most common theme adjustments to the front end where someone with basic html, css, and js skills could work collaboratively in the cloud and not need to set up a dev environment.

I understand if this is not the direction you want to take page builder, I just like what you guys are doing and was hoping to use it instead of one of the many other page builder tools out there like google sites, system.io, wix, square space, etc.

**Comment by Pavel910** [comment]
@japomani yes you're right, we don't strive to be Wix/Squarespace. Different audience :)
Still, thanks for the feedback, we appreciate your time and will keep this in mind for future improvements.

**Comment by japomani** [comment]
I'm curious who you think your audience is? A simple page builder is not that useful for a power user, and a page builder that is too simple is not that useful for non-technical user.

It seems like for your page builder to be useful, you need a power user paired with a non-technical user. Someone who can customize your page builder so that it can be useful for a non-technical user.

It seems to me you will need to strike the right balance of simple/power.

**Comment by Pavel910** [comment]
> It seems like for your page builder to be useful, you need a power user paired with a non-technical user. Someone who can customize your page builder so that it can be useful for a non-technical user.

Exactly that. The majority of Webiny users have developers preparing the system for their content-writers/marketers, so once the theme is configured, elements created, etc., content writers just use that. If you look at our community, there are many web-design agencies, who prepare systems for the end-user. We have clients with entire teams of developers developing custom Page Builder plugins based on corporate standards, so content writers just write content using those predefined elements.
