### ISSUE TITLE
resize layout cells

### ISSUE THREAD

**Issue by japomani** [webiny/webiny-js#2310]
### Describe the solution you'd like.

I wish I could resize the 2 and 3 cell layout options so the cells were a size that better fit my design. In other platforms this is done by putting a handle on the border between cells and sliding back and forth.

**Comment by Pavel910** [comment]
@japomani Arbitrary cell resizing is how it used to be, but it didn't work well for responsiveness and was extremely clunky. So we switched it to these fixed presets, so it's a lot more robust from the responsive design standpoint. Unfortunately, this isn't something we'll be changing any time soon.
