### ISSUE TITLE
Allow a custom color swatch pallet

### ISSUE THREAD

**Issue by japomani** [webiny/webiny-js#2312]
### Describe the solution you'd like.

two primary colors is not enough, I have 5 accent colors. Let me create the color swatch through the UI, not with code

### Describe alternatives you've considered.

Looks like I'll have to dig into the code a lot to make this change, and it will probably get broken when I update to a newer version

**Comment by Pavel910** [comment]
@japomani you can add as many colors as you want in the theme: https://github.com/webiny/webiny-js/blob/next/apps/theme/pageBuilder/index.ts#L10-L14

Just add more key/value pairs to define your colors, and change the existing once if necessary.

https://www.webiny.com/docs/page-builder/theming/introduction

**Comment by japomani** [comment]
I did change those but my new colors did not show up in the color picker

$webiny-pb-theme-primary: #ed008c !default;
$webiny-pb-theme-secondary: #00adef !default;
$webiny-pb-theme-background: #eaecec !default;
$webiny-pb-theme-surface: #424242 !default;
$webiny-pb-theme-on-primary: #ffffff !default;
$webiny-pb-theme-on-secondary: #ffffff !default;
$webiny-pb-theme-on-surface: #000000 !default;
$webiny-pb-theme-on-background: #131313 !default;
$webiny-pb-theme-text-primary: #424242 !default;
$webiny-pb-theme-text-secondary: #424242 !default;
$webiny-pb-theme-color-border: #424242 !default;
$webiny-pb-theme-accent-green: #00a652 !default;
$webiny-pb-theme-accent-pink: #ed008c !default;
$webiny-pb-theme-accent-blue: #00adef !default;
$webiny-pb-theme-accent-yellow: #fef200 !default;
$webiny-pb-theme-accent-purple: #2e3192 !default;
$webiny-pb-theme-accent-lightyellow: #fffccc !default;
$webiny-pb-theme-accent-lightgreen: #e6f6ee !default;

Also, any solution that requires me to edit the backend files won't work for me, I need a quick and easy solution

**Comment by Pavel910** [comment]
Then Webiny is not a good fit for you :) There's nothing we can do about it right now.

What you changed are SASS variables, which are meaningless unless you define CSS variables for them and map them to the theme, which I linked in the previous comment.
