### ISSUE TITLE
Installing Theme Manager not working

### ISSUE THREAD

**Issue by TripleA-rocks** [webiny/webiny-js#2325]
### Version

5.25.0

### Operating System

MacOS Monterey 12.2.1

### Browser

Chrome

### What steps will reproduce the bug?

1. Install webiny according to the documentation ->  https://www.webiny.com/docs/get-started/install-webiny
2. Install Multi-Tenancy according to the documentation -> https://www.webiny.com/docs/enterprise/multi-tenancy
3. Install Theme-Manager according to the documentation -> https://www.webiny.com/docs/enterprise/theme-manager

### What is the expected behavior?

The expected behaviour is to be able to install Theme-Manager

### What do you see instead?

The api deploy works
But I get errors while deploying apps/admin and apps/website

<code> export 'ThemeSource' (reexported as 'ThemeSource') was not found in './types' (module has no exports) </code>

### Additional information

I'm using M1 processor, if it helps

Futher more while trying to get more information I identified the file throwing the error.

yarn  webiny watch apps/admin --env=dev
Watching admin package...
ℹ Compiling Code
Starting the development server...
✔ Code: Compiled with some errors in 18.63s
Failed to compile.
export 'ThemeSource' (reexported as 'ThemeSource') was not found in './types' (module has no exports)
ERROR in ./node_modules/@webiny/app-theme-manager/index.js 3:0-38
export 'ThemeSource' (reexported as 'ThemeSource') was not found in './types' (module has no exports)
webpack compiled with 1 error
No issues found.
ℹ Compiling Code
✔ Code: Compiled with some errors in 4.19s
Failed to compile.
export 'ThemeSource' (reexported as 'ThemeSource') was not found in './types' (module has no exports)
ERROR in ./node_modules/@webiny/app-theme-manager/index.js 3:0-38
export 'ThemeSource' (reexported as 'ThemeSource') was not found in './types' (module has no exports)
webpack compiled with 1 error

**Comment by Pavel910** [comment]
@TripleA-rocks thanks for reporting, will look into it and get back to you.

**Comment by Pavel910** [comment]
@TripleA-rocks I was able to reproduce this, it's a type error that was introduced in 5.25.0 (that release contained a lot of TS  changes and upgrades), and it will be fixed in 5.26.0 (release planned some time next week). Once again, thanks for reporting! 🍻

**Comment by TripleA-rocks** [comment]
Hi @Pavel910 that is awesome news. Thank you for your work. Glad to be a part of the community. Cheers 🍻!
