### ISSUE TITLE
[pageBuilder] Max width of grid elements is hard coded

### ISSUE THREAD

**Issue by endymion1818** [webiny/webiny-js#2336]
### Is your feature request related to a problem? Please describe.

In a recent support thread a user wanted to change the width of the `<Grid/>` element and found it was not possible to do so easily.

### Describe the solution you'd like.

I think this should be a new setting where the user can override the default and have more control over the overall width of grid elements:

![image](https://user-images.githubusercontent.com/2216344/164034516-86d80dfd-be56-431a-be16-9824a51a73ce.png)
.

### Describe alternatives you've considered.

Users can still override the default width by modifying this line https://github.com/webiny/webiny-js/blob/12ce090c6576aaa7bf4af7ef0cfb73e617a9cde4/packages/app-page-builder/src/editor/plugins/elements/grid/index.tsx#L92

**Comment by Pavel910** [comment]
Shouldn't the grid always be 100% wide? A grid container always fills the available space. It doesn't make sense to make the grid width configurable 🤔

**Comment by jimjoes** [comment]
Well at the moment, you can specify a px width or a %. Currently the default is 1100px. My requirement is to have a way to configure the max width of the content on a pagebuilder page to 800 and 1024 on two different projects. I think the grid should be able to have a relative % width, definitely, but I'm less convinced by px/rem (although I can see the case). If I could easily configure a max-width for the pagebuilder container, then my requirement is satisfied. I guess I could add a container in the react app, but the preview in the admin app wouldn't be aware of that, so not sure how to achieve my goal *natively*

**Comment by endymion1818** [comment]
Thanks for your input @jimjoes, this is possible but not with the grid element — you can set it with the block element which wraps the grid, and then set the grid to 100% width:

![Setting 100% width with the block element](https://user-images.githubusercontent.com/2216344/165066614-b21c06f8-352e-4368-8a21-49d6175b0d49.png) 

You might have to mess with the margins of the grid element, and the padding of the block a bit to get the effect you want.

Let us know how you get on :-D
