### ISSUE TITLE
Apollo progress bar

### ISSUE THREAD

**Issue by Pavel910** [webiny/webiny-js#235]
Something along these lines:
```
import nprogress from "nprogress";

const createProgressLink = () => {
    let runningOperations = 0;
    return new ApolloLink((operation, forward) => {
        runningOperations++;
        const observable = forward(operation);
        nprogress.start();
        return new Observable(observer => {
            const subscription = observable.subscribe({
                next: data => {
                    runningOperations--;
                    if (runningOperations < 1) {
                        nprogress.stop();
                    }
                    return observer.next.bind(observer)(data);
                },
                error: observer.error.bind(observer),
                complete: observer.complete.bind(observer)
            });

            return () => {
                subscription.unsubscribe();
            };
        });
    });
};
```

## Problems
- styling the progress bar depending on the context (empty Login view and AdminLayout)?
- `nprogress` is a singleton with global styles - not too happy about that
- ideally it should be a component that receives a network status via props and shows/hides the loader

**Comment by Pavel910** [comment]
https://material.io/design/components/progress-indicators.html#linear-progress-indicators

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
