### ISSUE TITLE
Visual issues on pages list

### ISSUE THREAD

**Issue by Pavel910** [Webiny/webiny-js#236]
1) When navigation is opened - button appears on top of the overlay

![image](https://user-images.githubusercontent.com/3920893/47197012-f32f8180-d363-11e8-870a-fac71df2e4a7.png)

2) When creating a new page, modal dialog appears below the page content

![image](https://user-images.githubusercontent.com/3920893/47197085-44d80c00-d364-11e8-8649-cba45d3269ee.png)

**Comment by Pavel910** [comment]
![image](https://user-images.githubusercontent.com/3920893/47200184-57a70c80-d375-11e8-98f0-9ca4ea15ad1f.png)

**Comment by Pavel910** [comment]
Revision selector in the editor bar:
![image](https://user-images.githubusercontent.com/3920893/47200214-79a08f00-d375-11e8-9ae3-a99a334c715f.png)

**Comment by SvenAlHamad** [comment]
First two issues are sorted. 
Issue 3 will be sorted with the switch to {version}, instead of {name}.
Issue 4 is pending the document root element so we can pass on the theme body layout.
@Pavel910

**Comment by SvenAlHamad** [comment]
Need also to style this message:
![image](https://user-images.githubusercontent.com/3808420/47267287-9eddfa80-d539-11e8-95f6-1aae005c0798.png)

**Comment by SvenAlHamad** [comment]
Need to improve the visuals on the page revisions list:
![image](https://user-images.githubusercontent.com/3808420/47267457-fbdab000-d53b-11e8-9990-6350319cf082.png)

**Comment by SvenAlHamad** [comment]
In terms of the `document` holder, these are the references:
editor => `packages/webiny-app-cms/src/editor/plugins/elements/document/Document.js:7`
render => `packages/webiny-app-cms/src/render/plugins/elements/document/Document.js:10`
