### ISSUE TITLE
Unable to preview/render pages from different locale

### ISSUE THREAD

**Issue by swapnilmmane** [webiny/webiny-js#2363]
### Version

5.25.0

### Operating System

macOS

### Browser

Firefox

### What steps will reproduce the bug?

I have added a new locale and created a page for this new locale. While previewing(or viewing) this locale-specific page, getting the following error on the browser's console.  

```
TypeError: e.pageBuilder.getPublicMenu.data is null
    lt https://d1n36r2lhtbutt.cloudfront.net/static/js/main.26a2caaa.js:1
    lt https://d1n36r2lhtbutt.cloudfront.net/static/js/main.26a2caaa.js:1
    Jo https://d1n36r2lhtbutt.cloudfront.net/static/js/65.dcf5d609.js:2
    Eu https://d1n36r2lhtbutt.cloudfront.net/static/js/65.dcf5d609.js:2
    ms https://d1n36r2lhtbutt.cloudfront.net/static/js/65.dcf5d609.js:2
    vs https://d1n36r2lhtbutt.cloudfront.net/static/js/65.dcf5d609.js:2
    us https://d1n36r2lhtbutt.cloudfront.net/static/js/65.dcf5d609.js:2
    rs https://d1n36r2lhtbutt.cloudfront.net/static/js/65.dcf5d609.js:2
    Qs https://d1n36r2lhtbutt.cloudfront.net/static/js/65.dcf5d609.js:2
    Ks https://d1n36r2lhtbutt.cloudfront.net/static/js/65.dcf5d609.js:2
    cs https://d1n36r2lhtbutt.cloudfront.net/static/js/65.dcf5d609.js:2
    Ks https://d1n36r2lhtbutt.cloudfront.net/static/js/65.dcf5d609.js:2
    hydrate https://d1n36r2lhtbutt.cloudfront.net/static/js/65.dcf5d609.js:2
    86952 https://d1n36r2lhtbutt.cloudfront.net/static/js/main.26a2caaa.js:1
    t https://d1n36r2lhtbutt.cloudfront.net/locale/:1
    <anonymous> https://d1n36r2lhtbutt.cloudfront.net/static/js/main.26a2caaa.js:1
    O https://d1n36r2lhtbutt.cloudfront.net/locale/:1
    <anonymous> https://d1n36r2lhtbutt.cloudfront.net/static/js/main.26a2caaa.js:1
    r https://d1n36r2lhtbutt.cloudfront.net/locale/:1
    <anonymous> https://d1n36r2lhtbutt.cloudfront.net/static/js/main.26a2caaa.js:1
65.dcf5d609.js:2:662622
```

### Here are the steps to reproduce the error (considering we already have one default locale `en-US`): 

1. Create a new locale `hi-IN` from the Admin app. 

2. Create a static page category.
![category](https://user-images.githubusercontent.com/7145848/165891221-8c296f58-e439-42d4-87bd-0f20b854ab94.png)

3. Create 'About Us' with the URL `about-us`  page in the `hi-IN` local.

4. Preview this page from the editor, you will see the page content for a moment, and then it will show the blank white screen. We get the error mentioned above on the browser's console. 

P.S. Looking at the error, I tried creating a menu for this new locale, but this also doesn't fix this error.

### What is the expected behavior?

The page should be rendered properly. 

### What do you see instead?

On previewing the page from the editor, see the page content for a moment, and then it shows the blank white screen. We get the error mentioned above on the browser's console.

**Comment by SvenAlHamad** [comment]
The underlying issue is explained in #2979. Once that one is fixed, this one will be automatically resolved.

**Comment by Pavel910** [comment]
@SvenAlHamad `2979` doesn't exist. Please post the correct link, thanks.
