### ISSUE TITLE
[Headless CMS] Make filter by status work on the API side

### ISSUE THREAD

**Issue by Pavel910** [webiny/webiny-js#2371]
### Is your feature request related to a problem? Please describe.
The filter by `status` shown in the screenshot below works on the client side.

![image](https://user-images.githubusercontent.com/3920893/166439433-06179d75-e4c0-468b-9b86-2d17fca40317.png)

### Describe the solution you'd like.
When filtering by status, it would be a lot more correct to let the API do the filtering. Currently there's no input for `status` on the GraphQL Schema.

**Comment by deepansh946** [comment]
@Pavel910 Can I work on this issue?

**Comment by Pavel910** [comment]
@deepansh946 this view has been rewritten last year, and now looks like this (see screenshot), and all the filtering functionality was rebuilt, so we can close this issue. Thanks for jumping in!

![CleanShot 2024-03-01 at 09 58 47](https://github.com/webiny/webiny-js/assets/3920893/df127d65-7fc7-4839-b515-c53da7882461)
