### ISSUE TITLE
Use CloudFront Origin Access Identity to make S3  buckets private

### ISSUE THREAD

**Issue by blimmer** [webiny/webiny-js#2387]
### Is your feature request related to a problem? Please describe.

Currently, the `app` and `admin` buckets are set to have `public-read` ACLs. Many organizations enforce that all S3 buckets must be marked as private for compliance reasons. Their content can still be served via CloudFront.

### Describe the solution you'd like.

Because the app and admin console are served via CloudFront, I think we could use an Origin Access Identity to make the buckets private, and require them to be served via CloudFront.

**Comment by Pavel910** [comment]
This is on our TODO list for the near future, and you could basically tweak the Pulumi config yourself within your project, but we do want to make this a default setup. Thanks for taking the time to report this!
