### ISSUE TITLE
Page Builder - Element tree doesn't display the full path

### ISSUE THREAD

**Issue by SvenAlHamad** [webiny/webiny-js#2397]
### Version

5.26

### Operating System

iOS

### Browser

Safari

### What steps will reproduce the bug?

Add a block and a grid into the page builder editor. Select the cell in the editor.

### What is the expected behavior?

The element tree at the bottom of the page should say Block > Grid > Cell.

### What do you see instead?

Instead, it currently displays just "Cell".

<img width="1172" alt="image" src="https://user-images.githubusercontent.com/3808420/168076248-a98bb4c6-a54b-4566-ae9e-c4ad475d685e.png">

**Comment by jimjoes** [comment]
+1!

**Comment by Pavel910** [comment]
Ran in to this myself, did a bit of digging, and this is only happening on new empty blocks. Once you add content to them, or even simply reload the editor, they do show the correct breadcrumbs 🤔 

https://user-images.githubusercontent.com/3920893/174140086-5ef17e50-e5ce-4171-bfa9-6b11983ade10.mp4

**Comment by Pavel910** [comment]
@monikawebiny this is resolved. Closing.
