### ISSUE TITLE
Can't add hyphen in page URL's

### ISSUE THREAD

**Issue by websuits** [webiny/webiny-js#2407]
### Version

2.25

### Operating System

OSX

### Browser

Chrome

### What steps will reproduce the bug?

Create new page, try to change page url to something-like-that. Can't add hyphen, nothing adds when you type it.

### What is the expected behavior?

Add the hyphen

### What do you see instead?

Nothing

**Comment by winglunlam** [comment]
@websuits 
From my past experience, you can add hyphen like that:

1.  change page url to somethinglikethat
2. move cusor to the place that you want to add hyphen and then add hyphen there, like this: something-likethat

Hope this can help you.

**Comment by Pavel910** [comment]
This bug was fixed twice already and it somehow keeps resurfacing 🤔🤯

Will doublecheck this, thanks for reporting.

**Comment by Pavel910** [comment]
@wllam44 @websuits I just checked this on 5.26. and that bug is not present there. I know we fixed it in the past, just not sure which version exactly. Please upgrade to 5.26. to get rid of that bug. Thanks for bringing this up 👍
