### ISSUE TITLE
Admin app login screen active for a split second after successful login

### ISSUE THREAD

**Issue by plsalvado** [webiny/webiny-js#2409]
### Version

5.23.1

### Operating System

macOS

### Browser

Safari

### What steps will reproduce the bug?

Log out of the Admin app and try to log back in.

### What is the expected behavior?

After the user logs in successfully with valid credentials, the app should redirect the user immediately to the Admin App. The form should be enabled for further input after the user has been authenticated successfully.

### What do you see instead?

While the credentials are being validated server-side, the Login button and the rest of the form are disabled from further input. This is all ok and what's expected.

But once the response comes back and the user has been authenticated successfully, you'll see the form being re-enabled again for a split second, before it redirects the user to the Admin App. 

https://user-images.githubusercontent.com/8825508/169003621-0963757d-0006-435c-8f60-31a769ad3007.mov

**Comment by Pavel910** [comment]
@monikawebiny this is resolved as well. Not sure why Unito is reopening there.
