### ISSUE TITLE
 create-webiny-project error at yarn setup

### ISSUE THREAD

**Issue by andperks6** [webiny/webiny-js#2417]
after running 
`npx create-webiny-project my-new-project   `
I get this error
`ENOENT: no such file or directory, open '/Users/username/code/test/my-new-project/.yarnrc.yml'`
prepare project folder claims to run successfully but if I kill the process before files are cleaned up there is no .yarnrc.yml created. Tested with yarn 2.4.2 and 1.22.19

Full Log:
`                                                                                                                       
Initializing a new Webiny project in /Users/username/code/test/my-new-project...
  ✔ Prepare project folder
  ✖ Setup yarn
    → ENOENT: no such file or directory, open '/Users/username/code/test/my-new-project/.yarnrc.yml'
    Install template package
    Initialize git

ERROR OUTPUT: 
----------------------------------------
ENOENT: no such file or directory, open '/Users/username/code/test/my-new-project/.yarnrc.yml'

SYSTEM INFORMATION: 
----------------------------------------
Operating System: darwin
Node: 14.17.3
Yarn: 2.4.2
create-webiny-project: 5.26.0
Template: N/A
Template Options: {}

Please open an issue including the error output at https://github.com/webiny/webiny-js/issues/new.
You can also get in touch with us on our Slack Community: https://www.webiny.com/slack

Writing log to /Users/username/code/test/cwp-logs.txt...
Cleaning up generated files and folders...
Done.
`

**Comment by Kracker1911** [comment]
I also got the error, my yarn version is 3.2.1.
@andperks6 have you solved it?

**Comment by zibberzoo** [comment]
I have the same error.  I am on WSL2 with Ubuntu 20.04 with the following output generated:

developer@kfcP53:~/webiny-js$ npx create-webiny-project my-new-project
npx: installed 166 in 6.843s
Initializing a new Webiny project in /home/developer/webiny-js/my-new-project...
  ✔ Prepare project folder
  ✖ Setup yarn
    → ENOENT: no such file or directory, open '/home/developer/webiny-js/my-new-project/.yarnrc.yml'
    Install template package
    Initialize git

ERROR OUTPUT:
----------------------------------------
ENOENT: no such file or directory, open '/home/developer/webiny-js/my-new-project/.yarnrc.yml'

SYSTEM INFORMATION:
----------------------------------------
Operating System: linux
Node: 14.20.0
Yarn: 1.22.19
create-webiny-project: 5.31.0
Template: N/A
Template Options: {}

Please open an issue including the error output at https://github.com/webiny/webiny-js/issues/new.
You can also get in touch with us on our Slack Community: https://www.webiny.com/slack

Writing log to /home/developer/webiny-js/cwp-logs.txt...
Cleaning up generated files and folders...
Done.

**Comment by zibberzoo** [comment]
Same issue trying newer Node & Yarn versions:

developer@kfcP53:~/webiny-js$ npx create-webiny-project my-new-project
npx: installed 166 in 16.302s
Initializing a new Webiny project in /home/developer/webiny-js/my-new-project...
  ✔ Prepare project folder
  ✖ Setup yarn
    → ENOENT: no such file or directory, open '/home/developer/webiny-js/my-new-project/.yarnrc.yml'
    Install template package
    Initialize git

ERROR OUTPUT:
----------------------------------------
ENOENT: no such file or directory, open '/home/developer/webiny-js/my-new-project/.yarnrc.yml'

SYSTEM INFORMATION:
----------------------------------------
Operating System: linux
Node: 16.17.0
Yarn: 2.4.3
create-webiny-project: 5.31.0
Template: N/A
Template Options: {}

Please open an issue including the error output at https://github.com/webiny/webiny-js/issues/new.
You can also get in touch with us on our Slack Community: https://www.webiny.com/slack

Writing log to /home/developer/webiny-js/cwp-logs.txt...
Cleaning up generated files and folders...
Done.

**Comment by Pavel910** [comment]
Can you post the contents of `cwp-logs.txt`? Thanks.

**Comment by zibberzoo** [comment]
The content of the cwp-logs.txt file is simply the Error Output above:

Error: ENOENT: no such file or directory, open '/home/developer/webiny-js/my-new-project/.yarnrc.yml'

**Comment by zibberzoo** [comment]
I spun up a new Ubuntu LTS VM (VMware Workstation Pro 16.x on Windows 11), and I have the same problem with 

1. Node 16.17.0 & Yarn 1.22.19 & create-webiny-project 5.31.0
2. Node 16.17.0 & Yarn 3.1.0 & create-webiny-project 5.31.0
3. Node 16.17.0 & Yarn 3.2.3 & create-webiny-project 5.31.0
4. Node 14.20.0 & Yarn 3.2.3 & create-webiny-project 5.31.0
5. Node 14.20.0 & Yarn 1.22.19 & create-webiny-project 5.31.0

@Pavel910,  on what platform and with which versions of Node, Yarn, & create-webiny-project are you having success?

Thanks,
Z

**Comment by Pavel910** [comment]
@zibberzoo within the team, we run Webiny on Node 14 and 16 (depends on the developer), and we use Windows 11 and macOS (various versions). In our CI/CD pipelines we test project creation using `ubuntu-latest`, so we have all OS-es covered.

Regarding Yarn, we have it installed on 1.22.x and 2.4.3 (again, depends on the developer), but Yarn is pretty much irrelevant, because when a Webiny project is being created, internally we call `yarn set version berry`, so yarn is installed per project.

If you want to see what the project looks like at the moment of failure, run `create-webiny-project` with `--no-cleanup`, this will keep the project files so you can inspect them.

**Comment by zibberzoo** [comment]
@Pavel910 , once I removed all things .yarn* (directory and rc file) that came with the repository (as I had to do with a package.json and yarn.lock file), then I was able to get through the project creation.  Since you may have others who are not regular yarn users, may I recommend you either check for .yarn* in the createProject.js (where you check for yarn.lock & package.json), make a note in your documentation, or not commit .yarn* materials?

Thanks for your help.

**Comment by Pavel910** [comment]
@zibberzoo I don't think I follow. Can you please explain which exact file was causing issues, and where in the directory hierarchy was it located? I'm sensing it was higher up the hierarchy, but please confirm. Thanks!

Also, what do you mean by `that came with the repository`?

**Comment by zibberzoo** [comment]
@Pavel910, 

Successful approaches:
1. Commenting out the yarnPath in the webiny-js/.yarnrc.yml file allowed success and included the following output block

```
➤ YN0000: ┌ Post-resolution validation
➤ YN0068: │ @apollo/react-hoc ➤ peerDependencies ➤ apollo-cache: No matching package in the dependency tree; you may not need this rule anymore.
➤ YN0068: │ @apollo/react-hoc ➤ peerDependencies ➤ apollo-link: No matching package in the dependency tree; you may not need this rule anymore.
➤ YN0068: │ @apollo/react-hoc ➤ peerDependencies ➤ apollo-utilities: No matching package in the dependency tree; you may not need this rule anymore.
➤ YN0068: │ @storybook/addon-info ➤ peerDependencies ➤ react-dom: No matching package in the dependency tree; you may not need this rule anymore.
➤ YN0068: │ @storybook/addon-knobs ➤ peerDependencies ➤ react-dom: No matching package in the dependency tree; you may not need this rule anymore.
➤ YN0068: │ @storybook/addon-links ➤ peerDependencies ➤ react-dom: No matching package in the dependency tree; you may not need this rule anymore.
➤ YN0068: │ @storybook/api ➤ peerDependencies ➤ react-dom: No matching package in the dependency tree; you may not need this rule anymore.
➤ YN0000: └ Completed

```
2. Deleting webiny-js/.yamlrc.yml and webiny-js/.yarn resulted in success with the only noticeable difference being the lack of the "Post-resolution validation" block from Approach 1.  [This Approach 2 seemed worth trying given the contents of the Post-resolution validation block matched the packageExtensions in the .yarnrc.yml.]

I see that yarnpkg recommends committing .yarn, .yarnrc.yml, yarn.lock, and package.json; however, create-webiny-project disallows package.json and yarn.lock, and the yarnPath in .yarnrc.yml appears to be creating issues on both my clean WSL2 Ubuntu and "regular" Ubuntu environments and with @andperks6's setup given above.

I'm open to other approaches to resolve the issue, and I'm glad to run some more test scenarios.

Thanks,
Z

**Comment by Pavel910** [comment]
@zibberzoo what I don't understand is, _when_ do you delete those? `create-webiny-project` is a single process from start to the end. At what point do you go there and manually delete stuff?

Could you record a video of the entire process and share with us? It would really help us understand your journey from the beginning. Thanks a lot!

**Comment by zibberzoo** [comment]
@Pavel910, here is the sequence:

1. clone webiny-js repository
2. cd to webiny-js and run npx create-webiny-project my-new-project
3. error regarding existing webiny-js/package.json and webiny-js/yarn.lock
4. remove existing webiny-js/package.json and webiny-js/yarn.lock
5. run npx create-webiny-project my-new-project
6. error per my first post in this thread
7. comment out yarnPath in webiny-js/.yarnrc.yml 
8. run npx create-webiny-project my-new-project
9. successful build of my-new-project with "Post-resolution validation" block in prior post
10. notice that (a) "Post-resolution validation" block corresponds to the packageExtensions in webiny-js/.yarnrc.yml, (b) "Post-resolution validation" states no such dependencies exist, and (c) webiny-js/my-new-project/.yarnrc.yml doesn't reference packageExtensions or plugins listed in webiny-js/.yarnrc.yml
11. remove webiny-js/.yarnrc.yml and run npx create-webiny-project proj2
12. successful build of proj2 with same results as my-new-project except missing the "Post-resolution validation" block
13. remove webiny-js/.yarn just for fun and run npx create-webiny-project proj3
12. successful build of proj3 with same results as my-new-project except missing the "Post-resolution validation" block

If you need a video, then I'll work towards that, but you'll just see me go through the steps above unless you want to see a different variation.

Z

**Comment by Pavel910** [comment]
@zibberzoo ok now I see what the issue is. The first 2 steps explain it all:
```
1) clone webiny-js repository
2) cd to webiny-js and run npx create-webiny-project my-new-project
```

You cannot, and shouldn't, run `create-webiny-project` within a cloned repo :) That's it. All the errors make sense now that I understand your exact steps. May I ask, what was the reason for running `create-webiny-project` within a cloned repo?

Cheers!

**Comment by Pavel910** [comment]
If you just want to start a Webiny project within a cloned repo, follow this guide: https://github.com/webiny/webiny-js/blob/next/docs/CONTRIBUTING.md

Basically, `webiny-js` repo is already a Webiny project, just like the one you get with `create-webiny-project`, except it also contains all our packages.

**Comment by zibberzoo** [comment]
I'm just trying to test webiny-js.  I've been following the webiny docs (https://www.webiny.com/docs/get-started/install-webiny) and github (https://github.com/webiny/webiny-js).  Are those both stale?

**Comment by Pavel910** [comment]
They're not stale, but you've mixed them up. It's either one OR the other. 
To create a standalone project, use `create-webiny-project` (don't clone our repo).
To work on our repo, follow the `contributing` guide I linked in my previous comment.

So pick one of these paths, whatever it is you want to do, and follow that. The two are in no way related. Hope this helps :)

**Comment by zibberzoo** [comment]
My bad. Since the github repository (I found via search) linked to the webiny docs, I assumed the former was necessary for the latter.

Z

**Comment by Pavel910** [comment]
No worries :) Just follow https://www.webiny.com/docs/get-started/install-webiny and you'll be good to go.
Let us know if you have any more problems, and join our Community Slack if you need help with anything: https://www.webiny.com/slack
