### ISSUE TITLE
Headless CMS : An object can not contain multiple files in a Content Model 

### ISSUE THREAD

**Issue by sunnythelucky** [webiny/webiny-js#2452]
### Version

5.27.0

### Operating System

OS

### Browser

Chrome

### What steps will reproduce the bug?

Hey Team, Thank you for your support. I have an issue regarding setting up Content Models. 

When I add files to the property, a list of files inside an object errors out in the preview and if I tried to save the model it errors out as well when trying to create a new Entity. 

![Screenshot 2022-05-30 at 12 38 48](https://user-images.githubusercontent.com/40551978/171033177-9f66d570-c00a-400d-ba52-b1bfc34d761e.png)

### What is the expected behavior?

I want an object which contains all the files so that I am able to name the collection of files uploaded.

**Comment by Pavel910** [comment]
@sunnythelucky I can reproduce this. Thanks for reporting!
