### ISSUE TITLE
Add custom logic on model's field

### ISSUE THREAD

**Issue by pikkolojoe** [webiny/webiny-js#2455]
### Is your feature request related to a problem? Please describe.

Creating a model entry, if given to the customer, could be complex, as there may be fields that are not needed.

It would be useful to be able to guide the user to fill in the entry correctly, hiding or showing a field based on the value of another.

**Comment by Pavel910** [comment]
@pikkolojoe check this out: https://www.webiny.com/docs/headless-cms/extending/customize-entry-form-layout

It requires a plugin to build a custom layout, but it does what you need. Let me know if this helps.

**Comment by pikkolojoe** [comment]
Hi @Pavel910,
I managed to make some logic, but it seems to be very slow, right?

**Comment by Pavel910** [comment]
It is slow in terms of development, and very hard-coded, but it's the best we have today to get you unblocked. 

We're collecting feedback and ideas in that area from various users and clients, so feel free to drop your thoughts or maybe even other software as an example. Much appreciated!

**Comment by pikkolojoe** [comment]
I find it very slow even while inserting a new entry, it takes about 2/3 seconds before displaying what has been typed from the keyboard. By inserting a log, I see that it is called many times at every slightest modification of the form.

**Comment by Pavel910** [comment]
That's not related. We're using it regularly for various purposes, with lots of custom components and it never slowed down the UI. It's probably something within your code, or some custom component you're using.


Form rerenders will happen, because data flows top to bottom, but we never ran into visible issues with it.

**Comment by pikkolojoe** [comment]
Ok, it seems that the slowdown is only reflected by working locally, so that's okay.
