### ISSUE TITLE
yarn webiny deploy fails with exit code 255

### ISSUE THREAD

**Issue by freyp577** [webiny/webiny-js#2459]
Hi,
we are new to webiny and evaluating it for a new project. So we read the overview (partly) and then decided to try to install it into a new AWS account to continue with the evaluation

install was successful, but deploy running "yarn webiny deploy" fails
we see the following error but do not know what it means

can you please give us some directions where to look and how to fix the cause of the deployment [error?]

 +  aws:elasticsearch:Domain webiny-js created
 +  pulumi:pulumi:Stack api-dev creating error: update failed
 +  pulumi:pulumi:Stack api-dev **creating failed** 1 error

Diagnostics:
  pulumi:pulumi:Stack (api-dev):
    error: update failed

  aws:s3:BucketObject (./pbInstallation.zip):
    error: 1 error occurred:
        * Error putting object in S3 bucket (fm-bucket-430699e): AccessDenied: Access Denied
        status code: 403, request id: E8QJTCERXD35EFWX, host id: OHmp8x1+hKm6Q/51P+3kRI3UK4Jpxe1zoDflRpq5DgDa8BmgyiZPxZEFFxCBMLYCC9PhUDQJ7nI=

Resources:
    + 30 created

**Comment by freyp577** [comment]
Update: I assume it is related to the isue documented in
[issue #2290](https://github.com/webiny/webiny-js/issues/2290)

our organization does not allow public access to internally used S3 buckets

is there a way to deploy webiny without having public access to the S3 bucket that is created by pulumi?

**Comment by Pavel910** [comment]
Left a comment on that issue you are referring to (there are 3 basically identical issues). Can't tell if it would really break your deployment, but it's definitely something to address.
