### ISSUE TITLE
GraphQL - `createCategory` Mutation Throwing an Incorrect Error Message

### ISSUE THREAD

**Issue by adrians5j** [webiny/webiny-js#2471]
### Version

5.29.0

### Operating System

/

### Browser

/

### What steps will reproduce the bug?

Just try issuing the following mutation, and you should be able to see the error message on the right:

![Snipaste_2022-06-09_11-50-28](https://user-images.githubusercontent.com/5121148/172862557-9f85cab5-516e-4ff2-8e5d-5315faf25bfc.png)

### What is the expected behavior?

We should not get this system-level error. We should get the error message thrown from the `CreateDataModel` model (`packages/api-page-builder/src/graphql/crud/categories.crud.ts:195`).

### What do you see instead?

The error is shown in the screenshot.

### Possible solution

This is basically happening because of the incorrect order of operations here.

![image](https://user-images.githubusercontent.com/5121148/172862674-1287bc4a-1966-47c9-bf83-e9cddf99ca99.png)

The fix needs to be applied [here](https://github.com/webiny/webiny-js/blob/next/packages/api-page-builder/src/graphql/crud/categories.crud.ts#L187-L195). We need to switch the order of operations.

**Comment by Avi98** [comment]
If no one is looking into it. Can I take this up

**Comment by adrians5j** [comment]
Sry @Avi98, it was actually already solved by @neatbyte-vnobis.

Didn't even notice this issue wasn't closed. :O

But thanks for the good will @Avi98 🙂 🍻
