### ISSUE TITLE
Error on Account details page

### ISSUE THREAD

**Issue by winglunlam** [webiny/webiny-js#2488]
### Version

5.24.0

### Operating System

MacOS

### Browser

Chrome

### What steps will reproduce the bug?

1. Create a security group that have "No access" for Admin Users.
![fig1](https://user-images.githubusercontent.com/44934955/173990106-b773b32c-3a78-45e2-ae36-ddf08bce12d4.png)

2. Create an account who is assigned to the security group.
![fig2](https://user-images.githubusercontent.com/44934955/173990494-f0c80722-aad8-4921-a37c-34a5c95a1e27.png)

3. Log in the account

4. Go to the Account details page
![fig3](https://user-images.githubusercontent.com/44934955/173990539-b6d57b65-b711-4b67-b52b-74473eba236b.png)

5. Blank page appears and error occurs
![fig4](https://user-images.githubusercontent.com/44934955/173990625-4f2369d4-e843-4cd8-8a38-0736aadfb355.png)

### What is the expected behavior?

Should be able to see the "Account details" page even if the permission of "Admin Users" set to "No Access".

### What do you see instead?

Blank page appears and error occurs
![fig4](https://user-images.githubusercontent.com/44934955/173990625-4f2369d4-e843-4cd8-8a38-0736aadfb355.png)

**Comment by Pavel910** [comment]
@wllam44 this is something else. The error says `cannot read properties of undefined (reading 'adminUsers')`, which means the permissions themselves are undefined. Can you please check the network requests, and find the `Login` mutation. What's the response of that mutation? Thanks.

**Comment by winglunlam** [comment]
@Pavel910 below is the response of the `Login` mutation:

[{"data":{"security":{"login":{"data":{"id":"c7d46527-c82f-45ed-864d-22f6d01b99b9","displayName":"test test","type":"admin","permissions":[{"name":"content.i18n"},{"name":"cms.*"},{"name":"pb.category","rwd":"rwd"},{"name":"pb.menu","rwd":"rwd"},{"name":"pb.page","rwd":"rwd","pw":"rc"},{"name":"pb.settings"}],"profile":{"email":"test@testing.com","firstName":"test","lastName":"test","avatar":null,"gravatar":"https://www.gravatar.com/avatar/eca74378f20815070e1bec3ee81bfabc","__typename":"AdminUser"},"__typename":"AdminUserIdentity"},"error":null,"__typename":"SecurityIdentityLoginResponse"},"__typename":"SecurityMutation"}},"extensions":{"console":[]}}]

**Comment by Pavel910** [comment]
@wllam44 thanks a lot! We'll have a look at this 👍

**Comment by Pavel910** [comment]
The actual error is not on react side, it's on the GraphQL API side. It's a simple permission check bug. Should be easy to fix. Thanks for reporting @wllam44 🍻 

![CleanShot 2022-06-16 at 13 48 49](https://user-images.githubusercontent.com/3920893/174063480-27bf1e4b-f2d7-45ba-b6d8-bb49b3cdb5fa.png)

**Comment by winglunlam** [comment]
Great to hear that. Thanks a lot.
