### ISSUE TITLE
pulumi webiny blog updates

### ISSUE THREAD

**Issue by susanev** [webiny/webiny-js#2503]
hi @adrians5j, i think yall recently made some changes that are causing the webiny blog on the pulumi website to have some 404s now, and i think some of the content may need to be updated as well.

mind giving us some direction on how you'd like the content updated?
https://github.com/pulumi/pulumi-hugo/blob/master/themes/default/content/blog/how-webiny-built-a-serverless-application-framework/index.md

ref: https://github.com/pulumi/pulumi-hugo/issues/1658

**Comment by adrians5j** [comment]
Thanks for reporting this @susanev, I'll take a look at this during this week and get back to you with an update (via this GH issue).
