### ISSUE TITLE
[Deployment] Using Localstack for local deployment and development

### ISSUE THREAD

**Issue by ancs21** [webiny/webiny-js#2519]
### Is your feature request related to a problem? Please describe.

Because we need to deploy to a real AWS environment, it's so hard for testing and deployment.

### Describe the solution you'd like.

Using [Localstack](https://localstack.cloud/)

**Comment by endymion1818** [comment]
Thanks for your interest @ancs21 ! We have looked at this a number of times in the past but we don't believe it's the best solution for Webiny, even though it does add an extra step to the evaluation process.

Please see https://github.com/webiny/webiny-js/issues/1528 as well as this article for more background: https://www.webiny.com/blog/local-development-is-dying-and-it-s-for-the-better
