### ISSUE TITLE
deploy api error

### ISSUE THREAD

**Issue by amirarabirazdadeh** [webiny/webiny-js#2559]
### Version

5.30.0

### Operating System

windows 10 Enterprise LTSC 1809

### Browser

google chrome

### What are the steps to reproduce this bug?

1. Fork and clone webiny repo
2. yarn install
3. yarn setup-project
4. yarn webiny deploy apps/core --env=dev
5. yarn webiny deploy apps/api --env=dev

### yarn webiny deploy apps/api --env dev

webiny info: Running "hook-before-build" hook...
webiny error: An error occurred while processing hook-before-build-generate-common-handlers plugin: ENOENT: no such file or directory, copyfile 'C:\Users\username\webiny-js\packages\serverless-cms-aws\dist\handlers\common\api\fileManager\download\handler.js' -> 'C:\Users\username\webiny-js\.webiny\workspaces\apps\api\fileManager\download\build\handler.js'

**Comment by Pavel910** [comment]
@amirarabirazdadeh thanks for reporting. We'll double-check this on Windows (@swapnilmmane) and get back to you.
