### ISSUE TITLE
504 error from CloudFront on large video/mp4 files

### ISSUE THREAD

**Issue by gil-3bd** [webiny/webiny-js#2570]
### Version

5.30.0

### Operating System

macOS Monterey 12.4

### Browser

Google Chrome

### What are the steps to reproduce this bug?

When uploading a large (1GB) video/mp4 file through File Manager, the files upload successfully but when I try to access or load the file via the "File Details" URL the files don't load and eventually I get a 504 error from CloudFront. However, if the file is under 50MB they load correctly. 

### What is the expected behavior?

When loading any video/mp4 file from example url `https://uniqueurl.cloudfront.net/files/videofile.mp4` should redirect to the expected  url  example: `https://fm-bucket-00000.s3.amazonaws.com/videofile.mp4` without any timeout 504 errors from CloudFront. 

### What do you see instead?

Timeout 504 error from CloudFront

### Possible solution

Figure out how to handle large video/mp4 files download in the download lambda function.

**Comment by gil-3bd** [comment]
Upgrading to **Webiny v5.31.0** has fixed the **504 Error** when accessing large files in the  File Manager.

**Comment by gil-3bd** [comment]
I'm trying to upload a single 5GB file _(not multiple)_ via the File Manager but now I’m getting an error that reads **“Multiple max size exceeded.”** even after increasing the **"Maximum file upload size"** value. However, if the file is under 1GB it uploads correctly.

<img width="639" alt="image" src="https://user-images.githubusercontent.com/82060323/186962088-73d41c9a-70e9-4f4a-b4ab-b177fbc35d2b.png">

It looks like there is a limit of **1000mb** fallback to the files [here](https://github.com/webiny/webiny-js/blob/f03c32e78a4db8ef6a62041051b746b0608a8f09/packages/app-admin/src/components/FileManager/FileManagerView.tsx#L610) on the code

**Comment by Pavel910** [comment]
@gil-3bd Good catch. What do you think, should we remove that client side limitation entirely, and let users upload whatever they like? I don't remember when and why, but I think that limitation was defined there completely randomly.

**Comment by gil-3bd** [comment]
@Pavel910 I think we should let the users upload whatever they like by defining it in the backend **General Settings**
