### ISSUE TITLE
Expose configuration for website app preview Cloudfront

### ISSUE THREAD

**Issue by timruppert** [webiny/webiny-js#2616]
### Is your feature request related to a problem? Please describe.

We are currently configuring our website domain and would like the preview domain to also be configurable, but it's not exposed in the app.resources during the createWebsiteApp function.

### Describe the feature's behavior.

When a user is working with the page builder, and they want to see work in progress, they get taken to the prerendering service and it's on an internal domain.  We'd like to expose that so that our users would be taken to something like web-preview.mydomain.com

### Describe alternatives you've considered.

Leaving the configuration free and manually managing it.  It is working at the moment because the custom headers are not applied to it - so it works if I add our wild card cert and alternate domain name to cloud front and configure the front end.  Longer term, it'd be better to have this be something that's scripted :)

**Comment by Pavel910** [comment]
@timruppert @adrians5j does this look acceptable?

![CleanShot 2022-09-16 at 18 56 14](https://user-images.githubusercontent.com/3920893/190690543-ec7f2d0b-685d-4fed-bd8e-fc6207c742f3.png)

I'm trying to come up with the simplest possible solution. This one seems rather simple, but it will require you to have both delivery and preview domains be handled by the same certificate.

Alternatively, we can do this, to completely detach preview and delivery domains configuration:

![CleanShot 2022-09-16 at 18 57 34](https://user-images.githubusercontent.com/3920893/190690703-9abab388-ddba-434e-88c2-7f896c5aec9c.png)

Awaiting your feedback :)

**Comment by adrians5j** [comment]
I'd like to implement 2nd solution. @Pavel910 can you green-light it please?

**Comment by Pavel910** [comment]
@adrians5j let's go with the 2nd option 👍

**Comment by adrians5j** [comment]
Thanks! Will submit PR soon!
