### ISSUE TITLE
Switch places of dev and prod configs for Elasticsearch in the Core pulumi app

### ISSUE THREAD

**Issue by Pavel910** [webiny/webiny-js#2630]
### Version

Presumably, all >=5.29. versions.

### What are the steps to reproduce this bug?

Create a new project, use DynamoDB + Elasticsearch setup, and deploy. 

### What is the expected behavior?

`--env=dev` should deploy the small development instance, and `--env=prod` should deploy a production instance.

### What do you see instead?

Dev and Prod configs places are switched, so `dev` deploys a `prod` config, and vice versa.

### Possible solution

Switch places of config getters in this location:
https://github.com/webiny/webiny-js/blob/next/packages/pulumi-aws/src/apps/core/CoreElasticSearch.ts#L65

**Comment by LarrydNguyen** [comment]
Hey, @Pavel910 I raised a PR, but there's some kind of failure in the testing, I'm not sure where and could really use some guidance.

**Comment by brunozoric** [comment]
Hi @LarrydNguyen, outside collaborators do not have access to our Elasticsearch cluster so that test is failing. PR is otherwise ok - I will merge.
