### ISSUE TITLE
`uploadFolderToS3` doesnt support video file

### ISSUE THREAD

**Issue by taifok** [webiny/webiny-js#2678]
### Version

v5.31.0

### What are the steps to reproduce this bug?

I imported video file in react app. the app files is uploaded with `utf-8` encoding but not `buffer` for these files.
so the video file cannot be viewed on S3.

### Additional information

relevant code: 
https://github.com/webiny/webiny-js/blob/6e84b043f6f5bd37f5e02babdd51bad43f5914b3/packages/pulumi-aws/src/utils/uploadFolderToS3.ts#L134

### Possible solution

Can we just use `buffer` encoding for the files?

**Comment by adrians5j** [comment]
Fixed by https://github.com/webiny/webiny-js/pull/2635.

Will be released this week.

🙂 

P.S. Will close this issue.
