### ISSUE TITLE
You have the impression that you can change a Content Model created in code in the admin UI

### ISSUE THREAD

**Issue by robin-vinck** [webiny/webiny-js#2704]
### Version

5.31

### Operating System

macOS Monterey

### Browser

Google chrome

### What are the steps to reproduce this bug?

1. Create a content model defined in code
2. Open the content model entries
3. Click on the name of the model
4. It seems like you are able to change this model, if you make a change and try to save it fails

<img width="1215" alt="Schermafbeelding 2022-10-21 om 19 16 43" src="https://user-images.githubusercontent.com/53557527/197252914-219ab161-0311-4ea0-b300-b5e432b8b7b4.png">

### What is the expected behavior?

I would expect the same behavior as on the content models page as well.
When you try to edit the model you receive the message: "Content model is registered by a plugin"

<img width="815" alt="Schermafbeelding 2022-10-21 om 19 19 48" src="https://user-images.githubusercontent.com/53557527/197252984-99c387d1-447e-40b0-a90e-d3189ddea726.png">

### What do you see instead?

The standard entry editor.

<img width="1440" alt="Schermafbeelding 2022-10-21 om 19 20 38" src="https://user-images.githubusercontent.com/53557527/197253169-9f873ffc-0e26-447f-8e22-ee1b1239002d.png">

### Possible solution

Show the same message when trying to open the content model: "Content model is registered by a plugin"

OR

Disable editing in the editor.

**Comment by brunozoric** [comment]
Hi @robin-vinck 
[Here](https://github.com/webiny/webiny-js/blob/next/packages/app-headless-cms/src/admin/views/contentEntries/ContentEntriesList.tsx#L153) is where the link is rendered. If you get the chance, fix it and make a PR. I'll mark this as good first issue as it's simple to fix.
Btw. you have a `plugin` property on `contentModel` to check if it's a model created via plugin.

**Comment by robin-vinck** [comment]
Hi @brunozoric 

It seems like I cannot open an issue branch.
<img width="340" alt="Schermafbeelding 2022-11-01 om 12 12 25" src="https://user-images.githubusercontent.com/53557527/199220728-60af4343-ebb1-4f67-b9f1-7e950f2fe489.png">
Following this guide: 
https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-a-branch-for-an-issue

**Comment by Avi98** [comment]
I think this issue is fixed

**Comment by brunozoric** [comment]
Fixed with the PR:
https://github.com/webiny/webiny-js/pull/2769
