### ISSUE TITLE
Fix PB paragraph rendering

### ISSUE THREAD

**Issue by m0nikaza** [webiny/webiny-js#2751]
### Version

5.33

### What are the steps to reproduce this bug?

Go to this URL, and recreate the left side, with bolded titles and text, using the Paragraph element in the editor.
https://site.webiny.com/signup/demo-request/

![CleanShot 2022-11-02 at 15 38 52](https://user-images.githubusercontent.com/3920893/199518668-dfee1157-f55a-4a3c-af07-c2b54e09edee.png)

Then, open the website preview, and you'll only see the first line of text. If you inspect the markup in the dev tools, most of it will be gone, due to nested `<p>`.

### What is the expected behavior?

PB paragraph to render correctly

### Additional information

Nested `<p>` is not allowed, and that’s what happens sometimes in the Paragraph content, within the `Text` component [which can be found here](https://github.com/webiny/webiny-js/blob/dev/packages/app-page-builder/src/render/components/Text.tsx#L35).

### Possible solution

A solution that worked for me was doing this simple check to avoid `p` element being created.

```
React.createElement(tag === "p" ? "div" : tag, { ....})
```

**Comment by Pavel910** [comment]
Fixed in this commit: https://github.com/webiny/webiny-js/commit/956625a786fca1e99ee0bf5d08c961c55038dd89
