### ISSUE TITLE
Various minor visual fixes

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#288]
1. Label for multi image is positioned incorrectly. You can check this out by visiting `/admin/users`, and replace the code in `packages/webiny-app-admin/src/views/Users/AvatarImage.js` with following code (changes `SingleImageUpload` to `MultiImageUpload`):

```// @flow
import * as React from "react";
import { withImageUpload } from "webiny-app/components";
import { MultiImageUpload } from "webiny-ui/ImageUpload";

const AvatarImage = props => {
    return <MultiImageUpload {...props} />;
};

export default withImageUpload({multiple: true})(AvatarImage);
```

![image](https://user-images.githubusercontent.com/5121148/48699955-fc25a400-ebea-11e8-9728-6b1d1910e22f.png)

2. CMS Editor - Image component - because borders are slightly transparent (marked with red arrows in sshot), their color is not solid when Image element is hovered (you can see colors from behind a bit  and Image component's bottom dark border). Just select Image component and hover over it, and you should be able to notice it.

![image](https://user-images.githubusercontent.com/5121148/48029558-c1cdf880-e14e-11e8-90bf-eb182f6629ca.png)

3. CMS Editor - Background settings - we need to style background image section (especially positioning). Please note that components are disabled when image is not selected.

![image](https://user-images.githubusercontent.com/5121148/48145884-1a6ad600-e2b4-11e8-8486-1b4aaa68a785.png)

4. I noticed that these controls might be a bit bigger. Please take a look and if you think they could be a bit bigger, please increase the size.

![image](https://user-images.githubusercontent.com/5121148/48146055-7f263080-e2b4-11e8-9219-0f0f62fe4376.png)

5. Cannot click here.

![image](https://user-images.githubusercontent.com/5121148/48940454-e5978980-ef17-11e8-8456-2314f0891451.png)

5.A Cannot see the label once the image is selected. User won't know what is selected image for.

6. Please add social media icons here. 

![image](https://user-images.githubusercontent.com/5121148/49071847-2a306700-f22f-11e8-8306-71f6b5b25040.png)

**Comment by Pavel910** [comment]
Z-index of Slate toolbar:

![image](https://user-images.githubusercontent.com/3920893/50384119-84063e80-06c0-11e9-9e81-0133c0fa645e.png)

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
