### ISSUE TITLE
Image Editor - additional minor features

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#294]
1. Ability to add class
2. Ability to initially select a tool
3. Must be able to select available tools
4. Immediate resize feature
5. Add method in render prop for apply and finish so that we don't have to do it manually each time

**Comment by adrian1358** [comment]
Not needed at this very moment, low priority.

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
