### ISSUE TITLE
wip: fix minor visual issues

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#310]
This issue is WIP (issues from `cms/general-settings` branch, not yet merged into `development`).

1. Added FontAwesome resize icon, because material didn't have anything similar. Please check and replace if you think this is not appropriate. The height definitely needs some adjustments.

![image](https://user-images.githubusercontent.com/5121148/49582428-492ca880-f955-11e8-90a5-fa2ce1244f28.png)

Instructions:
This settings icon can be seen in TypeForm CMS editor element. You must register it manually in order to see it in CMS. Setup instructions can be found in package's README.md. Register CMS plugins in `packages/demo-admin/src/plugins/index.js`.

2. I noticed that this and other embed elements have this message when the link in settings dialog isn't set. Probably we should create blank version of this element.
![image](https://user-images.githubusercontent.com/5121148/49584713-6d3fb800-f95c-11e8-92f4-5d879566d33d.png)

3. Apply additional styles (installation Instructions are available in`webiny-mailchimp` README.md).

![image](https://user-images.githubusercontent.com/5121148/49645863-a2f8a580-fa1d-11e8-8524-ec30c95c93a6.png)

4. Height of tabs incorrect. 
![image](https://user-images.githubusercontent.com/5121148/49702690-47840e80-fbfb-11e8-9388-9c5aad784739.png)

5. Text is centered in admin, but not on frontend site.
![image](https://user-images.githubusercontent.com/5121148/49895948-2ff29300-fe52-11e8-988b-06bc3ed066c0.png)

6. When Webiny CMS is installed, users will have default homepage, 404 and error pages already created.  We should create cool default pages. Go for it! :)

For example:
![image](https://user-images.githubusercontent.com/5121148/49965919-d73cfc00-ff1e-11e8-99fb-d6a8c4c620d2.png)

In site (accessed over `http://localhost:3002` by default), just visit "/" for homepage, or type anything random into the address to access 404 page. For error page, you will need to open the page in editor, and check the URL over which it can be accessed. These URLs are for now random, but will make them `/error` and `/not-found` in the near future. 

![image](https://user-images.githubusercontent.com/5121148/50002280-e748f000-ff9f-11e8-93c3-46b1f8a5c505.png)

BTW, if for some reason these pages were not set in CMS settings (maybe user removed them), we still try to load GenericError pages, which can be found here `packages/demo-site/src/cms`. These will just output generic message. Maybe we could apply some additional styles here too.

7. Fix overlap, I often want to click edit, but delete gets triggered. 

![image](https://user-images.githubusercontent.com/5121148/50112398-70318700-023f-11e9-9ad5-2bc6cd5b199a.png)

8. Scrollbars showing in image editor dialog:

![image](https://user-images.githubusercontent.com/5121148/50283768-3935be00-0457-11e9-85f2-7f0a38247e2d.png)

Just try to select a background image for a block.

P.S. Just noticed it's not just the image editor:
![image](https://user-images.githubusercontent.com/5121148/50286480-ca109780-045f-11e9-8979-164c53d6a7c4.png)

**Comment by adrian1358** [comment]
@SvenAlHamad this one will soon be good to go, will notify you additionally.

**Comment by adrian1358** [comment]
You can start with this issue(s) @SvenAlHamad.

The repo in which all integrations are implemented: https://github.com/Webiny/webiny-addons

Setup instructions are in README.md (and also in each integration's README.md file), but basically the steps are the same as in `webiny-js` repo. Just have in mind that here all `webiny-js` deps, like `webiny-app`, `webiny-api`, `webiny-app-cms` etc. are downloaded via NPM (currently latest 1.8.0 packages are set in package.json files).

If you'll need anything (eg. mailchimp API key), let me know.

One last note, `AutoComplete` is broken, you have to select twice the item in dropdown, and some other anomalies are present. Will check this soon.
