### ISSUE TITLE
Missing richt text editor for Heading variables in Blocks

### ISSUE THREAD

**Issue by ma-schmidt-de** [webiny/webiny-js#3226]
### Version

5.34.7

### Operating System

macOS

### Browser

Firefox 112.0.1

### What are the steps to reproduce this bug?

* Create a new Block
* Add the Heading and a Paragraph page element
* Link both Elements in order to create variables for them
* Save Changes
* Create a new page, with arbitrary category and add the block you just created
* Modify the variables of Heading and Paragraph and try to use the rich text editor

### What is the expected behavior?

Both Paragraph and Heading variables support editing via rich text editor as they do in the Block editor, when you do in-line editing.

### What do you see instead?

The Paragraph variable supports the RTE but the Heading does not.

![Screenshot 2023-04-21 at 09 52 25](https://user-images.githubusercontent.com/19306046/233576899-0937c6f1-d52c-4e8d-af24-9acdb78348b4.png)

### Additional information

RTE for Heading's in-line editing in the Block editor.
![Screenshot 2023-04-19 at 15 09 52](https://user-images.githubusercontent.com/19306046/233577105-925abb7a-abf2-468a-ba63-6ca4b70001b7.png)

RTE for Paragraph variable for Blocks added to a page.
![Screenshot 2023-04-19 at 15 15 45](https://user-images.githubusercontent.com/19306046/233577228-d833c523-8b26-49e7-9876-3b392a26abe1.png)

### Possible solution

According to @adrians5j the new release 5.35 will include a new rich text editor. It might resolve these issue already.

**Comment by SvenAlHamad** [comment]
Hey @ma-schmidt-de - with the release of v5.35 we're switching to the lexical editor, and there you'll have access to the RTE on both heading and paragraph elements. I'll close this one for now, but if you spot this issue after the v5.35 is out, feel free to just ping us back here again.
