### ISSUE TITLE
fix(editor): user must be informed that locked page revision cannot be edited

### ISSUE THREAD

**Issue by adrian1358** [Webiny/webiny-js#335]
If page revision is locked, any changes made to it in the editor won't have effect.

User should be aware of this.

For example I tried editing these settings:

![image](https://user-images.githubusercontent.com/5121148/49997298-7ac6f480-ff91-11e8-81aa-430fb453124d.png)

At first I thought it was a bug (save not working properly).

**Comment by adrian1358** [comment]
The quickest (not sure if acceptable for v1) solution would be to just disable editor for locked pages. We just show a tooltip, saying that the editor cannot be opened since the page is locked, and that they should just create a new revision.

This would be quickest / easiest for v1. 

I also discussed this with @Pavel910. Although the upper solution would be the easiest, I agree with him that the editor should always be 'openable'. He also made a good point here, that the user might need to open a locked page just to save an element for re-use in other page.

**Comment by SvenAlHamad** [comment]
We can just add a bar on the bottom of the page that notifies that use the page is locked. The bar can be displayed above the editor, as well as settings and other controls. 
If you can just add a dummy div, I'll sort out the visuals.

**Comment by adrian1358** [comment]
Confused by your answer :)

a, b or c? Or ?

![image](https://user-images.githubusercontent.com/5121148/50002715-4824f800-ffa1-11e8-9199-94777ab35f9a.png)

Thanks!

**Comment by SvenAlHamad** [comment]
B
