### ISSUE TITLE
Image entity - additional attributes

### ISSUE THREAD

**Issue by adrian1358** [Webiny/webiny-js#35]
Implement following useful attributes on Image entity:

1. `width`, float
2. `height`, float
3. `aspectRatio`, dynamic
4. `isPortrait`, dynamic
5. `isLandscape`, dynamic

**Comment by Pavel910** [comment]
@adrian1358 this will be done in the entity itself and will probably use some 3rd party package to read image data so I'm removing `webiny-file-storage` as it is not related.

**Comment by adrian1358** [comment]
@Pavel910 Cool.

**Comment by Pavel910** [comment]
@adrian1358 is this entity still in use?
