### ISSUE TITLE
Image preview font

### ISSUE THREAD

**Issue by SvenAlHamad** [Webiny/webiny-js#354]
It seems the fonts are not displayed correctly when doing an image snapshot of a block/element.

Editor preview:
![image](https://user-images.githubusercontent.com/3808420/50297323-7b212d00-0474-11e9-82d0-3378cd4f77e7.png)

Image snapshot:
![image](https://user-images.githubusercontent.com/3808420/50297352-870cef00-0474-11e9-95a5-eb461ed0e945.png)

**Comment by adrian1358** [comment]
Closing this one, as it's something we cannot fix due to CORS rules.

> As of Chrome 64, new CORS rules are enforced for stylesheets. You'll need to use a local development server to do local testing of functionality that depends on the CSS Object Model. For details, see Cannot access cssRules from local css file in Chrome.


(https://stackoverflow.com/questions/49088507/cannot-access-rules-in-external-cssstylesheet)
