### ISSUE TITLE
Optimize sliders

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#357]
![image](https://user-images.githubusercontent.com/5121148/50342050-98f89b80-0521-11e9-8ec4-9acce0013240.png)

![image](https://user-images.githubusercontent.com/5121148/50342719-8d5aa400-0524-11e9-945f-8b72e9e0c79a.png)

**Comment by roman-vabishchevych** [comment]
I have a problem width with the slider when desktop/mobile switching. 

After switching the tab, the slider takes 100

Screen gif:
![wbny slider desktop mobile tabs](https://user-images.githubusercontent.com/4134474/68020084-15155100-fca6-11e9-8644-f97e5c465d97.gif)

**Comment by roman-vabishchevych** [comment]
@doitadrian 
@Pavel910

**Comment by Pavel910** [comment]
@roman-vabishchevych I'll take a look at it in the following days.

**Comment by Pavel910** [comment]
@roman-vabishchevych this is fixed and released. The related issue is #621 and PR #631.
I'm closing this issue as I'm not even sure if it's related or not since the original issue by @doitadrian has no description except the screenshot.
