### ISSUE TITLE
Delete single column inside row

### ISSUE THREAD

**Issue by SvenAlHamad** [webiny/webiny-js#363]
At the moment when you have a single column inside a row, the delete option is disabled for that column. A better way would be to enable the delete option, but when we delete the column, the row should also be deleted automatically.

**Comment by Pavel910** [comment]
Note to self:
if the remaining block does not have any more children - ti should also be deleted.

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
