### ISSUE TITLE
fix: tooltip must be placed behind dialog overlay

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#372]
![image](https://user-images.githubusercontent.com/5121148/50388340-729a5200-0713-11e9-8490-45eff8c15841.png)

**Comment by adrian1358** [comment]
You can check this by hovering over "New Draft" tooltip, and then clicking on the "+" icon.

**Comment by adrian1358** [comment]
BTW, unnecessary scrollbars in the dialog were already reported in #310 (last item in the list).
