### ISSUE TITLE
5.39.0 - Using `AWS_PROFILE` in Env Vars No Longer Works

### ISSUE THREAD

**Issue by adrians5j** [webiny/webiny-js#3772]
I discovered that when you try using AWS_PROFILE in env vars, the profile is not detected in the STS call (although the creds are picked up!):

![image](https://github.com/webiny/webiny-js/assets/5121148/2a033766-6dab-4621-bc8f-80b6eb71b215)

Let's see why this `profile` is `undefined` here. Maybe it's AWS SDK3-related?

**Comment by Edward13ruf** [comment]
I am also experiencing this issue. Had to revert to 5.38.0

**Comment by adrians5j** [comment]
From which version you reverted back to 5.38?

**Comment by Edward13ruf** [comment]
> From which version you reverted back to 5.38?

Latest. I believe that's 5.38.2. I ran `npx create-webiny-project` but then it couldn't pick up my AWS profile until I instead did `npx create-webiny-project@5.38.0`.

For context I'm a new user building the app for the first time.

**Comment by adrians5j** [comment]
Closed with https://github.com/webiny/webiny-js/pull/3828.
