### ISSUE TITLE
Create project failing due to `yarn add @webiny/cwp-template-aws@latest`

### ISSUE THREAD

**Issue by pranavburnwal** [webiny/webiny-js#3795]
### Version

latest

### Operating System

MacOS - Apple Silicon

### Browser

NA

### What are the steps to reproduce this bug?

`npx create-webiny-project webiny-cms` 

to an empty folder

### What is the expected behavior?

App should start the base.

### What do you see instead?

![image](https://github.com/webiny/webiny-js/assets/15976005/f0270028-e111-4fdc-87d1-420573b94a81)

### Additional information

Copy pasting the whole output
```
Initializing a new Webiny project in /Users/pranavburnwal/playground/webiny-cms...
  ✔ Prepare project folder
  ✔ Setup yarn
  ✖ Install template package
    → Error: ENOENT: no such file or directory, stat '/Users/pranavburnwal/playground/webiny-cms/.yarn/releases/yarn-3.6.4.cjs'
    Initialize git

ERROR OUTPUT:
----------------------------------------
Command failed with exit code 1: yarn add @webiny/cwp-template-aws@latest
Internal Error: ENOENT: no such file or directory, stat '/Users/pranavburnwal/playground/webiny-cms/.yarn/releases/yarn-3.6.4.cjs'
Error: ENOENT: no such file or directory, stat '/Users/pranavburnwal/playground/webiny-cms/.yarn/releases/yarn-3.6.4.cjs'

SYSTEM INFORMATION:
----------------------------------------
Operating System: darwin
Node: 18.16.0
Yarn: N/A
create-webiny-project: 5.38.2
Template: N/A
Template Options: {}

Please open an issue including the error output at https://github.com/webiny/webiny-js/issues/new.
You can also get in touch with us on our Slack Community: https://www.webiny.com/slack

Writing log to /Users/pranavburnwal/playground/cwp-logs.txt...
Cleaning up generated files and folders...
Done.
```

**Comment by pranavburnwal** [comment]
I will be happy to debug if any steps are provided.

**Comment by brunozoric** [comment]
hi @pranavburnwal 
Can you check that your `npx` is on latest version? Also, you should be on `yarn` v**1.22.21**. They had some bugs related to setting a newer version of yarn.
Also, join our Slack, so we can talk there: https://webiny-community.slack.com/

**Comment by pranavburnwal** [comment]
> hi @pranavburnwal Can you check that your `npx` is on latest version? Also, you should be on `yarn` v**1.22.21**. They had some bugs related to setting a newer version of yarn. Also, join our Slack, so we can talk there: [webiny-community.slack.com](https://webiny-community.slack.com/)

This got sorted, thanks @brunozoric ! Closing!

PS: Once I saw your notification, I thought Anoop (founder/maintaner of https://github.com/usebruno/bruno/) changed his name.. lol
