### ISSUE TITLE
Twitter Broken Link

### ISSUE THREAD

**Issue by JuanPabloDiaz** [webiny/webiny-js#3864]
### What are the steps to reproduce this bug?

This issue is in Twitter, it does not have anything to do with the code in GitHub.
In the [Twitter homepage](https://twitter.com/WebinyCMS), the GitHub URL is incorrect.
it Should be [http://github.com/webiny/webiny](https://t.co/5ypvorGQjD) and not [http://github.com/webiny/webiny-](https://t.co/5ypvorGQjD)

### What is the expected behavior?

Take you to the GitHub page for Webiny

### What do you see instead?

404 error
![404](https://github.com/webiny/webiny-js/assets/25883220/e442ea9d-0681-41f9-9a41-12a4bdb0ecbd)

⭐️ GitHub 👉 [http://github.com/webiny/webiny-](https://t.co/5ypvorGQjD)…

### Possible solution

⭐️ GitHub 👉 [http://github.com/webiny/webiny](https://t.co/5ypvorGQjD)…

**Comment by swapnilmmane** [comment]
Thank you @JuanPabloDiaz for reporting it. We have fixed the URL! :)
