### ISSUE TITLE
Initial deployment fails

### ISSUE THREAD

**Issue by Alexander-Stulov** [webiny/webiny-js#3905]
### Version

5.39.1

### Operating System

macOS 14.3.1 

### What are the steps to reproduce this bug?

Executing steps described in https://www.webiny.com/docs/get-started/install-webiny

npx create-webiny-project cms - OK
yarn webiny deploy - FAILS with error webiny error: api-graphql

### What is the expected behavior?

The project will be deployed as described

### What do you see instead?

Can't deploy API. Error: "webinar error: api-graphql"
Can't continue

<img width="954" alt="Monosnap cms — -zsh — 136×45 2024-02-27 23-43-11" src="https://github.com/webiny/webiny-js/assets/2744160/dbca3eb3-db57-4bb6-bbc6-0cf75c664146">

**Comment by brunozoric** [comment]
hi @Alexander-Stulov 
What are the versions of node, npx, yarn and npm?

**Comment by adrians5j** [comment]
TIP: you can easily get all of these versions (except NPM at the moment) by simply running `yarn webiny about` in your project folder.

**Comment by Alexander-Stulov** [comment]
OS                             darwin (arm64)
Node.js                     v21.3.0
NPX                           10.2.4
Yarn                           3.6.4
NPM                          10.2.4

**Comment by brunozoric** [comment]
hi @Alexander-Stulov 
can you try with Node v18?

**Comment by Alexander-Stulov** [comment]
It works as expected with v18.19.0. Thanks! 
Please update the documentation to reflect that the current Node version is not supported/working.

**Comment by sebaacuna** [comment]
Happened to me too, same solution as Alexander. Hope it gets updated in the documentation.

**Comment by Pavel910** [comment]
@Alexander-Stulov @sebaacuna thanks for confirming, yeah we'll not only update docs but handle nodejs version checks better.
