### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'slice')

### ISSUE THREAD

**Issue by amirhemm** [webiny/webiny-js#3985]
### Version

5.39.2

### Operating System

Mac OS

### Browser

Chrome

### What are the steps to reproduce this bug?

On a fresh install after deploy open the admin for the first time.

### What is the expected behavior?

Open the admin page for the first time.

### What do you see instead?

Blank Page

**Comment by amirhemm** [comment]
I believe the Problem is the upgrade to webpack 5.

**Comment by Pavel910** [comment]
Closed by  #3986. @amirhemm 5.39.3 is out, and this is now fixed! Thanks for reporting! 🙏
