### ISSUE TITLE
Toolbar positioning

### ISSUE THREAD

**Issue by SvenAlHamad** [Webiny/webiny-js#407]
In some cases, when switching between elements that had previously an open toolbar, the toolbar doesn't get positioned correctly. 

![image](https://user-images.githubusercontent.com/3808420/50565810-9b7da100-0d2a-11e9-8612-d1371a9c04cf.png)

**Comment by Pavel910** [comment]
Note to self:
when an element is being deactivated it should also deactivate all active settings plugins.

**Comment by Pavel910** [comment]
@SvenAlHamad at this point I am unable to reproduce the issue. If you manage to catch a reproduction case, please reopen the issue.
