### ISSUE TITLE
Puppeteer is throwing an exception for render function.

### ISSUE THREAD

**Issue by amirhemm** [webiny/webiny-js#4107]
### Version

5.39.3

### Operating System

Mac OS

### Browser

Chrome

### What are the steps to reproduce this bug?

It stopped working all the sudden. Possibly the runtime of the Lambda function got updated automatically.

### What is the expected behavior?

Should update the delivery bucket with the pre-rendered page after publishing.

### What do you see instead?

 ERROR "Protocol error: Connection closed. Most likely the page has been closed." on the cloud watch log

### Possible solution

Set the runtime manually using the Runtime ARN. Or upgrade the code to work with the latest Nodejs 18.x runtime.

**Comment by Pavel910** [comment]
@amirhemm this was fixed in 5.39.5: https://www.webiny.com/docs/release-notes/5.39.5/changelog
