### ISSUE TITLE
fix: in editor, if "Slide Left" animation is selected, scrollbars appear

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#415]
In this image, the image (parent block) has "Slide Left" animation attached.

![image](https://user-images.githubusercontent.com/5121148/50592139-1d88d980-0e93-11e9-96fa-c7837abd6f45.png)

**Comment by SvenAlHamad** [comment]
This is a know bug on the AOS library - the fix is pending on their end. I did manage to fix this on the site render side, but not in the page editor ... I'll review again and check if there is way to fix it in the editor.

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
