### ISSUE TITLE
Add delimiter from Lexical toolbar (headless CMS)

### ISSUE THREAD

**Issue by agnihotrish** [webiny/webiny-js#4215]
### Is your feature request related to a problem? Please describe.

Please add the functionality to add delimiter from lexical toobar in headless CMS. This functionality was present in the legacy Editor.JS toolbar. Even Lexical playground (https://playground.lexical.dev/) has the ability to insert a delimiter/horizontal rule.

### Describe the feature's behavior.

Please add the functionality to add delimiter/horizontal rule from lexical toobar in headless CMS.

### Describe alternatives you've considered.

Continue using Legacy editor.js.

**Comment by Pavel910** [comment]
@agnihotrish following this documentation article you can add any toolbar action you want: https://www.webiny.com/docs/headless-cms/extending/lexical-editor

Thing is, it's impossible to satisfy every project, or know what toolbar is useful to you. We do provide a system of plugins so you can customize the editor in a very straightforward way. It will only take you a few minutes to add that horizontal delimiter plugin yourself.
