### ISSUE TITLE
fix: style "not authorized" admin view

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#423]
![snip20190105_3](https://user-images.githubusercontent.com/5121148/50727657-38bb4980-111e-11e9-9263-03f198c9a4f4.png)

**Comment by doitadrian** [comment]
Old one, closing.

**Comment by daniloff200** [comment]
Well, I should ask, in what it should be fixed?
Centered, font-size change, any other ideas?

**Comment by Ashu96** [comment]
Hey @daniloff200 
Welcome! Here are some links to get you started:
Some instructions about contributing: https://github.com/webiny/webiny-js/blob/master/docs/CONTRIBUTING.md
Our YouTube channel with different videos about the project, how stuff works, etc: https://www.youtube.com/c/Webiny/videos

**Regarding this issue**:

We're looking for something similar to this one:

![image](https://user-images.githubusercontent.com/13612227/94798360-25c2cf80-03ff-11eb-8b12-f57d1b659680.png)


Here is the code responsible for rendering the `Not authorized` view:
https://github.com/webiny/webiny-js/blob/master/packages/app-security/src/admin/plugins/secureRouteError.tsx#L14

We use `emotion` (CSS-in-JS) for writing style. For example, https://github.com/webiny/webiny-js/blob/master/packages/app-mailchimp/src/admin/components/MailchimpElementAdvancedSettings.tsx#L24

Here is the asset used in the sample screenshot:
https://drive.google.com/file/d/1T_BgtSyX5pwm7HHdpElTmZ-w6GA4vkXo/view?usp=sharing

If you have any other questions, please do leave a comment or reach out via [Slack](https://www.webiny.com/slack/) it will be a lot quicker :)
Cheers!

**Comment by aloks98** [comment]
Hey, how I do reach the not authorized page? I have made some changes but cannot figure out how to reach the page.

**Comment by Ashu96** [comment]
Hey @aloks98,
This view is rendered by [SecureRoute](https://github.com/webiny/webiny-js/blob/master/packages/app-security/src/components/SecureRoute.tsx) component, which is used throughout the admin app and other Webiny apps to **secure the route from unauthorized access** as the name suggest.

For example, https://github.com/webiny/webiny-js/blob/master/packages/app-page-builder/src/admin/plugins/routes.tsx#L52
Here if the user doesn't have the required scope `"pb:menu:crud"` [code reference](https://github.com/webiny/webiny-js/blob/master/packages/app-page-builder/src/admin/plugins/routes.tsx#L20), this component will render the `no access view`.

Whenever a user without the required scope visits the [route](https://github.com/webiny/webiny-js/blob/master/packages/app-page-builder/src/admin/plugins/routes.tsx#L50), he will get this error page/view.

**Comment by lokeshvenkatesan** [comment]
I am taking up this issue.

**Comment by aloks98** [comment]
@Ashu96 here is a ss for that
![webiny](https://user-images.githubusercontent.com/45600289/94985933-2337b580-0578-11eb-9efe-6ae6bd26fcc7.png)
