### ISSUE TITLE
Is there any onboarding guide for making my first contributions or knowing the stack quickly?

### ISSUE THREAD

**Issue by dikshantrajput** [webiny/webiny-js#4254]
I have seen the `contributing` file, `code of conduct`, `how to setup guides` and all but is there a specific onboarding guide available specific to this repository So that I can quickly start to contribute? Or something where I can know all the prerequisites before contributing

**Comment by swapnilmmane** [comment]
Hi @dikshantrajput, welcome to the Webiny community, and thank you for your interest in contributing!

Currently, we don't have a dedicated onboarding guide for contributors, as most of the information is covered in our contributing file. However, we can definitely work on improving it with more details.

To help you get familiar with the project, we recommend checking out our [Developer Training Course (beta)](https://www.youtube.com/playlist?list=PL9HlKSQaEuXTGvfbFiBg0u_gOhphvof2r), which provides a solid overview of Webiny.

@dikshantrajput, could you please join our [community Slack](https://www.webiny.com/slack)? We can discuss more about your tech experience, and I can guide you on how to contribute to the project. I’d also be happy to assist you with any questions.

**Comment by dikshantrajput** [comment]
Thanks you for your response. I will check put the resource you suggested!!!

**Comment by swapnilmmane** [comment]
Great, thank you @dikshantrajput!
