### ISSUE TITLE
Save zoom level into localstorage

### ISSUE THREAD

**Issue by SvenAlHamad** [Webiny/webiny-js#432]
At the moment the user can change the zoom level of the page preview, in the page list, but that zoom level resets on each page reload, or when a new page is selected.

The zoom level should be stored in localstorage for better UX.

Reference: https://github.com/Webiny/webiny-js/blob/development/packages/webiny-app-cms/src/admin/plugins/pageDetails/previewContent/PagePreview.js#L60

**Comment by Pavel910** [comment]
Closed in development branch.
