### ISSUE TITLE
Page editor - scroll to top

### ISSUE THREAD

**Issue by SvenAlHamad** [webiny/webiny-js#445]
In page editor, when you have a longer page where you need to scroll down. When you're at the bottom of the page, and then click the cog in the toolbar (where the preview option is located), the page suddenly jumps to the very top.

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
