### ISSUE TITLE
Page preview animations with zoom

### ISSUE THREAD

**Issue by SvenAlHamad** [webiny/webiny-js#446]
The animations are not triggering when there is a zoom applied to the page preview. Do we have any potential options to resolve that. Maybe trigger force refresh when zoom is applied, although how CSS scale works, this might not fix the problem. Another potential solution is to adjust the scroll offset for the zoom percentage. Third option would be to disable animations in page preview completely.

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
