### ISSUE TITLE
Option to remove box shadow once set

### ISSUE THREAD

**Issue by SvenAlHamad** [webiny/webiny-js#447]
At the moment there is no way to remove a box-shadow from an element once it's set. We need to introduce an option to "clear" the applied effect.

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
