### ISSUE TITLE
fix: pages list design

### ISSUE THREAD

**Issue by doitadrian** [Webiny/webiny-js#459]
On site:
![image](https://user-images.githubusercontent.com/5121148/52425705-d2e72680-2afc-11e9-84db-93f8d6bfbf40.png)

In editor:
![image](https://user-images.githubusercontent.com/5121148/52425728-de3a5200-2afc-11e9-924f-b1b659ffc617.png)

**Comment by Pavel910** [comment]
Closing, this is fixed long ago.
