### ISSUE TITLE
Fix CSS positioning / visibility issues with header in preview mode in editor

### ISSUE THREAD

**Issue by doitadrian** [Webiny/webiny-js#471]
You can see that the whole header component is actually present in the DOM, but not visible when in preview mode.

![snip20190228_26](https://user-images.githubusercontent.com/5121148/53591261-e170ad00-3b93-11e9-89d7-6bf2f7939c14.png)

@SvenAlHamad

**Comment by Pavel910** [comment]
Fixed and released!
