### ISSUE TITLE
How to support lik Webiny.configureModule

### ISSUE THREAD

**Issue by geek4go** [Webiny/webiny-js#486]
How to support lik old version Webiny.configureModule('Webiny/Layout/Logo', (Logo)...   customize config component？

**Comment by doitadrian** [comment]
Hi @geek4go,

based on the code snippet you provided, it seems to me that you were referring to the old version of Webiny. To make sure you have the latest, just follow the steps provided here: https://docs.webiny.com/docs/developer-tutorials/local-setup

Let us know if you have any additional questions.

**Comment by geek4go** [comment]
thank you。the configureModule feature replaced by 'webiny-plugins' in the new version?

**Comment by Pavel910** [comment]
@geek4go what you are referring to is an entirely old system, over 1 year old.
We have since abandoned that approach completely.

To use the new Webiny and setup a local development project have a look at the link provided by @doitadrian. Let us know if you need help!

**Comment by geek4go** [comment]
👍
