### ISSUE TITLE
Published web-site does not work in any browser

### ISSUE THREAD

**Issue by IhostVlad** [webiny/webiny-js#487]
Published web-site https://hackernews.z1.webiny.com/ does not work in any browser
Error is identical: `SCRIPT5022: Plugin must have a "name" or "_name" key.`

![image](https://user-images.githubusercontent.com/14352827/54684957-b0e2ba00-4b26-11e9-8563-deccf4d630a6.png)
![image](https://user-images.githubusercontent.com/14352827/54685139-19319b80-4b27-11e9-9905-d235708750a3.png)

**Comment by Pavel910** [comment]
@IhostVlad Weird, it does load normally for me:

![image](https://user-images.githubusercontent.com/3920893/54702998-463a7a00-4b38-11e9-9709-4132a11405e4.png)

I'll test it on Edge, see if I can reproduce the problem.
