### ISSUE TITLE
admin start command fails on Windows

### ISSUE THREAD

**Issue by coreylenertz** [Webiny/webiny-js#515]
Webiny Version: master
OS Platform: Windows

## Problem:

Please refer to docs on set up:
https://docs.webiny.com/docs/developer-tutorials/local-setup

__Starting an app build__
To start an admin app dev build: `cd packages/admin && yarn start`

```
yarn run v1.15.2
warning package.json: No license field
$ PORT=3001 rescripts start
'PORT' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Suggested Solution:

Please use cross-env for start script. 

https://github.com/Webiny/webiny-js/blob/f6a85d725e4ae172233debc5db3f493b41481b05/packages/webiny-cli/src/init/template/packages/admin/package.json#L33

**Comment by Pavel910** [comment]
Hi @coreylenertz,

could you please tell me what terminal are you using on Windows?

I'm using WSL (Windows Subsystem for Linux ) and Hyper terminal, that's the reason I never bumped into this error. I'll definitely add `cross-env`, just wondering what terminal you were using so I can test better in the future. 

Thanks!

**Comment by Pavel910** [comment]
The fix is released in the latest webiny-cli, closing.
