### ISSUE TITLE
Failed to compile flow enabled js files

### ISSUE THREAD

**Issue by coreylenertz** [webiny/webiny-js#517]
Followed local setup docs per https://docs.webiny.com/docs/developer-tutorials/local-setup

`$ cd packages/admin && yarn start`

```
Failed to compile.

../theme/src/layouts/blog.js
SyntaxError: packages\theme\src\layouts\blog.js: Unexpected token, expected ";" (7:5)

   5 | import { Addons } from "webiny-app/components";
   6 |
>  7 | type Props = {
     |      ^
   8 |     children: React.Node
   9 | };
  10 |
```

## This is:

- Bug

## Specifications

  - version: latest
  - OS: Windows
  - Browser: N/A, Error emanates from NodeJS

## Expected Behavior

Flow files should compile without error.

## Actual Behavior

The dev server reports an error when compiling. The start/build process is halted.

## Steps to Reproduce the Problem

1. Follow instructions on local setup docs page. Use windows.
2. After yarn setup, invoke yarn start from the packages/admin folder
3. Dev server starts and error message is displayed.

## Detailed Description

I assume flow needs an adjustment to how it is installed in babel config.

## Possible Solution

No idea.

**Comment by Speedwares** [comment]
Also facing the same issue. Any solution

**Comment by Pavel910** [comment]
@coreylenertz @Speedwares I'll investigate this today on my Windows machine and get back to you as soon as I figure out what's wrong.  Thanks for the report!

**Comment by Pavel910** [comment]
Hey @coreylenertz @Speedwares ,
sorry for the delay, the entire team was really busy with fixes/feature and preparation of the next release.

I finally got to my Windows machine, and I am unable to reproduce this one.
I'm using Windows 10 and Git Bash and everything is building as expected.

What `webiny-cli` package version are you using?

If one of you could push your test project to github so I can clone the exact installation, that would be most helpful. Thanks!
