### ISSUE TITLE
Fonts have increased in size

### ISSUE THREAD

**Issue by doitadrian** [Webiny/webiny-js#521]
![image](https://user-images.githubusercontent.com/5121148/56659215-d1111600-669c-11e9-9a93-8bb058d18181.png)

![image](https://user-images.githubusercontent.com/5121148/56676180-037f3b00-66be-11e9-9a14-2b3008065080.png)

![image](https://user-images.githubusercontent.com/5121148/56676479-acc63100-66be-11e9-95fb-6913d8e4b2ba.png)

**Comment by Pavel910** [comment]
This is fixed and released. Closing.
