### ISSUE TITLE
Error while deploy (detect directory)

### ISSUE THREAD

**Issue by Fi1osof** [Webiny/webiny-js#524]
- Bug

  - version: API v 0.1.0
  - OS: ubuntu
  - Browser: Any

## Expected Behavior
Deploy site

## Actual Behavior
 Deploying /disk_kingstone/var/www/test/webiny/my-project/packages/admin...
{ Error: /disk_kingstone/var/www/test/webiny/my-project/packages/api/disk_kingstone/var/www/test/webiny/my-project/packages/admin/.webiny: ENOENT: no such file or directory, open '/disk_kingstone/var/www/test/webiny/my-project/packages/api/disk_kingstone/var/www/test/webiny/my-project/packages/admin/.webiny'

Duplicated path /disk_kingstone/var/www/test/webiny/my-project/packages/

**Comment by Pavel910** [comment]
Hi @Fi1osof, I'm trying to reproduce this but it all seems to be working just fine (I am using OSX).

Could you specify the exact command used to start a deploy?
I tested both `yarn webiny deploy` (to deploy all apps) and `yarn webiny deploy packages/admin` to deploy just the admin app. Both seem to resolve paths correctly.

Please send as much info as you can, commands used, entire stack of the error, so I can try to pinpoint the problem.

Thanks!

**Comment by Fi1osof** [comment]
Hi @Pavel910,

Sorry, seems it's my error. I start deploy from packages/api. From root of project deployed success.
