### ISSUE TITLE
SSR

### ISSUE THREAD

**Issue by Fi1osof** [Webiny/webiny-js#525]
## This is:
- Feature request

Is SSR mode planing?  (Server-side rendering).
Thanks!

**Comment by Pavel910** [comment]
Hi @Fi1osof, 

absolutely! It is already in the works (we actually have it working in one of our development branches) and we expect it to be released during the next month (May).

Stay tuned! :)

**Comment by Fi1osof** [comment]
@Pavel910 thanks!

**Comment by Pavel910** [comment]
@Fi1osof this is released and is enabled for all sites in our Cloud + all projects bootstrapped by `webiny-cli@2.2.0`. Please give it a try and let us know if you have any feedback regarding this feature.

P.S.
Local SSR testing is also available, just run `webiny start-app site --ssr` (see `--help` for usage).
