### ISSUE TITLE
BUG: no such file or directory, stat '<PROJECT_ROOT>/node_modules/webiny-cli/lib/init/template/.gitignore'

### ISSUE THREAD

**Issue by mstruebing** [Webiny/webiny-js#534]
## This is:
- Bug

## Specifications

  - version: webiny-cli: 2.1.2 (node v12 npm v6.9)
  - OS: Linux <HOSTNAME> 5.1.2-arch1-1-ARCH #1 SMP PREEMPT Wed May 15 00:09:47 UTC 2019 x86_64 GNU/Linux

  - Browser: The bug doesn't occur on the browser ;)

## Expected Behavior

The `webiniy init` command should run through with no error messages and a positive exit status (0)

## Actual Behavior

It says that no file `.gitignore` can be found in `<PROJECT_ROOT>/node_modules/webiny-cli/lib/init/template/.gitignore`.

## Steps to Reproduce the Problem

1. `cd /tmp && mkdir webiny && npm init -y && npm i -D webiny-cli && ./node_modules/.bin/webiny init`

## Detailed Description

When initializing, the tool seems to look for a templates and copy files into my current directory but it doesn't seem to find the `.gitignore` file.

## Possible Solution

I would suggest to add a `.gitignore` to the path where the cli is looking for.

**Comment by mstruebing** [comment]
After looking into the code I can see it's actually there, so I think it will get lost while publishing.

**Comment by Pavel910** [comment]
@mstruebing thanks, will look into it!

**Comment by mstruebing** [comment]
I'm already into it but can't get it to build properly :/

I've tried to add a `.npmignore` and use the `npm pack` command. Maybe this helps you.

**Comment by Pavel910** [comment]
Could you please describe what exactly are you trying to achieve? Are you trying to make it work in your local project or in this repo? I could then help you out.

Also, if you are trying to fix the `webiny-cli` package, feel free to open a pull request so I can see the file changes and help with comments/guidelines.

Thanks for your time :)

**Comment by mstruebing** [comment]
I've tried to do a `yarn install && yarn build` inside the root of the repository.
Then I switched to the `webiny-cli` package and did a `npm pack`.
But when inspecting the resulting `webiny-cli-2.1.0.tgz` there is the needed `.gitignore` present.

**Comment by Pavel910** [comment]
@mstruebing this is fixed and released in the latest version `2.2.0`.

Closing the issue, if you encounter the same problem again, please reopen.
