### ISSUE TITLE
Unabled in import svg and component

### ISSUE THREAD

**Issue by CurtisHumphrey** [Webiny/webiny-js#540]
## This is:
- Bug

## Specifications

  - version: 2.2.2
  - OS: Mac
  - Browser: N/A

## Expected Behavior
When using
```
import { ReactComponent as AddCircleOutline } from "webiny-app-cms/editor/assets/icons/baseline-add_circle-24px.svg";
```
expect AddCircleOutline to be react component

## Actual Behavior
AddCircleOutline is not present

## Steps to Reproduce the Problem
1. Create a new component (like the example in the docs)
2. Add AddCircleOutline to the react return

## Possible Solution
I tried moving the file to be relative and in the same repo but still had the same error

**Comment by Pavel910** [comment]
@CurtisHumphrey this is fixed and released in `webiny-cli@2.2.3`. Please upgrade your CLI and setup a new project. It had something to do with `webiny-rewire` package in the project monorepo, so the fastest way to get going is to setup a blank project using the new version of CLI.

Thanks for reporting, much appreciated! 🍻
