### ISSUE TITLE
yarn webiny deploy fails with error

### ISSUE THREAD

**Issue by arturhefczyc** [Webiny/webiny-js#543]
## This is:
- Bug

## Specifications

  - version: webiny-cli 2.2.4
  - OS: MacOSX
  - Browser: ANY

## Expected Behavior

yarn webiny deploy
should deploy current website to cloud.webiny.com without error.

## Actual Behavior

I have installed everything locally following instructions in the online documentation.
First deployment ran correctly without any issues.

However, after working for a while on the website, modified theme, added category and new page, I tried to run deploy again but it fails with the following error:

```
 $ yarn webiny deploy
yarn run v1.16.0
$ '/net-webiny/node_modules/.bin/webiny' deploy

＞ Deploying api (/net-webiny/packages/api)
ℹ Running build...
$ cross-env NODE_ENV=production webpack --config=webpack.config.js --progress
module.js:550
    throw err;
    ^

Error: Cannot find module '..'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/net-webiny/packages/api/node_modules/.bin/cross-env:4:16)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
webiny deploy [name]

Deploy an app or a function by name. If no name is specified, all apps and
functions will be deployed.

Positionals:
  name  Package name to deploy (optional)

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]
  --ci       Set this flag when running in a CI environment.
                                                      [boolean] [default: false]

TypeError: format.replace is not a function
    at formatString (/net-webiny/node_modules/webiny-cli/lib/logger.js:14:20)
    at Object.error (/net-webiny/node_modules/webiny-cli/lib/logger.js:26:27)
    at Deploy.deployPackage (/net-webiny/node_modules/webiny-cli/lib/deploy/index.js:193:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
error Command failed with signal "SIGINT".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
## Steps to Reproduce the Problem

I do not have actual steps. As explained. Installed local following documentation.
First deployment worked, next, after some changes to the website does not.

**Comment by Pavel910** [comment]
@arturhefczyc thanks for the report, just to verify: you did run the `webiny deploy` from the root of your project, right?

**Comment by arturhefczyc** [comment]
Double-checked and yes, ran it from the root of my project.

Artur

**Comment by arturhefczyc** [comment]
I did some more investigating on the issue. Created a brand new website on cloud.webiny.com and tried to deploy to this new website and still the same error.
So it looks like even the first deploy to website on cloud.webiny.com fails.

I guess there might be something with my local system but I cannot figure out what.

**Comment by Pavel910** [comment]
@arturhefczyc would you be so kind and create a github repo for the project you are trying to deploy?
I tried to deploy my own custom project to both existing and new site and everything works fine for me.

I will gladly take a look at your project to figure out what's wrong, so please create a repo I can use and I'll dive into it right away.

Cheers!

**Comment by arturhefczyc** [comment]
All our code is on github already. It is just not a public repo.

Please send me your github user name and I will grant you access to the repository.

Artur

**Comment by Pavel910** [comment]
It's `Pavel910`.

**Comment by arturhefczyc** [comment]
Ah, ok. I found your account and sent you invite for the repository. Please feel free to connect and check it out.

**Comment by arturhefczyc** [comment]
OK, I am doing some more tests and experiments. I committed/pushed all my code to github repo and then cloned it into fresh folder on my local machine. Now the deploy seems to be running ok. It is not finished yet but it is past the point where it showed error before.

**Comment by arturhefczyc** [comment]
Deploy finished kind of successfully but also showed an error at the end:
```
✔ Deploys created successfully!
＞ Activating api...
＞ Activating admin...
＞ Activating site...
✔ Deploy process completed!

ℹ Your apps/functions were deployed to these URLs:
＞ https://xyz.z1.webiny.com/function/api
＞ https://xyz.z1.webiny.com/admin
＞ https://xyz.z1.webiny.com/
error Command failed with signal "SIGINT".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by arturhefczyc** [comment]
Actually, one question about the deploy process. Does it also copy the database content to cloud? I do not see any of my new pages or categories on the cloud after deployment.

**Comment by arturhefczyc** [comment]
Yes, deployment ran kind of successfully after cloning the repository locally. But from the new folder on my local machine the website does not run. I mean all application start successfully, connect to local  mongodb but the admin interface does not show and the web site does not show either.
All I get in the browser is blank, empty page.

**Comment by arturhefczyc** [comment]
I am sorry for spamming you with comments. I am just working on it and trying to get it working. And I am finding new details which I think might be helpful to you.

I am on my website on webiny cloud now, after above successful deployment but none of my changes seem to be deployed. Not just database content.
I have created new page layout for a new category which is part of the filesystem structure. After deployment the new layout is not available on the cloud either.
I wonder if any of my changes were actually deployed.

**Comment by arturhefczyc** [comment]
What node.js version does webiny required?

**Comment by Pavel910** [comment]
@arturhefczyc To answer the questions first:
1) minimum nodejs version is `8.10`, that's what all code gets transpiled to.
2) database content is not copied during deploy. Synchronizing DB is a complex thing to execute, and at this point we haven't addressed it yet, as it requires some proper planning, so it is on the TODO list.
3) The error `error Command failed with signal "SIGINT".` can be safely ignored, it sometimes happens after the deploy is finished, but has nothing to do with the deploy itself.
4) `But from the new folder on my local machine the website does not run` - make sure you copy the `.env` file in the root of your project, because it is added to `.gitignore`, so when you make a clone - it's not there. I will make a not of this and add the necessary checks to the CLI.

Regarding the project:
I cloned the repo, installed dependencies and ran local site and admin successfully (it worked immediately). I could immediately see your changes to the website (primary colors, dark footer).

After verifying the local project is running fine, I ran full deploy (`yarn wby deploy`).

![image](https://user-images.githubusercontent.com/3920893/59146656-27d67300-89f1-11e9-9795-dec7254cc1fc.png)

Then I modified the footer, and re-deployed the site `yarn wby deploy site`:
![image](https://user-images.githubusercontent.com/3920893/59146667-48063200-89f1-11e9-9a00-cb5499e126f7.png)

Note the `Cheers!` in the footer :)
You can view the site here: https://tigase-net-pavel.z1.webiny.com/

(NOTE: sometimes you do need to refresh the newly deployed site a few times, as there is a caching mechanism in the background, and we are still tweaking the behavior of cache invalidation).

All that said, I wonder what's going wrong on your side...

**Comment by arturhefczyc** [comment]
Thanks a lot for comprehensive help.

Yes, after careful replicating all the steps, step by step I was able to successfully redeploy Webiny to a website on cloud.webiny.com.

But it works from a new, fresh directory to which I cloned the git repo. I cannot get it working from my old, original folder where I first created the Webiny website and committed to git repo. But this is not a big deal. As long as I can get the whole process working, I am OK with it. Even if for time being I have to clone to fresh dir from time to time.

What confused me the most is that neither database or files are deployed during the proces. So, it is not possible to fully work on the website locally with all the content and then, once everything is ready deploy it to the web. This is not a big issue either as long as I understand it now.

Many website development services with such a workflow that you can modify the website locally and deploy to the cloud allow also the DB deployment and all files. Which all can be copied in both ways.
My suggestion is to make a note in your documentation that the DB and files are not deployed with the deploy command.

Once again thank you for your help.

**Comment by arturhefczyc** [comment]
Hi, just heads up.
The original error/problem reported in the ticket happened again.

I was actually able to solve it without cloning to a fresh directory. All I did was this:
```
$ rm -rf node_modules
$ yarn
```
After that it all started to work again.

**Comment by Pavel910** [comment]
@arturhefczyc hopefully we'll be able to somehow identify and replicate this problem. It's difficult to figure out what's going on if there are no "steps-to-reproduce".

Regarding DB and files, we'll add it to the docs, sure. 
Do shoot your ideas/requests our way, we'll add them to our wishlist bucket.

Cheers!
