### ISSUE TITLE
Changing header font style

### ISSUE THREAD

**Issue by arturhefczyc** [Webiny/webiny-js#547]
## This is:
- Question

## Specifications

  - version: 2.2.4
  - OS: Mac
  - Browser: ANY

## Detailed Description

I am trying to change style, font, spacing and other attributes for h1 header. I make changes in file theme/src/style/elements/typography.scss and edit '.webiny-cms-typography-h1' element definition.

However, my changes have no effect on my local working copy of the website. It seems that the system detects that I changed the file because I can see in the terminal message "compiling..." after saving the file.

So my question is how to correctly change the style of selected element.

1. Am I changing the correct file?
1. Assuming this is correct file, do I need to do anything else to apply my changes on the website?
1. Should existing pages pickup the change right away or there is something else I need to do?

thank you for your help.
Artur

**Comment by Pavel910** [comment]
You don't need to do anything. Our apps use `react-scripts` (so it's basically a create-react-app), and there is no extra magic on top of it. It is simple React + Sass, once it compiles it has to work.

NOTE: `.webiny-cms-typography-h1` class is only used in the <h1> typography inserted in the Page Editor.

**Comment by Pavel910** [comment]
Have a look at the compiled styles, do they reflect your changes?

![image](https://user-images.githubusercontent.com/3920893/59249257-9f401880-8c24-11e9-9109-ec332f83a70f.png)

**Comment by arturhefczyc** [comment]
Yes, this works perfectly well. It does even automatically updates the website when I change the file on drive.
My mistake was that I was changing typography for h1 when I actually used h2 element on website. Hence the change was not making any effect.

Thank you for your help.
