### ISSUE TITLE
CMS Category examples

### ISSUE THREAD

**Issue by arturhefczyc** [webiny/webiny-js#548]
## This is:
- Feature request
- Idea

There are 2 categories out of the box for Static page and Blog. However, they are both the same in the theme code, the same layout. Basically empty page. 
If I want to create a new Page then regardless which category I choose I always end-up with an empty page to fill from scratch.

It would be really helpful to have the blog Category and Layout different with predefined elements at least as a code example for further tuning. And also good starting point for developing own categories and layouts.

Ideally, the blog category and layout should be more like a typical blog out of the box.

**Comment by SvenAlHamad** [comment]
I agree. It would be a nice complementary feature to kind of define a starting position for when creating a new page inside a certain category. 
We will explore the option for one of the upcoming releases.

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
