### ISSUE TITLE
Basic website statistics

### ISSUE THREAD

**Issue by arturhefczyc** [Webiny/webiny-js#549]
## This is:

- Feature request
- Idea

Some basic website/page stats are necessary. At least page views. So we could know how much traffic the website gets.

Alternatively an easy way to integrate with Google Analytics is a must have feature.

**Comment by SvenAlHamad** [comment]
Hi @arturhefczyc,

for statistics, it's best just to use google analytics. We don't have a plan to develop anything specifically for Webiny as there are more than enough tools out there that you can easily embed to your site.

To embed a 3rd party tool like google analytics, you can use the google tag manager integration. Google tag manager allows you to embed any 3rd party javascript to Webiny. You will find the integration in your main menu. You will also need to register for a free google tag manager account here: https://tagmanager.google.com/

Hope this helps.

**Comment by Pavel910** [comment]
The `packages/site/public/index.html` file is the place where you can add whatever extra javascript you may need. Each app has its own `public/index.html`.

**Comment by arturhefczyc** [comment]
Ok, makes sense, thank you.
