### ISSUE TITLE
Is there a way to embed JavaScript code on page

### ISSUE THREAD

**Issue by arturhefczyc** [Webiny/webiny-js#550]
## This is:
- Question

We are using external payment gateway and subscription service for our products. So I would like to have a page with information about our products with "subscribe" or "Checkout" button or
dynamically populated list of products with current prices.
We can easily do this by embedding ready to use JavaScript code provided by external service.

However, I cannot find a way to add JavaScript code to the page content (static or blog).

**Comment by SvenAlHamad** [comment]
The best way to embed certain javascript would be by using google tag manager, as explained in this issue #549. 
The CMS doesn't allow embedding JS code directly ... although we might explore this option at a later stage maybe. Let me know how you get along with google tag manager for now.

**Comment by arturhefczyc** [comment]
Thank you.
