### ISSUE TITLE
Only 10 categories in a list when new page creating.

### ISSUE THREAD

**Issue by roman-vabishchevych** [webiny/webiny-js#560]
Only 10 categories in a list when new page creating.

## This is:
- Bug

## Expected Behavior
Expect a full list of categories.

## Actual Behavior
Got only 10 categories

## Steps to Reproduce the Problem
1. Create more than 10 categories.
2. Try to create a new page.
3. In popup window "Select a category" you'll get only 10 categories.

## Possible Solution
in file ’webiny-app-cms/admin/views/Pages/CategoriesDialog.js’ need to correct query:
```
const loadCategories = gql`
    query ListCategories($sort: JSON) {
        cms {
            listCategories(
              sort: $sort
              perPage: 666 //add perPage param plz
            ) {
                data {
                    id
                    name
                    url
                }
            }
        }
    }
`;
```

**Comment by Pavel910** [comment]
@roman-vabishchevych this is fixed. We're releasing next version on Tuesday, so stay tuned :) 🍻

**Comment by roman-vabishchevych** [comment]
🤩
