### ISSUE TITLE
Add filter by category 

### ISSUE THREAD

**Issue by roman-vabishchevych** [webiny/webiny-js#561]
## This is:
- Feature request

Now I have more than 97 pages, and filter by category must-have in this case.

<img width="494" alt="image" src="https://user-images.githubusercontent.com/4134474/64101492-aafc3080-cd76-11e9-94bb-732a81c52b9d.png">

**Comment by Pavel910** [comment]
Hi @roman-vabishchevych, thanks for your request! We are currently working on our next milestone which will prepare Webiny for self-hosting on AWS using Serverless Framework (their new Components, to be more specific), and we will include this feature in the next release.

After the release we will shut down our Cloud, but we will be glad to help you migrate your website and prepare it for self-hosting. We'll get in touch with you after the official release :)

Cheers! 🍻

**Comment by roman-vabishchevych** [comment]
You are the best, guys! 
Thanks for your work.

I read your repo every day and made 3 sites. 
We wrote a lot of plugins – https://gitlab.com/SE7ENSKY/se7ensky-plugins

At now I serve these sites on DigitalOcean and glad to hear about self-hosted AWS, cause cloud was not handy for us. Say how we can support you, guys?

**Comment by Pavel910** [comment]
Wow! This is so cool, great job! 🎉 
That's an impressive set of plugins you have there 👏 Glad you found your way around Webiny without even asking a question, but if you do have questions - please do reach out!

Our next release will introduce some minor changes to the Page Builder plugins (we uncovered some bad decisions along the way), and I will be glad to jump on your plugins repo and help you quickly migrate them so you don't waste your time. We'll discuss it later once there is the next Webiny version out (I will also provide you with the DB migration script as it involves some data fixing).

At this point, simply continue working as you were and send all the bugs and feature requests our way :) Thanks for your offer. Once we push the next release through the door, it will be much easier to collaborate. 

P.S. I noticed you have a plugin `adminOnBoarding` which renders a hidden div to disable our built-in plugin. You can easily `unregister` any plugins you wish, by doing:
```js
import { registerPlugins, unregisterPlugin } from "webiny-plugins";
// Register all the plugins
registerPlugins(...);

// Now unregister the ones you don't need
unregisterPlugin("toolbar-onboarding");
unregisterPlugin("...");
```

P.P.S. would you care publishing some of your plugins to `npm` later on? Maybe other people would find them useful and we would be glad to display them on our `plugins` page (coming with the next release). We could introduce a naming convention like `webiny-plugin-slider-block`, etc. Tell us what you think about it.

**Comment by roman-vabishchevych** [comment]
Thanks, Pavel! 
Of course, we'll publish our plugins to npm, just we are waiting for the new Webiny release :)

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
