### ISSUE TITLE
How soon is the headless module coming?

### ISSUE THREAD

**Issue by wc-matteo** [Webiny/webiny-js#563]
Is it something that still far off? Any chance it's ready for the year?

**Comment by Pavel910** [comment]
Hi @wc-matteo,

currently we are working on self-hosting using `serverless components` to allow anyone to deploy Webiny to their own AWS account (and later multi-cloud). We're going 100% open-source, and our current Cloud offering will be shut down.

Headless is the next thing we'll be focusing on after self-hosting is done. It is partially done, but still requires a decent amount of work. We are hoping to have it by the end of this year.

If you're interested, please subscribe to our newsletter and you'll receive all our updates.

Cheers!

**Comment by wc-matteo** [comment]
Thanks a lot for the info. Great project!
