### ISSUE TITLE
Bring carousel component in the page builder to use in the page. 

### ISSUE THREAD

**Issue by choudharypravesh03** [webiny/webiny-js#564]
## This is:

- Question

## Specifications

  - version: 1
  - OS: Mac
  - Browser: Chrome

## Expected Behavior
When I add a carousel component from Storybook to the local code and register plugin, I should be able to see the component in the page builder so that I can drag and drop it to my page.

## Actual Behavior
When I add carousel to my local code and register plugin, I need that Carousel component in my page builder so that I can add it to my page. But I am not able to see it there.

## Detailed Description
Can you please help out for a way to do this ?

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
