### ISSUE TITLE
Cannot login to admin app. The site does not show up, errors in the console.

### ISSUE THREAD

**Issue by pavelhov** [webiny/webiny-js#566]
When I try to login to the admin site, I get Invalid login response. 

Username: admin@webiny.com
Password: 12345678
When I try to access the site app I see the loading spinner but nothing else. Checked the console and saw null pointers.

I fallowed the init guide 
https://docs.webiny.com/docs/developer-tutorials/local-setup

Am I missing something?

**Comment by Pavel910** [comment]
Hi @pavelhov, sorry you ran into issues. However, we are about to release a huge upgrade to the system, self-hosting, serverless framework, Cognito authentication, so the problem you are seeing will most probably be gone. If you are interested in trying it, please subscribe to our newsletter and you'll be notified.

We are working hard on this new release and it will be out in the upcoming weeks, so stay tuned!
Thanks for trying out Webiny, we hope you'll have a better time with the next release :) 🍻

**Comment by veerjainATgmail** [comment]
Hi @Pavel910 , is form-builder part of upcoming upgrade? thanks. mj.

**Comment by Pavel910** [comment]
@veerjainATgmail Form builder is scheduled for second week of November, if I remember our plan correctly :) Next week we're launching the next major release of Webiny, with self-hosting, and shortly after that the Form Builder is due.

**Comment by pavelhov** [comment]
Looking forward to the next release 👍
