### ISSUE TITLE
development branch .. build error (ubuntu 18.04) fsevents

### ISSUE THREAD

**Issue by veerjainATgmail** [webiny/webiny-js#569]
Build error with development branch.

## This is: Bug
- Bug
Log:
330-15ikb:~/webiny-js$ git status
On branch development
Your branch is up to date with 'origin/development'.
nothing to commit, working tree clean
330-15ikb:~/webiny-js$ yarn 
yarn install v1.16.0
[1/4] Resolving packages...
[2/4] Fetching packages...
error fsevents@2.1.1: The platform "linux" is incompatible with this module.
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
330-15ikb:~/webiny-js$ date
Fri Oct 25 09:38:10 IST 2019

## Specifications
  - version: Latest development branch
  - OS: Ubuntu
  - Browser: NA

## Expected Behavior
  "optionalDependencies": {
    "fsevents": "^2.0.7"
  },

## Actual Behavior
yarn fails with error

## Steps to Reproduce the Problem
yarn install

**Comment by veerjainATgmail** [comment]
making     "fsevents": "^2.0.7" as optionalDependencies solve this issue.

**Comment by veerjainATgmail** [comment]
Thanks. :+1:

**Comment by gomonkey** [comment]
After you fix it, I still have the same error 

```
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
```

**Comment by Ashu96** [comment]
Hey @gomonkey 

BTW, which version of `webiny` and OS are you using?

**Comment by gomonkey** [comment]
@Ashu96  I don't know which version is it, I think is the last version of the branch. 
I just follow the instructions in the documentation [here](https://docs.webiny.com/docs/get-started/quick-start)
The server is Ubuntu 18.04 (64-bit), same error as reported in this issue.

**Comment by Pavel910** [comment]
@gomonkey that's not an error, just an `info`. For example, for `OSX` that dependency works fine so it will be installed. For Windows, it will simply skip that dependency but print that `info` to tell you that it's `Excluding it from installation.`.
