### ISSUE TITLE
GraphQL API URL returns "Internal server error"

### ISSUE THREAD

**Issue by D40373764** [webiny/webiny-js#574]
## This is:

- Bug

## Specifications

  - version: 2.0.0
  - OS: macOS Catalina
  - Browser: Chrome

## Expected Behavior

Open the GraphQL API URL - you should see a GraphQL playground!

## Actual Behavior

Open the GraphQL API URL and it shows {"message": "Internal server error"}

## Steps to Reproduce the Problem

1. From the command line run "webiny create webiny-cms".
2. Update the api/.env.json file to set the MONGODB_SERVER and MONGODB_NAME properties.
3. From the command line run "webiny deploy-api".
4. Wait 10 minutes and open GraphQL API URL: https://d1mknguhssca1d.cloudfront.net/graphql

## Detailed Description

I am using Heroku mLab MongoDB add-on and it is publicly available.
My AWS account has 2 buckets created.

**Comment by D40373764** [comment]
I am seeing the following error in lambda log.

2019-10-30T19:21:54.239Z ed045ebe-3fa2-4233-924e-610090695cb6 ERROR Invoke Error
{
    "errorType": "MongoParseError",
    "errorMessage": "Invalid connection string",
    "stack": [
        "MongoParseError: Invalid connection string",
        "    at parseConnectionString (/var/task/handler.js:184568:21)",
        "    at connect (/var/task/handler.js:187546:3)",
        "    at ConnectOperation.execute (/var/task/handler.js:187469:5)",
        "    at /var/task/handler.js:44735:26",
        "    at new Promise (<anonymous>)",
        "    at executeOperation (/var/task/handler.js:44728:10)",
        "    at MongoClient.connect (/var/task/handler.js:66316:10)",
        "    at Function.MongoClient.connect (/var/task/handler.js:66479:22)",
        "    at init (/var/task/handler.js:258571:47)",
        "    at config_0 (/var/task/handler.js:258579:20)"
    ],
    "name": "MongoParseError"
}

My MongoDB setting are:
    "MONGODB_SERVER": "mongodb://****:****@ds141238.mlab.com:41238",
    "MONGODB_NAME": "heroku_jj1p4961",

I guess my "MONGODB_SERVER" string is wrong. what's should be the correct format?
Thank you!

**Comment by naterenbarger** [comment]
I am having a similar issue. Looking at the CloudWatch logs it appears to be an issue with the Mongo connection.  
"MongoParseError: Invalid connection string",
"    at parseConnectionString (/var/task/handler.js:147281:21)"
and also
"Error: Apollo Server requires either an existing schema, modules or typeDefs",
"    at ApolloServer.initSchema (/var/task/handler.js:66062:23)"

I am using MongoDB Atlas and have set up the IP whitelist with 0.0.0.0/0. It also requires a user to be created and I attempted the use the format user:password@mongo.db.server.url as the MONGODB_SERVER in the api/.env.json. Is there another format or variable that should be used for the Mongo connection?

**Comment by doitadrian** [comment]
The connection string should look something like this:

`mongodb+srv://{USER}:{PASSWORD}@atlastest-kvgdz.mongodb.net/test?retryWrites=true&w=majority`

**Comment by naterenbarger** [comment]
Updating the MONGODB_SERVER variable in the api/.env.json to match that connection string worked for me.

**Comment by doitadrian** [comment]
Awesome @naterenbarger!

Did this work for you too @D40373764 ?

**Comment by D40373764** [comment]
I use Atlas MongoDB and it is working. Not sure why Heroku mLab is not working.
Thank you!

**Comment by doitadrian** [comment]
Awesome, we'll revisit the mLab issue if it happens again in the future. Closing this one!
