### ISSUE TITLE
API Gateway Timeout

### ISSUE THREAD

**Issue by sihutch** [webiny/webiny-js#576]
Hi,

How is the files module able to handle large files that exceed the 29 second upper limit for API Gateway timeouts (see: https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html)

**Comment by sihutch** [comment]
Thanks for the reply. On their own, AWS pre-signed URLs are not very secure. Can you please provide some details on anything that you have done to secure them further

**Comment by doitadrian** [comment]
Hi @sihutch,

just a tiny note - we're using pre-signed POST payloads, not pre-signed URLs.

Additionally, the GQL field that's responsible for delivering this payload is not publicly available. Only logged in users (with proper security role) can access it. This can be further controlled with our built-in ACL.

Feel free to let me know if you have additional questions.

Thank you!
