### ISSUE TITLE
Deploy-api fails with getPreSignedPostPayload doesn't exist

### ISSUE THREAD

**Issue by naterenbarger** [webiny/webiny-js#579]
## This is:

- Bug

## Specifications

  - version: 2.0.0
  - OS: Ubuntu 19.04
  - Browser: Firefox

## Expected Behavior

`webiny deploy-api` should successfully deploy the api.

## Actual Behavior

The deploy fails part way through with the error <path to project>/node_modules/@webiny/api-files/plugins/resolvers/utils/getPreSignedPostPayload doesn't exist

## Steps to Reproduce the Problem

1. Create a new webiny project
2. webiny depoly-api

## Detailed Description

I was able to find the file but it the file name is a different case. It's looking for:
getPreSignedPostPayload
Actual filename is:
getPresignedPostPayload

Locally renaming the file with a capital S and re-running webiny deploy-api worked and deployed the api successfully. 

## Possible Solution

Rename the file 
api-files/plugins/resolvers/utils/getPresignedPostPayload
to
api-files/plugins/resolvers/utils/getPreSignedPostPayload

**Comment by doitadrian** [comment]
Thanks a lot @naterenbarger.

I will fix this, and try to enforce an eslint rule, so this doesn't repeat.
