### ISSUE TITLE
getPreSignedPostPayload build failure issue

### ISSUE THREAD

**Issue by rpalmite** [webiny/webiny-js#583]
## This is:

- Bug

## Specifications

  - version: 2.0.0 (webiny --version)
  - OS: Linux 900X4B 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
  - Browser: Version 78.0.3904.70 (Official Build) (64-bit)

## Expected Behavior

API should run

## Actual Behavior

When attempting to deploy the api using defaults (local) I get the following build failed message:

> webiny deploy-api
This is the first deploy of local environment, so it may take a few minutes.
Here's 🍺 to make the time pass faster :)
[
  '/home/russell/development/cms/webiny/webiny-project/my-project/node_modules/@webiny/api-files/plugins/resolvers/uploadFile.js\n' +
    "Module not found: Error: Can't resolve './utils/getPreSignedPostPayload' in '/home/russell/development/cms/webiny/webiny-project/my-project/node_modules/@webiny/api-files/plugins/resolvers'\n" +
    "resolve './utils/getPreSignedPostPayload' in '/home/russell/development/cms/webiny/webiny-project/my-project/node_modules/@webiny/api-files/plugins/resolvers'\n" +
    '  using description file: /home/russell/development/cms/webiny/webiny-project/my-project/node_modules/@webiny/api-files/package.json (relative path: ./plugins/resolvers)\n' +
    '    using description file: /home/russell/development/cms/webiny/webiny-project/my-project/node_modules/@webiny/api-files/package.json (relative path: ./plugins/resolvers/utils/getPreSignedPostPayload)\n' +
    '      no extension\n' +
    "        /home/russell/development/cms/webiny/webiny-project/my-project/node_modules/@webiny/api-files/plugins/resolvers/utils/getPreSignedPostPayload doesn't exist\n" +
    '      .wasm\n' +
    "        /home/russell/development/cms/webiny/webiny-project/my-project/node_modules/@webiny/api-files/plugins/resolvers/utils/getPreSignedPostPayload.wasm doesn't exist\n" +
    '      .mjs\n' +
    "        /home/russell/development/cms/webiny/webiny-project/my-project/node_modules/@webiny/api-files/plugins/resolvers/utils/getPreSignedPostPayload.mjs doesn't exist\n" +
    '      .js\n' +
    "        /home/russell/development/cms/webiny/webiny-project/my-project/node_modules/@webiny/api-files/plugins/resolvers/utils/getPreSignedPostPayload.js doesn't exist\n" +
    '      .json\n' +
    "        /home/russell/development/cms/webiny/webiny-project/my-project/node_modules/@webiny/api-files/plugins/resolvers/utils/getPreSignedPostPayload.json doesn't exist\n" +
    '      as directory\n' +
    "        /home/russell/development/cms/webiny/webiny-project/my-project/node_modules/@webiny/api-files/plugins/resolvers/utils/getPreSignedPostPayload doesn't exist\n" +
    '[/home/russell/development/cms/webiny/webiny-project/my-project/node_modules/@webiny/api-files/plugins/resolvers/utils/getPreSignedPostPayload]\n' +
    '[/home/russell/development/cms/webiny/webiny-project/my-project/node_modules/@webiny/api-files/plugins/resolvers/utils/getPreSignedPostPayload.wasm]\n' +
    '[/home/russell/development/cms/webiny/webiny-project/my-project/node_modules/@webiny/api-files/plugins/resolvers/utils/getPreSignedPostPayload.mjs]\n' +
    '[/home/russell/development/cms/webiny/webiny-project/my-project/node_modules/@webiny/api-files/plugins/resolvers/utils/getPreSignedPostPayload.js]\n' +
    '[/home/russell/development/cms/webiny/webiny-project/my-project/node_modules/@webiny/api-files/plugins/resolvers/utils/getPreSignedPostPayload.json]\n' +
    ' @ /home/russell/development/cms/webiny/webiny-project/my-project/node_modules/@webiny/api-files/plugins/resolvers/uploadFile.js 12:54-96\n' +
    ' @ /home/russell/development/cms/webiny/webiny-project/my-project/node_modules/@webiny/api-files/plugins/graphql.js\n' +
    ' @ /home/russell/development/cms/webiny/webiny-project/my-project/node_modules/@webiny/api-files/plugins/index.js\n' +
    ' @ ./handler.js',
  '/home/russell/development/cms/webiny/webiny-project/my-project/node_modules/@webiny/api-files/plugins/resolvers/uploadFiles.js\n' +
    "Module not found: Error: Can't resolve './utils/getPreSignedPostPayload' in '/home/russell/development/cms/webiny/webiny-project/my-project/node_modules/@webiny/api-files/plugins/resolvers'\n" +
    "resolve './utils/getPreSignedPostPayload' in '/home/russell/development/cms/webiny/webiny-project/my-project/node_modules/@webiny/api-files/plugins/resolvers'\n" +
    '  using description file: /home/russell/development/cms/webiny/webiny-project/my-project/node_modules/@webiny/api-files/package.json (relative path: ./plugins/resolvers)\n' +
    '    using description file: /home/russell/development/cms/webiny/webiny-project/my-project/node_modules/@webiny/api-files/package.json (relative path: ./plugins/resolvers/utils/getPreSignedPostPayload)\n' +
    '      no extension\n' +
    "        /home/russell/development/cms/webiny/webiny-project/my-project/node_modules/@webiny/api-files/plugins/resolvers/utils/getPreSignedPostPayload doesn't exist\n" +
    '      .wasm\n' +
    "        /home/russell/development/cms/webiny/webiny-project/my-project/node_modules/@webiny/api-files/plugins/resolvers/utils/getPreSignedPostPayload.wasm doesn't exist\n" +
    '      .mjs\n' +
    "        /home/russell/development/cms/webiny/webiny-project/my-project/node_modules/@webiny/api-files/plugins/resolvers/utils/getPreSignedPostPayload.mjs doesn't exist\n" +
    '      .js\n' +
    "        /home/russell/development/cms/webiny/webiny-project/my-project/node_modules/@webiny/api-files/plugins/resolvers/utils/getPreSignedPostPayload.js doesn't exist\n" +
    '      .json\n' +
    "        /home/russell/development/cms/webiny/webiny-project/my-project/node_modules/@webiny/api-files/plugins/resolvers/utils/getPreSignedPostPayload.json doesn't exist\n" +
    '      as directory\n' +
    "        /home/russell/development/cms/webiny/webiny-project/my-project/node_modules/@webiny/api-files/plugins/resolvers/utils/getPreSignedPostPayload doesn't exist\n" +
    '[/home/russell/development/cms/webiny/webiny-project/my-project/node_modules/@webiny/api-files/plugins/resolvers/utils/getPreSignedPostPayload]\n' +
    '[/home/russell/development/cms/webiny/webiny-project/my-project/node_modules/@webiny/api-files/plugins/resolvers/utils/getPreSignedPostPayload.wasm]\n' +
    '[/home/russell/development/cms/webiny/webiny-project/my-project/node_modules/@webiny/api-files/plugins/resolvers/utils/getPreSignedPostPayload.mjs]\n' +
    '[/home/russell/development/cms/webiny/webiny-project/my-project/node_modules/@webiny/api-files/plugins/resolvers/utils/getPreSignedPostPayload.js]\n' +
    '[/home/russell/development/cms/webiny/webiny-project/my-project/node_modules/@webiny/api-files/plugins/resolvers/utils/getPreSignedPostPayload.json]\n' +
    ' @ /home/russell/development/cms/webiny/webiny-project/my-project/node_modules/@webiny/api-files/plugins/resolvers/uploadFiles.js 12:54-96\n' +
    ' @ /home/russell/development/cms/webiny/webiny-project/my-project/node_modules/@webiny/api-files/plugins/graphql.js\n' +
    ' @ /home/russell/development/cms/webiny/webiny-project/my-project/node_modules/@webiny/api-files/plugins/index.js\n' +
    ' @ ./handler.js'
]

Build failed!

## Steps to Reproduce the Problem

1. sudo npm -g install @webiny/cli
2. webiny create my-project
3. cd my-project
4. vi api/.env.json
5. edit "MONGODB_SERVER" line to specify "mongo-cluster-<my-cluster-id>.gcp.mongodb.net",
6. log into mongodb atlas and create database/collection webiny/webiny
7. edit "MONGODB_NAME" to have value "webiny"
8. webiny deploy-api
9. see actual behavior section

## Detailed Description

The change I'm asking for is unclear to me at this point. Support is really what I need. But likely a documentation update that would help me avoid this build issue would be appreciated -- which I would be happy to make if I can get past this.

## Possible Solution

N/A

Posting this as a bug because the documentation suggested reaching out through github to get build support. Thanks in advance!!!

**Comment by Pavel910** [comment]
@rpalmite this is released! In your project run `yarn upgrade` and you're good to go.
To be sure you got the fix, run `yarn list @webiny/api-files`, should be `2.0.1`

**Comment by rpalmite** [comment]
This still isn't working for me. Not sure what's wrong.

$ yarn list @webiny/api-files
yarn list v1.19.1
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ @webiny/api-files@2.0.1
Done in 5.12s.


$ webiny deploy-api --env=dev --debug
This is the first deploy of dev environment, so it may take a few minutes.
Here's 🥤 to make the time pass faster :)
💡 Loaded dev environment from /home/russell/development/cms/webiny/webiny-js/examples/api/.env.json...

  DEBUG ─ Collecting components from the template.
  DEBUG ─ Executing the template's components graph.
  DEBUG ─ Creating new user pool.
  DEBUG ─ Created user pool us-east-1_1lNGoJgQQ.
  DEBUG ─ Creating new user pool client.
  DEBUG ─ Loaded user ID: a9374756-516c-4700-acbf-801ae4118457
  DEBUG ─ Tracking is ENABLED
  DEBUG ─ Tracking component: @webiny/serverless-aws-cognito-user-pool (deploy)
  DEBUG ─ Starting deployment of lambda gkiiq5j-9ha0xfn to the us-east-1 region.
  DEBUG ─ No role provided for lambda gkiiq5j-9ha0xfn.
  DEBUG ─ Syncing role gkiiq5j-7maur2s in region us-east-1.
  DEBUG ─ Creating role gkiiq5j-7maur2s.
  DEBUG ─ Saved state for role gkiiq5j-7maur2s.
  DEBUG ─ Role gkiiq5j-7maur2s was successfully deployed to region us-east-1.
  DEBUG ─ Deployed role arn is arn:aws:iam::247750974130:role/gkiiq5j-7maur2s.
  DEBUG ─ Packaging lambda code from /home/russell/development/cms/webiny/webiny-js/components/serverless-files/dist/functions/manageFiles.
  DEBUG ─ Creating lambda gkiiq5j-9ha0xfn in the us-east-1 region.
  DEBUG ─ Successfully deployed lambda gkiiq5j-9ha0xfn in the us-east-1 region.
  DEBUG ─ Deploying bucket webiny-js-dev-0909b481 in region us-east-1.
  DEBUG ─ Checking if bucket webiny-js-dev-0909b481 exists.
  DEBUG ─ Bucket webiny-js-dev-0909b481 does not exist. Creating...
  DEBUG ─ Bucket webiny-js-dev-0909b481 created. Confirming it's ready...
  DEBUG ─ Bucket webiny-js-dev-0909b481 creation confirmed.
  DEBUG ─ Setting acceleration to "true" for bucket webiny-js-dev-0909b481.
  DEBUG ─ Bucket webiny-js-dev-0909b481 was successfully deployed to the us-east-1 region.
  DEBUG ─ Saved state for serverless-files component: applied CORS configuration to the "webiny-js-dev-0909b481" S3 bucket.
  DEBUG ─ Saved state for serverless-files component: added "lambda:InvokeFunction" permission to the "manageS3Objects" Lambda.
  DEBUG ─ Saved state for serverless-files component: applied bucket notification configuration to the "webiny-js-dev-0909b481" S3 bucket.
  DEBUG ─ Starting deployment of lambda gkiiq5j-k0lzahl to the us-east-1 region.
  DEBUG ─ No role provided for lambda gkiiq5j-k0lzahl.
  DEBUG ─ Syncing role gkiiq5j-gjmz39l in region us-east-1.
  DEBUG ─ Creating role gkiiq5j-gjmz39l.
  DEBUG ─ Saved state for role gkiiq5j-gjmz39l.
  DEBUG ─ Role gkiiq5j-gjmz39l was successfully deployed to region us-east-1.
  DEBUG ─ Deployed role arn is arn:aws:iam::247750974130:role/gkiiq5j-gjmz39l.
  DEBUG ─ Packaging lambda code from /home/russell/development/cms/webiny/webiny-js/components/serverless-files/dist/functions/imageTransformer.
  DEBUG ─ Creating lambda gkiiq5j-k0lzahl in the us-east-1 region.
  DEBUG ─ Successfully deployed lambda gkiiq5j-k0lzahl in the us-east-1 region.
  DEBUG ─ Starting deployment of lambda gkiiq5j-jdrf2hw to the us-east-1 region.
  DEBUG ─ No role provided for lambda gkiiq5j-jdrf2hw.
  DEBUG ─ Syncing role gkiiq5j-tjdibft in region us-east-1.
  DEBUG ─ Creating role gkiiq5j-tjdibft.
  DEBUG ─ Saved state for role gkiiq5j-tjdibft.
  DEBUG ─ Role gkiiq5j-tjdibft was successfully deployed to region us-east-1.
  DEBUG ─ Deployed role arn is arn:aws:iam::247750974130:role/gkiiq5j-tjdibft.
  DEBUG ─ Packaging lambda code from /home/russell/development/cms/webiny/webiny-js/components/serverless-files/dist/functions/downloadFile.
  DEBUG ─ Creating lambda gkiiq5j-jdrf2hw in the us-east-1 region.
  DEBUG ─ Successfully deployed lambda gkiiq5j-jdrf2hw in the us-east-1 region.
[
  '/home/russell/development/cms/webiny/webiny-js/packages/api-files/src/plugins/resolvers/uploadFile.js\n' +
    "Module not found: Error: Can't resolve './utils/getPreSignedPostPayload' in '/home/russell/development/cms/webiny/webiny-js/packages/api-files/src/plugins/resolvers'\n" +
    "resolve './utils/getPreSignedPostPayload' in '/home/russell/development/cms/webiny/webiny-js/packages/api-files/src/plugins/resolvers'\n" +
    '  using description file: /home/russell/development/cms/webiny/webiny-js/packages/api-files/package.json (relative path: ./src/plugins/resolvers)\n' +
    '    using description file: /home/russell/development/cms/webiny/webiny-js/packages/api-files/package.json (relative path: ./src/plugins/resolvers/utils/getPreSignedPostPayload)\n' +
    '      no extension\n' +
    "        /home/russell/development/cms/webiny/webiny-js/packages/api-files/src/plugins/resolvers/utils/getPreSignedPostPayload doesn't exist\n" +
    '      .wasm\n' +
    "        /home/russell/development/cms/webiny/webiny-js/packages/api-files/src/plugins/resolvers/utils/getPreSignedPostPayload.wasm doesn't exist\n" +
    '      .mjs\n' +
    "        /home/russell/development/cms/webiny/webiny-js/packages/api-files/src/plugins/resolvers/utils/getPreSignedPostPayload.mjs doesn't exist\n" +
    '      .js\n' +
    "        /home/russell/development/cms/webiny/webiny-js/packages/api-files/src/plugins/resolvers/utils/getPreSignedPostPayload.js doesn't exist\n" +
    '      .json\n' +
    "        /home/russell/development/cms/webiny/webiny-js/packages/api-files/src/plugins/resolvers/utils/getPreSignedPostPayload.json doesn't exist\n" +
    '      as directory\n' +
    "        /home/russell/development/cms/webiny/webiny-js/packages/api-files/src/plugins/resolvers/utils/getPreSignedPostPayload doesn't exist\n" +
    '[/home/russell/development/cms/webiny/webiny-js/packages/api-files/src/plugins/resolvers/utils/getPreSignedPostPayload]\n' +
    '[/home/russell/development/cms/webiny/webiny-js/packages/api-files/src/plugins/resolvers/utils/getPreSignedPostPayload.wasm]\n' +
    '[/home/russell/development/cms/webiny/webiny-js/packages/api-files/src/plugins/resolvers/utils/getPreSignedPostPayload.mjs]\n' +
    '[/home/russell/development/cms/webiny/webiny-js/packages/api-files/src/plugins/resolvers/utils/getPreSignedPostPayload.js]\n' +
    '[/home/russell/development/cms/webiny/webiny-js/packages/api-files/src/plugins/resolvers/utils/getPreSignedPostPayload.json]\n' +
    ' @ /home/russell/development/cms/webiny/webiny-js/packages/api-files/src/plugins/resolvers/uploadFile.js 2:0-70 7:29-52\n' +
    ' @ /home/russell/development/cms/webiny/webiny-js/packages/api-files/src/plugins/graphql.js\n' +
    ' @ /home/russell/development/cms/webiny/webiny-js/packages/api-files/src/plugins/index.js\n' +
    ' @ ./handler.js'
]
  DEBUG ─ An error occurred during deployment of files

Build failed!

**Comment by doitadrian** [comment]
Hello @rpalmite, 

sorry, there was one more file that had an incorrect import.

Created a PR, should be merged and released soon enough.

I will let you know!

**Comment by everyonce** [comment]
can we reopen this is we're waiting on a PR?  I can't get my first attempt at this to build due to the above error

**Comment by Pavel910** [comment]
@everyonce releasing the fix in a few minutes.

**Comment by Pavel910** [comment]
@everyonce @rpalmite this is released. Run `yarn upgrade` to get the latest package versions.
