### ISSUE TITLE
How could I edit UpdatePageInput argument and UpdateRevision function implementation?

### ISSUE THREAD

**Issue by V1xel** [webiny/webiny-js#585]
Hello, could you please tell, how could I edit schema? 
I need to update the published flag in update revision function or make something to achieve revision unpublishing.

**Comment by V1xel** [comment]
I've resolved this problem via the additional plugin, with a function, that writes "published" field right to the database. Still, is it possible to override or edit existing schema?

**Comment by doitadrian** [comment]
Hi @V1xel,

first of all, great job! 

Regarding the overriding... Currently, it's not possible. 

But we realize this might be something developers might need, and we already sketched a few ideas on how you'll be able to do it.

For now, I suggest you stick to your solution but watch out for the announcements. 

Will create a new PR for this.

Thanks again!
