### ISSUE TITLE
webiny: command not found MacOS 

### ISSUE THREAD

**Issue by mstennie** [webiny/webiny-js#599]
## This is:
- Bug
- Question

## Specifications

  - version:
  - OS: MacOs 10.14.6
  - Browser: No Browser

## Expected Behavior
When I install the cli via npm, I should be able to run `webiny` command.

## Actual Behavior
When installing the cli, I get the error
`-bash: webiny: command not found`
working well with yarn.

## Steps to Reproduce the Problem

1. install cli
2. run `webiny`

## Detailed Description

N/A
## Possible Solution

N/A

**Comment by Pavel910** [comment]
@mstennie Did you install the CLI globally? If yes, this looks like a problem with your PATH not including the location of global npm modules.

If you run `npm root -g` - it will tell you where the global packages are installed, eg: `/usr/local/lib/node_modules`

If you run `which webiny` it should tell you where the binary for `webiny` is located, eg: `/usr/local/bin/webiny`.

Make sure your PATH contains the corresponding folder for binaries. Run `echo $PATH`, which will print the entire PATH, and check if it contains something like `/usr/local/bin`.

**Comment by Pavel910** [comment]
Closing this as the answer is provided above, but not feedback from the author is received. Please reopen if necessary.
