### ISSUE TITLE
CredentialsError: Missing credentials in config

### ISSUE THREAD

**Issue by IvaTsu** [webiny/webiny-js#602]
## This is:
- Question

## Specifications

  - version: 10.14.16
  - OS: Mac OS
  - Browser: Chrome 

## Expected Behavior
Deploy Webiny API

## Actual Behavior
Getting an error: "CredentialsError: Missing credentials in config"

## Steps to Reproduce the Problem

1. Install Webiny: `yarn global add @webiny/cli`
2. Create the project: `webiny create webiny-cms`
3. Run `webiny deploy-api` in the `root`

## Detailed Description
When going through the steps, described in docs: https://docs.webiny.com/docs/get-started/quick-start/, at step 4, after 76 seconds of deploy, I am getting the error: `CredentialsError: Missing credentials in config`

The `api/.env.json` looks like this:
```
{
  "default": {
    "GRAPHQL_INTROSPECTION": true,
    "GRAPHQL_PLAYGROUND": true,
    "MONGODB_SERVER": "mongodb+srv://user:password@cluster.mongodb.net/webiny-f36504d6?retryWrites=true&w=majority",
    "MONGODB_NAME": "webiny-f36504d6",
    "S3_BUCKET": "webiny-files-f36504d6",
    "JWT_SECRET": "gm6RjlRwkrfW4sS69mc37N+lIrAFcYhK/SCrxh2Xk8GQP9d74HGfsytTu8bL"
  }
}
```

P.S.: Tried to connect to the Atlas via MongoDB Compass - it works. The network access is allowed from anywhere (e.g. added `0.0.0.0/0` to the Network Access)

Anything I am missing from being able to run the project locally?

**Comment by Pavel910** [comment]
Hey @IvaTsu, the credentials in question are your AWS credentials that should be configured in `~/.aws/credentials`.

That file should look something like this:
```
[default]
aws_access_key_id = [your_access_key_id]
aws_secret_access_key = [your_secret_access_key]
```

There is a link in the Quick Start guide to the video explaining how to setup an IAM user and get those credentials: https://www.youtube.com/watch?v=tgb_MRVylWw

Let me know if you need more help, cheers!

**Comment by IvaTsu** [comment]
Yeah, that helped. Thanks!

P.S.: Maybe there should be a side note in `Quick Start` documentation regarding setting up serverless AWS providers and credentials to run the project?
For me, that wasn't obvious.

**Comment by Pavel910** [comment]
@IvaTsu actually there is a link, but I guess it's not too visible:
![image](https://user-images.githubusercontent.com/3920893/68333497-e8639e00-00d8-11ea-86e5-b224e9b47560.png)

Will make it more obvious in the next update. Glad you got it working :)
