### ISSUE TITLE
Quickstart fails on step 4 with InvalidSignatureException

### ISSUE THREAD

**Issue by tforster** [webiny/webiny-js#612]
Following along with the quickstart https://docs.webiny.com/docs/get-started/quick-start/#! and it fails on step 4 with `InvalidSignatureException: Signature expired: 20191110T104635Z is now earlier than 20191110T211309Z (20191110T211809Z - 5 min.)`

## This is:

- Bug?

## Specifications

  - version: 2.3.0
  - OS: Ubuntu 18.04 / WSL2 / Windows 10 Pro
  - Browser: Google Chrome 78.0.3904.97 (Official Build) (64-bit)

## Expected Behavior

Should not fail, and the API should start

## Actual Behavior

The following is found in the console

``` shell
/my-project webiny deploy-api
This is the first deploy of local environment, so it may take a few minutes.
Here's ☕️ to make the time pass faster :)

  An error occurred during deployment of cognito

InvalidSignatureException: Signature expired: 20191110T104635Z is now earlier than 20191110T211309Z (20191110T211809Z - 5 min.)
```

**Comment by tforster** [comment]
The problem turns out to be specific to WSL2 following a hardware sleep. Seems that in sleep mode the host Windows 10 clock continues but the WSL2 VM is frozen. When the hardware, and the VM, are reawoken the host has the correct time but the VM is now {sleep-duration} behind.

I ran `sudo hwclock -s` which resyncs the WSL2 VM clock to the host and now I no longer see teh Cognito message.

**Comment by TommyJackson85** [comment]
@tforster I am having this same error and when I run """sudo hwclock -s""" on mac terminal I get a "command not found" error. Do you know another way to fix this?

**Comment by tforster** [comment]
@TommyJackson85 My issues were specific to WSL2 which is the native Linux layer in Windows and thus the Linux (Debian) command to resync. The Mac operating system is based on BSD Unix which predates Linux and is not Linux compatible. 

In my specific case, there was an early bug in WSL2 that the clock was not being updated after the system was awoken from a sleep cycle. So WSL2 thought the date/time was earlier than it actually was. Hence the command to resync the time. Is your issue manifesting after you wake up the system?

**Comment by TommyJackson85** [comment]
@tsforster As my issue is specifically related to doing a local setup for contributions, I am going to create a new issue report on mine. I need to check if I am doing everything correctly, i.e. to check if my environment variables are correct.
