### ISSUE TITLE
Admin - rename "Forms" into "Form Builder"

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#615]
In Admin UI, we should rename the "Forms" labels in the left menu to "Form Builder", which is the name we're using in the docs. Except for that, "Form Builder" sounds much better than just plain "Forms".

![image](https://user-images.githubusercontent.com/5121148/68944853-3484a180-07af-11ea-88ae-f0d8f1315479.png)

The labels can be found in the following files:

- `packages/app-forms/src/admin/plugins/settings/index.js`
- `packages/app-forms/src/admin/plugins/routes`

Note: rember to also change the page title (via Helmet, can be found in the referenced files).

**Comment by enmesarru** [comment]
May i take this ?

**Comment by doitadrian** [comment]
Sure, go ahead :)

**Comment by enmesarru** [comment]
Here is the PR:
https://github.com/webiny/webiny-js/pull/616
