### ISSUE TITLE
yarn setup-repo fails on Windows

### ISSUE THREAD

**Issue by fodurrr** [webiny/webiny-js#620]
After forking and cloning the repo for local development the `yarn setup-repo` fails on Windows 10.

## This is:

- [x] Bug
- Feature request
- Question
- Idea

## Specifications

  - version: current
  - OS: Windows 10
  - Browser: Chrome

## Expected Behavior

yarn setup-repo should run without issues on Windows platform

## Actual Behavior

yarn setup-repo fails

## Steps to Reproduce the Problem

1. fork and clone repo
2. install packages with yarn 
3. run yarn setup-repo command fails

## Detailed Description

yarn setup-repo fails with the following error message:
`Failed to build @webiny/serverless-files package: Command failed: yarn build
'cp' is not recognized as an internal or external command`

**Comment by Pavel910** [comment]
@fodurrr thanks for reporting. To be honest we haven't given this proper testing on Windows, looks like it's time we did that. I'll let you know when this is tested and sorted. Cheers!

**Comment by fodurrr** [comment]
@Pavel910 :) I was thinking to start to contribute but first I wanted to see how everything works. It is difficult without knowing anything about the project to start to dig into setup issue.

**Comment by Pavel910** [comment]
@fodurrr absolutely. That's on us to fix, I'll jump on it first thing tomorrow 🚀

**Comment by Pavel910** [comment]
@fodurrr could you tell me a little bit more about what terminal are you using?

**Comment by fodurrr** [comment]
First I tried with git-bash for windows then with normal windows cmd.exe prompt.
May be I will have time during the weekend to try again.

**Comment by Pavel910** [comment]
@fodurrr I just merged the fixes for Windows. I used VSCode and the Git bash terminal to test everything. Seems to be working nicely now. Please don't try the `cmd`, there is no chance that one can work.

So simply pull the `master` branch again, and give it a try using Git bash once more. 

Let me know if you run into more problems with Windows, and I'll get on it right away. I've moved to Windows for the time being, so I'm also developing on Windows now.

**Comment by fodurrr** [comment]
Hi,

I could setup the the repo, deployed the APIs to AWS but now I hit some cors issues.

`Access to fetch at 'https://d2xyyod0mq34bs.cloudfront.net/graphql' from origin 'http://localhost:3001' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

![image](https://user-images.githubusercontent.com/10008597/69274956-5e84fc00-0bd3-11ea-98fe-0a1d07277aab.png)

![image](https://user-images.githubusercontent.com/10008597/69275174-ca676480-0bd3-11ea-9a22-34164af8cf14.png)

for me the headers seems fine. Do you have any hint why it is not working?

Not the admin and not the site.

Thanks

**Comment by Pavel910** [comment]
@fodurrr can you confirm that your API is actually working by itself?

Try opening the API URL in the browser, it should open the GraphQL Playground.
Also, make sure you've setup the database connection URL in the `api/.env.json`.

**Comment by fodurrr** [comment]
API URL: https://d2xyyod0mq34bs.cloudfront.net/graphql, no playgorund just message that request timed out :(

I created account at Atlas mongodb I can connect via compass from my laptop.

Database connection string in `api/.env.json` is  `"MONGODB_SERVER": "mongodb+srv://fodurrr:<my password>@webiny-yxkxa.mongodb.net/test?retryWrites=true&w=majority",`

All cors set to '*' during the setup right? in the handler.js? so this should not be cors?
May be the database connection string?

**Comment by doitadrian** [comment]
Sorry for asking, just wanted to double-check, the connection string you set in the `.env.json` file contains the actual password?

This looks like a DB connection issue to me.

**Comment by fodurrr** [comment]
yes it contains the password, however first I had a really encrypted and url encoded password which I updated to a simply one now to be able to see if it solves the issue or not.

When I changed the db connection string (password) then I redeployed the API with `webiny deploy-api` again. May be the redeployment did not take into account that I changed the connection string in the .env file?

**Comment by SvenAlHamad** [comment]
@fodurrr make sure that in mongo atlas you have 0.0.0.0 whitelisted under the network section. Without that lambda won't be able to connect to your db.

**Comment by fodurrr** [comment]
I suspected that something with the db connection :) Yep, thats it :) I think that should be added to the docs, I whitelisted my laptop and my home desktop but the 0.0.0.0 is the key :) thanks
Now I try the next steps.
Thanks for the quick helps

**Comment by fodurrr** [comment]
Cool graphql playground is working and I am setting up the admin now, thanks

**Comment by SvenAlHamad** [comment]
Great, I'm glad it worked.

We do have that in the docs ;) 
![image](https://user-images.githubusercontent.com/3808420/69278994-54ff9200-0bdb-11ea-92a8-d8583cf71847.png)

**Comment by Pavel910** [comment]
But not in the docs for contributors 🤦‍♂ I'll add it tomorrow :)

**Comment by fodurrr** [comment]
Sry I started with the contribution page and I just quickly went through on normal quickstart, somehow I missed it.

**Comment by Pavel910** [comment]
This is exactly the type of testing and feedback we need :) Docs and guides need user testing just as any other piece of code, so your feedback is priceless 🚀 👍
