### ISSUE TITLE
Helloworld Webiny App

### ISSUE THREAD

**Issue by jinman** [webiny/webiny-js#628]
This is a question. Is there any simple tutorial similar to https://docs.webiny.com/docs/deep-dive/plugins-crash-course where we can see how to build a webiny "app" in which we can see how to add corresponding main menu item, settings menu, locale, theme. We have looked at 
@webiny/app-mailchimp, @webiny/app-i18n, @webiny/app-admin. But these too be either too simple or too complex.

HelloWorld Webiny App will be absolute minimum things that we need to leverage Webiny's UI framework without the API and will help create similar react apps. After install, we would see Menu, Settings, List and main canvas and use of RWMC, emotion/styles and material-UI components.

**Comment by Pavel910** [comment]
We do plan to have that in the docs, but a `hello-world` app package is also a great idea 👍 . There's a lot to document, so we're slowly making our way through the docs/bugs/features, hard to find a good balance, but soon all these topics will be covered.

If it would help you, I can give you references to the related plugins that register menus, settings menus, etc. Let me know if I can help in any way while the docs are being made.

Cheers!

**Comment by jinman** [comment]
Thanks for the quick reply and sorry for my tardy reply. We would love it if you can point us to the right direction in the existing apps (page-builder, form-builder, etc) and (if we are able to do it), we would love to contribute it back in terms of documentation and/or code as well.

Here is what we were thinking about hello-world webiny app: If we want to create a new app or move an existing serverless react app in webiny, what are the prerequisites?

1. Plugins for Register Menu, Settings Menu
2. Packaging and config - uninstall and install
3. Authentication and Authorization / Security
4. UI components and props for reuse/consitency
5. Storybook and Styling to match the theme

We can do the same for backend (Serverless API/commodo etc.) but first we thought it might be good to focus only on the react app. 

Thanks!

**Comment by Pavel910** [comment]
@jinman we do have a storybook with our UI components: https://storybook.webiny.com/
As long as you are using those components in the context of our `admin` app, those components will look and work seamlessly.

Regarding everything else (1, 2 and 3), I'll quickly put together a `hello-admin` app and push it to our repo; I think it will be much faster than for both you and me. 

We would greatly appreciate if you could later write an article or two for our Docs. We're totally outgunned on that front and could use any help we can get 🚀

**Comment by doitadrian** [comment]
I like the approach, Next.js has taken: https://nextjs.org/learn/basics/getting-started/setup

**Comment by doitadrian** [comment]
A few notes:

- webiny create xyz - explain initially generated folder structure and files

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
