### ISSUE TITLE
Change structure of CLI commands

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#635]
I propose a bit different structure of API / apps CLI commands.

Instead of `webiny deploy-apps` and `webiny deploy-api`, we would have the following structure:

`webiny apps deploy --debug --env dev ...`
`webiny api deploy --debug`

So, you have to first use `apps` and `api` and then the command you wish to execute.

**Comment by Pavel910** [comment]
This can easily be done without introducing breaking changes. What I like about this is that commands get scoped to a particular "section", like `api` or `apps`  and so each "section" can have more child commands. Also it allows us to introduce commands like `push` and `pull` for state management as discussed in #633.

**Comment by doitadrian** [comment]
Yeah, "section" is the same word that comes to my mind too.

👍

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
