### ISSUE TITLE
How do you define a link between two pages?

### ISSUE THREAD

**Issue by mectors** [webiny/webiny-js#639]
Dumb question but if you want to link between two pages, what is the URL structure you need to introduce in the link on the first page?

## This is:

- Question

**Comment by SvenAlHamad** [comment]
Hey Martin, 

If I understood your question correctly, you want to place a link on one page so when a user clicks on that link, that it takes him to another page on your website? 

To add a link between two pages, you should use a relative link, without the domain name. For example, if the page you want to link to has a url of: `http://domain.com/my/page` you would put `/my/page` into the link field. 

Another option to link between pages is to use the page list element in page builder. That one will list all your pages matching certain criteria. The generated list will automatically have links to the matched pages. An example is the "Welcome to Webiny" page that you get when you install the system.

Hope this answers your question.

**Comment by mectors** [comment]
Thanks that solved it.
