### ISSUE TITLE
Internal Site App

### ISSUE THREAD

**Issue by jinman** [webiny/webiny-js#640]
This is feature request/Question. 
 
Can we move the Site App  to "internal" aka. behind the login?
How can we change the ACL/security later so "Site" settings can have toggle setting so it can go behind login. This will enable a lot of other use cases such as Intranet, Knowledgebase etc.  Admins and Editors can get access editing content, employees and other internal folks can see the site.

**Comment by Pavel910** [comment]
Yes, that can be done relatively easy, it's a matter of mounting an extra React component which manages authentication via Cognito (it's pluginable, but we provide a Cognito  plugin by default). 

We also have components for handling authorization, so you can render app views based on user's scopes and roles. 

Let me setup an example to double-check everything and I'll just add to our repo.

**Comment by Pavel910** [comment]
OK so I'm working on adding support for secured site app, it's actually pretty simple to implement, but I've encountered a problem that has more to do with rendering of UI, you can see the discussion and a proposed solution in #641.

This will be resolved soon enough; I'll keep you updated. And there will also be a working example in our repo. Stay tuned :)

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
