### ISSUE TITLE
Standardize the way how apps and plugins register their layouts

### ISSUE THREAD

**Issue by SvenAlHamad** [webiny/webiny-js#641]
## The Problem
Often Webiny plugins and apps have several parts. Take for example the Mailchimp plugin or the Form Builder. One of these parts is a component that defines how the render looks like for the ‘site’ app for that plugin or app.

The dilemma we face is around where the render is defined and how it’s introduced into the theme. 

### Option 1 - using plugins to register new render layouts
The Mailchimp plugin, for example, has its render as part of the plugin, and you don’t need to define it inside the theme. Alternatively if you do want to change the layout or add new ones, you can do that by registering a new plugin under the name ‘pb-page-element-mailchimp-component’. 

#### Pros of this approach:
- No need to configure anything once the plugin is installed
- Easy to register new layouts via plugins

#### Cons:
- Not super clear in terms of how the render layout looks like
- To change the colors and other visual styles, the user needs to explore the generated HTML and CSS classes
- Not using the provided theme system as some other components

### Option 2 - registering a new component via the theme
The Form Builder registers it’s layout via the theme. The layout component actually resides inside the theme. 

#### Pros of this approach:
- Using the standard theme system
- Easy to customize and change the layout

#### Cons:
- Currently the FB layout is tightly coupled with the theme package

## Conclusion
Although Webiny plugin and theme systems allow multiple ways of registering and providing layouts for apps and components, we need to have “standardized” way which should also set the guidelines for new apps and community contributions. 

This discussion is to figure out what that approach would be. As the main guidelines we would like to address the following items:
- a standard that works both for Page Builder elements as well as apps like the Form Builder
- an easy way of registering new layouts when a new plugin or app is introduced
- the developer should have the ability to customize a default layout
- a layout can contain both images and css files next to the react component

**Comment by Pavel910** [comment]
Another related thing is styling of common input elements, like `input`, `textarea`, `select`, etc. We have multiple apps which render those, like `Form Builder`, `Mailchimp`, and now `Security`. Each of those have their own CSS classes and markup, which is redundant; it meas I need to re-style every app instead of just styling global components in my theme.

I'm currently working on a `secured site` app example, which allows you to put a website behind login. The `security` views are currently hardcoded with `@webiny/ui` package and only work with `admin` app CSS. I managed to separate the security logic from the UI, but I'm still facing the dilemma of how to expose those views  for customization. The problem with redundant input elements makes it even worse.

I have a separate set of views you can pass to the `cognito` plugin to render each step of the login process, but it would be nice if I could at least reuse the existing input/buttons components and not define them again in my own views.

**Comment by Pavel910** [comment]
After an extensive discussion on a conference call, we've decided to push the `everything is a plugin` concept even further. When everything is following the same design pattern, it's much easier to think about the structure of an app, write documentation, and contribute to a project.

## Theme package changes
- `theme` package is to be removed in favor of an `npm` module
- themes are to be registered as regular plugins and will only contain simple configuration like typography, colors, etc. that is necessary for Page Builder 
- themes can contain as many plugins as needed to extend app specific functionality
- theme CSS/SCSS will be imported in each app directly
- minor theme customizations can be done via theme plugin factory
- Page Builder and Form Builder layouts, that are currently part of the theme, will be registered as plugins as well (this will make it easier to provide default behavior out of the box by simply importing plugins from an npm package)
- `<PageBuilderProvider>` no longer needs `theme` as a prop; it will pull the theme from plugins

## Reuse of UI components in non-admin apps
Regarding components like `input`, `textarea`, `button`, etc., we will create default `base` CSS classes that will be used across apps, but each app will also have its specific component class for easy element targeting. Example: `<input className={"webiny-base--input webiny-app-forms--input"} .../>` (class names are not final yet).

Side note:
`project-utils` package is to be published on `npm` for easier maintenance. It was my strong opinion that this package should be located in each project so devs can tweak stuff in it. However, there have already been situations where it would be much easier to release a fix to this package if we had it on `npm`.

**Comment by Pavel910** [comment]
This is implemented, closing.
