### ISSUE TITLE
Broken link in `packages/validation/README.md`

### ISSUE THREAD

**Issue by jbampton** [webiny/webiny-js#653]
The `validation` link is broken in the table of contents since there are two headings
 with the text `validation`.

Currently the link in the table of contents links back to the README's top level heading.

https://github.com/webiny/webiny-js/tree/master/packages/validation

![Screen Shot 2020-01-07 at 2 37 12 am](https://user-images.githubusercontent.com/418747/71832976-c2b63d80-30f7-11ea-9d35-3178741b7c81.png)

I can add a PR to fix it if you tell me what it should be changed to.

**Comment by geekysrm** [comment]
Fixed in https://github.com/webiny/webiny-js/pull/1276.
Please merge.
