### ISSUE TITLE
Broken image and broken link in `packages/cli/create/template/README.md`

### ISSUE THREAD

**Issue by jbampton** [webiny/webiny-js#655]
The Webiny logo is broken at the top of the `README` and the `docs` link is broken too.

https://github.com/webiny/webiny-js/blob/master/packages/cli/create/template/README.md

## This is:
- Bug

![Screen Shot 2020-01-07 at 4 27 03 am](https://user-images.githubusercontent.com/418747/71839556-25630580-3107-11ea-95be-d194059f6de1.png)

Let me know what the link should be and I will add a PR to fix this issue.

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
