### ISSUE TITLE
Minimum password length is different from defined in Cognito

### ISSUE THREAD

**Issue by naokia** [webiny/webiny-js#657]
## This is:

- Bug

## Specifications

In any environment

## Expected Behavior

Password shorter than 8 characters should be rejected by validation module.
(because minimum password length on cognito is 8 characters)

## Actual Behavior

Password shorter than 8 characters passes validation on front end.
But, Validation on Cognito reject it.

## Steps to Reproduce the Problem

1. Display initial account setting screen. (titled "Install Security")
2. Input password shorter than 8 characters. and click "Install Security"
3. Validation pass, but an error by Cognito is shown

## Possible Solution
Set minimum length on validation module to 8 characters same as cognito

**Comment by Pavel910** [comment]
Hey @naokia, good find! Our default password policy for `cognito` component looks like this:

```js
const defaultPasswordPolicy = {
    minimumLength: 8,
    requireLowercase: false,
    requireNumbers: false,
    requireSymbols: false,
    requireUppercase: false,
    temporaryPasswordValidityDays: 7
};
```

However, the installation form is not in sync with those settings. I'm leaving this issue opened; we need to figure out a good approach to keeping those settings in sync. @doitadrian This is something to discuss after our upcoming release.

**Comment by Pavel910** [comment]
Just to document a potential solution: the idea is to fetch Cognito Password Policy via SDK when a login form is rendered, so we can render an appropriate validation on password field. I'll try to implement this after we get our next release through the door.
