### ISSUE TITLE
[CLI]: No warning shows up if an unknown command is passed in

### ISSUE THREAD

**Issue by jamesgeorge007** [webiny/webiny-js#659]
## This is:

- Bug

## Specifications

  - version:
  - OS:
  - Browser:

## Expected Behavior

An appropriate warning message along with the help information (optional) should show up.

## Actual Behavior

Nothing is logged on to the console.

## Steps to Reproduce the Problem

1. Install the CLI globally
2. `webiny junkcmd`

## Detailed Description

Users should be warned if an unrecognized command is passed in.

## Possible Solution

Make use of the `yargs API` to validate the respective case.

**Comment by doitadrian** [comment]
Thanks for the report!
