### ISSUE TITLE
Considering Typescript or Aurora Serverless Data API?

### ISSUE THREAD

**Issue by sergiofilhowz** [webiny/webiny-js#663]
Hi there, 

I've been looking at Webiny for a year from time to time and I really like the project. Serverless, GraphQL, and Drag n' Drop CMS... all of these altogether, well... amazing!! Congratulations!

I'm considering on contributing to this awesome project and one thing that I noticed is that Typescript would really help on creating plugins / connectors like Database / Security.

What do you think on probably migrate some modules to Typescript?

Regardless of Typescript. Since this project is meant to be serverless first. I want to create a database connector to AWS Aurora Serverless Data API. https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/data-api.html

What do you all think?

## This is:
- Idea

**Comment by Pavel910** [comment]
Hey @sergiofilhowz, glad you like Webiny :)  You'll be delighted to hear that we are finalizing migration to Typescript, it will be included in our upcoming release. Most of the plugins now have their corresponding types, so it will be much easier to contribute and discover the system.

Regarding Aurora, I'll let @doitadrian give you the information regarding that, as he's the author of our DB layer library.

Looking forward to seeing your PRs and issues 🚀 Cheers!

**Comment by doitadrian** [comment]
Hi @sergiofilhowz, 

supporting Serverless Aurora is actually something we were considering at one point in time, and actually we have the MySQL driver already. Yes, it's a bit old, but it could definitely be refactored, to meet the latest code requirements.

If there is a real interest from the community for the support for MySQL, or you are willing to give it a try, I can prepare a separate issue for this, where I can outline everything that needs to be done.

**Comment by sergiofilhowz** [comment]
Thanks @doitadrian and @Pavel910 

Awesome to have Typescript on Webiny! :)

I've been wondering these days and probably makes more sense to me to use DynamoDB instead of a database because I don't want to run too many resources for this website at the moment.

And I also saw that you already have one issue open to create DynamoDB implementation.
