### ISSUE TITLE
[Bug] [Admin] Broken Link in Default Content

### ISSUE THREAD

**Issue by rpalmite** [webiny/webiny-js#664]
## This is:

- Bug

## Expected Behavior

Links in default content should work

## Actual Behavior

There's a broken link

## Steps to Reproduce the Problem

1. Create a new instance of webiny
2. Create an admin and log in
3. Go to Page > Get Started 
4. Notice to the link to https://docs.webiny.com/docs/cms-guides/get-started-webiny-administration

## Detailed Description

![image](https://user-images.githubusercontent.com/123492/72707274-a0f69500-3b92-11ea-9b79-bccd9f367c34.png)

![image](https://user-images.githubusercontent.com/123492/72707124-49f0c000-3b92-11ea-8fa1-411086142b6d.png)

The link to is a dead-link. The content must have moved.
https://docs.webiny.com/docs/cms-guides/get-started-webiny-administration

## Possible Solution

Update the link :)

**Comment by doitadrian** [comment]
Fixed and merged in #688.
