### ISSUE TITLE
[Idea] [Admin] Suggestion for changes to the admin navigation menu

### ISSUE THREAD

**Issue by rpalmite** [webiny/webiny-js#665]
## This is:

- Idea

## Detailed Description

I believe Pages, Categories, Menus, and Form Builder are likely to be most frequently used and deserve top hierarchy status in the admin navigation menu. Currently they're all contained within Content.

![image](https://user-images.githubusercontent.com/123492/72706138-dcdc2b00-3b8f-11ea-9f4e-ff7dae111631.png)

## Possible Solution

I suggest removing the content menu completely and hoisting up Pages, Categories, Menus, and Form Builder.

Languages and security on the other hand would likely make better sub-menu items of the parent Settings.

![image](https://user-images.githubusercontent.com/123492/72706374-7572ab00-3b90-11ea-9ba9-3a4304c01532.png)

**Comment by Pavel910** [comment]
Hi @rpalmite , thanks for the detailed example. The structure we provide by default comes from many years of building custom software for clients, where content management is just a minor part of the system. Webiny is not like Wordpress where you only have content management and maybe 1-2 additional modules. The goal of Webiny is to be a platform for web apps - whatever they are, not specifically page/content building; so our default navigation structure allows better/cleaner organization of independent apps in that sense.

Ideally, in the future we would upgrade the core admin app to allow customization of main menu so each user can rearrange menu items to fit their needs. What do you think about that?

**Comment by SvenAlHamad** [comment]
As Pavel mentioned, the current menu structure is taking into account that you can add many more items/apps to Webiny and still have a good experience with the navigation. 

I do also understand your point, wherefrom somebody who only wants to use Webiny as a CMS, splitting out individual items into top-level navigation would improve the user experience. 

For now to easiest way would be to overwrite the current plugins, that register those menu items, with your own plugin that defines the structure more suitable for your need. This is a straight forward change if you know your way around with javascript. Pavel here can probably provide a code reference if required.

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
