### ISSUE TITLE
[UX] [Admin] Split Screen Layout

### ISSUE THREAD

**Issue by rpalmite** [webiny/webiny-js#666]
## This is:

- Idea

## Detailed Description

As it stands currently, I feel that clicking "(+)" and having it erase your current fields, which you may not expect and may not even realize happened, could use some improvement.

Current experience:

![image](https://user-images.githubusercontent.com/123492/72705738-d1d4cb00-3b8e-11ea-8a8c-03e7cc6a0af5.png)

## Possible Solution

The use of split screen and material design on the Pages, Categories, Menus, Security Users, etc is what creates an unusual experience for me. I believe it's more typical to have the material button for creating addition content hovering over a list of current content. Clicking that button would then bring up a new screen that allows the user to add a new element.

This would change the experience from this:

![image](https://user-images.githubusercontent.com/123492/72705738-d1d4cb00-3b8e-11ea-8a8c-03e7cc6a0af5.png)

To something more akin to this:

![image](https://user-images.githubusercontent.com/123492/72709530-c4700e80-3b97-11ea-9872-f15f905ec3fd.png)

Clicking (+)...

![image](https://user-images.githubusercontent.com/123492/72709693-08fbaa00-3b98-11ea-9592-c7cf08b572d3.png)

Selecting a category..

![image](https://user-images.githubusercontent.com/123492/72709655-f5e8da00-3b97-11ea-9a5c-26f397a6cdf3.png)

While this would add an additional click to the user experience of admin, I believe this additional click would create a more natural feeling user interaction.

I tried to look for documentation directly supporting the hypothesis that this is more a natural flow for a material app, as I know material design goes beyond simple icons to suggest particular interactions and gestures, but I didn't find anything that directly mentioned the aforementioned interaction. The closest documentation was this https://material.io/design/interaction/gestures.html# in which you can see the examples use an interaction more akin to my suggestion. Also, google's own apps like Gmail use an interaction more like what I suggest here.

If seeing the preview is of especial importance, I would suggest having an ability to toggle between previews and a list view.

![image](https://user-images.githubusercontent.com/123492/72713655-0309c700-3ba0-11ea-9956-d044c2758b89.png) vs ![image](https://user-images.githubusercontent.com/123492/72713690-1157e300-3ba0-11ea-8219-b0b4085c1517.png)

as would be common for file management applications.

Or at very least, just moving the (+) to the left so it's over the list of current items (although for other reasons I think this is less preferred).

**Comment by Pavel910** [comment]
Great feedback @rpalmite. I myself am not much of a UX expert, but maybe @SvenAlHamad could join the discussion and share his insight.

**Comment by SvenAlHamad** [comment]
Hey @rpalmite thanks for taking the time an opening this issue.

You have a good point, it's unexpected that the (+) restarts your form, especially if you have already typed something into the fields.  It's not good from the UX side.

The solutions you have suggested do have some advantages, but also many tradeoffs. The reason we have opted-in for the split-screen view is to use up all that screen real-estate. 

Going back to the original problem you have described, I believe we can take another approach. What do you think of a solution where when you enter, or amend, some of the fields in the form, and then clicked the (+) button that you get a message asking you if you want to continue as your action will restart the form?

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
