### ISSUE TITLE
[Idea] [Admin] Rename Security Users to Users

### ISSUE THREAD

**Issue by rpalmite** [webiny/webiny-js#668]
## This is:

- Idea

## Detailed Description

The term security users sounds less natural than simply users.

## Possible Solution

I think simply having a hierarchy of "Security > Users" would more naturally express that users are related to security. The typical user of this application inside my company is in marketing and this simple change would improve a reluctance to add users caused by the naming of this screen.

**Comment by Pavel910** [comment]
The term Security encompasses more than just users; there are groups, roles, we're also planning to add Personal Access Tokens, maybe even support for different Auth providers. In a broad sense it is exactly that - app security.

Let's keep this one open and see if we can get more feedback from the community.

Thanks for opening! 🍻

**Comment by SvenAlHamad** [comment]
On this one, I would reflect on my comment on issue #665

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
