### ISSUE TITLE
Control Z in Page Creator issue

### ISSUE THREAD

**Issue by tjrexer** [webiny/webiny-js#672]
Using the hotkey Ctrl+z to undo a objects move in Page Creator requires multiple actions to completely undo.

## This is:
- Feature request

## Expected Behavior
Ctrl+z should undo last user initiated action.

## Actual Behavior
Ctrl+z undoes last action, either user initiated or automatic back end.

## Steps to Reproduce the Problem
1. Move object from one part in page, to another.
2. Observe seamless move.
3. Click Ctrl+z, watch original object return, but object in new location remains.
4. Click Ctrl+z, watch object in new location to be removed, leaving only original object.

## Detailed Description
Using the hotkey Ctrl+z to undo a objects move in Page Creator requires multiple actions to completely undo.  This is most likely because when physically moving an object, it is copied to the new location first, and then removed from the original location.  However, each action is recorded as an individual action that must be undone.  

## Possible Solution
If these actions could be grouped into a single command, it would streamline user actions.

**Comment by Pavel910** [comment]
Thanks for reporting :) You're spot on - it's caused by multiple actions being dispatched to perform any operation. It's difficult to identify the "beginning" of an action, since moving elements sometimes causes a lot of actions being dispatched in the background, for example, when moving a Column from a Row to a different Row. 

If you have some ideas, please do share 🍻 ❤️

**Comment by tjrexer** [comment]
If you tagged each user initiated change with an ID and count how many actions are dispatched, you can then track through how many tasks need to be rolled backed.  When the user hits ctrl-z, repeat it for the number of times needed to undo the tasks.  You can keep memory available by only tracking the last, 10 - 20 user initiated changes.

It would also be good to have an up-publish option.  The resources page is a great example, if I want to keep the list of resources, but I don't want it to be published when I go live or I have my own resources page I want to publish.

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
