### ISSUE TITLE
Page updates unrecoverable

### ISSUE THREAD

**Issue by tjrexer** [webiny/webiny-js#673]
About 30 minutes worth of work on a page is now gone and un-recoverable.

## This is:
- Bug

## Specifications

  - version: 2.6.0
  - OS: WSL (Ubuntu 18.04.3 LTS)
  - Browser: Firefox

## Expected Behavior
Any page changes should be saved, or rolled back if failed.

## Actual Behavior
It seems like new page is created, and then re-named to the old page.

## Steps to Reproduce the Problem
![image](https://user-images.githubusercontent.com/7013045/73125209-41bdc980-3f72-11ea-83a4-8dfcea9962ed.png)

1. Modify page content.
2. When page crashes with the error attached, page is un-recoverable.
```Column/<
src/render/plugins/elements/column/Column.js:18

  15 |     >
  16 |         {element.elements.map(element => (
  17 |             /* $FlowFixMe */
> 18 |             <Element element={element} key={element.id} />
     | ^  19 |         ))}
  20 |     </ElementRoot>
  21 | </ElementAnimation>

Column
src/render/plugins/elements/column/Column.js:11

   8 | const Column = ({ element }: { element: PbElementType }) => {
   9 |     return (
  10 |         <ElementAnimation>
> 11 |             <ElementRoot
  12 |                 element={element}
  13 |                 className={"webiny-pb-base-page-element-style webiny-pb-layout-column"}
  14 |                 style={{ width: (element.data.width || 100) + "%" }}
```

## Detailed Description
Seems to be an error with the an individual column not being able to be rendered.  I was just looking to re-order buttons within a block.

However, this also causes issues with the page remaining in the editor since you can't load the page to delete it.

**Comment by tjrexer** [comment]
Certain Blocks are not being updated at all:

Post change: Listed as saved
![image](https://user-images.githubusercontent.com/7013045/73125525-9878d280-3f75-11ea-90b6-5105b6ad3072.png)

After Exiting Editor:
![image](https://user-images.githubusercontent.com/7013045/73125532-b5150a80-3f75-11ea-99bd-0bf1d5be86f0.png)

**Comment by tjrexer** [comment]
During re-build of page, the original is now un-editable for a new error.  This was caused after the editor thought I tried to move a text field.  When I moved it back, and tried to edit the text again, it returned this error and won't let me edit the page.

`TypeError: element.data is undefined
../../node_modules/@webiny/app-page-builder/editor/plugins/elements/row/RowChild.js/RowChild</<
src/editor/plugins/elements/row/RowChild.js:87

  84 |         <ResizeHandle
  85 |             {...resizeProps}
  86 |             leftWidth={leftElement.data.width}
> 87 |             rightWidth={element.data.width}
     | ^  88 |         />
  89 |     )}
  90 | </Resizer>

render
src/editor/components/Resizer.js:46

  43 | };
  44 | 
  45 | render() {
> 46 |     return this.props.children({
     | ^  47 |         isResizing: this.state.dragging,
  48 |         onMouseDown: this.onMouseDown
  49 |     });`

**Comment by Pavel910** [comment]
@tjrexer great, I'll implement `ErrorBoundries` on elements so one broken element doesn't blow up the entire editor. Will see if I can reproduce any of the  bugs, but good finds anyway 🍻 ❤️

**Comment by Pavel910** [comment]
This issue should be resolved now. In #726 we added per-element handling of errors, so in case any particular element explodes, it will be handled locally, and you'll get a chance to delete the broken element.
