### ISSUE TITLE
Page Builder: Tooltip text field doesn't clear

### ISSUE THREAD

**Issue by tjrexer** [webiny/webiny-js#674]
Tooltip for an already exited Text Field is still available and rendered.

## This is:
- Bug

## Specifications

  - version: 2.6.0
  - OS: WSL (Ubuntu 18.04.3 LTS)
  - Browser: Firefox

## Expected Behavior
Only tooltip for current working text field should be available.

## Actual Behavior
Multiple tooltips overlap based on what text fields are being edited.

## Steps to Reproduce the Problem
1. Click in Text field 1.
2. Change text to Heading 1.
3. Click into Text field 2 to edit.

![image](https://user-images.githubusercontent.com/7013045/73125384-3c617e80-3f74-11ea-9cb5-9ef65a4bdc5d.png)

## Detailed Description
Tooltip doesn't seem to clear.  Could be that the original object is never released.

### Edit:
Applies to text in buttons as well.

**Comment by Pavel910** [comment]
Thanks, will see what we can do about it.

**Comment by Pavel910** [comment]
Managed to identify the exact reproduction steps for this bug: once the menu appears and you click outside of the text, the element gets deactivated but the menu is not hidden. This one will be tricky to handle but I'll see what I can do about it so it is not some kind of an insane hack.

**Comment by tjrexer** [comment]
There may also be another bug that is related, haven't fully troubleshot it to determine if it's a bug or user error though.  It seems there are some cases where clicking out of the text, the element doesn't always save to the database.  It still seems cached because you can exit the editor, and it looks the same.  However, after you navigate to a new page and back, the text changes have been reverted.  I wonder if they're related, that leaving the text element doesn't properly save & complete out it's tasks and that's why it remains.

**Comment by Pavel910** [comment]
Great feedback, I'll test this behavior when I get to this issue.

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!

**Comment by tjrexer** [comment]
Bug still exists in latest version.  Attached a screenshot for example.  Tooltip with `heading 1` is the previously selected field, while tooltip with `heading 2` is the currently selected field.  Not sure what else you guys are looking for.

<img width="1174" alt="image" src="https://user-images.githubusercontent.com/7013045/96661205-8a47bf00-1319-11eb-943d-ecb54c053b92.png">

**Comment by Pavel910** [comment]
@tjrexer not looking for anything, it was a bad stale bot configuration using Adrian's token, so it looks like it was him commenting, but in fact we just spammed our own repo accidentally :D
