### ISSUE TITLE
Update Apollo cache when a new Form is created.

### ISSUE THREAD

**Issue by Pavel910** [webiny/webiny-js#678]
Forms created in form builder are not visible in the page builder if the `listForms` query is executed BEFORE the form was created.

Say I opened the page builder, tried adding a Form, but realized I have not yet created a form, I went to Form builder, created a new form, but when I go back to the page editor, the forms list is not refreshed.

**Comment by doitadrian** [comment]
Excellent, will fix/release this over the following days.
