### ISSUE TITLE
Create a new database name for each new project

### ISSUE THREAD

**Issue by Pavel910** [webiny/webiny-js#679]
During some refactors, we moved the database connection data to `.env.json` in the root of the project. However, we forgot to update the CLI script that is creating the project and injecting the actual data into the file.

## Task description
`packages/cli/create/index.js:84` contains the line of code that injects the per-project database name into the `api/.env.json`. It needs to be applied to the `.env.json` instead.

**Comment by Fsalker** [comment]
I'll look into this
