### ISSUE TITLE
Fix links included in the initial Page Builder pages

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#683]
Initial Page Builder pages, that come out-of-the box with every Webiny installation, contain links to some of the docs.webiny.com pages.

But, a few links on the `For Developer` and `Get Started` pages point to non-existing pages. So we need to fix this (and we probably need to check all of the links on these initial pages).

And additionally, for some reason, all of the links in these pages are prefixed with the current site's domain, so basically all links are broken. 

The fix for that should probably land somewhere in the `packages/app-page-builder/src/render/plugins/slate/link/index.tsx` file.

**Comment by Fsalker** [comment]
I'd like to take this on ☄

**Comment by doitadrian** [comment]
Be my guest @Fsalker :)

**Comment by doitadrian** [comment]
I will provide a few instructions quickly @Fsalker . Hold on :)

**Comment by doitadrian** [comment]
Added a short document that says a few words about the initial data and files that are utilized in the Page Builder process (all located in a single ZIP file).

https://github.com/webiny/webiny-js/blob/master/packages/api-page-builder/README.md

The links we're talking about in this issue are all located in the initial pages that are created in the Page Builder installation process, and these pages can be found in the mentioned ZIP file. 

So you will have to unzip that, correct the broken links in the `data/pagesData.json`, create a new ZIP and commit it.

Once you're done let me know, and I'll test it out.

And of course if you have more questions, feel free to ask, I'm here.

Thanks!

**Comment by Fsalker** [comment]
Sure, I'm very easygoing with the issue.

If this is critical I may always speed it up 😄. I'm coming with questions / feedback soon.

**Comment by Fsalker** [comment]
Thanks!

**Comment by doitadrian** [comment]
@Fsalker, it's not critical, take as much time as you need!

Thank you! 🍻
