### ISSUE TITLE
Improve error messaging on apps deploy.

### ISSUE THREAD

**Issue by Pavel910** [webiny/webiny-js#685]
Currently, if you run a `deploy-apps` command, and the environment config is missing in the `.env.json` file, the output looks like this:

![image](https://user-images.githubusercontent.com/3920893/73464362-14f92000-437f-11ea-82b2-c72026d45c45.png)

Ok, it does tell you that the environment config is missing. But it **doesn't** tell you that you get that config by deploying an API for that respective environment, i.e.: `webiny deploy-api --env=dev`. 

We need to improve the message and output something like:
```
Environment "dev" is missing in ./apps/admin/.env.json file.
Have you deployed the corresponding API environment?
To deploy the API, run "webiny deploy-api --env=dev"
```

The related code is located here: `packages/cli/sls/deploy.js:43`

@doitadrian how does this look to you?

**Comment by doitadrian** [comment]
Looks good to me @Pavel910, I think this will help.

**Comment by ahmad-reza619** [comment]
i would like to try this one, but i'm first time contributor. Am i really have to make an AWS account to contribute to this issue?

**Comment by Pavel910** [comment]
@ahmad-reza619 for this particular issue you can get away without AWS account as this error is thrown before the actual deploy process begins. Let us know if you need help, and please review our [contributing guide](https://github.com/webiny/webiny-js/blob/master/CONTRIBUTING.md).

We're here for any questions :)

**Comment by ahmad-reza619** [comment]
thanks @Pavel910 , i'm on it 👍
