### ISSUE TITLE
Implement ErrorBoundary in PB Editor

### ISSUE THREAD

**Issue by Pavel910** [webiny/webiny-js#686]
The related issue is #673. We need to implement [React Error Boundaries](https://reactjs.org/docs/error-boundaries.html) on the `Element` components, so they don't blow up the entire editor. This way content editor will be able to remove the broken element from the content.

The related components that need to implement the error boundaries are:
1) `packages/app-page-builder/src/render/components/Element.tsx`
2) `packages/app-page-builder/src/editor/components/Element.tsx`

**Comment by Fsalker** [comment]
I'll snatch this

**Comment by Pavel910** [comment]
Closed by #726
