### ISSUE TITLE
Create a list of necessary AWS permissions and check them before deploying anything.

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#690]
## This is:
- Bug

## Detailed Description
Before executing the `webiny-api deploy` or `webiny-apps deploy`, we should check if the user has AWS credentials (profile) set properly. Because currently, if that's not the case, the user will experience the following error:
![image](https://user-images.githubusercontent.com/5121148/73764902-042c1e00-4774-11ea-8eeb-ef7e6d740e2a.png)

**Comment by Pavel910** [comment]
The SLS components are doing the check for credentials. This error is not about the missing credentials, but about wrong permissions those credentials have. That's the issue we talked about earlier, where we need to create an exact list of permissions and check those.

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
