### ISSUE TITLE
Incorrect link on initial "Get Started" page

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#698]
## This is:
- Bug

## Expected Behavior
The link should contain the correct URL.

## Actual Behavior
The link contains an incorrect URL.

## Steps to Reproduce the Problem
1. Open YOUR_SITE/blog/get-started
2. On the bottom, there is a button `JOIN WEBINY COMMUNITY`
3. Check its link, it's wrong

![image](https://user-images.githubusercontent.com/5121148/73971487-434aa280-491f-11ea-8342-e2cb7c5e23b1.png)

## Possible Solution
Fix the link. Short information on how to access these initial pages (they are in a ZIP file) can be found here: https://github.com/webiny/webiny-js/tree/master/packages/api-page-builder

**Comment by ahmad-reza619** [comment]
Hi @doitadrian where is the link should goes to? i have tried to open it and it points to https://community.webiny.com

**Comment by doitadrian** [comment]
Oh, it seems that this was already resolved via #683. 

Sorry for that :/

Will close this immediately.
