### ISSUE TITLE
Page Builder - image element rendered with incorrect dimensions

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#699]
## This is:
- Bug

## Expected Behavior
Images should be the same size.

## Actual Behavior
Image is large in preview, and small in the editor.

## Steps to Reproduce the Problem
1. Add a new image element, and select an image (possibly small)
2. Compare its size with the one in the page preview mode

## Possible Solution
Check render/editor plugins and determine which one is rendering the image incorrectly.

`packages/app-page-builder/src/render/plugins/elements/image/Image.tsx`
`packages/app-page-builder/src/editor/plugins/elements/image/Image.tsx`

![image](https://user-images.githubusercontent.com/5121148/74030733-0f6b8d80-49b0-11ea-8527-0e36f8568bc4.png)

**Comment by ganeshmani** [comment]
I would like to work on this issue

**Comment by TommyJackson85** [comment]
@ganeshmani are you still working on this issue?
If not, I will work on this issue if it is still relevant (after the recent changes to the project I mean).

**Comment by ganeshmani** [comment]
@TommyJackson85 feel free to take this issue..

**Comment by TommyJackson85** [comment]
@doitadrian is this issue still relevant with the recent changes to the application?

**Comment by Pavel910** [comment]
@TommyJackson85 I believe it's still relevant. If this was closed, it would be referenced by a PR. So feel free to jump on it. I'll assign you to this issue.

**Comment by TommyJackson85** [comment]
@Pavel910 Ok good to know, I will work on it next.

**Comment by TommyJackson85** [comment]
I'm having issues trying to upload images. They dont load once they're uploaded.
Is this a new bug?
<img width="906" alt="Screenshot 2020-07-10 at 18 51 58" src="https://user-images.githubusercontent.com/22279028/87183709-8948cf80-c2de-11ea-896f-ba9627be6149.png">

**Comment by TommyJackson85** [comment]
@Pavel910 When putting loading images through render and not the images the width and height keys dont appear to be generated.
 Maybe as a further enhancement, instead of changing the width/height to 100% (when width/height keys are not found) we could attempt to render the image src file in advance to find it's ```naturalHeight``` / ```naturalWidth``` dimensions.
```    
const style = { width, height };
    if (!style.width) {
        style.width = "100%"; 
    } else {
        style.width += style.width.endsWith("px") ? "" : "px";
    }
```
Could create a separate issue on this if its not relevent.

**Comment by TommyJackson85** [comment]
Continue this conversation in the new PR if you like.
