### ISSUE TITLE
Can't seem to install - An error occurred during deployment of cognito

### ISSUE THREAD

**Issue by kszpirak** [webiny/webiny-js#700]
Can't seem to install webiny-js. using MacOS Mojave 10.14.6

Here is my stack trace:
`
**webiny deploy-api --debug**

This is the first deploy of local environment, so it may take a few minutes.
Here's 🍪 to make the time pass faster :)
💡 Loaded local environment from /Users/user/src/test-serverless/frontend/www.test.com/webiny/.env.json...
💡 Loaded local environment from /Users/user/src/test-serverless/frontend/www.test.com/webiny/api/.env.json...

  webiny Collecting components from the template. +0ms
  webiny Executing the template's components graph. +9ms
  webiny:cognito Creating new user pool. +0ms

  **An error occurred during deployment of cognito

TypeError: this.context.instance.getResourceName is not a function**
`
How can I debug / check where the issue might be? Also how can I specify the AWS profile I want to deploy this to?

Thanks

Konrad

**Comment by doitadrian** [comment]
Thank you for the report @kszpirak, can you let us know which version of `@webiny/cli`, node and yarn you have installed?

**Comment by Pavel910** [comment]
This is definitely a CLI issue (that `getResourceName` method is related to the improved resource names that were introduced in the CLI v3). So please upgrade your `@webiny/cli` to the newest version and it will work just fine.

Cheers!
