### ISSUE TITLE
Allow for custom names with multiple projects

### ISSUE THREAD

**Issue by tjrexer** [webiny/webiny-js#701]
If hosting multiple sites with webiny, it may become difficult to manage which functions, endpoints, & buckets are used for which application.  You can look through the env files, but if you are trying to manage or troubleshoot within AWS it is difficult.

## This is:
- Idea

## Detailed Description
You can easily add another string between the function name and the unique id.  This would make it easier to differentiate which application you are looking at since the id would be something like <uuid>_<env>_files_graphql.

Add an option for the app name here
https://github.com/webiny/webiny-js/blob/170cd06dc00a635adc3ae88370f18056116fd9b1/packages/cli/cli.js#L35-L41

Implement here, after uuid.
https://github.com/webiny/webiny-js/blob/170cd06dc00a635adc3ae88370f18056116fd9b1/packages/cli/create/index.js#L144-L147

**Comment by tjrexer** [comment]
Could also just replace webiny-uuid with <app>-uuid.

**Comment by Pavel910** [comment]
With our latest release we have improved the naming of resources, so they now look like this:

![image](https://user-images.githubusercontent.com/3920893/74090464-ecbe9f00-4aab-11ea-9d43-500b77e1c05e.png)

So the structure of the name is: `{sls_id}_{env}_{alias}_{purpose}`.
`{sls_id}` is taken from `api/.serverless/_.json`, `{alias}` is the key of the resource from `serverless.yaml` and `{purpose}` is kind of a short description which is internal to the component being deployed.

**Comment by Pavel910** [comment]
Ah I get it now, you actually want a human-readable string to be a part of this ID, like `my-project_sqxkkbs_local_pageBuilder_graphql`, right?

I think that shouldn't be a problem 👍

**Comment by tjrexer** [comment]
Yep, that's the idea.

**Comment by Pavel910** [comment]
@tjrexer this is an old issue, so I'm closing it and just wanted to inform you that the resource naming was upgraded to look like this `49ae3be_webiny-js_api_dev_apolloGateway`, so the pattern goes like this: `{stateId}_{projectName}_{stack}_{env}_{resourceName}`.
