### ISSUE TITLE
CSS File not updated on deployment

### ISSUE THREAD

**Issue by tjrexer** [webiny/webiny-js#708]
After updating the SCSS file and pushing to production environment the html file still has a reference to an older version of the main.uuid.css file.

## This is:
- Bug

## Specifications

  - version: 3.0.1
  - OS: Ubuntu 18 (WSL)
  - Browser: Firefox & Chrome

## Expected Behavior
After updating App.scss to include custom scss file, should expect new css file to be re-deployed and html file to be updated with correct filename.

## Actual Behavior
main.uuid.scss is update, but html file still references older version.

## Steps to Reproduce the Problem
1. Build project locally, with custom scss (either directly modifying App.scss or import a custom scss).
2. Validate css changes locally.
3. Push to production environment.
4. Validate css in production.
5. Make new schanges to scss.
6. Validate css changes locally.
7. Push to production environment.
8. No css is loaded as the main.uuid.css file is no longer valid.

**Comment by tjrexer** [comment]
Glad you fixed it in the code, what's the best short term solution for me? Remove the Site Lambda function and re-deploy?

**Comment by doitadrian** [comment]
Hi @tjrexer, we will be releasing a set of fixes today or early tomorrow, so I'll let you know when that's out.

**Comment by doitadrian** [comment]
One thing to note here, please just remove the `invalidateOnDeploy` flag in your `apps/serverless.yml` file. We realized it's not needed in the end (don't worry, cache invalidation will still happen on site visit).

![image](https://user-images.githubusercontent.com/5121148/74520550-164a5100-4f18-11ea-970b-eacf7b30ec66.png)
