### ISSUE TITLE
Page Builder - if installing on localhost, add warning about site domain

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#711]
## This is:

- Feature request

## Description
In the Page Builder app's installation process, users need to enter their site domain. Normally, if the app was deployed to the cloud (and being accessed via CloudFront URL), the admin and site apps will reside on the same domain. So, prefilling the site domain input with the domain over which the admin was accessed, is in 99.99% cases correct.

But in localhost, admin and site apps are hosted on different ports, and that's why we cannot just take the domain over which the admin was accessed. Usually, admin is hosted on `localhost:3000` and site on `localhost:3001`.

## Possible Solution
If the installation is happening on localhost, let's automatically prefill the `http://localhost:3000` as the site domain, and also add a note to the user - saying that they should start the site app in order to double-check the port.

**Comment by doitadrian** [comment]
The input is located here: `packages/app-page-builder/src/admin/plugins/install.tsx:121`.

The default value for the Domain field is set here: `packages/app-page-builder/src/admin/plugins/install.tsx:95`

**Comment by Arvisix** [comment]
I'll take this one

**Comment by TommyJackson85** [comment]
@Arvisix are you still working on this? 
If not, I will work on this issue if it is still relevant (after the recent changes to the project I mean).

**Comment by Pavel910** [comment]
@TommyJackson85 this issue is being handled by one of our developers. @Ashu96 please confirm :)

**Comment by Ashu96** [comment]
Thanks @Pavel910 

@TommyJackson85 this issue has been resolved. We will close this on shortly. 🙂
