### ISSUE TITLE
Run AWS credentials check automatically via CLI

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#713]
## This is:
- Feature request

## Expected Behavior
In order to make DX better, let's automatically execute the following check for our users, and throw a clear error message if the credentials are incorrect / missing.

![image](https://user-images.githubusercontent.com/5121148/74251470-78bf0980-4cec-11ea-874a-21ff0f42b909.png)

**Comment by glennfaison** [comment]
What do you think about running `aws sts get-caller-identity` as a node.js `child_process`? This is based on the assumption that the AWS CLI will be installed before running `yarn setup-repo`.

**Comment by Pavel910** [comment]
@glennfaison that was the idea, yes. We use [execa](https://www.npmjs.com/package/execa) in our CLI for all child process executions.

This is the place where the check should be implemented: `packages/cli/sls/execute.js:6`, right at the beginning of that function.

**Comment by TommyJackson85** [comment]
I will work on this issue if it is still relevant (after the recent changes to the project I mean).

**Comment by Pavel910** [comment]
@TommyJackson85 this can now be implemented much better then I initially envisioned, by using a recent addition to the CLI - deploy hooks.

In here `packages/cli-plugin-deploy-components/index.js` add a new plugin of type `hook-before-deploy`, which looks like this:

```
{
    type: "hook-before-deploy",
    async hook(params, context) {
        // check AWS credentials
    }
}
```

This plugin will automatically be processed each time you run a `deploy` command. You just need to implement credentials checks. 

Let me know if you have questions along the way!

**Comment by TommyJackson85** [comment]
@Pavel910 should i use the [child process node.js documentation](https://nodejs.org/api/child_process.html) to run the aws commands within the hook function? 

So far this is what I am going for:
<img width="795" alt="Screenshot 2020-07-05 at 17 43 41" src="https://user-images.githubusercontent.com/22279028/86537466-21ae1100-bee7-11ea-9ff5-06f7974db052.png">

Correct what you see for me so far. I will create a PR later tonight.

**Comment by Pavel910** [comment]
@TommyJackson85 use the SDK: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/STS.html#getCallerIdentity-property

And of course, move the plugin into a separate folder, the same way `deploy` and `remove` are handled.
If the user doesn't have the credentials, print a message and attach a link to our docs: https://docs.webiny.com/docs/guides/aws-credentials

**Comment by TommyJackson85** [comment]
> @glennfaison that was the idea, yes. We use [execa](https://www.npmjs.com/package/execa) in our CLI for all child process executions.
> 
> This is the place where the check should be implemented: `packages/cli/sls/execute.js:6`, right at the beginning of that function.

@Pavel910 I assume this post is out dated as this file doesn't exist anymore? The command will now be executed from ```packages/cli-plugin-deploy-components/index.js```, correct?

I've created an aws folder with files index.js and aws.js following the same template as ```deploy``` and ```remove```, for the time being.
What will be passed in ```params``` and ```context``` when this function is run? Should ```execa``` be inside the hook function or will be params or context?

I haven't written anything yet in "aws/aws.js"
Trying something like this from "aws/index.js":
<img width="878" alt="Screenshot 2020-07-05 at 19 32 12" src="https://user-images.githubusercontent.com/22279028/86539718-cbe16500-bef6-11ea-894a-25c84feadc45.png">

**Comment by Pavel910** [comment]
@TommyJackson85 yes this issue was opened long ago, and a lot of things changed in the meantime. You're on a good path here.

Just do a `console.log` to see what comes in `params` :) Here are some references to the code that executes hooks:
https://github.com/webiny/webiny-js/blob/master/packages/cli-plugin-deploy-components/deploy/deploy.js#L79

And `context` is an instance of CLI context: https://github.com/webiny/webiny-js/blob/master/packages/cli/context.js

For this particular plugin, `params` are irrelevant, as you want to check AWS credentials on every deploy.

**Comment by TommyJackson85** [comment]
> @TommyJackson85 yes this issue was opened long ago, and a lot of things changed in the meantime. You're on a good path here.
> 
> Just do a `console.log` to see what comes in `params` :) Here are some references to the code that executes hooks:
> https://github.com/webiny/webiny-js/blob/master/packages/cli-plugin-deploy-components/deploy/deploy.js#L79
> 
> And `context` is an instance of CLI context: https://github.com/webiny/webiny-js/blob/master/packages/cli/context.js
> 
> For this particular plugin, `params` are irrelevant, as you want to check AWS credentials on every deploy.

just updated my last post haha!

**Comment by Pavel910** [comment]
@TommyJackson85 credentials will not be passed in `params`. See the link in my previous comment. These plugins are generic, and `params` will contain some basic information about the deploy process.

Webiny itself doesn't load AWS credentials; we absolutely don't care where they come from, as long as AWS SDK is happy.

**Comment by TommyJackson85** [comment]
@Pavel910 I am trying to run ```lerna watch``` on ```cli-plugin-deploy-components``` to ```console.log(params)``` , but its saying no packages found. Is it only some of the packages that need to be run lerna watch?
Here are the commands I am using:
<img width="966" alt="Screenshot 2020-07-07 at 12 43 38" src="https://user-images.githubusercontent.com/22279028/86775842-9dc36880-c04f-11ea-9396-eb07b7e89db0.png">

**Comment by Pavel910** [comment]
@TommyJackson85 that package is written in Vanilla JS, so you don't need to build it. Just add code as you wish and run the deploy.

**Comment by TommyJackson85** [comment]
am i to run it from apps/admin or from api? it is a cli package.

**Comment by Pavel910** [comment]
@TommyJackson85 it's a CLI plugin, used in `webiny.root.js`. It add `deploy` command to the CLI. So to run its code, you need to run the deploy, as you normally do it. Run it from `sample-project` folder, `npx webiny deploy api --env=local`.

**Comment by TommyJackson85** [comment]
oh sorry! I was running yarn start from admin by mistake.

**Comment by TommyJackson85** [comment]
Result of ```params``` and ```context```  ("params:::::::::" and "context::::::::::" are just strings and running in the console to mark which is which):
<img width="1056" alt="Screenshot 2020-07-07 at 14 26 51" src="https://user-images.githubusercontent.com/22279028/86788373-00236580-c05e-11ea-90f8-082a6c81745f.png">
<img width="1058" alt="Screenshot 2020-07-07 at 14 27 07" src="https://user-images.githubusercontent.com/22279028/86788381-044f8300-c05e-11ea-8fa6-fa0fb7b08401.png">

are we doing anything with params of context for this feature?

**Comment by Pavel910** [comment]
@TommyJackson85 
1) you don't need neither `params` nor `context` for what you're doing.
2) hooks are not repeated twice, they are 2 separate plugins, see the last letter - it's different.
3) to fix `posthog-node` problem, you can either run `yarn` to install all dependencies, or update your fork to the latest `master` because I removed that dependency today.

**Comment by TommyJackson85** [comment]
> @TommyJackson85
> 
> 1. you don't need neither `params` nor `context` for what you're doing.
> 2. hooks are not repeated twice, they are 2 separate plugins, see the last letter - it's different.
> 3. to fix `posthog-node` problem, you can either run `yarn` to install all dependencies, or update your fork to the latest `master` because I removed that dependency today.
> 
> Whenever you see `Cannot find module...`, most likely you forgot to run `yarn` to install all dependencies.

yeah I know, I didn't make a bid deal about the error, I just thought it was to do with the code I wrote. Will fix it now.

**Comment by TommyJackson85** [comment]
fixed it and trying to import aws for the sts
<img width="580" alt="Screenshot 2020-07-07 at 15 15 21" src="https://user-images.githubusercontent.com/22279028/86794782-cb66dc80-c064-11ea-9e73-ccfe355e654d.png">
I was getting an sts wasnt defined and now an aws wasnt defined.
Do I need to import aws from a specific file for this?

**Comment by TommyJackson85** [comment]
for further context here, I found this is the webiny-js project folder:
```
const getAccountId = async aws => {
    const STS = new aws.STS();
    const res = await STS.getCallerIdentity({}).promise();
    return res.Account;
};
```
I assume this is a global function that passes in an aws parameter, but i cant find being used anywhere in the project.

**Comment by Pavel910** [comment]
@TommyJackson85 nothing is global, and there is no magic. You need to require `aws` like you normally would require any other library:

```js
const STS = require("aws/clients/sts");
```

The function you're referring to (getAccountId) is part of the package, see the screenshot below:
![image](https://user-images.githubusercontent.com/3920893/86812305-29082280-c07f-11ea-9240-033e8a857135.png)

It has nothing to do with what you're doing. So you need to require the `sts` client, and do the checks in the plugin. Regular JS, no magic :) Webiny is not providing any magic or silver bullets for anything. It's all  plain JS; we just offer some structure and a system of plugins.

Feel free to ask if something is confusing or unclear. Cheers!

**Comment by TommyJackson85** [comment]
"aws/clients/sts" wasnt found, I received this error:
```(node:3103) UnhandledPromiseRejectionWarning: Error: Cannot find module 'aws/clients/sts'```
 so I used "aws-sdk" instead like this (is it the same?):
```const sts = require("aws-sdk/clients/sts");```
Seems to work better but I am now getting this error:
```  🚨 Hook cli-command-aws encountered an error: sts.getCallerIdentity is not a function```
Am I using this correctly?:

<img width="731" alt="Screenshot 2020-07-07 at 22 28 47" src="https://user-images.githubusercontent.com/22279028/86845355-45b55200-c0a1-11ea-99dd-5d34e24b438b.png">

**Comment by Pavel910** [comment]
@TommyJackson85 yes `aws-sdk` is the right package, my bad.

Read AWS docs to see how SDK clients are being used: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/STS.html
You need to instantiate it.

In AWS docs you'll always see them reference the clients as `var sts = new AWS.STS();`, via the `AWS` variable. That's because the docs are written as if you were loading the whole SDK, but we just want to use the specific client.

So all in all, it would look like this:
```js
const STS = require("aws-sdk/clients/sts");
const sts = new STS();
await sts.getCallerIdentity({}).promise();
```

2 things to note:
1) `await` can only work with Promises, that's why the `.promise()` appended to `await sts.getCallerIdentity({}).promise();`. All AWS SDK methods support this. Don't use the old callback syntax, it's really on its way out of common usage. Also, if you're using callback, you can't use try/catch to catch errors thrown from them.
2) `getCallerIdentity` doesn't take any parameters (see the docs). So don't pass the hook parameters to SDK calls, that's not what they're for. In your case, you can simply define `hook` as `async hook() { ... }` without any parameters, if they confuse you.

**Comment by TommyJackson85** [comment]
> @TommyJackson85 yes `aws-sdk` is the right package, my bad.
> 
> Read AWS docs to see how SDK clients are being used: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/STS.html
> You need to instantiate it.
> 
> In AWS docs you'll always see them reference the clients as `var sts = new AWS.STS();`, via the `AWS` variable. That's because the docs are written as if you were loading the whole SDK, but we just want to use the specific client.
> 
> So all in all, it would look like this:
> 
> ```js
> const STS = require("aws-sdk/clients/sts");
> const sts = new STS();
> await sts.getCallerIdentity({}).promise();
> ```
> 
> 2 things to note:
> 
> 1. `await` can only work with Promises, that's why the `.promise()` appended to `await sts.getCallerIdentity({}).promise();`. All AWS SDK methods support this. Don't use the old callback syntax, it's really on its way out of common usage. Also, if you're using callback, you can't use try/catch to catch errors thrown from them.
> 2. `getCallerIdentity` doesn't take any parameters (see the docs). So don't pass the hook parameters to SDK calls, that's not what they're for. In your case, you can simply define `hook` as `async hook() { ... }` without any parameters, if they confuse you.

Thanks for the help so far! Have a look at my PR request to see how I am doing.
