### ISSUE TITLE
Buttons & Images only link internally

### ISSUE THREAD

**Issue by tjrexer** [webiny/webiny-js#719]
When adding a url to a button only internal pages are linked.  

## This is:
- Bug

## Specifications

  - version: 3.1.2
  - OS: Ubuntu 18 WSL
  - Browser: Firefox

## Expected Behavior
Links should open to external pages if the url is complete.

## Actual Behavior
Site url is appended to the front of the url in the link.

## Steps to Reproduce the Problem
1. Create a button or an image.
2. Update the link to a url
3. Test link.

## Detailed Description
I'm trying to link out to an external site with a button, but the link only allows internal urls.

## Possible Solution
Add a slider to allow external instead of internal like new tab.  If slider is active, don't alter URL.

**Comment by Pavel910** [comment]
This sounds very familiar; we did have a PR recently, related to link construction and we also had this problem with external links not so long ago. I'll review it again, thanks for reporting 👍

**Comment by tjrexer** [comment]
Taking a closer look, it looks like the page renders 2 Anonymous Objects.
![image](https://user-images.githubusercontent.com/7013045/74786564-06fe3700-527b-11ea-8c6c-863e71fb26c8.png)

The outer object links to the correct place.
![image](https://user-images.githubusercontent.com/7013045/74786588-154c5300-527b-11ea-8b1a-16840d7b3ff9.png)

But the inner Object, has added the section to the url.
![image](https://user-images.githubusercontent.com/7013045/74786639-31e88b00-527b-11ea-804b-96f3f726a3ca.png)


Also, taking a look in the DB, it is stored as the straight url.
![image](https://user-images.githubusercontent.com/7013045/74786670-49277880-527b-11ea-8051-04f69c3be809.png)

Only related section that I can find is [here](https://github.com/webiny/webiny-js/blob/8a33b92b8753e704c863b17c41ef8ce93dac795c/packages/app-page-builder/src/render/plugins/elements/button/Button.tsx#L35-L50).  It looks like in the last commit, it was converted from just `a` to a conditional and render either `Link` or `a`.  I know I've had problems in other projects with `Link` vs `a`.

**Comment by tjrexer** [comment]
Pushed PR #724 

Long term solution might be to add another boolean value for the link object.  This way you don't have to determine whether to do a `Link` or `a` based on an internal value.  This can either be populated by user selection or automatically.  Automatically, could mimic the menu functionality, or could compare the href against the site url.  The disadvantage to the later method would be if a user changes the site url, you would then have to re-calculate all links to see if they are now internal or external.

**Comment by tjrexer** [comment]
What's the best way to fix this in the short term. I've added the code in the PR with `yarn add file:path` to apps/site but when I run `webiny deploy-apps --env=prod` it doesn't actually update the production js, am I missing a reference somewhere? I also re-deployed the API with no success.

**Comment by Pavel910** [comment]
If it's urgent and you really need it `now`, the easiest way would be to override the Page Builder plugins that render those links: `pb-render-page-element-button` and `pb-render-page-element-image`.

Here are the references:
https://github.com/webiny/webiny-js/blob/master/packages/app-page-builder/src/render/plugins/elements/button/index.tsx
https://github.com/webiny/webiny-js/blob/master/packages/app-page-builder/src/render/plugins/elements/image/index.tsx

Simply recreate these plugins in your app, and register them after all the other plugins in your `App.js`: `apps/site/src/App.js:11`.

If you can wait till tomorrow, I can dedicate some time and fix this officially in the Link component.

**Comment by tjrexer** [comment]
That fix worked, missed it in the project root.  I don't want to derail any dev you guys have in flight since I seem to be the only person affected by it.  I'll take a look at the re-work you recommended in the PR & work it in.

**Comment by Pavel910** [comment]
Perfect! If you need help let me know :) Thanks for your time and effort ❤️
