### ISSUE TITLE
SSR cache does not refresh

### ISSUE THREAD

**Issue by val-fom** [webiny/webiny-js#720]
## This is:

- Bug

## Specifications

  - version: @webiny/http-handler-ssr@2.0.3

## Expected Behavior

Cache refreshes asynchronously.
When refreshing the page, `max-age` in response headers should be ~19 `(staleTtl)`, then ~60 `(ttl - staleTtl)`

## Actual Behavior

`max-age` header always shows around ~19 `(staleTtl)` and never gets ~60 `(ttl - staleTtl)`

## Possible Solution

See PRs

**Comment by doitadrian** [comment]
Fixed by #722. Closing.
