### ISSUE TITLE
CLI - Scaffolding

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#730]
## This is:
- Feature request

## Detailed Description
When it comes to creating initial files for a new GraphQL service or a new React app, currently, our users still have to do a significant amount of manual repetitive work.

That's why we want to add the "scaffolding" function to the CLI. Basically, if a user wants to start creating a new GraphQL service, he would use the CLI to generate all of the initial files. 

This will enable the user to immediately jump to the code, which not only will make the DX better, but will also reduce the amount of docs we'll need to write.

## Possible Solution
The command might look something like the following:

```webiny scaffold```

After that, the CLI will internally search for all `@webiny/cli-scaffold-*` and `webiny-cli-scaffold-*` packages, and output the list with the [Inquirer](https://github.com/SBoudrias/Inquirer.js/).

Once a user selects a scaffold template, the CLI will select and execute the template's "list-options" code. In other words, the CLI will start asking questions that were defined in the selected template (e.g. a folder in which the scaffolding should be executed). Once all of the options have been chosen, the scaffolding starts and the user should end up with all of the necessary files in place.

I suggest that in these scaffold templates, we just use named exports for every part of the scaffolding process. For example:

```js
// packages/cli-scaffold-graphql-service/index.js

module.exports.name = "GraphQL Service";
module.exports.description = "GraphQL Service";

// Generates the interactive options selection . Not sure if this just 
// returns the params for the inquirer, or the inquirer can be directly 
// used here. I believe the first option is better.
module.exports.options = () => { ... }

// Generates (or copy&pastes, depends on the template) all of the necessary files, 
// based on the selected options.
module.exports.scaffold = ({ options }) => { ... } // or module.exports.generate = () => {}
```

Either that, or we can just export a simple object with all of these properties. We can even export the plugin here or array of plugins, so in the future, we could maybe add additional customizations here. If you ask me, I would actually do something like that. For example:

```js
// packages/cli-scaffold-graphql-service/index.js

module.exports = [
	{
		type: "scaffold-template",
		name: "scaffold-template-apollo-graphql-service",
		scaffold: {
			name: "...",
			description: "...",
			options: () => {}
			generate: () => {}
		}
	},
	{ ... } // If needed, more plugins could be exported, but I don't see an example right now.
]
```

The actual CLI code is located in the `packages/cli` folder.

**Comment by doitadrian** [comment]
When you get a chance @Pavel910, could you please share your thoughts regarding the actual files that need to be generated. We can start with the API, and then resolve the apps part (I know you had some new ideas in the apps department).

And of course, any suggestions/comments on the said above are also welcome.

**Comment by Pavel910** [comment]
I really don't think we need to go over the top with plugins here. Just regular default export of an object:

```js
module.exports = {
    name: "Webiny Apollo Service",
    scaffold(options) {
        // Create whatever it is you're creating
    }
}
```

As you @doitadrian  said, the `options` method can return an array of options for inquirer, we'll just run the inquirer internally to get the answers and forward them to `scaffold` function.

--
At this point I don't have anything to add that was not already mentioned. Let's get this going and we'll review as we go and maybe add/change things along the way.

**Comment by doitadrian** [comment]
@Fsalker You can start with this when you're ready.

BTW @Pavel910 the other PR from @Fsalker requires my attention before merging it.

**Comment by Pavel910** [comment]
@doitadrian I was editing my comment as you posted the response; I added 2 templates I would like to start with.

I'm not touching that PR, it's yours ;)

**Comment by doitadrian** [comment]
Sorry @Pavel910! 

Great addition, thank you!

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
