### ISSUE TITLE
Page List Link for Menu Fails

### ISSUE THREAD

**Issue by tjrexer** [webiny/webiny-js#731]
Adding a menu item with a ~~folder~~ page list fails to render.

## This is:
- Bug

## Specifications

  - version: 3.2.1
  - OS: OSX 10.15.3
  - Browser: Firefox

## Expected Behavior
Drop Down should open with a list of all pages in the category.

## Actual Behavior
Page crashes when renders menu with an error pointing to this section.
https://github.com/webiny/webiny-js/blob/3da0566f29e1d46df0e7c357be0b42bdaa4c7d2b/packages/app-page-builder-theme/src/components/Navigation.tsx#L5-L7

## Steps to Reproduce the Problem
1. Start admin portal.
2. Go to menu.
3. Add ~~folder~~ page list menu item.
4. Save menu.
5. Open site (or hard re-load)
6. Page renders, then when menu tries to load it crashes with error.

## Detailed Description
After reviewing the db, there is no page listed in the menu object.  This may be the source of the error.  The query may be only returning a single link item, not a list as intended.

## Possible Solution
A list of link objects should be returned by the query, not just a single object.  Additionally, the ~~folder~~ page list link should not immediately render a page.

However, additional improvements can be added at the same time:
1. Limit the number of items included in lists.  Use case: If a category is used for blog posts, only the top number of posts should be shown.
2. ~~Folder~~ Page List renders a page that includes more information than just the page name.  Same query can be used, with more information presented.  Same use case as above for categories as blog posts.

**Comment by tjrexer** [comment]
Mistyped in original, it's a page list not a folder.  I solved the problem with a folder and manually creating the page links as needed.

**Comment by Pavel910** [comment]
I'll see what's going on. The entire menu structure is constructed on the API side, so most probably there is a bug there, and React just explodes due to invalid data being returned. 

Thanks for creating an issue :)

**Comment by doitadrian** [comment]
@tjrexer The PR has been submitted and hopefully will be merged/released today.

**Comment by doitadrian** [comment]
Released! 

`yarn upgrade @webiny/api-page-builder` is what you'll need, but of course, you can run `yarn upgrade --scope @webiny` in order to upgrade all `@webiny/*` packages.

If that doesn't work (like it was the case a while ago 🙂), then I guess `yarn upgrade-interactive` will be a way to go.
