### ISSUE TITLE
Clicking outside of the text of a menu button doesn't link to another page

### ISSUE THREAD

**Issue by Fsalker** [webiny/webiny-js#737]
When creating a `Navigation` component (`packages/app-page-builder-theme/src/components/Navigation.tsx`), it is only possible to access the linked url by clicking on the button's text itself (the **blue** area in the screenshot).

Even though the `li` element intuitively shows us we're focusing the button, clicking it sometimes won't do anything. This happens when we click on the `li`'s padding rather than its anchor's content (the **green** area in the screenshot).

![image](https://user-images.githubusercontent.com/16700631/75762815-f7cfbc80-5d43-11ea-9950-4f2ed41f6e2a.png)

## This is:
- Bug

## Steps to Reproduce the Problem
Run the `site` app (ie: from `./examples/apps/site`) and check the menu.

**Comment by SvenAlHamad** [comment]
We should remove the padding from the list item `li`, and move it to the anchor element...this will fix it.

**Comment by doitadrian** [comment]
Had to revert changes made in the PR, since it introduced another bug with displaying the menu items:
![image](https://user-images.githubusercontent.com/5121148/80815021-37dcdf80-8bcd-11ea-8899-c9e70396b310.png)

**Comment by TommyJackson85** [comment]
I will work on this issue if it is still relevant (after the recent changes to the project I mean).

**Comment by Pavel910** [comment]
@Ashu96 @doitadrian please confirm this is still an issue, I'm totally out of the loop on this one.

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
