### ISSUE TITLE
When navigating between pages the scroll bar doesn't go to the top.

### ISSUE THREAD

**Issue by SvenAlHamad** [webiny/webiny-js#738]
## This is:
- Bug

## Specifications
  - version: 3
  - OS: Mac
  - Browser: Chrome

## Expected Behavior
If I navigate to one page, scroll to the bottom of the page, and then click on another page in the main navigation, the new page opens, but the scroll bar still stays on the bottom of the page. 

## Actual Behavior
The scrollbar should go to the top of the page as I navigate between pages.

## Steps to Reproduce the Problem
1. Open one page
2. Scroll to the bottom of the page
3. Open another page
4. Check where your scrollbar is positioned.

**Comment by TommyJackson85** [comment]
I will work on this issue if it is still relevant (after the recent changes to the project I mean).

**Comment by TommyJackson85** [comment]
@SvenAlHamad I am not seeing any issue here, can you be more specific on how you came across this problem, like what pages?
@Pavel910 has this issue already been fixed?

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
