### ISSUE TITLE
Introduce fine-grained security scopes

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#747]
## This is:

- Feature request

## Detailed Description
Currently, the security scopes that are assigned in the GraphQL API plugins are just too vague. In other words, they don't allow fine-grained permissions control. 

For example, for all of the `Menu`-related GQL fields (`packages/api-page-builder/src/plugins/graphql.ts`), we used the `pb:menu:crud` security scope. Because of this, users cannot create a new role that would, for example, only give access to `createMenu` and `updateMenu` GQL endpoint.

![image](https://user-images.githubusercontent.com/5121148/76211878-7eceda00-6207-11ea-9161-cd8947c06f35.png)

### Use more fine-grained scopes
Security scopes should be more fine-grained. In other words, instead of using `pb:menu:crud` for the `createMenu`, use `pb:menu:create`.

### Webiny default apps - create initial roles in the installation process
With this, we'll also need to create a couple of useful roles for each app, so that users don't have to construct them on their own.

What's important here is that these roles must be inserted in the app's installation process. So, for example, when you install the Page Builder app, it would also create roles like `Pages CRUD`, `Publish pages`, and so on (whatever comes to your mind, that might be useful).

##### Example of a CRUD role
`Menus CRUD` role could consist of `pb:menu:create`, `pb:menu:read`, `pb:menu:update`, and `pb:menu:delete` scopes. The same could be done for `Categories CRUD`, `Pages CRUD` etc.

### Fix issue in the menus
One issue that will probably reach the surface once we do the above, is the visibility of menus in the Admin UI. For example, if we take a look at the menus plugins for the Form Builder app, we can see that the user has to have `i18n-locales` role in order to see the menu item (`packages/app-i18n/src/admin/plugins/menus.tsx`):

![image](https://user-images.githubusercontent.com/5121148/76212837-a32bb600-6209-11ea-9e21-9d6354c18230.png)

So, we'll have to define the actual scopes that are going to be needed in order for the menu item to be visible. This is because the security scope is the only security resource that is static (it's defined on the API side and it doesn't change), as opposed to roles, which are created by users.

The same applies for routes (`packages/app-i18n/src/admin/plugins/routes.tsx`):
![image](https://user-images.githubusercontent.com/5121148/76213061-23eab200-620a-11ea-9b78-2de4c53a3145.png)

**Comment by Pavel910** [comment]
Linking this with #1206 and #1194  which describe how fine-grained permissions will work.
