### ISSUE TITLE
I18N Service Plugins - Improve Error Messaging

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#748]
## This is:

- Feature request

## Detailed Description
Currently, if a user forgets to pass the `I18N_API_URL` into the serverless component (`serverless.yml`), the whole service would not work at all. 

![image](https://user-images.githubusercontent.com/5121148/76301239-3b837280-62be-11ea-8b91-558fe73fa40c.png)

And if you open the CloudWatch log, you can see the following error:
![image](https://user-images.githubusercontent.com/5121148/76301183-24448500-62be-11ea-9516-f802a3d05219.png)

## Possible Solution
This error probably won't mean a lot to the user, so let's make it a bit more friendly. 

Let's check the passed env variable here: `packages/api-i18n/src/plugins/service.ts:32`. 

If it doesn't exist, or it's not a valid URL, we should throw an error message like 
> `I18N_API_URL env variable is not a valid URL. Make sure it's specified in the service configuration.`. 

This is just a quick example. Of course, you are allowed to use your imagination / be creative 😃

**Comment by Arvisix** [comment]
May I start working on this issue?

**Comment by doitadrian** [comment]
Sure, go for it! 

If you need any assistance, just let us know here, or via [gitter](https://gitter.im/Webiny/webiny-js).
