### ISSUE TITLE
[UI improvement] The "i" icon that opens picture properties in File Manager is not obvious 

### ISSUE THREAD

**Issue by bigb123** [webiny/webiny-js#756]
## This is:

- Improvement

## Specifications

  - version: @webiny/cli@3.2.5, @webiny/serverless-files@2.3.3, @webiny/api-files@2.2.1
  - OS: MacOs Catailna 10.15.3
  - Browser: 73.0.1

## Expected Behavior

The "i" icon that opens picture's properties panel in File Manager should be easy accessible.

## Actual Behavior

The "i" icon that shows picture properties in File Manager is hidden and it requires to know where to hover the mouse over the picture (top right corner) to open the panel on the right.

![webiny file manager info icon](https://user-images.githubusercontent.com/9221943/76642102-373cab00-6585-11ea-8aaa-763e7b80a722.gif)

## Detailed Description

I found this icon accidentally. 

It took me a week or two to figure out that I don't have to remove the pictures records from the MongoDB to get rid of the photos from file manager because there's a magic "i" button that shows picture properties on the right after clicking on it. 

Probably new users can struggle with the same problem.

## Possible Solution
Showing the "i" icon after hovering the mouse over any part of the picture rather than on the top right corner will make access to the picture details more obvious.

**Comment by SvenAlHamad** [comment]
Fully agree. I need to check why the icon isn't showing on the image hover. I believe that was the original behaviour.  
Thanks for reporting, we'll sort it out.

**Comment by Ashu96** [comment]
Is anyone working on this issue? If not I would love to contribute

**Comment by Pavel910** [comment]
@Ashu96 sure, go ahead! I'll assign you to this issue :)
