### ISSUE TITLE
Page Builder - "Icon" page element not working

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#761]
## This is:

- Bug

## Specifications

  - version:
  - OS: MacOS
  - Browser: Version 80.0.3987.132 (Official Build) (64-bit)

## Expected Behavior
I should be able to add the `Icon` page element to my page.

## Actual Behavior
An error occurs.

![image](https://user-images.githubusercontent.com/5121148/76825577-a41ca300-681a-11ea-8059-0e9d9daaaa2b.png)

## Steps to Reproduce the Problem
1. Create a new page.
2. Add a new empty block.
3. Insert an `Icon` element into it.

![ezgif-6-4ae2579c012a](https://user-images.githubusercontent.com/5121148/76825592-af6fce80-681a-11ea-9c7e-dd57b0e1e073.gif)

**Comment by Ashu96** [comment]
Hey @doitadrian 
I would love to help with this bug fix :smile:

**Comment by Pavel910** [comment]
@Ashu96 Great, have fun :D
