### ISSUE TITLE
yarn install failed. Cypress installation error !

### ISSUE THREAD

**Issue by Joel-Raju** [webiny/webiny-js#763]
Did a clone and yarn install. Installation throws an error

`The Cypress App could not be downloaded.`

I'm not using a proxy.

## This is:
- Bug

## Specifications

  - version:
  - OS: Mac OS 10.15.3 (19D76)
  - Browser: Firefox 74.0 (64-bit)
 -  Node: v12.14.1
 -  Yarn: 1.21.1

## Expected Behavior
Installation should be successful

## Actual Behavior
Installation throws an error

## Steps to Reproduce the Problem

1. `git clone`
2. `yarn`

## Detailed Description
```bash
Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/4.2.0?platform=darwin&arch=x64
Error: Corrupted download

Expected downloaded file to have checksum: 66ae5ac2fb9e10f0d055928a12cb3fb1a25493a4d39699f0c638e9c2f1f9b02d2c5eb24a8ed0555ac9bb31512ea65d45cddf7a728c26807a97698e20fb23ab53
Computed checksum: d8c0f1c1eb5389ebd0b8e9b002a269ea14c3bda79a0487f3397aaeeab86935ed928d25a3a9614461ba8db144887caa7a2abaa1237c55d917b90926be39aa12ad

Expected downloaded file to have size: 172922629
Computed size: 172922629

----------

Platform: darwin (19.3.0)
Cypress Version: 4.2.0
The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/4.2.0?platform=darwin&arch=x64
Error: Corrupted download

Expected downloaded file to have checksum: 66ae5ac2fb9e10f0d055928a12cb3fb1a25493a4d39699f0c638e9c2f1f9b02d2c5eb24a8ed0555ac9bb31512ea65d45cddf7a728c26807a97698e20fb23ab53
Computed checksum: d8c0f1c1eb5389ebd0b8e9b002a269ea14c3bda79a0487f3397aaeeab86935ed928d25a3a9614461ba8db144887caa7a2abaa1237c55d917b90926be39aa12ad

Expected downloaded file to have size: 172922629
Computed size: 172922629

----------

```

**Comment by Pavel910** [comment]
@Joel-Raju had this same error the other day in my fork, a re-run fixed it for me. I think it was a network connection issue on my side. Could you try running `yarn` again? This doesn't really have anything to do with Webiny itself.

**Comment by Joel-Raju** [comment]
I tried re-running it a couple of times, but still it fails. Opening an issue in Cypress repo https://github.com/cypress-io/cypress/issues/6789

**Comment by Pavel910** [comment]
I just tried your fork, `yarn` completes successfully, all dependencies installed normally.
I'm using Windows 10, node `v10.14.0`. Also tried using `v12.14.1` - everything works as expected.

Very weird 🤔

**Comment by Pavel910** [comment]
@Joel-Raju I'm closing this issue for now as it is not related to Webiny. Once you manage to install the repo, please let us know what was the issue with Cypress, so we can help other community members who might get that error.

Thanks!

**Comment by Joel-Raju** [comment]
@Pavel910 Okay. I'll keep you posted.

Thanks.

**Comment by drexlar5** [comment]
@Joel-Raju I changed my cypress version to 4.2.0 in my package.json file and retried the installation. That solved the issue.
