### ISSUE TITLE
The Error snackbar from Account settings is not closeable

### ISSUE THREAD

**Issue by Fsalker** [webiny/webiny-js#766]
## This is:
- Bug

## Specifications
  - OS: Windows 10
  - Browser: Chrome

## Expected Behavior
When clicking the `Close` button, the `Snackbar` element should vanish. Also, the `Close` message is currently black on a dark gray background (see the screenshot below), which makes it nearly invisible and is thus very difficult to use: its text color should be more user friendly. 🙂

## Actual Behavior
Clicking on the `Close` button does nothing.

## Steps to Reproduce the Problem
1. Run the `admin` app (this may be the `examples/apps/admin` app) and navigate to the Account's settings which you may also find at URL route `/admin/account`.
2. Edit `packages/app-security/src/admin/views/Account.tsx`'s `onSubmit` handler by making an error appear. Your code should transform from:
`const { error } = response.security.updateCurrentUser;`
into, for example:
`const { error } = { message: "This is an arbitrary error" }`
3. Click on `Update Account`. You should see the snackbar show up exactly like in the screenshot below.

## Additional info
You may see a list of `Tokens` in my screenshot. That's a new feature which I am currently working on - don't worry if you don't see it in the app yet. 🍻

![image](https://user-images.githubusercontent.com/16700631/77253600-f4a15f80-6c63-11ea-80f3-02c01691d95d.png)

**Comment by afzalsayed96** [comment]
Not only in case of error but also for success. Shouldn't both scenarios have a close button?

![Screen Shot 2020-06-15 at 8 39 06 PM](https://user-images.githubusercontent.com/14029371/84674791-0a63af80-af49-11ea-8ede-d2daafa25e5e.png)

**Comment by Pavel910** [comment]
@afzalsayed96 success messages disappear automatically, but error messages don't , thus the close button.

**Comment by afzalsayed96** [comment]
Hey @Pavel910 - I'm able to see that the error message disappears on it's own as well following your steps to reproduce. Has something changed recently?

**Comment by Pavel910** [comment]
I don't think so, this needs some debugging and styling. That `Close` button should be visible, there's definitely something wrong going on.
