### ISSUE TITLE
Admin - handle non-existing routes

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#768]
## This is:

- Bug

## Detailed Description
If a user opens a non-existing route in the Admin app, a blank page is shown.

![image](https://user-images.githubusercontent.com/5121148/77301988-e2213780-6cf0-11ea-9305-0e587cdc5b93.png)

## Possible solution
Let's create a simple "Not found" page.

An example that shows how a default route is registered can be found [here](https://github.com/webiny/webiny-js/blob/master/packages/app-page-builder/src/site/plugins/index.tsx#L14). So basically, it's a route that doesn't have the `path` prop defined.

At this moment, I believe this route could be part of the `@webiny/app-admin` plugins. If so, it should be added here `packages/app-admin/src/plugins/index.ts`.

**Comment by amitsin6h** [comment]
I would like to work on this

**Comment by Pavel910** [comment]
@amitsin6h Awesome! Let us know if you need help with the setup. Please consult the [CONTRIBUTING](https://github.com/webiny/webiny-js/blob/master/CONTRIBUTING.md) guide to help you get started.

We're also on https://gitter.im/Webiny/webiny-js if you need help.

**Comment by Anshuman71** [comment]
@doitadrian I followed your proposed solution steps and I added the plugin for `no-matching-route` but it is getting rendered on every route as I have not given a path prop. In `<Swtich />` it takes the last route if no other route matches, I'm not sure how that works in webiny-js.
Can you please help me?

**Comment by Pavel910** [comment]
Hi @Anshuman71, just tried this in our repo, this seems to work just fine:

```tsx
// apps/admin/App.tsx

import adminTemplate from "@webiny/app-template-admin-full";
import "./App.scss";
import { Route } from "@webiny/react-router";
import React from "react";

export default adminTemplate({
    cognito: {
        region: process.env.REACT_APP_USER_POOL_REGION,
        userPoolId: process.env.REACT_APP_USER_POOL_ID,
        userPoolWebClientId: process.env.REACT_APP_USER_POOL_WEB_CLIENT_ID
    },
    plugins: [
        {
            type: "route",
            name: "not-found-route",
            route: <Route render={() => <div>Route not found!</div>} />
        }
    ]
});
```

So, to make this work on a more global level, and not only in your app, I would add the following route:

```tsx
<Route render={() => <Redirect to={opts.defaultRoute || "/"} />} />
```

At this here reference: `packages/app-template-admin/src/index.tsx:64` so that it looks like this:

![image](https://user-images.githubusercontent.com/3920893/85049632-37a49d80-b195-11ea-9fa9-77961fe0c123.png)

Let me know if you need more help!

**Comment by Anshuman71** [comment]
@Pavel910 thanks a lot. Let me try to follow these steps
