### ISSUE TITLE
Jump to a specific location on the same page using Webiny menu

### ISSUE THREAD

**Issue by bigb123** [webiny/webiny-js#771]
## This is:
- Feature request

## Detailed Description
Some businesses require just a simple website with one, long, scrollable landing page. It will be very useful to present to the user all page's sections with Webiny menu and let him jump directly to a specific part of the page.

Example (comes from https://barluca.com.au/)
![example copy](https://user-images.githubusercontent.com/9221943/77466248-911e5a00-6e3c-11ea-871d-de55bb39231a.gif)

**Comment by amitsin6h** [comment]
Oh, this is interesting targeting `id` in `href` will do it. I would like to add this feature

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
