### ISSUE TITLE
Clicking outside of the white account button does nothing

### ISSUE THREAD

**Issue by Fsalker** [webiny/webiny-js#773]
A very similar bug to #737 happens with the Account button in `admin` app when clicking outside of the button (see the blue arrow in the screenshot below). A `pointer` cursor is shown & the button's glowing animation is played regardless, as if it was functioning.

![image](https://user-images.githubusercontent.com/16700631/77560212-d470db00-6ec5-11ea-8b66-ed6a87c352ee.png)

## This is:

- Bug

## Specifications
  - OS: Windows 10
  - Browser: Chrome

## Expected Behavior
The account popup should appear.

![image](https://user-images.githubusercontent.com/16700631/77559191-8a3b2a00-6ec4-11ea-9500-ac54cf358356.png)

## Actual Behavior
Literally nothing happens.

## Steps to Reproduce the Problem
1. Run the `admin` app
2. Click inside the div's square, but outside the white circle (as marked in the screenshot)

## Possible Solution
Check the displayed `UserImage` element in `packages/app-security/src/admin/plugins/UserMenu/UserImage.tsx`.

It's loaded as a plugin in `packages/app-admin/src/plugins/UserMenu/UserMenu.tsx:21`.

You may inspect its parent elements and see exactly why the button's malfunctioning. Either make clicking outside of work as intended or remove the possibility of doing so altogether by suppressing the visual effects (the pointer cursor, the button's animation, ...)

**Comment by b0nbon1** [comment]
I'd love to contribute this one as my first issue

**Comment by Pavel910** [comment]
Great! Let us know if you need any help along the way 🚀
