### ISSUE TITLE
Allow use sls offline plugin

### ISSUE THREAD

**Issue by gbitdev** [webiny/webiny-js#782]
It will good to allow to use severless offline plugin to fully offline development.

## This is: Feature request

**Comment by Pavel910** [comment]
@gbitdev this won't be possible as we're not using Serverless Framework itself, but their Serverless Components. 

The best thing you can do at this point to develop completely offline is to use test driven development, and white tests for your plugins. With our upcoming release we will greatly improve testability and provide some tools to easily construct tests (we use those same tools to develop ourselves). 

Cheers!
