### ISSUE TITLE
Support for DynamoDB - data restructuring - Headless CMS search table

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#785]
## This is:
- Idea
- Discussion

## Introduction
As mentioned in the initial issue, ideally, we would like to have all base Webiny apps multi-database compatible.

In a couple of discussions, we figured this might not be quite possible for the Headless CMS app. More specifically, it seems that the way data-filtering-purposed collections are currently designed won't fit into the DynamoDB model, and as an alternative, the idea was to just provide a separate package for the Headless CMS app (e.g. `@webiny/api-headless-cms-dynamodb`).

I'd say this option is definitely on the table, but still, I wanted to check if we could come up with a different data model, with which additional packages wouldn't be needed (because more code = more maintenance).

In the following text, two ideas will be presented. The first one can be discarded, but still, I decided to include it here, just to have a better understanding of how the second one came to existence.

> In this issue, note that when we say "search", we actually mean "filter". We're not referring to textual searches here at all! Text searching will get covered in another issue.

#### Locales
This is a simplified table of locales, which we need in the Search table. Nothing change here.

| ID  | code  |
| --- | :---: |
| L1  | en-GB |
| L2  | de-DE |

#### Search Table
The revised Search table looks like this:

| ID  | contentModel | ref | locale | v1           | v2          | v3                                   | v4     |
| --- | ------------ | --- | ------ | ------------ | ----------- | ------------------------------------ | ------ |
| A   | product      | R1  | L1     | Chair        | home        | A chair for everybody.               | 105    |
| B   | product      | R1  | L2     | Stuhl        | zuhause     | Ein Stuhl für alle.                  | 100    |
| C   | product      | R2  | L1     | Desk         | home        | Very nice desk.                      | 500    |
| D   | product      | R2  | L2     | Schreibtisch | zuhause     | Sehr schöner Schreibtisch.           | 400    |
| E   | product      | R3  | L1     | TV           | electronics | Have fun with this new TV            | 1500   |
| F   | product      | R3  | L2     | Fernseher    | elektronik  | Viel Spaß mit diesem neuen Fernseher | 1333   |
| G   | vehicle      | R4  | L1     | VW           | Golf        | Very cool car.                       | 10,000 |
| H   | vehicle      | R4  | L2     | VW           | Golf        | Sehr cooles Auto.                    | 9,000  |

> R1...R4 are references to actual database entries in the main `CmsContent` table - the one which holds all inserted content by users.

> In a real database, we wouldn't need the `ID` column. I added it here just for discussion / reference purposes.

#### Abstracted column names
A couple of differences from the current data model we have. The main one is that we no longer need multiple tables (one table per content-model). Everything would be stored in a single table. 

In order to do that, we had to abstract column names to v1, v2, v3, ..., vn ("v" stands for "value"). And since we are dealing with abstract column names, that means we'd need to have a map that would give us the information on what value is represented by each column. For example:

| ID  | content-model | v1    | v2       | v3          | v4          |
| --- | ------------- | ----- | -------- | ----------- | ----------- |
| a   | product       | title | category | price       | description |
| b   | vehicle       | brand | model    | description | price       |

> Again, no need for the ID field.

So, if a user was querying `give me "product" where category equals "shoes"`, internally we would do a filter `content-model = "product" & v2 = "shoes"`. So, with the provided map, we would know that the `category` column is actually `v2`.

Note that for other content models, `v2` can mean anything, so e.g. for `vehicle` content model, `v2` is mapped to `model` (model of the actual vehicle).

#### Indexes
When we start to examine indexes, we start to see why this whole approach won't work.

For the PK, we would use the following combination of fields: `contentModel + ref + locale`. No problem there.

The problem occurs when we start defining other indexes. Yes, the user might do a search based on the `v1` column and in that case, we might use the `contentModel + locale + v1` index, but what happens if we wanted to do a search with `v1` and `v2`, or with `v2` and `v3`?

Then we run into troubles and it turns out that if we'd make indexes for every combination of these values, we would be super inefficient. Not only we'd have a huge amount of indexes which of course will become expensive, but some of these indexes most probably won't even be accessed, because some of the searches performed by actual users won't even them. Thus, we're wasting resources here.

##### Three indexed values

|  #  | v1  | v2  | v3  |
| :-: | :-: | :-: | :-: |
|  1  |  ∙  |     |     |
|  2  |     |  ∙  |     |
|  3  |     |     |  ∙  |
|  4  |  ∙  |  ∙  |     |
|  5  |  ∙  |     |  ∙  |
|  6  |     |  ∙  |  ∙  |
|  7  |  ∙  |  ∙  |  ∙  |

(prepend `contentModel` and `locale` to every row)

##### Four indexed values

To have full-index coverage for just four columns, we'd have to create 15 indexes. 🤪

|  #  | v1  | v2  | v3  | v4  |
| :-: | :-: | :-: | :-: | :-: |
|  1  |  ∙  |     |     |     |
|  2  |     |  ∙  |     |     |
|  3  |     |     |  ∙  |     |
|  4  |     |     |     |  ∙  |
|  5  |  ∙  |  ∙  |     |     |
|  6  |  ∙  |     |  ∙  |     |
|  7  |  ∙  |     |     |  ∙  |
|  8  |     |  ∙  |  ∙  |     |
|  9  |     |  ∙  |     |  ∙  |
| 10  |     |     |  ∙  |  ∙  |
| 11  |  ∙  |  ∙  |  ∙  |     |
| 12  |  ∙  |  ∙  |     |  ∙  |
| 13  |  ∙  |     |  ∙  |  ∙  |
| 14  |     |  ∙  |  ∙  |  ∙  |
| 15  |  ∙  |  ∙  |  ∙  |  ∙  |

(prepend `contentModel` and `locale` to every row)

#### Conclusion

1. A lot of indexes, probably not efficient to put all of the indexes since not all of them will be utilized. DynamoDB is made for predictive access patterns, and not for this all-over-the-place querying.

2. If we want to have this all-over-the-place querying automatically supported, DynamoDB is not the right tool for the job. Users will need to specify searches that are about to happen (should be changeable along the way).

## 2. The proposed idea

As mentioned, the main problem with the previous approach is that we would have to create a lot of indexes which would get inefficient very soon.

After thinking about it, I realized that we just won't be able to do it like that, and that instead of trying to cover all possible search patterns, we are going to need to ask the user (in the Headless CMS App) which searching / sorting he wants to have enabled. In terms of the UX, I realize that this is another thing user will have to think about, but I believe when we analyze the pros and the cons, and if we work hard on the UX for that, we might be able to pull it off. 

And also, note that creating indexes in advance presents an issue for any database, not only for the DynamoDB.

##### Search table
This is the proposed structure of the Search table.

| ID  | environment | contentModel | ref | locale | fields         | v1          | v2  |
| --- | ----------- | ------------ | --- | ------ | -------------- | ----------- | --- |
| A   | prod        | product      | R1  | L1     | price          | 110         | -   |
| B   | prod        | product      | R1  | L2     | price          | 100         | -   |
| C   | prod        | product      | R2  | L1     | price          | 233         | -   |
| D   | prod        | product      | R2  | L2     | price          | 213         | -   |
| E   | prod        | product      | R1  | L1     | category,price | electronics | 110 |
| F   | prod        | product      | R1  | L2     | category,price | elektronik  | 100 |
| G   | prod        | vehicle      | R2  | L1     | category,price | home        | 233 |
| H   | prod        | vehicle      | R2  | L2     | category,price | zuhause     | 213 |

Subtle but significant differences there.

Basically, while the user is working on his content model, he would also be able to choose which searching / sorting he wants to enable.

He might want to enable searching by `price`, `category`, and `category + price`.

Once he does that, we take the existing data and copy it into the Search table, but with the above structure.

The `fields` columns would contain the combination of the field, and the v1, v2, v3, ..., vn would contain the values for these fields.

So, if a user is searching by price,  the `fields = "price"` rows would be utilized. If user is searching by category and price, then the `fields = "category,price"` rows would be utilized. Note that the `fields` column doesn't just give us the combination of fields, but also tells us what are the v1, v2, v3, ..., vn values actually representing. So, for the `category,price` value of the `fields` column, we know that the `v1` is representing `category`, and that the `v2` is representing `price`.

So basically, we are creating our own indexes in a way. This means that every time a user adds the combination of a new field, data will have to get copied. And of course, on changes of the actual content, the indexes will have to be updated. But when you think about it, it's not actually very different from what a database is actually doing when an index is created. 

##### Indexes

Primary key looks good: `contentModel + ref + locale`

And I'd say secondary indexes look good as well:

`contentModel + locale + fields | + v1`
`contentModel + locale + fields | + v1 + v2`
`contentModel + locale + fields | + v1 + v2 + v3`
`contentModel + locale + fields | + v1 + v2 + v3 + v4`
`contentModel + locale + fields | + v1 + v2 + v3 + v4 + v5`
(... continue for example to v10 if neeeded ...)

So basically, we need as many indexes, as many field combinations we have. If the user, for a specific content model, selected a combination of five fields, then we'd need five indexes. But that's it, for any other 5-field-combination, the same index would be utilized (that we created when the user for the first time used a five-field combination).

In terms of indexes count, I'd say this is more efficient than the previous idea.

##### Conclusion

With this approach, the main benefit is that we don't have to create a bunch of indexes in advance but we create them on-demand. And that is basically the main takeaway of this issue - we shouldn't try to magically support any search, but let the user define what's possible. Again, it's gonna create a UX friction we'll need to address, but I think with the right attention, it should be fine.

## Final words
The question that occurs to me here, would it be just better to allow the app to create real indexes on the database, instead of us creating these improvised indexes? 

If not, then this approach would be OK I believe. But note that in that case, we'll have to do all of the heavy lifting (copying / managing the data), instead of leaving it to the database.

Anyways, let's s see if any of these approaches make any sense. It's possible that I'm missing something (on any front - database, architecture, UX, you name it), so yeah, if so, please share your thoughts. 

Let's see if this whole attempt of "trying to avoid making a separate package for the Headless CMS / DynamoDB" was in vain. ;)

**Comment by doitadrian** [comment]
I created a separate issue, which explains the idea for a new data structure for the Headless CMS Search table, which would possibly enable us to avoid making a separate package for the Headless CMS app, when used with the DynamoDB database. This was discussed the other day on Slack.

Please read it when you get a chance and let me know your thoughts.

@Pavel910 @SvenAlHamad @ostappartyka @jfgrissom

**Comment by Pavel910** [comment]
Since you and I discussed this in details, I think this is a good way to support all databases. It's a different approach from what we used to have through the years, but it's an interesting one.

The major benefit of this approach is that we don't need to have 2 tables per content model. We can store all the data in 1 data table + 1 search table for the entire CMS (this would work with SQL, Mongo, Dynamo).

**Comment by kisg** [comment]
If you store every content in a single table like you propose, then you essentially loose the option to use a strongly typed database (like SQL), or you need to store every value in a generic "binary blob" or "string" field. Am I missing something?

Also, these tables will grow in size pretty quickly, because they store everything in one place.

I am also not sure why the separate search table is better then having a content-model table for each type, and then defining composite indices based on the same information that you are encoding it in the search table:

- CREATE INDEX xx1 ON content-model (locale, field1)
- CREATE INDEX xx2 ON content-model (locale, field1, field2)
- CREATE INDEX xx3 ON content-model (locale, field1, field2, field3)

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
