### ISSUE TITLE
Storybook Dialogs are outdated

### ISSUE THREAD

**Issue by Fsalker** [webiny/webiny-js#786]
So, one day I decided to use Webiny Dialogs in order to make an awesome UI for Access Tokens. I immediately copy-pasted the example from [our Storybook](https://storybook.webiny.com/?path=/story/components-dialog--usage).

But to my dismay, I was unable to use Dialogs because the imports could not be resolved. For example, **DialogHeaderTitle** doesn't exist in @webiny/ui/Dialog.

I then inspected [the source code](https://github.com/webiny/webiny-js/blob/master/packages/ui/src/Dialog/Dialog.stories.tsx#L44) and realised that the docs were outdated... 😫

![image](https://user-images.githubusercontent.com/16700631/78895517-ad92d700-7a77-11ea-93f0-6e9537c87ce5.png)

**Note**: This might not be the only outdated component. Someone has to go through and check all of them. 😄

## This is:
- Bug

## Specifications
  - OS: Windows 10
  - Browser: Chrome

## Expected Behavior
We should see the correct components in the docs. Check the [source code](https://github.com/webiny/webiny-js/blob/master/packages/ui/src/Dialog/Dialog.stories.tsx#L43).

## Actual Behavior
We see the unexisting components such as **DialogHeaderTitle** in the **Code** [Storybook section](https://storybook.webiny.com/?path=/story/components-dialog--usage).

## Steps to Reproduce the Problem
Try importing the currently shown example (which includes the **DialogHeaderTitle** component), you'll immediately get an error.

## Possible Solution
@Pavel910 Perhaps all it takes to solve this issue is redeploying Storybook 😎

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
