### ISSUE TITLE
Page Builder: saved page elements not visible in the elements menu

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#787]
## This is:

- Bug

## Expected Behavior
When we save a custom page element in Page Builder editor, the element should be visible in the page-elements menu on the left side of the screen.

![ezgif-2-7b621d46430d](https://user-images.githubusercontent.com/5121148/78898746-99010f80-7a74-11ea-8c09-3a2f378fb1ea.gif)

## Actual Behavior
It's not visible.

![image](https://user-images.githubusercontent.com/5121148/78898229-bf727b00-7a73-11ea-9fed-a4d10f7a230f.png)

## Detailed Description
The problem lies here [`packages/app-page-builder/src/admin/utils/createElementPlugin.tsx:8`](https://github.com/webiny/webiny-js/blob/master/packages/app-page-builder/src/admin/utils/createElementPlugin.tsx)

The plugin type "pb-page-element" is incorrect.

## Possible Solution
The actual plugin type is "pb-editor-page-element", so we'll need to correct it.

**Comment by Jeremytijal** [comment]
I tried your solution and it's working. 
![Capture d’écran 2020-04-10 à 14 51 09](https://user-images.githubusercontent.com/40340340/78992207-09726400-7b3b-11ea-9be8-a0fb46d74c43.png)

**Comment by doitadrian** [comment]
Hey that's awesome @Jeremytijal.

Would you be so kind as to submit a PR, please?

🍻🍻🍻
