### ISSUE TITLE
S3 Bucket Names for webiny-serverless-page-builder-XXXXXX is not unique preventing multi-account deployments.

### ISSUE THREAD

**Issue by cbabione** [webiny/webiny-js#791]
## This is:
Question (perhaps bug)

Hello, and awesome work so far!  I have been looking for a serverless solution like Webiny for a while now -- Glad I have found it!

I have a multi-account AWS environment using control tower, with development and production environments in different accounts.  I was able to use the documented variables to assign AWS profiles correctly, change database endpoint, and set S3 bucket names for the webiny-files bucket.  But I do not see a variable to set the webiny-serverless-page-builder bucket per environment.  This causes an error when deploying to my production account because the computed bucket name for webiny-serverless-page-builder is the same from my dev environment and breaks the webiny deployment process.

What is the best practice for a multi-account strategy?  Is there a way to set the webiny-serverless-page-builder bucket name in environment settings with the other variables?

Please advise on options I may have to get around this delima as it is really my only blocker right now.  I am sure I could hack a solution together, but would rather take guidance to ensure I future proof the solution.  If you don't have a solution, let me know and I will see what I may be able to do to get around this and share back to the community.

Thank You,
Chris

**Comment by Pavel910** [comment]
Hi @cbabione, thanks for opening this issue. We discovered this bug ourselves several days ago, and in our upcoming release we'll improve the resource naming of all resources (including that page builder bucket).

However, your use case is something we haven't thought about: using 2 different accounts, for different environments. Glad you reported this.

A couple of quick and dirty fixes, before I release a fix for the component that's deploying page builder:
1) you can go to your S3 and attach a policy to the bucket which would give your other account access to it.
2) you can edit this in your node_modules (I know it sucks, but just as a temporary bypass):
`node_modules/@webiny/serverless-page-builder/serverless.js:17` make this look like:

```js
const s3Output = await s3Component({
    name: `webiny-serverless-page-builder-${env}-${this.context.instance.id}`,
    region
});
```

Sorry for the inconvenience, I'll fix this and let you know when it's available on `npm`.

Cheers!

**Comment by cbabione** [comment]
I was actually looking in the serverless.js to do just what you suggested, but wanted your take on it before I did as there might have been something better you had in mind.  Thanks for the prompt response, and if you need help testing in multi account environments in the future, let me know as I would be happy to assist.

**Comment by Pavel910** [comment]
Using multiple accounts to deploy the same project causes this bug, because each project has its unique ID, which is used in resource names. So, if you try deploying the same project with 2 accounts, the unique ID stays the same, and you get that `bucket name is not unique` error, which makes perfect sense.

So there are 2 ways to solve this: either include an `env` value in the resource name, or make that unique ID be per-environment, so each environment gets its own unique ID. Not sure what's the best way to go.

One way or another, if you mess with multiple AWS accounts, you will get into a situation where you hit this error no matter how hard we try to avoid it, so I think we'll just go with this `env` fix, and document this for future users who deploy with multiple accounts, just so they are aware of the problem.

**Comment by Pavel910** [comment]
@doitadrian I'm trying to look at this issue from a different perspective: would it be possible to avoid creating this S3 bucket for page-builder installation files completely, and let the PB use the original `files` bucket as a storage for that ZIP file? 

I'm looking at the code and I think this would totally work. What do you think?

**Comment by doitadrian** [comment]
This looks doable @Pavel910 and I'll see that we implement this now, since we're already working on the `acceleration` fix.

**Comment by Pavel910** [comment]
This is long resolved! :) Closing.
