### ISSUE TITLE
Save Element Fails in Firefox

### ISSUE THREAD

**Issue by mdm373** [webiny/webiny-js#801]
## This is:
- Bug

## Specifications

  - version: 3.2.8
  - OS: macOS Catalina 10.15.3
  - Browser: Firefox 75

## Expected Behavior
- Page builder opened, Page Edited, Element Save Selected
- Selecting Save from Save Element Modal
- Should save the element (also, the image preview does not appear in the modal)

## Actual Behavior
Clicking save, nothing happens in UI.

## Steps to Reproduce the Problem
Use Firefox, I can confirm this error is not happening in chrome after installing chrome.

## Detailed Description
console error appears multiple times

- `uncaught exception: Object`

no network traffic errors

## Possible Solution
🤷

**Comment by Pavel910** [comment]
Thanks for reporting @mdm373! It's great that you narrowed it down to Firefox, we'll see what's going on there :) 🍻

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
