### ISSUE TITLE
How to create a Page Builder theme?

### ISSUE THREAD

**Issue by leandrofinger** [webiny/webiny-js#806]
I'm trying to create a page builder theme to set a default style for the whole project. I've read the docs and I've tried to base it on app-page-builder-theme but I was not able to extract it from the monorepo and create my own repo. Is there a sample theme repo?

## This is:
- Question

**Comment by doitadrian** [comment]
Hi @leandrofinger, 

you can find the complete source code of the theme [here](https://github.com/webiny/webiny-js/tree/master/packages/app-page-builder-theme/src), from where you should be able to copy it into your project.

I know it's not ideal, but try it, and we'll see how we can optimize this.

@Pavel910 This could be a good addition to the CLI/scaffolding feature?

**Comment by Pavel910** [comment]
@doitadrian yeah sure, let's get back to this after the upcoming release, and we can start working on improving DX on this front :)

**Comment by leandrofinger** [comment]
@doitadrian I've followed your suggestion copying the theme as a plugin, but it seems to ignore the scss file changes. I've added `import './styles.scss';` to theme index.js file. Is there something else?

**Comment by doitadrian** [comment]
Could you maybe me give me a ping via [gitter](https://gitter.im/Webiny/webiny-js) so maybe you could share some sshots / code?

Thanks!

**Comment by doitadrian** [comment]
Resolved.

The user did import his own `styles.scss` correctly, but the original import `@import "~@webiny/app-form-builder-theme/styles.scss";` (from the `apps/site/src/App.scss`) was still there. Once we removed that one, everything worked.
