### ISSUE TITLE
Project creation failed

### ISSUE THREAD

**Issue by fengzaiku** [webiny/webiny-js#807]
## Specifications

  - version:
node v12.10.0
npm 6.10.3
yarn 1.22.4
nvm 1.1.7

  - OS:
win10
  - Browser:

## Steps to Reproduce the Problem
1.npm -g install @webiny/cli
2.webiny create my-project

## Detailed Description

F:\factor-example\webiny>webiny create my-project

Webiny collects anonymous usage analytics to help improve the developer experience.
If you'd like to opt-out run webiny disable-tracking.
To learn more, check out https://www.webiny.com/telemetry/.

📦 Creating a new Webiny project in F:\factor-example\webiny\my-project...
√ Finished loading package versions
/ Installing dependencies...(node:13612) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1 (Unknown system error -1): yarn
    at makeError (D:\Program\nvm\v12.10.0\node_global\node_modules\@webiny\cli\node_modules\execa\lib\error.js:59:11)
    at handlePromise (D:\Program\nvm\v12.10.0\node_global\node_modules\@webiny\cli\node_modules\execa\index.js:112:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:13612) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13612) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Pavel910** [comment]
Hi @fengzaiku, is there anything in yarn log file in the `my-project` folder?

**Comment by fengzaiku** [comment]
my-project
    ├─api
    │  └─.serverless
    └─apps
        ├─.serverless
        ├─admin
        │  ├─handler
        │  ├─public
        │  │  └─favicons
        │  └─src
        │      ├─config
        │      └─plugins
        └─site
            ├─handler
            ├─public
            ├─src
            │  ├─config
            │  └─plugins
            └─ssr
This is the currently generated directory

**Comment by fengzaiku** [comment]
> Hi @fengzaiku, is there anything in yarn log file in the `my-project` folder?
my-project
├─api
│ └─.serverless
└─apps
├─.serverless
├─admin
│ ├─handler
│ ├─public
│ │ └─favicons
│ └─src
│ ├─config
│ └─plugins
└─site
├─handler
├─public
├─src
│ ├─config
│ └─plugins
└─ssr
This is the currently generated directory

**Comment by Pavel910** [comment]
Unfortunately it's such a vague error, I can't really tell you anything useful :( The best we can do is wait for our next release; we're creating a new tool to bootstrap the project without global installations, and hopefully it will make it work for you. 

I know it's not ideal, but there isn't much I can do without a proper error log, sorry.

**Comment by fengzaiku** [comment]
I looked at the yarn log log file, but its contents were empty

**Comment by fengzaiku** [comment]
I delete "@webiny/api-plugin-security-cognito": "latest" in pakage.json under the directory global template.Then, it was installed successfully.Finally I need to install it separately

**Comment by Pavel910** [comment]
@fengzaiku if you had `"@webiny/api-plugin-security-cognito": "latest"` it means the project creation was broken in the first place. Those `latest` version numbers are replaced with actual version of the packages on `npm` at the time of project creation.

I would recommend you to create a blank project from scratch as broken project setup can cause more problems down the line. 

Let me know if you need more help :)

**Comment by fengzaiku** [comment]
First of all, thanks for the answer. I built it with "@webiny/api-plugin-security-cognito": "^3.0.2"
