### ISSUE TITLE
Headless CMS - Indexes

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#813]
With this feature, users will be able to select indexes for a content model, which will enable them to sort and filter data in a way they need it.

- [x] Create "Indexes" tab in the CM Editor

We decided indexes will be defined in a third tab, here:
![image](https://user-images.githubusercontent.com/5121148/80870336-0c79f380-8ca6-11ea-982f-13080b839a74.png)

This should list all existing indexes, allow the user to remove them, and of course, allow them to add new ones.

- [x] Create GraphQL mutations to support the above UI

- [ ] Create a background process that will actually generate / remove the indexed data (for v1, it doesn't have to be async, we can optimize this post-release)

- [x] Finally, regarding the API side, we need to ensure that GraphQL schema is changed once a user applies indexes. In other words, if a new "price" index was added, users must be able to filter and sort entries by "price" via GraphQL queries.

- [x] TBD - since the changes need to be published first, should these indexes be created on that event, and not immediatelly? 

![image](https://user-images.githubusercontent.com/5121148/80871367-739aa680-8cac-11ea-85c8-3532bc7adeb5.png)

- [x] These need be removed:

![image](https://user-images.githubusercontent.com/5121148/80871548-8d88b900-8cad-11ea-8b72-483c9360d809.png)

- [ ] Continuing from the previous task, we need "searchable" and "sortable" flags to be removed on the API side as well.

**Comment by doitadrian** [comment]
This is the very beginning of the indexes UI. I'm sure there are things to adjust. I really did a raw version here, just so we can start discussing the UI ASAP.

## A) Indexes list

![image](https://user-images.githubusercontent.com/5121148/81726810-41e1c680-9488-11ea-87b6-693b7f1cb612.png)

1. Here we have a simple list of indexes. The only action that we offer here is the delete button. Why is that? Why no edit button? 

I wouldn't allow editing indexes, just create and delete. The sole reason is the amount of data (on big systems) that is being processed in the background. Not sure, what are your thoughts?

P.S. Just figured that we can allow editing, but if a user does a change, we change the status (read point number 2 for details on statuses) to "pending", and until it gets back to "active", we don't allow changes.

2. You can also notice that I added a status label (active, pending). I'll see if it's not too complicated to implement this way of handling indexes creation (async). If it's too much time, I'll just remove it and implement a more simple approach (like we discussed on one of our previous calls).

## B) Create index dialog
![image](https://user-images.githubusercontent.com/5121148/81726433-a0f30b80-9487-11ea-8237-37449d148408.png)

1. Okay, so here I was thinking we do a list of fields, with simple checkboxes. I divided them in two columns, just for cases where a content model has many fields. 

Should we try a simple list maybe?

2. Since indexes creation is a heavy operation, I would maybe make this dialog a two step wizard. Nothing complicated, instead of the `+ CREATE`, I would just put `NEXT` button or something like that, which one clicked, a summary screen (step) would be shown with all of the details, and a warning message that indexes creation may take some time. Things like that, just to super-alert the user what's about to happen.

What do you think?

@webiny/webinydevteam @SvenAlHamad

**Comment by Pavel910** [comment]
@doitadrian the UI looks very clean to me, if we can get away with these checkboxes, I would try that. Alternatively, we could have a simple list with <Switch/> component.

Regarding index actions, I would NOT have the `edit` action. Simply having `create` + `delete` is much more straightforward.

The `active/pending` label, I don't really understand how you will track the index creation, and if you plan to store flags in the database - I wouldn't bother. For this release let's just do a simple message telling the user that it may take a few moments before indexes are generated.

**Comment by doitadrian** [comment]
Adding field types for checkbox labels = 👍 

Regarding the rest... OK, let's go without active/pending.

What do you guys think about the confirmation/summary screen (the one shown after the user preses NEXT in the dialog)?

I mean, I wanted to create another confirmation dialog after submitting the first, but that would then mean we'd have two dialogs. The main one, and the confirmation one, which is shown after the main one is closed.

That's why I thought putting NEXT button and showing the summary/confirmation in the same dialog might be a better idea. To avoid multiple dialogs and opening/closing them. Not only it's tricky in code, but a wierd UX if you ask me.

**Comment by Pavel910** [comment]
@doitadrian do we need the confirmation dialog at all? I guess it depends on `when` the index creation is initiated. Is it on `content model publish`, or `confirmation dialog submit`, or `content model save` ?

If it's not on `confirmation dialog submit`, then I don't think it's necessary.

**Comment by SvenAlHamad** [comment]
For confirmation, we can use the Alert component? 

Overall, the UI is simple and clean, it's gonna work nicely for v1.
In terms of the checkboxes, personally I don't mind them but if you have a more complex model it might be tricky. Although for v1, again, this looks fine. 

What I would maybe add to this screen is a reference to a documentation article so the user understands how indexes work.

**Comment by doitadrian** [comment]
Finally got the chance to respond...

@Pavel910 

Yeah, now when I think about it, the save isn't happening until the content model is saved. You are right.

Still, I'm wondering about the best approach. I mean, let's do it, but at least, when indexes are altered in the indexes tab, once the save button is clicked, I would show a confirmation dialog, which would tell the user that he's about to update indexes, which might take some time, etc. What do you think about that?

@SvenAlHamad 
Does that change anything regarding your first comment (using Alert components)?

I'll add a TODO regarding the link to the indexing article, so we can add it later.

**Comment by Pavel910** [comment]
@doitadrian I honestly don't see the point of having an extra dialog. In the end, the user doesn't care, he just wants to modify indexes. I'm not sure what's the best UX. Also, you'll be editing indexes one by one, so having a confirmation dialog after adding each index is "slow" for the lack of a better word.

Maybe just having that `<Alert>` at the top of the index creation dialog is enough? `It may take a few moments before your index are functional` or something like that 🤔

**Comment by doitadrian** [comment]
Yeah, I wouldn't show multiple confirmations for multiple indexes. Just one dialog, that would show the user a summary of all updates that are about to happen, and of course the warning that it might take some time. It doesn't matter if user edited just one, or multiple indexes.

I would go with this dialog just so it really catches the user's attention, but if you think guys this is too much, we can go with a simple alert in the index creation dialog as well.

**Comment by doitadrian** [comment]
Just to be sure, this is the Save button I was referring to:
![image](https://user-images.githubusercontent.com/5121148/81812306-3b099100-9526-11ea-9ed2-b85570059e7f.png)

**Comment by Pavel910** [comment]
Ok I just realized you want to show this `summary` dialog on `Content model save`. Then it makes sense to me.

**Comment by doitadrian** [comment]
Yeah, sorry if I didn't manage to explain it well. :)

**Comment by doitadrian** [comment]
Indexes tab: 
![indexes-tab](https://user-images.githubusercontent.com/5121148/82250767-5fada080-994c-11ea-9c24-174f00428de9.gif)

1 - Before all, "Preview" tab and "Indexes" tab will show the not available message if no fields were added

2 - When you go to the "indexes" tab, by default, one index is already there. It's the "id" index which is automatically created for all content models, and enables searching models by id. It cannot be deleted, as communicated when you hover over the disabled edit icon.

3 - From there, users can add new indexes, consisting of one or more fields.

4 - In the dialog, if a user tries to create an index that already consists (same fields picked), an alert message will popup and the submit button will be disabled.

5 - Once the form is submitted, the index is added to the list, and a snackbar is shown, telling the user to save the model, only then the index will be added.

6 - I didn't do any summaries/confirmations for now when saving the content model.

7 -  When deleting, a confirmation dialog is shown. After accepting, a snackbar is shown, again telling the user to save the content model in order to apply the changes.

Let me know your thoughts when you get a chance. Thanks!

**Comment by SvenAlHamad** [comment]
For me, this looks good for v1. One thing I might add is an info message to the indexes tab that indexes define how you can search and sort your results for this content model, and also provide a link to an article on docs.webiny.com. For us it’s clear what “indexes” are, but for a new user, it might not make total sense the first time they see this interface.

**Comment by doitadrian** [comment]
Will add a short message, I think it's a good idea.

With that, the link sounds awesome. We created an [issue](https://github.com/webiny/webiny-js/issues/844) for that a couple of days ago, so once we have the article, we'll link it.
