### ISSUE TITLE
Headless CMS - Merge "float" and "integer" fields into a single "number" field

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#814]
No need to have two separate fields. For now, let's just go with a single "number" field and later down the road we can adjust this if needed.

BONUS:
I totally forgot that we have the `graphql-scalar` plugin.  So while you're at it, please document it as well.

Just create a new entry here: https://docs.webiny.com/docs/api-development/plugins-reference

**Comment by doitadrian** [comment]
@Pavel910 For this one, we're gonna need a separate `Number` type for the GraphQL schema I'd say. It's either that or the user will have to select the number type in field options.

What do you think?

Some good info here - https://www.apollographql.com/docs/apollo-server/schema/scalars-enums/

Also, check this to see how you can add new scalars: `packages/graphql/src/createSchema/prepareSchema.ts:29`

**Comment by Pavel910** [comment]
I think a custom scalar type for GQL is actually a good idea 👍
