### ISSUE TITLE
CRUD List item count

### ISSUE THREAD

**Issue by Pavel910** [webiny/webiny-js#821]
After moving to cursor based pagination we no longer have a clear information about what "page" of data the user is looking at, because it's not possible to know with cursor based pagination. 

However, we can cheat a little, and do it the same way Gmail, AWS Console, etc. do, by tracking current page in the app state, and at least provide the pagination information as long as the user stays on the same route.

## Where do we want to show it?
![image](https://user-images.githubusercontent.com/3920893/81561031-d1a54900-9392-11ea-9f44-abcb01cee4d6.png)

## Implementation
This will require to upgrade the following hook: 
`packages\app\src\hooks\useDataList\useDataList.ts` 

and the `DataList` component:
`packages\ui\src\List\DataList\DataList.tsx`

Also, it's best to move `useDataList` and `useAutocomplete` hook to the `app-admin` package and reduce the scope of features in this hook to focus on good Admin app UX.

**Comment by ianvonholt** [comment]
I wanted to add on-to this that pagination is broken with items pertaining to a DateTime string. 

At least with the MongoDB Commodo connector, the cursor is decoded and the query is built here: https://github.com/webiny/commodo/blob/a16b57379ae058ee2c5899cbb50234e04f2a266c/packages/fields-storage/src/withStorage.js#L331

**Comment by Pavel910** [comment]
@ianvonholt cursor always contains at least the `id` of the item. The `id`, which is basically a MongoID string, satisfies all the requirements for a valid cursor.

Why exactly do you think that pagination is `broken` ?

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
