### ISSUE TITLE
Headless CMS - `createdBy` not resolved

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#828]
As we can see in the following screenshot, the ID is returned, but `firstName` and `lastName` not.

![image](https://user-images.githubusercontent.com/5121148/81378141-0e5d1000-9107-11ea-9bc9-f060a0b73f06.png)

The data exists in the SecurityUser entry:
![image](https://user-images.githubusercontent.com/5121148/81378229-36e50a00-9107-11ea-9a4b-af67635d65d6.png)

**Comment by EmilK15** [comment]
The scope of this has changed to remove createdBy props.
