### ISSUE TITLE
Check node and yarn versions in CWP

### ISSUE THREAD

**Issue by Pavel910** [webiny/webiny-js#842]
In `create-webiny-project`, in this file `packages/create-webiny-project/bin.js` we should perform checks for node version and yarn version. `node` should be `>= 10.14.0` and `yarn` must be `1.x`.

Copy the logic from here: https://github.com/webiny/webiny-js/blob/master/packages/cli/bin.js and adjust the messages.

**Comment by doitadrian** [comment]
@Pavel910 Resolved this one, closing.
