### ISSUE TITLE
Headless CMS - Rich text component - add support for images.

### ISSUE THREAD

**Issue by SvenAlHamad** [webiny/webiny-js#846]
This is an issue placeholder. Initially, the Headless CMS rich text component won't support image. In one of the upcoming releases, we actually want to add this feature. 
Detailed requirement TBD.

**Comment by alastair-todd** [comment]
Is there a rough prio/eta?
Bit of a showstopper for my project but in no rush...go live is months off...

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
