### ISSUE TITLE
Headless CMS - add "Meta" tab in the content entry form

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#851]
This could show some basic information, for example `createdBy`, `createdOn`, `updatedBy`, `updatedOn`, ...

I've seen some systems call this tab "Info" as well.

![image](https://user-images.githubusercontent.com/5121148/82153048-6f9e8500-9865-11ea-996c-f99f139c7442.png)

**Comment by doitadrian** [comment]
P.S. Seen some systems also have the Comments/Conversations tab too. Just mentioning it, might be useful for the future.

**Comment by ng29** [comment]
Hey @doitadrian / @Pavel910 

can i pick this up? And more info regarding this will be highly appreciated 👍 

Cheers,

**Comment by Pavel910** [comment]
Closing this. Something along these lines will be introduced once we get the real publishing workflow going.
