### ISSUE TITLE
Headless CMS - Add a view with all API URLs

### ISSUE THREAD

**Issue by Pavel910** [webiny/webiny-js#863]
## This is:
- Feature request

## Description
We need to have a place where users can find a list of all URLs to all APIs and environments. Or at least have it per-environment.

When I was using Contentful I was going nuts trying to construct the API URL. I want it to be accessible within 2-3 clicks at most. It can be a separate view, a Dialog, whatever. We just need to make it very easily accessible.

For example:
```
Environment: Production
Content Delivery API:  CDN_URL/cms/read/production
Content Preview API: CDN_URL/cms/preview/production
Content Management API: CDN_URL/cms/manage/production
```

**Comment by SvenAlHamad** [comment]
Can we display this information on the environment screen in the admin area?

**Comment by doitadrian** [comment]
Actually, these links that Pavel pasted are environment aliases.

So you would have to go to the environment aliases, to get these.

But somehow I have the feeling this is too buried, it would take a lot of effort for the user to reach these.

I was thinking something like this:
![image](https://user-images.githubusercontent.com/5121148/82685533-a6eda700-9c54-11ea-9632-7c7129583b37.png)

So we put a small `(i)` icon, which would show a tooltip, with this info.

```
Environment: CustomCreatedEnv
Alias: CustomAlias
Content Delivery API:  CDN_URL/cms/read/custom-alias
Content Preview API: CDN_URL/cms/preview/custom-alias
Content Management API: CDN_URL/cms/manage/custom-alias
```

**Comment by Pavel910** [comment]
Or maybe even a dialog. So you have an icon, you click it - get a detailed dialog? Tooltip might look too crowded 🤔

**Comment by doitadrian** [comment]
That's OK too, especially because you'd probably want to c/p these links, and with a dialog, we'll be able to put COPY buttons.

**Comment by doitadrian** [comment]
Add CMS links in environments and environment aliases views. 
Also add it in the Access Tokens form.

**Comment by EmilK15** [comment]
The approach here so far is to create an (i) icon next to the name of the production.
Probably will have to pull the urls from the environment alias endpoint from GraphQL api and then display a small popup with those urls in a nice format

**Comment by EmilK15** [comment]
Added a small (i), and will add an information icon for it so it's not next:
But here is what the current modal looks like with CopyButtons attached:
![image](https://user-images.githubusercontent.com/9532882/85319649-d2e88c00-b48f-11ea-9943-7f2a75d22089.png)

**Comment by EmilK15** [comment]
Changed a few things: Mainly the icon color so it matches moreso to the rest of Webiny.
Added information icon to AliasesForm.
Thought @doitadrian I do have a question about this case for access tokens: should it display only the base url, or a url for every environment it's connected to?
![image](https://user-images.githubusercontent.com/9532882/85459812-99d41880-b570-11ea-8e54-1e46998d523e.png)

![image](https://user-images.githubusercontent.com/9532882/85459852-a5bfda80-b570-11ea-9ec1-6da180ce410f.png)

**Comment by doitadrian** [comment]
Regarding ATs question that @EmilK15 posted... Yeah, I think it's gonna get nasty if we print out all URLs, for every selected AT.

If you ask me, I'd just not-implement it here.

Anyone else feeling differently? @webiny/developers

**Comment by doitadrian** [comment]
After this, @EmilK15, let's continue our conversation in the actual PR.

**Comment by Pavel910** [comment]
@EmilK15 @doitadrian I'm not entirely sure what you're talking about, but if you talk about a Dialog, you could render URLs for each environment in Tabs. A Tab per Envrionment.

**Comment by doitadrian** [comment]
We can do that, thought it's was a bit of an overkill. 

But yeah, if you think we should not not-have-it in the access tokens area, let's implement your idea @Pavel910.

**Comment by Pavel910** [comment]
Let's not do it at all then at this point and see how it goes with the users.
