### ISSUE TITLE
Headless CMS - pressing Esc closes the edit field dialog

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#871]
Clicking on this, shows the I18N overlay. Pressing escape, closes both the overlay, and the edit field dialog.

![image](https://user-images.githubusercontent.com/5121148/82639552-42592a80-9c09-11ea-9b9d-e7f65b203720.png)

**Comment by sunguru98** [comment]
Firstly, may I know what is the intended result, and how should it happen?
P.S I still have no idea how to fix it, although I do have a lot of state change experience in React, hence may I take this to challenge myself haha?

**Comment by doitadrian** [comment]
Sorry for the delay @sunguru98,  we were super swamped with our new BETA release. Since it's out, all of the further fixes need to be done in the `release-4.x` branch.

Now, regarding the issue...

When you click the icon on which the arrow is pointing to, a full-screen UI pops up, which lets you to enter different values for all of the available locales.

**Comment by sundeep-charan** [comment]
Aww .. I see, pretty doable I think. So may I take up on this one, BTW, I also applied to webiny for the developer role, so this would be a good chance to prove myself.

**Comment by sundeep-charan** [comment]
If you could assign my username on to the assignees' option that would be great @doitadrian

**Comment by doitadrian** [comment]
Didn't expect that fast of a response 👍

**Comment by doitadrian** [comment]
I'll provide more instructions in an hour/two.

Just to give you a general idea how it might be solved.

**Comment by sundeep-charan** [comment]
Haha, pretty excited. One small question, I should be pushing this change onto the release-4.x branch right?

**Comment by doitadrian** [comment]
Yeah, PR to that branch would be awesome.

**Comment by sunguru98** [comment]
Any advices on how to start the repo (backend as well as SPA)? .. Pretty unfamiliar and overwhelmed seeing all the other files haha.

**Comment by Pavel910** [comment]
Read this whole document:
https://github.com/webiny/webiny-js/blob/release-4.x/docs/CONTRIBUTING.md

And before deploying your API do just this DB setup step: https://next.webiny.com/docs/get-started/quick-start#2-setup-database-connection

**Comment by doitadrian** [comment]
Hey @sunguru98, 

so, the I18N overlay I mentioned can be found here `packages/app-i18n/src/admin/components/I18NInputLocalesOverlay.tsx`.

In it, please try to utilize this lib: https://github.com/doitadrian/react-hotkeyz lib in order to capture the `Esc` key, and do what's necessary.

We've used the lib on several occasions throughout `app-*` packages, so you should be able to find some useful examples.

Let us know if you have any questions.

Thanks! 🍻

**Comment by sunguru98** [comment]
Hi @doitadrian, I am currently stuck at a place where I have to deploy from the sample_project directory. After installing webiny-cli, I am facing the following error.
**Unknown arguments: deploy, api**. Any ideas?

**Comment by Pavel910** [comment]
@sunguru98 you don't need to install `webiny-cli` especially not that particular package name :)
`@webiny/cli` is present in the repository, in `packages/cli`, and all you need to do is run it using `npx webiny deploy ....`. 

`npx` will resolve `webiny` to your `node_modules`.

**Comment by sunguru98** [comment]
Gotcha! Thanks for the assist @Pavel910

**Comment by sunguru98** [comment]
Here comes another roadblock lol. I have successfully deployed and the cli asked me to setup my user information by creating an account. Everything is done, and I am right now at the following page.
<img width="1440" alt="Screenshot 2020-05-27 at 2 03 08 AM" src="https://user-images.githubusercontent.com/32637757/82947798-3df09100-9fbe-11ea-87dc-723692ab7730.png">

My question is how should I exactly manoeuvre towards the buggy package which has been mentioned, as this is the first time I am working on a monorepo, I am sort of confused on transitioning from the sample-project to the packages folder mentioned. How and what should I do inorder to link my process towards those said packages.

**Comment by doitadrian** [comment]
Open Headless CMS app / Models section.

![image](https://user-images.githubusercontent.com/5121148/82948274-c90f5e00-9fa1-11ea-8ecd-e685378985b5.png)

Create a new entry by clicking on the green (+) sign button, located in the bottom-right corner.

Once you're in the Content Model Editor, dragging/dropping one of these fields should open the Field Settings dialog.

![image](https://user-images.githubusercontent.com/5121148/82948400-007e0a80-9fa2-11ea-99cc-89160ef522c4.png)

**Comment by sunguru98** [comment]
No words to express my thankfulness. Simply amazing @doitadrian. I will check it out right away.

**Comment by sunguru98** [comment]
@doitadrian, Apologies for the delayed reply. Status update: Still stuck in figuring out the codebase, and especially react-hotkeys examples are not clear enough, the z-index attribute is something which is not clear, I noticed that the PORTAL for i18n-inputs-locale-container is possessing the 2nd overlay and dialog container is possessing the Dialog component. I also figured out that EditFieldDialog is the parent which is calling I18NInput which in turn is containing the I18NInputLocalesOverlay. The hierarchy is found, but the approach is a bit confusing. Hope I made sense.

**Comment by doitadrian** [comment]
I feel you.

Basically, it behaves in theory like a standard z-index you might have already seen in the CSS world.

If you're on, let's say, `zIndex` 150, all shortcuts that were registered on lower z-indexes (e.g. 149) will not be triggered.

This is especially useful in cases like these, where you, for example, have a modal, which might have shortcuts on one `zIndex`, and then we are opening the I18N overlay that goes over the modal. So, hitting shortcuts that were registered on a modal should not be triggered while we're in the I18N overlay.

I believe the zIndex of 50 should suffice in your case, but try it out.

**Comment by sunguru98** [comment]
Phew!!! After 9 hours of scratching and swearing, I finally made it work. It literally boiled down to just three things, stop the propagation and close the dialog. The useHotkeys library's zIndex was a bit confusing. I thought it as the CSS's zIndex and tried to match it with the library's term. But it is working now. May I commit the changes from my side? @doitadrian  & @Pavel910.

**Comment by doitadrian** [comment]
Thanks @sunguru98 . 

I know, the docs for the lib are lacking :)

Yeah, please create a PR so we can make a review.

Thanks a lot!

**Comment by sunguru98** [comment]
> I feel you.
> 
> The z-index, in theory, behaves like a standard z-index you might have already seen in the CSS world.
> 
> If you're on, let's say, `zIndex` 150, all shortcuts that were registered on lower z-indexes (e.g. 149) will not be triggered.
> 
> This is especially useful in cases like these, where you, for example, have a modal, which might have shortcuts on one `zIndex`, and then we are opening the I18N overlay that goes over the modal. So, hitting shortcuts that were registered on a modal should not be triggered while we're in the I18N overlay.
> 
> I believe the zIndex of 50 should suffice in your case, but try it out.

I bumped the zIndex value all the way to 121 and checked it lol. I can change the value if you want. 
The code is like this right now.
<img width="832" alt="Screenshot 2020-05-27 at 8 30 57 PM" src="https://user-images.githubusercontent.com/32637757/83037075-fff47b00-a058-11ea-8217-4b943c1deca5.png">

**Comment by sunguru98** [comment]
Awaiting for the merging haha.
