### ISSUE TITLE
Headless CMS - fix indexes creation (API/Apps)

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#889]
- [ ] Fix label

Once an index is added, this here should say something more informative, like:
> Not created yet, please save the content model to apply the changes.

![image](https://user-images.githubusercontent.com/5121148/82860710-c9184b00-9f1a-11ea-9198-df1be472d3b3.png)

- [ ] Make sure once the content model is saved, the label gets updated with the time (so, it should look like the above "id" entry)

- [ ] For some reason, the "id" index gets recreated on each submit (the `createdOn` is always refreshed on submit).

**Comment by sunguru98** [comment]
May I take this as well? Just adding up my odds to the hiring process lol.

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
