### ISSUE TITLE
Headless CMS - Welcome screen

### ISSUE THREAD

**Issue by SvenAlHamad** [webiny/webiny-js#891]
Create a welcome screen for when users first enter the admin area. 

A welcome screen should contain:
- button to create a first content model/page
- access to Webiny community

**Comment by EmilK15** [comment]
![welcomeScreen](https://user-images.githubusercontent.com/9532882/83259987-fe28d580-a186-11ea-8bff-574c78adb053.png)

**Comment by EmilK15** [comment]
![welcomeScreen](https://user-images.githubusercontent.com/9532882/83260781-5ad8c000-a188-11ea-8c69-f263375cdd7e.png)
Dark mode version

**Comment by EmilK15** [comment]
![welcomeScreen2](https://user-images.githubusercontent.com/9532882/83261219-fd913e80-a188-11ea-91a7-70d208b65df1.png)
Similarly the bottom could be spaced out so its two community links per line like this

**Comment by Pavel910** [comment]
I think we should add a lot more context here, because out of the blue you're inviting people to create a Content Model, and they are in here for the first time. It's kinda confusing.

**Comment by SvenAlHamad** [comment]
Thanks for the screenshot @EmilK15 

I would add a few changes to the screen:
1. The font size on dark mode should also change. It should be white.
2. As for "Join us", please rename that into "Join our community:"
3. Let's have Slack (https://webiny.com/slack), Github (https://github.com/webiny/webiny-js), Medium (https://blog.webiny.com) and Twitter (https://twitter.com/WebinyPlatform) there.

**Comment by SvenAlHamad** [comment]
Also agree on the what Pavel said - maybe just add some context to both the upper bit regarding the task of creating the first content model and the lower bit that people know that in our community they can learn, discuss and ask for help.

**Comment by EmilK15** [comment]
![image](https://user-images.githubusercontent.com/9532882/83295244-a73df300-a1bc-11ea-8a57-1a74cfabe393.png)
![image](https://user-images.githubusercontent.com/9532882/83295272-b329b500-a1bc-11ea-9c81-993916c43573.png)
Above are the new page previews with the added body text, fixed dark mode lighting, and links to Medium and Twitter pages.

**Comment by Pavel910** [comment]
@EmilK15 FormBuilder is one thing. Content Models are part of Headless CMS, and that's another thing.

From this text it sounds like in FormBuilder you're creating a Content model.

**Comment by doitadrian** [comment]
I see we didn't mention it, but a link to the docs site might be useful here as well.

**Comment by doitadrian** [comment]
I think additional formatting should be added here as well.

![image](https://user-images.githubusercontent.com/5121148/83300222-e9d0f100-a1f7-11ea-86cd-a54f8dc575a4.png)

We ended the sentence (1) with `:`, and then in a new line, we just started a new one (2 and 3).  

Using list bullets might be a nicer approach here.

**Comment by SvenAlHamad** [comment]
I had a think about this, and the main problem I had with this approach was that it won't work for when a user has multiple apps installed, i.e. headless + pb + fb. To solve that my idea is that each app can have a plugin to register it's own very simple widget to the welcome screen. I've created a mockup below. The plugin for registering widgets takes 3 parameters: title description and a CTA. This approach will now work regardless if the user has 1 app, or 10 apps installed. 

 I've also polished out the visual style for the rest of the screen. 

![welcome screen](https://user-images.githubusercontent.com/3808420/83329369-fa797980-a280-11ea-9845-4944f7119189.png)

**Comment by Pavel910** [comment]
This looks great and is very easy to implement!

**Comment by Ashu96** [comment]
Agreed! Looks awesome :rocket:

**Comment by Pavel910** [comment]
@SvenAlHamad how is this layout achieved in the CSS/Grid context ,is this a 4+4+4, then if we have 5 widgets it breaks down into a new Grid Row, or is this a flexbox with fixed widget width which breaks itself and centers everything?

**Comment by SvenAlHamad** [comment]
@Pavel910 the part with app widgets can be a simple flexbox where you have 3 boxes with a fixed width. This way even if you have more than 3  apps, flexbox will automatically push the remaining boxes into new rows, you don’t need to code that logic, flexbox css will handle it.

**Comment by EmilK15** [comment]
![image](https://user-images.githubusercontent.com/9532882/83445604-43fdcc00-a41b-11ea-8c6f-9fdf2af17889.png)
![image](https://user-images.githubusercontent.com/9532882/83445626-4cee9d80-a41b-11ea-8952-04a5d2075e76.png)
Latest look and feel for the welcome page

**Comment by SvenAlHamad** [comment]
@EmilK15 almost there, two small bits to be corrected:

1. The padding inside the app box needs to be bigger, set it to something like 20px (see the arrow in the image)
2. The grid is not aligned correctly between the upper bit and lower bit. I suggest adjusting it by tweaking the width or the margins. 

![83451786-8b895580-a425-11ea-95ab-2aaab2602eef](https://user-images.githubusercontent.com/3808420/83501293-d2c02680-a4b7-11ea-8528-b5c18017c5bb.png)

**Comment by Pavel910** [comment]
And if you don't mind, I'd put those button icons left of the text, the `Documentation` and `Code examples`. It would look a lot cleaner that way.

**Comment by EmilK15** [comment]
![image](https://user-images.githubusercontent.com/9532882/83534158-7f9da200-a4be-11ea-943a-3d686ba656ba.png)
![image](https://user-images.githubusercontent.com/9532882/83534216-904e1800-a4be-11ea-9e22-c99c622c08f6.png)
Latest screenshots with those revisions you mentioned
