### ISSUE TITLE
Webiny install process - add the option to subscribe to the newsletter.

### ISSUE THREAD

**Issue by SvenAlHamad** [webiny/webiny-js#892]
Reference: https://github.com/webiny/website/blob/master/src/components/footer/newsletter.js

**Comment by Pavel910** [comment]
@EmilK15 the UI should go in here:
`packages/app-plugin-security-cognito-theme/src/admin/views/InstallForm.tsx:35`
and the `onSubmit` callback needs to be implemented here `packages/app-plugin-security-cognito-theme/src/admin/index.ts:53`.

That will allow you to subscribe the user to the newsletter when the form is submitted.
