### ISSUE TITLE
Headless CMS - Bug in Safari on Mac

### ISSUE THREAD

**Issue by endymion1818** [webiny/webiny-js#898]
## This is:
- a Bug
## Specifications

  - version: 4.0.0-beta.2
  - OS: macOS Catalina 10.15.4 
  - Browser: Safari 13.1 (15609.1.20.111.8)

## Expected Behavior
I should be able to see the word "search" clearly and see the words I type 

## Actual Behavior
Text is partially obscured

## Steps to Reproduce the Problem
1. Launch Headless CMS
2. Open in Safari
3. Observe issue, screenshot below

<img width="1133" alt="Screenshot 2020-05-27 at 13 28 44" src="https://user-images.githubusercontent.com/2216344/83058213-ef8bd280-a04f-11ea-9e05-6114f1a80b52.png">

## Possible Solution
Maybe remove the `line-height` declaration from `.mdc-text-field__input`

**Comment by sunguru98** [comment]
If you could assign me, I shall look into it @endymion1818

**Comment by doitadrian** [comment]
Go for it @sunguru98, I think this one is a bit more appropriate than the other one you mentioned the other day.

Let's see how this one will go.

**Comment by peterjgrainger** [comment]
@doitadrian can I have a go at this?

**Comment by doitadrian** [comment]
Sure, go ahead @peterjgrainger :)

**Comment by AlbionaHoti** [comment]
Hey @peterjgrainger, can you please post an update of your progress on the issue and the solutions you tried (communication here is key) - Join our [slack community](webiny.com/slack) to communicate faster with the community and the core team. Enjoy :)

**Comment by peterjgrainger** [comment]
Ok, will do, thanks

**Comment by peterjgrainger** [comment]
@AlbionaHoti I've tried this in safari `Version 14.0 (15610.1.28.1.9, 15610)` and there doesn't seem to be the same problem.

I couldn't find a way of downloading exact versions of safari to test it out on. Maybe this issue could be closed?

![image](https://user-images.githubusercontent.com/1332395/96146421-2c247180-0efe-11eb-9840-86b9e764b8f8.png)

**Comment by endymion1818** [comment]
Hmm I’ll test in the latest version when I can

**Comment by endymion1818** [comment]
OK so the issue only occurs on focus, when you begin to type in the box:

<img width="771" alt="Screenshot 2020-10-18 at 14 18 22" src="https://user-images.githubusercontent.com/2216344/96368640-cf6ac600-114c-11eb-858e-d0ec5c1382fd.png">

**Comment by endymion1818** [comment]
Hmm autocomplete seems to think I type that a lot ...

**Comment by peterjgrainger** [comment]
Ah, I see it. I'll take a look
