### ISSUE TITLE
Admin app typography tweaks for RichTextEditor

### ISSUE THREAD

**Issue by Pavel910** [webiny/webiny-js#899]
This is what the typography looks like now:

![image](https://user-images.githubusercontent.com/3920893/83067357-d7737d80-a066-11ea-8154-b1021642f177.png)

The file in question is `packages\app-admin\src\styles\typography.scss`. This task depends on the completion of Slate migration.

**Comment by sunguru98** [comment]
May I take this task? A little debriefing would do great, as I would love to code scss as well :)

**Comment by anushkrishnav** [comment]
I would like to work on this issue . Any guide / Doc I can refer to .

**Comment by AlbionaHoti** [comment]
@sunguru98 Can you please confirm if you want to continue working on this issue? If not, @anushkrishnav you can continue :) 

We will add more details regarding the issue!

**Comment by sunguru98** [comment]
Hey 👋 Albiona, currently I am not doing any open source, so you can very well let him do it. Thanks.

**Comment by anushkrishnav** [comment]
Would be glad to know more about this issue. And how I can get started

**Comment by AlbionaHoti** [comment]
@anushkrishnav We will get back with more details shortly, thank you for your patience!

**Comment by AlbionaHoti** [comment]
@anushkrishnav due to our next big update of the Webiny version 5, we will no longer use Slate, that being said we will close this issue. We are sorry we didn't update it earlier! In the meantime, check out the issues Hacktoberfest project, we will definitely update/add more issues.
