### ISSUE TITLE
CLI doesn't suggest the correct API name

### ISSUE THREAD

**Issue by Fsalker** [webiny/webiny-js#901]
If you want to deploy one of the api's lambda functions such as `cmsGraphQL` using `webiny deploy api cmsgraphql --env=dev", it won't work. The CLI doesn't really tell you anything either and it's rather cryptic.

This is because the deployed lambda function's name is case sensitive and you should use `webiny deploy api cmsGraphQL --env=dev` instead.

Our CLI should suggest the correct form. We could use [Levenshtein distance](https://www.npmjs.com/package/fast-levenshtein) for this and suggest the closest match (up to a max distance of 2 for example).

## This is:
- Feature request

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
