### ISSUE TITLE
Headless CMS - Access Tokens improvements

### ISSUE THREAD

**Issue by Pavel910** [webiny/webiny-js#907]
Make the input a `CopyInput`, so we have that `copy to clipboard` button:

![image](https://user-images.githubusercontent.com/3920893/83299695-f7d24200-a1f6-11ea-85d7-d5549467dcf7.png)

**Comment by SvenAlHamad** [comment]
I've also noticed that when I create a new token it shows up on in the list on the left side, but it says no environments, although I’ve assigned it an environment.

Can you add a description under the Token field -  "Token will be shown once you save the form” (only when you are creating a new token)
