### ISSUE TITLE
CWP template build utils

### ISSUE THREAD

**Issue by Pavel910** [webiny/webiny-js#909]
We need to create a utility within each of the `cwp-template-*` packages, to copy the setup from `sample-project` so we don't have to do it manually. 

We consider `sample-project` to be the source of truth, and `.adiorc.js` now also includes those packages when checking dependencies. Adding this script would ensure our CWP packages are in sync with the `sample-project` and project dependencies are checked before publishing,

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
