### ISSUE TITLE
Headless CMS - remove GQL filtering for `multipleValues` fields

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#910]
Fields with `multipleValues` enabled cannot be searched at the moment. That's why we don't need filters like these:

![image](https://user-images.githubusercontent.com/5121148/83377006-8354fa00-a3d4-11ea-8209-5d5bfa825193.png)

Check all fields, and remove dynamic creation of any filters if the field has `multipleValues` enabled.

P.S. We're gonna need to revisit this topic in the future.

**Comment by EmilK15** [comment]
After testing in the following fashion, we came to the conclusion that it was not possible to reproduce this problem via the UI.
1. Create a Content Model
2. Edit the Content Model to have a list of text values
3. Clicking on Indexes Tab shows that the text values are **unable** to be indexed in order for them to appear in the `/cms/read/development` and `/cms/manage/development` api url's.

So we are switching the scope of this bug to be adding a test that will emulate exactly this phenomenon and it will expect that when trying to add the list of tags as an index to throw an error.
