### ISSUE TITLE
Navigating away from PB Editor causes loss of last edited text

### ISSUE THREAD

**Issue by Pavel910** [webiny/webiny-js#912]
All the details are described in this topic https://community.webiny.com/t/bug-text-block-not-updating/239/3.

We need to try blocking the navigation event, and let the Editor complete it's `save` operation before allowing the user to change routes (this includes clicking the in-editor Back button as well as the browser Back button).

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
