### ISSUE TITLE
Headless CMS - RichText - Paste HTML from external sources

### ISSUE THREAD

**Issue by Pavel910** [webiny/webiny-js#917]
Currently you can either paste "text" or do "Paste as plain text". HTML data is not being handled. Would be nice to handle external data and paste it as plain text no matter where it comes from.

**Comment by icy-meteor** [comment]
Yes, this is good to have feature down the line.

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
