### ISSUE TITLE
Enable sending parameters

### ISSUE THREAD

**Issue by adrian1358** [Webiny/webiny-js#92]
Enable calling attributes as methods, so that additional parameters can be sent.

Eg. `await user.get('img.src:320:500')`

or

`await user.image.src('320', '500')`

**Comment by Pavel910** [comment]
And for `dynamic` attribute as well.

```
user.someDynamicAttr(10, 100)
```

**Comment by Pavel910** [comment]
And also when doing `toJSON`, I should be able to pass parameters to `onGetJSONValue`, just like we could do in PHP.

API call:
`_fields=src:thumbnail`

Entity attribute:
```
this.attr("src")
    .char()
    .onGetJSONValue((value, preset) => {
        // `preset` is the parameter from URL and should equal to `thumbnail`
        return /^(https?:)?\/\//.test(value) ? value : this.getURL(preset); 
    });
```
