### ISSUE TITLE
Adding a Security User workflow is unclear

### ISSUE THREAD

**Issue by EmilK15** [webiny/webiny-js#927]
## This is:
- Bug
## Expected Behavior
When you land on the page it seems like you need to click on this:
![image](https://user-images.githubusercontent.com/9532882/83678787-48a5ba00-a5ac-11ea-8559-c39e31c52df7.png)
## Actual Behavior
But clicking the button does nothing (see above)
## Possible Solution
Either the button creates a popup of the form to create a user (consistent with the rest of the button behavior within Webiny), or make the editing of the Bio more clear for the user in the first place.

**Comment by Pavel910** [comment]
This was reported by other users, so I'm marking this as `high priority`. We need to resolve this for the next release.

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
