### ISSUE TITLE
Headless CMS - handle incorrect API URLs

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#936]
Accessing an invalid URL, like the following...
```https://dugilt40hnfag.cloudfront.net/cms/reXYZad/5ecbedb4e78b2b00082b8b63```

...causes the following error to be thrown:
![image](https://user-images.githubusercontent.com/5121148/83794390-3efc7f00-a69e-11ea-9ba2-e4f3d02e7c7a.png)

**Comment by doitadrian** [comment]
Sorry to ask, but is there any progress on this one? :)

**Comment by EmilK15** [comment]
Yup sorry, was pre-occupied with another task. This will be done today

**Comment by EmilK15** [comment]
The error now shows the following when the alias url is incorrect:
![image](https://user-images.githubusercontent.com/9532882/86405109-ca0d6c80-bc7e-11ea-9a21-05f9df43f438.png)
![image](https://user-images.githubusercontent.com/9532882/86405134-d72a5b80-bc7e-11ea-9005-056ee5d064c2.png)
