### ISSUE TITLE
Deploy option for Yandex.Cloud

### ISSUE THREAD

**Issue by jevgen** [webiny/webiny-js#945]
There is no AWS in Russia. For local compliance, data ad its collection has to sit in Russia. Would be nice to have a deployment option for Yandex.Cloud

## This is:
- Feature request

**Comment by Pavel910** [comment]
Hi @jevgen, thanks for the information and your request. Currently we're pretty much focused on AWS only, but we do ideally want to deploy Webiny on other clouds as well. 

Hopefully we'll be able to pull this off in the future! 🍻

**Comment by Pavel910** [comment]
@jevgen do you know what is Yandex's alternative to AWS API Gateway and CloudFront? Those are the 2 missing pieces I can't seem to figure out.

**Comment by jevgen** [comment]
> @jevgen do you know what is Yandex's alternative to AWS API Gateway and CloudFront? Those are the 2 missing pieces I can't seem to figure out.

They published extensive documentation about that at https://cloud.yandex.ru/docs/overview/platform-comparison/aws
