### ISSUE TITLE
api cmsContent  error: commodo.withStorageName is not a function at createDataModel

### ISSUE THREAD

**Issue by boyuan459** [webiny/webiny-js#947]
## This is:

- Bug

## Specifications

  - version: develop branch
  - OS: MacOS Catalina version(10.15.1)
  - Browser:

## Expected Behavior

no error for withStorageName

## Actual Behavior

there are errors in cloudwatch as follow:
INFO	[@webiny/handler-apollo-server] An error occurred: 
{
    "requestContext": {
        "resourceId": "vjs1rs",
        "resourcePath": "/cms/{key+}",
        "httpMethod": "OPTIONS",
        "extendedRequestId": "NqROSFSISwMFkJg=",
        "requestTime": "05/Jun/2020:15:18:51 +0000",
        "path": "/prod/cms/manage/xxx",
       .......
    },
    "context": {
        "callbackWaitsForEmptyEventLoop": true,
        "functionVersion": "$LATEST",
        "functionName": "xxx",
        "memoryLimitInMB": "512",
        "logGroupName": "/aws/lambda/xxx_webiny-js_api_local_cmsContent",
        ....
    },
    "error": {
        "name": "TypeError",
        "message": "(0 , _commodo.withStorageName) is not a function",
        "stack": "TypeError: (0 , _commodo.withStorageName) is not a function\n    at createDataModel (/var/task/handler.js:112527:32)\n    at apply (/var/task/handler.js:97932:89)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
    }
}

## Steps to Reproduce the Problem

1. webiny deploy api --env=local
2. login to aws and go to CloudWatch -> CloudWatch Logs -> Log groups -> [your ] webiny js_api_local_cmsContent

## Detailed Description

change the commodo related libs to new release

## Possible Solution

change the minor version in the packages/commodo/package.json to
"@commodo/fields": "^1.1.0-next.14",
"@commodo/fields-storage": "^2.0.0-next.27",
"@commodo/fields-storage-ref": "^1.1.0-next.14",
"@commodo/fields-storage-soft-delete": "^2.0.0-next.27",
"@commodo/hooks": "^1.1.0-next.14",
"@commodo/name": "^1.2.0-next.14",

**Comment by Pavel910** [comment]
@boyuan459 actually the semver range is fine here, you don't have to change the versions, just install new packages, delete your `yarn.lock` and do `yarn` again, and it should pull the latest available versions.

If that doesn't help then we can update the versions numbers, sure, but it's not necessary.

If you'd like to change the package versions, feel free to send a PR with the updated versions. Thanks!
