### ISSUE TITLE
Can't install Security app

### ISSUE THREAD

**Issue by tomyun** [webiny/webiny-js#950]
## This is:
- Bug

## Specifications

  - version: 4.0.2
  - OS: macOS 10.15.5
  - Browser: Chrome 83

## Expected Behavior

Security app should be installed after an admin user is created.

## Actual Behavior

An error message shows up saying:
```
Something went wrong
User does not exist.
```

## Steps to Reproduce the Problem

1. Following a [Quick Start](https://docs.webiny.com/docs/get-started/quick-start) guide to install webiny (either full/cms template)
2. Deploy API
3. Start `admin` app

## Detailed Description

I followed a Quick Start guide to try set up both full/cms templates. The issue occurs right after starting `admin` app to set up my project. The first screen of the admin was to install Security app which let me go through creating an admin user. I followed the instruction, but then it couldn't proceed. Seems like a user entry was created in MongoDB.

## Possible Solution

Not a solution, but the issue seems very similar to #868.

**Comment by Pavel910** [comment]
Hi @tomyun, thanks for reporting. We had 2 other reports of this issue, and we're investigating. So far, we were unable to replicate this. It has to be some special set of conditions which trigger this behavior. I'll get back to you when we figure this out.

Cheers!

**Comment by Pavel910** [comment]
@tomyun we finally managed to replicate this - it's only happening for passwords shorter than 8 characters 😆 Such a stupid oversight on our side. Just use a password of at least 8 character, and it will be ok.

We'll fix this immediately and release in the following days with other bunch of improvements.
