### ISSUE TITLE
Unable to convert multiple lines to code block in Rich Text Editor

### ISSUE THREAD

**Issue by icy-meteor** [webiny/webiny-js#952]
Multiline content in rich text editor is treated as a separate entity for code block.

## This is:
- Feature request
- Bug

## Specifications

  - version: 4.0.2
  - OS: macOS Catalina 10.15.5 
  - Browser: Brave Version 1.9.76 Chromium: 81.0.4044.138 (Official Build) (64-bit) 

## Expected Behavior
Allow to select multiple lines into a single code block.

## Actual Behavior
Each line becomes a separate code block.

## Steps to Reproduce the Problem
Go to content model, create a new model with rich text editor. 
Type some multi-line content into the rich text editor and convert it to code.

![image](https://user-images.githubusercontent.com/22114682/83974111-6e162900-a908-11ea-9e47-6469066136c9.png)

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
