### ISSUE TITLE
Color of text in Rich Text Editor is black in dark mode

### ISSUE THREAD

**Issue by icy-meteor** [webiny/webiny-js#953]
The color of input text in rich text editor is black in dark mode. It should ideally be white.

## This is:
- Bug

## Specifications

  - version: 4.0.2
  - OS: macOS Catalina 10.15.5 
  - Browser: Brave Version 1.9.76 Chromium: 81.0.4044.138 (Official Build) (64-bit) 

## Expected Behavior
The text should be of a lighter color, maybe white.

## Actual Behavior
The text appears dark in dark mode.

## Steps to Reproduce the Problem
1. Go to content model, create a new model with rich text editor.
2. Switch to dark mode by clicking your profile icon on top right.
3. Type some multi-line content into the rich text editor.

# Detailed Description
![image](https://user-images.githubusercontent.com/22114682/83974204-30fe6680-a909-11ea-9e72-5cc701e3fcca.png)

**Comment by jarretmoses** [comment]
I noticed the preview styles are broken as well where the background color is incorrect (stays white). @icy-meteor are you currently working on this? I'd be interested in fixing this if not.

**Comment by icy-meteor** [comment]
@jarretmoses Feel free to work on it :)

**Comment by Ashu96** [comment]
Go ahead @jarretmoses 🙂

**Comment by jarretmoses** [comment]
Am working on now
