### ISSUE TITLE
Settings menu items visible to unauthorized user

### ISSUE THREAD

**Issue by Pavel910** [webiny/webiny-js#957]
## This is:
- Bug

## Expected Behavior
When creating a new user without any access permissions (no roles assigned), the user should not see menu items under Settings menu.

## Actual Behavior
The user is able to see the whole Settings menu, but when clicking on a menu item it renders a `Not Authorized` view.

![image](https://user-images.githubusercontent.com/3920893/84012893-89208180-a978-11ea-88d5-f7c101b6cf6b.png)

## Steps to Reproduce the Problem
1. Create a new user via Security -> Users module, don't assign any roles to the new user.
2. Log in with the new user credentials
3. Open the main navigation

## Possible Solution
I 'm guessing that `scopes` are not applied to the menu items, that's why they're visible.

**Comment by TommyJackson85** [comment]
@Pavel910 Let me try this as my first commit. :)

**Comment by TommyJackson85** [comment]
@Pavel910 Can you suggest to be where I might find the toolbar content being rendered or where I should start from? I am searching LeftDrawer, Toolbar, etc. Also checking through the ui folder in packages.

On logging into the created users account (with no permissions) I am navigated to the Not Authorized view first. I had to load localhost:3001 again to get to my logged in account.

**Comment by Pavel910** [comment]
@TommyJackson85 so each app is registering a plugin to add a new menu section, you can find that by searching your cloned repo for `type: "admin-menu-settings"`.

![image](https://user-images.githubusercontent.com/3920893/85289327-8d2fc180-b497-11ea-91c4-8d62abb438a3.png)

This will give you the location of all Settings menu plugins. You need to use the component `<SecureView>`, and here's an example how we use it: `packages/app-form-builder/src/admin/plugins/menus.tsx:16`

The `ui` package only contains the UI components we use in all of our apps, but there is no business logic there. It's just a library. You can find the components in the storybook, which is also located in the `ui` package: https://storybook.webiny.com/

**Comment by TommyJackson85** [comment]
Just trying it out on Form Builder > reCAPTHA
but its not rendering any changes for some reason. I just run ```yarn start``` from admin folder. Is this correct? 

<img width="655" alt="Screenshot 2020-06-22 at 15 06 52" src="https://user-images.githubusercontent.com/22279028/85296988-1516cb00-b49a-11ea-87fb-9c193bbd1e5e.png">

<img width="701" alt="Screenshot 2020-06-22 at 15 06 37" src="https://user-images.githubusercontent.com/22279028/85296981-134d0780-b49a-11ea-9b48-cc3099a6ca2e.png">

Just for futher context, I registered a normal account first, then following your steps I created another user from that account with no administrative dutites.

**Comment by Pavel910** [comment]
@TommyJackson85 please read this guide: https://github.com/webiny/webiny-js/blob/master/docs/CONTRIBUTING.md#local-setup

Especially pay attention to 6. and 7. You need to run a `watch` on packages you're working on, so your changes in `src` folder of the package are built to `dist` folder.

That document describes everything about our development process. Let me know if you're still stuck after it. Btw you can also join us on our Slack Community, it will be much faster to communicate that way:  https://www.webiny.com/slack

**Comment by TommyJackson85** [comment]
@Pavel910 please check the pull request I created. I'll be busy the next two days so I might not be able to work on it, just to let you know
