### ISSUE TITLE
Headless CMS - ADD image / image gallery fields

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#967]
Adding these fields might make it easier for users who are looking just that, as "File" filed might not be that obvious.

It's possible to copy the file field and make necessary adjustments.

**Comment by Ashu96** [comment]
Hey guys @webiny/developers @SvenAlHamad 

I think having a separate field for `Image` and `Image gallery` is not necessary.

We can try doing these for providing more context/clarity to users:
1. Add a description for each field in the editor.
2. Reword `multi values` toggle label such that it will be more clear to the user what is means. something like `use as a list of <field type>` i.e `use as a list of file`

---
![field-description](https://user-images.githubusercontent.com/13612227/84346249-2b38a780-abcd-11ea-85f7-977de22648c0.png)

![updated-label](https://user-images.githubusercontent.com/13612227/84346277-3b508700-abcd-11ea-82a0-d2e4da6f2c79.png)

---
Love to hear what you think about it?

**Comment by SvenAlHamad** [comment]
@Ashu96 that's also a good solution - I like it. 
Just one smaller amend, for the "multiple files" toggle. Expand the description to "Use as a list of files or an image gallery."
