### ISSUE TITLE
Headless CMS - add searching of content

### ISSUE THREAD

**Issue by doitadrian** [webiny/webiny-js#968]
Users need to be able to search for content via this search bar:
![image](https://user-images.githubusercontent.com/5121148/84055455-26011000-a9b5-11ea-9a8a-9ab4e6053422.png)

https://docs.webiny.com/docs/webiny-apps/admin/development/header

**Comment by alastair-todd** [comment]
Will there be a content search api endpoint as part of this feature?

**Comment by doitadrian** [comment]
Hey @alastair-todd , you can actually already search entries. For example: 

![image](https://user-images.githubusercontent.com/5121148/84927234-d1ecde80-b0cc-11ea-83af-1c3c07b48bff.png)

Did that answer your question?

P.S. Sorry for delay, basically I missed your question here.
