### ISSUE TITLE
Unable to deploy imageTransformer

### ISSUE THREAD

**Issue by cariboo** [webiny/webiny-js#976]
## This is:
- Bug

## Specifications

  - version: NodeJS 12.14.1 / yarn 1.21.1
  - OS: Mac OSX 10.15
  - Browser: Chrome

## Expected Behavior
Trying first local deployment with command yarn webiny deploy api --env=local

## Actual Behavior
Tried several times but always got the following error : 

  This is the first deploy of local environment, so it may take a few minutes.
  💡 Loaded local environment from <projectRoot>/.env.json.
  💡 Loaded local environment from <projectRoot>/api/.env.json.
  webiny Collecting components from the template. +0ms
  webiny Executing the template's components graph. +22ms
  webiny:databaseProxy Building 'databaseProxy' +0ms
  webiny:databaseProxy Finished building 'databaseProxy' +5s
  webiny:databaseProxy Starting deployment of lambda '8f46802c_xfiles_api_local_databaseProxy' to the 'us-east-1' region. +259ms
  webiny:databaseProxy No role provided for lambda '8f46802c_xfiles_api_local_databaseProxy' +184ms
  webiny:databaseProxy Syncing role 8f46802c-jj3stzh in region us-east-1. +11ms
  webiny:databaseProxy Creating role 8f46802c-jj3stzh. +564ms
  webiny:databaseProxy Saved state for role 8f46802c-jj3stzh. +16s
  webiny:databaseProxy Role 8f46802c-jj3stzh was successfully deployed to region us-east-1. +0ms
  webiny:databaseProxy Deployed role arn is arn:aws:iam::550451109557:role/8f46802c-jj3stzh. +0ms
  webiny:databaseProxy Packaging lambda code from './databaseProxy/build' +0ms
  webiny:databaseProxy Creating lambda '8f46802c_xfiles_api_local_databaseProxy' in the 'us-east-1' region. +666ms
  webiny:databaseProxy Successfully deployed lambda '8f46802c_xfiles_api_local_databaseProxy' in the 'us-east-1' region. +6s
  webiny:databaseProxy Setting function's concurrency limit to 15. +33ms
  webiny Loaded user ID: 02130910-342c-46b5-8ef3-10f6bfec50df +29s
  webiny Tracking is ENABLED +0ms
  webiny Tracking component: @webiny/serverless-function (deploy) +0ms
  webiny:cognito Creating new user pool. +0ms
  webiny:cognito Created user pool 'us-east-1_cEu3qDP1k'. +898ms
  webiny:cognito Creating new user pool client. +0ms
  webiny Tracking component: @webiny/serverless-aws-cognito-user-pool (deploy) +2s31s › Deploying...
  webiny:imageTransformer Building 'imageTransformer' +0ms
  webiny:imageTransformer Finished building 'imageTransformer' +5s
  webiny:imageTransformer Starting deployment of lambda '8f46802c_xfiles_api_local_imageTransformer' to the 'us-east-1' region. +1ms
  webiny:imageTransformer No role provided for lambda '8f46802c_xfiles_api_local_imageTransformer' +3ms
  webiny:imageTransformer Syncing role 8f46802c-w82l7rb in region us-east-1. +1ms
  webiny:imageTransformer Creating role 8f46802c-w82l7rb. +470ms
  webiny:imageTransformer Saved state for role 8f46802c-w82l7rb. +16s
  webiny:imageTransformer Role 8f46802c-w82l7rb was successfully deployed to region us-east-1. +0ms
  webiny:imageTransformer Deployed role arn is arn:aws:iam::550451109557:role/8f46802c-w82l7rb. +0ms
  webiny:imageTransformer Packaging lambda code from './files/transform/build' +1ms3s › Packaging...
  webiny:imageTransformer Creating lambda '8f46802c_xfiles_api_local_imageTransformer' in the 'us-east-1' region. +14s
  webiny An error occurred during deployment of imageTransformer +22m

InvalidSignatureException: Signature expired: 20200609T004532Z is now earlier than 20200609T004600Z (20200609T005100Z - 5 min.)
    at Object.extractError (/Users/coralie/Lab/xfiles/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (/Users/coralie/Lab/xfiles/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/Users/coralie/Lab/xfiles/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/coralie/Lab/xfiles/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/coralie/Lab/xfiles/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/coralie/Lab/xfiles/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/coralie/Lab/xfiles/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/coralie/Lab/xfiles/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/coralie/Lab/xfiles/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/coralie/Lab/xfiles/node_modules/aws-sdk/lib/request.js:685:12) {
  message: 'Signature expired: 20200609T004532Z is now earlier than 20200609T004600Z (20200609T005100Z - 5 min.)',
  code: 'InvalidSignatureException',
  time: 2020-06-09T00:51:00.296Z,
  requestId: 'f4afe9f5-81a1-459b-bad2-d244e5adaf39',
  statusCode: 403,
  retryable: true
}

✨  Done in 1382.59s.

## Steps to Reproduce the Problem
1. npx create-webiny-project xfiles
2. cd xfiles
3. set the MONGODB_SERVER value and AWS_REGION to eu-west-1
4. yarn webiny deploy api --env=local

**Comment by Pavel910** [comment]
Hi @cariboo, this is a known issue on slower internet connections, it's being resolved and will be released this week. In the meantime, you can do this quick fix:

At the top of your `api/resource.js`, add this:
```
const AWS = require("aws-sdk");
AWS.config.update({
    httpOptions: { timeout: 300000 }
});
```

So the whole problem here is that `imageTransformer` is deploying a huge ZIP with `sharp` dependency to manipulate images, and on slower internet connections it hits AWS SDKs default timeout. Using the code above you'll increase the timeout from 2 to 5 minutes.

We're working on a solution to avoid uploading that huge bundle all together.

Let us know how it goes. This workaround is confirmed to work by multiple users so it should help you as well :)

**Comment by cariboo** [comment]
Thanks for the quick answer but i got the same result :-(
I will wait for the next release.
