### ISSUE TITLE
S3 Accelerated 403 error

### ISSUE THREAD

**Issue by amirtds** [webiny/webiny-js#986]
## This is:
- Bug

## Specifications

  - version: 4.0.2

## Expected Behavior
S3 `accelerated` should be turned off

## Actual Behavior
During the deployment, the script tries to set accelerated to `true` for the S3 bucket

## Steps to Reproduce the Problem
Run `yarn webiny deploy api --env=local` and it gives 403 access denied for the S3 bucket serverless-aws-s3 package is using

## Detailed Description
https://webiny-community.slack.com/archives/C014Q0Z6A10/p1591800708065600

## Possible Solution
https://webiny-community.slack.com/archives/C014Q0Z6A10/p1591801257067200

**Comment by Pavel910** [comment]
Released in `v4.1.0`!
