### ISSUE TITLE
Headless CMS - Supporting authorization using JWT/PAT and public content

### ISSUE THREAD

**Issue by Pavel910** [webiny/webiny-js#994]
We got several inquiries about building an ecommerce app using Headless CMS. Some of the requested features are posing a blocker at this point in time:
1) having some/all of the content models publicly accessible 
2) being able to access the API using user's JWT, and not the access token

What are the things we need to consider to allow this type of use-case? @webiny/developers

**Comment by Pavel910** [comment]
@doitadrian @Fsalker this is also related to security scopes, but for now I would be happy with just allowing authenticated users access the API.

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
