### ISSUE TITLE
Client Site - Login Security Feature

### ISSUE THREAD

**Issue by balajijegadeesan** [webiny/webiny-js#999]
## This is:

- Question

## Specifications

  - version:
  - OS:
  - Browser:

## Expected Behavior
HI, How to add login feature to Client Site App. Currently admin app has this feature. I want to extend this feature to client Site. Pls help in this. thanx in advance.

## Steps to Reproduce the Problem

1.
2.
3.

## Detailed Description
HI, How to add login feature to Client Site App. Currently admin app has this feature. I want to extend this feature to client Site. Pls help in this. thanx in advance.

**Comment by Pavel910** [comment]
@balajijegadeesan we're working on the docs for app development and we'll include an article on how to setup security for the site app. Stay tuned!

**Comment by doitadrian** [comment]
Please reopen this issue once you add more information and updates here. If this is not the case and you need some help, feel free to seek help from our [Slack Community](https://www.webiny.com/slack) or ping one of the reviewers. Thank you for your contributions!
